import type { Lesson } from "@/lib/topics";

/** AP Biology — one Lesson per CED topic across all 8 units (57 topics). */

const KA = "https://www.khanacademy.org/science/ap-biology";

const U = {
  1: "Chemistry of Life",
  2: "Cell Structure and Function",
  3: "Cellular Energetics",
  4: "Cell Communication and Cell Cycle",
  5: "Heredity",
  6: "Gene Expression and Regulation",
  7: "Natural Selection",
  8: "Ecology",
};

const mk = (
  unit: keyof typeof U,
  id: string,
  title: string,
  blurb: string,
  keyIdeas: string[],
  sampleProblem: string,
  sampleWalkthrough: string,
  flashcards: { q: string; a: string }[]
): Lesson => ({
  slug: `bio-${id.replace(".", "-")}`,
  title,
  courses: [{ courseSlug: "ap-biology", unitNumber: unit, unitTitle: U[unit] }],
  blurb,
  keyIdeas,
  sampleProblem,
  sampleWalkthrough,
  flashcards,
  links: [{ title: "AP Biology", url: KA, source: "Khan Academy" }],
});

export const AP_BIOLOGY_LESSONS: Lesson[] = [
  mk(1, "1.1", "Structure of Water and Hydrogen Bonding",
    "Water's polarity produces H-bonds, giving it cohesion, adhesion, high specific heat, and unique density.",
    [
      "O pulls e⁻ stronger than H → polar covalent bonds → partial charges.",
      "Hydrogen bonds between H of one water and O of another.",
      "Properties: cohesion, adhesion, high specific heat, less dense as solid.",
      "Polar solvents dissolve polar solutes; water is 'universal solvent'.",
    ],
    "Why does ice float on water?",
    "In ice, hydrogen bonds lock water into an open crystal lattice, making solid less dense than liquid.",
    [
      { q: "Why is water polar?", a: "O is more electronegative; creates partial charges." },
      { q: "Hydrogen bond?", a: "Attraction between δ⁺ H and δ⁻ O/N/F of another molecule." },
      { q: "Cohesion vs adhesion?", a: "Cohesion: water-water; adhesion: water-other." },
      { q: "Why high specific heat?", a: "Lots of H-bonds absorb energy before molecules move faster." },
      { q: "Ice less dense?", a: "Open crystal lattice from H-bonds." },
    ],
  ),
  mk(1, "1.2", "Elements of Life",
    "C, H, O, N, P, S make up ~97% of living matter. Carbon's 4 bonds enable complexity.",
    [
      "CHNOPS: the building-block elements.",
      "Carbon: 4 valence electrons → versatile bonding.",
      "Trace elements: Fe, Mg, Ca, K, Na, Cl, etc. small amounts, critical roles.",
    ],
    "Why is carbon the basis of life's molecules?",
    "Four valence electrons let carbon form diverse, stable bonds — single, double, triple, and branched — enabling huge molecular diversity.",
    [
      { q: "CHNOPS?", a: "Carbon, Hydrogen, Nitrogen, Oxygen, Phosphorus, Sulfur." },
      { q: "Carbon's valence electrons?", a: "4" },
      { q: "Key role of N?", a: "Amino groups in proteins, bases in DNA/RNA." },
      { q: "Key role of P?", a: "Phosphate groups in ATP, nucleic acids." },
      { q: "Trace element example?", a: "Fe (hemoglobin), Mg (chlorophyll), Ca (bones, signaling)." },
    ],
  ),
  mk(1, "1.3", "Introduction to Macromolecules",
    "Four classes: carbs, lipids, proteins, nucleic acids. Built by dehydration; broken by hydrolysis.",
    [
      "Monomers → polymers via dehydration synthesis (remove H₂O).",
      "Polymers → monomers via hydrolysis (add H₂O).",
      "Proteins, DNA/RNA, carbs are polymers of repeating units; lipids are not true polymers.",
    ],
    "A disaccharide forms from two monosaccharides. What's released?",
    "One water molecule (dehydration synthesis).",
    [
      { q: "Dehydration synthesis?", a: "Two monomers joined, one H₂O released." },
      { q: "Hydrolysis?", a: "Polymer split into monomers by adding H₂O." },
      { q: "Four macromolecule classes?", a: "Carbs, lipids, proteins, nucleic acids." },
      { q: "Are lipids polymers?", a: "Not technically — no repeating monomer unit." },
      { q: "Protein monomer?", a: "Amino acid." },
    ],
  ),
  mk(1, "1.4", "Carbohydrates",
    "Sugars (CH₂O)_n. Monosaccharides → disaccharides → polysaccharides.",
    [
      "Mono: glucose, fructose, galactose.",
      "Di: sucrose (glu+fru), lactose (glu+gal), maltose (glu+glu).",
      "Poly: starch, glycogen (storage); cellulose, chitin (structural).",
      "Glycosidic linkage joins sugars; structural isomers differ.",
    ],
    "Why can humans digest starch but not cellulose?",
    "Both are glucose polymers, but starch has α-glycosidic bonds (digestible) and cellulose has β (humans lack the enzyme).",
    [
      { q: "Carb formula?", a: "(CH₂O)_n" },
      { q: "Storage poly in animals?", a: "Glycogen" },
      { q: "Storage poly in plants?", a: "Starch" },
      { q: "Structural poly plants?", a: "Cellulose" },
      { q: "α vs β glycosidic bonds?", a: "α digestible (starch); β not (cellulose)." },
    ],
  ),
  mk(1, "1.5", "Lipids",
    "Hydrophobic. Triglycerides (fats), phospholipids (membranes), steroids (signaling).",
    [
      "Triglycerides: glycerol + 3 fatty acids. Saturated vs unsaturated.",
      "Phospholipids: hydrophilic head + 2 hydrophobic tails → bilayer.",
      "Steroids: 4 fused rings (e.g., cholesterol, estrogen).",
      "Waxes: water-repellent coatings.",
    ],
    "Why do phospholipids spontaneously form bilayers in water?",
    "Hydrophobic tails cluster away from water; hydrophilic heads face water — bilayer minimizes free energy.",
    [
      { q: "Lipid property?", a: "Hydrophobic — don't dissolve in water." },
      { q: "Fatty acid saturated?", a: "No double bonds in tail — solid at room temp." },
      { q: "Fatty acid unsaturated?", a: "One or more double bonds — kinked, liquid." },
      { q: "Phospholipid structure?", a: "Hydrophilic head + two hydrophobic tails." },
      { q: "Steroid example?", a: "Cholesterol, testosterone, estrogen." },
    ],
  ),
  mk(1, "1.6", "Nucleic Acids",
    "DNA and RNA. Nucleotides = sugar + phosphate + base. Encode information.",
    [
      "DNA: deoxyribose, bases A T G C, double helix.",
      "RNA: ribose, bases A U G C, usually single-stranded.",
      "5' → 3' directionality.",
      "Base pairing: A-T (or A-U in RNA), G-C.",
    ],
    "DNA strand reads 5'-ATGC-3'. Complementary strand?",
    "3'-TACG-5' or written 5' to 3' as 5'-GCAT-3'.",
    [
      { q: "DNA sugar?", a: "Deoxyribose" },
      { q: "RNA sugar?", a: "Ribose" },
      { q: "Base pairing DNA?", a: "A-T, G-C" },
      { q: "Base pairing RNA?", a: "A-U, G-C" },
      { q: "5' → 3' means?", a: "Direction of new strand synthesis." },
    ],
  ),
  mk(1, "1.7", "Proteins",
    "Built from 20 amino acids. Four structure levels: primary, secondary, tertiary, quaternary.",
    [
      "Primary: amino acid sequence.",
      "Secondary: α-helix, β-pleated sheet (H-bonds in backbone).",
      "Tertiary: 3D fold from R-group interactions.",
      "Quaternary: multiple polypeptide chains (e.g., hemoglobin).",
      "Denaturation disrupts 3D shape.",
    ],
    "What forces hold tertiary structure together?",
    "R-group interactions: hydrogen bonds, ionic, hydrophobic, disulfide bridges (between cysteines).",
    [
      { q: "Number of amino acids?", a: "20" },
      { q: "Primary structure?", a: "Sequence of amino acids." },
      { q: "Secondary structure forms?", a: "α-helix, β-sheet (backbone H-bonds)." },
      { q: "Tertiary interactions?", a: "H-bonds, ionic, hydrophobic, disulfide." },
      { q: "Quaternary?", a: "Multiple polypeptide subunits assembled." },
    ],
  ),
  mk(2, "2.1", "Cell Structure and Function",
    "Organelles specialize; compartmentalization boosts efficiency.",
    [
      "Nucleus: DNA storage; nuclear envelope with pores.",
      "Ribosomes: protein synthesis.",
      "ER (rough/smooth): protein and lipid processing.",
      "Golgi: modifies, sorts, ships.",
      "Mitochondria: ATP via cellular respiration.",
      "Chloroplast: photosynthesis (plants).",
      "Lysosome: digestion (animal); vacuole (plant, storage).",
    ],
    "Which organelle is the 'protein factory'?",
    "Ribosome (free or bound to rough ER).",
    [
      { q: "Nucleus role?", a: "DNA storage and gene control." },
      { q: "Rough ER?", a: "Ribosomes attached — protein synthesis/modification." },
      { q: "Smooth ER?", a: "Lipid synthesis, detoxification." },
      { q: "Golgi function?", a: "Modify, sort, package for shipping." },
      { q: "Mitochondria?", a: "Site of cellular respiration / ATP." },
    ],
  ),
  mk(2, "2.2", "Cell Size",
    "Surface area-to-volume ratio limits cell size. Large cells: diffusion can't keep up.",
    [
      "As cells grow, V grows faster than SA.",
      "Higher SA:V → faster exchange.",
      "Solutions: stay small, elongate (neurons), internal membranes (ER).",
    ],
    "Why are nerve cells elongated?",
    "To maintain high SA:V and quickly transmit signals over long distances.",
    [
      { q: "SA:V as cell grows?", a: "Decreases." },
      { q: "Why does SA:V matter?", a: "Limits diffusion rate." },
      { q: "Adaptations for large volume?", a: "Flatten, elongate, fold membranes." },
      { q: "Rate of diffusion ∝?", a: "Surface area." },
      { q: "Microvilli in gut cells?", a: "Increase SA for absorption." },
    ],
  ),
  mk(2, "2.3", "Plasma Membrane",
    "Fluid mosaic of phospholipid bilayer with embedded proteins.",
    [
      "Bilayer: hydrophilic heads out, hydrophobic tails in.",
      "Membrane proteins: transport, receptor, enzyme, structural.",
      "Cholesterol (animal): temperature buffer.",
      "Selective permeability: small nonpolar cross freely; ions need channels.",
    ],
    "Why is the phospholipid bilayer selectively permeable?",
    "Hydrophobic core blocks polar/charged molecules but lets small nonpolar ones through.",
    [
      { q: "Main component of membrane?", a: "Phospholipid bilayer." },
      { q: "Who proposed fluid mosaic?", a: "Singer and Nicolson (1972)." },
      { q: "Role of cholesterol?", a: "Maintains fluidity across temperatures." },
      { q: "What crosses easily?", a: "Small nonpolar molecules (O₂, CO₂)." },
      { q: "What needs transport proteins?", a: "Ions, polar, large molecules." },
    ],
  ),
  mk(2, "2.4", "Membrane Permeability",
    "Lipid bilayer is impermeable to ions and polar molecules without transporters.",
    [
      "Passive diffusion: small nonpolar.",
      "Facilitated diffusion: via channels or carriers, down gradient.",
      "Active transport: against gradient, needs ATP.",
      "Bulk transport: endocytosis, exocytosis.",
    ],
    "Rank permeability: glucose, O₂, Na⁺.",
    "O₂ > glucose > Na⁺. O₂ is small/nonpolar; glucose needs transporter; Na⁺ is a charged ion needing channels.",
    [
      { q: "Easily permeable?", a: "Small nonpolar (O₂, CO₂, N₂)." },
      { q: "Need channels?", a: "Ions, water, polar." },
      { q: "Active transport requires?", a: "ATP (against gradient)." },
      { q: "Endocytosis?", a: "Cell takes in material via vesicle." },
      { q: "Exocytosis?", a: "Cell expels via vesicle fusion." },
    ],
  ),
  mk(2, "2.5", "Membrane Transport",
    "Passive (no ATP): diffusion, osmosis, facilitated. Active (ATP): pumps, co-transport.",
    [
      "Passive: down concentration gradient, no ATP.",
      "Active: against gradient, uses ATP.",
      "Sodium-potassium pump: 3 Na⁺ out, 2 K⁺ in per ATP.",
      "Electrochemical gradient = concentration + charge differences.",
    ],
    "What's the net charge movement per Na⁺/K⁺ pump cycle?",
    "3 + out, 2 + in = net +1 outside → hyperpolarization contribution.",
    [
      { q: "Passive transport energy cost?", a: "None (no ATP)." },
      { q: "Active transport energy source?", a: "ATP." },
      { q: "Na⁺/K⁺ pump ratio?", a: "3 Na⁺ out : 2 K⁺ in per ATP." },
      { q: "Primary active transport?", a: "Direct ATP use (e.g., Na⁺/K⁺ pump)." },
      { q: "Secondary active (co-transport)?", a: "Uses existing gradient to move another solute." },
    ],
  ),
  mk(2, "2.6", "Facilitated Diffusion",
    "Passive movement through protein channels or carriers.",
    [
      "Channel proteins: open pore (e.g., aquaporins, ion channels).",
      "Carrier proteins: bind and change shape.",
      "Still down gradient — no ATP.",
      "Gating: voltage-gated, ligand-gated.",
    ],
    "Can glucose enter cells without energy input?",
    "Yes — through a glucose carrier protein (facilitated diffusion, down gradient). But insulin-responsive uptake uses different glucose transporters.",
    [
      { q: "Facilitated diffusion?", a: "Passive, protein-mediated, down gradient." },
      { q: "Channel vs carrier?", a: "Channel = open pore; carrier = binds and flips." },
      { q: "Aquaporin?", a: "Water channel protein." },
      { q: "Voltage-gated channel?", a: "Opens/closes with membrane potential." },
      { q: "Does facilitated diffusion use ATP?", a: "No." },
    ],
  ),
  mk(2, "2.7", "Tonicity and Osmoregulation",
    "Hypotonic cell swells, hypertonic shrinks, isotonic stays same.",
    [
      "Osmosis: water moves toward higher solute concentration.",
      "Hypertonic (higher solute outside): cell loses water, shrinks.",
      "Hypotonic (lower solute outside): cell gains water, may lyse.",
      "Isotonic: no net change.",
      "Plants: turgor pressure when hypotonic (ideal); plasmolysis when hypertonic.",
    ],
    "Red blood cell in pure water — fate?",
    "Lyses — hypotonic environment causes water influx until membrane ruptures.",
    [
      { q: "Osmosis direction?", a: "Toward higher solute (lower water potential)." },
      { q: "Hypertonic?", a: "Higher solute outside — cell loses water." },
      { q: "Hypotonic?", a: "Lower solute outside — cell swells." },
      { q: "Isotonic?", a: "Equal solute; no net water movement." },
      { q: "Plant in hypotonic?", a: "Turgid (good — central vacuole full)." },
    ],
  ),
  mk(2, "2.8", "Mechanisms of Transport",
    "Size-dependent: bulk transport (endo/exocytosis) for large items.",
    [
      "Endocytosis: phagocytosis (cell eating), pinocytosis (cell drinking), receptor-mediated (specific).",
      "Exocytosis: vesicle fuses with membrane, releases contents.",
      "Uses ATP; moves large quantities.",
      "Receptor-mediated endocytosis: specific uptake of cholesterol (LDL), hormones.",
    ],
    "How do macrophages consume bacteria?",
    "Phagocytosis — extend pseudopods, engulf bacterium in a large vesicle, fuse with lysosome for digestion.",
    [
      { q: "Phagocytosis?", a: "Cell eating (large particles)." },
      { q: "Pinocytosis?", a: "Cell drinking (small dissolved)." },
      { q: "Receptor-mediated endocytosis?", a: "Specific — ligand binds receptor, triggers uptake." },
      { q: "Exocytosis?", a: "Vesicle fuses with membrane to release contents." },
      { q: "ATP required?", a: "Yes — bulk transport needs energy." },
    ],
  ),
  mk(2, "2.9", "Cell Compartmentalization",
    "Organelles create distinct environments for specialized reactions.",
    [
      "Compartments maintain different pH, ionic conditions, concentrations.",
      "Eukaryotes: membrane-bound organelles; prokaryotes: mostly not.",
      "Enzymes concentrated in specific locations for efficiency.",
      "Isolates incompatible reactions (e.g., digestive enzymes in lysosome).",
    ],
    "Why are digestive enzymes in lysosomes?",
    "To isolate them from cytoplasm where they would damage cell components; low pH activates them.",
    [
      { q: "Why compartmentalize?", a: "Specialize function, prevent harm, maintain conditions." },
      { q: "Lysosome pH?", a: "Acidic (~4.5-5)." },
      { q: "Compartments in prokaryotes?", a: "Few/none membrane-bound." },
      { q: "Benefit of ER/Golgi?", a: "Protein processing pipeline in sequence." },
      { q: "Where is Ca²⁺ stored?", a: "Smooth ER (for signaling)." },
    ],
  ),
  mk(2, "2.10", "Origins of Cell Compartmentalization",
    "Endosymbiotic theory: mitochondria and chloroplasts were once free-living bacteria.",
    [
      "Mitochondria and chloroplasts have own circular DNA, 70S ribosomes, double membranes.",
      "Size similar to bacteria; divide by binary fission.",
      "Likely engulfed and became symbiotic ~2 billion years ago.",
      "Supports eukaryotic origin story — Lynn Margulis.",
    ],
    "What evidence supports endosymbiotic theory?",
    "Double membrane, circular DNA, bacteria-like ribosomes, self-replication independent of host.",
    [
      { q: "Endosymbiotic theory?", a: "Mito/chloroplasts originated as engulfed bacteria." },
      { q: "Evidence: membranes?", a: "Double membrane (outer = host vesicle, inner = original)." },
      { q: "Evidence: DNA?", a: "Circular, bacterial-like." },
      { q: "Evidence: ribosomes?", a: "70S (like bacteria), not 80S (eukaryote)." },
      { q: "Proposed by?", a: "Lynn Margulis." },
    ],
  ),
  mk(3, "3.1", "Enzymes",
    "Biological catalysts; lower activation energy; substrate-specific.",
    [
      "Enzymes = mostly proteins; named with -ase.",
      "Active site binds substrate (induced fit).",
      "Don't change ΔG, just lower Ea.",
      "Reusable — aren't consumed.",
    ],
    "What does 'lower activation energy' mean?",
    "Enzymes make it easier for reactants to reach the transition state, so reactions occur faster at lower temperatures — without changing the reaction's overall thermodynamics.",
    [
      { q: "What do enzymes do?", a: "Lower activation energy Ea." },
      { q: "Active site?", a: "Region that binds substrate." },
      { q: "Induced fit?", a: "Enzyme shape adjusts when substrate binds." },
      { q: "Do enzymes change ΔG?", a: "No — only Ea." },
      { q: "Naming convention?", a: "Usually ends in -ase (sucrase, protease)." },
    ],
  ),
  mk(3, "3.2", "Environmental Impacts on Enzyme Function",
    "Temp, pH, substrate conc, inhibitors affect rate.",
    [
      "Temperature: rate increases then denatures above optimum.",
      "pH: optimum depends on enzyme (pepsin acidic, trypsin basic).",
      "Substrate [S]: rate rises until V_max (saturation).",
      "Competitive inhibitor: binds active site. Noncompetitive: binds allosteric.",
    ],
    "What does noncompetitive inhibition look like in Michaelis-Menten?",
    "V_max decreases (fewer enzymes available); K_m unchanged.",
    [
      { q: "Temperature past optimum?", a: "Denatures enzyme → activity drops." },
      { q: "Pepsin optimum pH?", a: "~2 (stomach)." },
      { q: "Trypsin optimum pH?", a: "~8 (small intestine)." },
      { q: "Competitive inhibitor?", a: "Binds active site." },
      { q: "Noncompetitive inhibitor?", a: "Binds allosteric, changes enzyme shape." },
    ],
  ),
  mk(3, "3.3", "Cellular Energy",
    "ATP is the universal energy currency. Hydrolysis of ATP → ADP + Pi releases energy.",
    [
      "ATP: ribose + adenine + 3 phosphates.",
      "Energy stored in phosphoanhydride bonds.",
      "ATP → ADP + Pi: releases ~7.3 kcal/mol.",
      "Coupled reactions: exergonic drives endergonic.",
    ],
    "How does ATP hydrolysis drive unfavorable reactions?",
    "The energy released from breaking ATP's phosphate bond is coupled to endergonic processes via enzyme-mediated phosphate transfer.",
    [
      { q: "ATP structure?", a: "Adenine + ribose + 3 phosphates." },
      { q: "ATP → ADP + Pi energy?", a: "~7.3 kcal/mol." },
      { q: "Coupled reaction?", a: "Exergonic drives endergonic." },
      { q: "Exergonic?", a: "ΔG < 0 (releases energy)." },
      { q: "Endergonic?", a: "ΔG > 0 (requires energy)." },
    ],
  ),
  mk(3, "3.4", "Photosynthesis",
    "6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂. Light reactions + Calvin cycle.",
    [
      "Light reactions in thylakoid: H₂O split, O₂ released, ATP + NADPH produced.",
      "Calvin cycle in stroma: CO₂ fixed to G3P → glucose using ATP + NADPH.",
      "Pigments: chlorophyll a (primary), chlorophyll b, carotenoids.",
      "RuBisCO fixes CO₂ (rate-limiting enzyme on Earth).",
    ],
    "Where do the light reactions occur?",
    "Thylakoid membranes (inside chloroplast); Calvin cycle in stroma.",
    [
      { q: "Overall photosynthesis?", a: "6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂" },
      { q: "Light reactions product?", a: "ATP, NADPH, O₂" },
      { q: "Calvin cycle input?", a: "CO₂, ATP, NADPH" },
      { q: "Calvin cycle product?", a: "G3P (→ glucose)" },
      { q: "Where does O₂ come from?", a: "Water splitting in PSII." },
    ],
  ),
  mk(3, "3.5", "Cellular Respiration",
    "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ~32 ATP. Glycolysis, Krebs, ETC.",
    [
      "Glycolysis (cytoplasm): glucose → 2 pyruvate + 2 ATP + 2 NADH.",
      "Pyruvate oxidation (matrix): pyruvate → acetyl-CoA.",
      "Krebs cycle (matrix): 2 ATP + 6 NADH + 2 FADH₂ + 4 CO₂ per glucose.",
      "ETC + chemiosmosis (inner membrane): ~26-28 ATP.",
      "Fermentation: no O₂ → NAD⁺ regenerated via lactate or ethanol.",
    ],
    "Why do we need oxygen?",
    "Final electron acceptor in ETC — without O₂, the chain backs up, NADH can't be re-oxidized, Krebs stops.",
    [
      { q: "Glycolysis location?", a: "Cytoplasm" },
      { q: "Krebs cycle location?", a: "Mitochondrial matrix" },
      { q: "ETC location?", a: "Inner mitochondrial membrane" },
      { q: "ATP per glucose (total)?", a: "~30-32 ATP" },
      { q: "Final electron acceptor?", a: "O₂ (makes H₂O)" },
    ],
  ),
  mk(4, "4.1", "Cell Communication",
    "Cells signal via direct contact, local, long-distance. Signal transduction amplifies response.",
    [
      "Local signaling: paracrine (neighbors), synaptic.",
      "Long-distance: hormones via bloodstream (endocrine).",
      "Direct contact: gap junctions, plasmodesmata.",
      "Universal receptor-signal-response pattern.",
    ],
    "Example of paracrine signaling?",
    "Growth factors acting on nearby cells in wound healing.",
    [
      { q: "Paracrine?", a: "Local signaling to nearby cells." },
      { q: "Endocrine?", a: "Long-distance via bloodstream hormones." },
      { q: "Synaptic?", a: "Neurotransmitters across synapse." },
      { q: "Gap junction?", a: "Direct cytoplasmic channel between animal cells." },
      { q: "Plasmodesmata?", a: "Plant-cell version of gap junctions." },
    ],
  ),
  mk(4, "4.2", "Introduction to Signal Transduction",
    "Signal → receptor → transduction → response. Amplifies and diversifies.",
    [
      "Reception: ligand binds receptor.",
      "Transduction: cascade of molecular events.",
      "Response: gene expression, enzyme activation, etc.",
      "Amplification: one signal → many responses.",
    ],
    "Why is amplification useful?",
    "A single signaling molecule can trigger a massive cellular response through cascades (e.g., one epinephrine → 10⁸ glucose molecules released).",
    [
      { q: "Three stages of signal transduction?", a: "Reception, Transduction, Response." },
      { q: "Amplification?", a: "One signal → many responses via cascade." },
      { q: "Specificity from?", a: "Receptor-ligand binding + downstream proteins." },
      { q: "Response examples?", a: "Gene expression, enzyme activation, cytoskeletal change." },
      { q: "Why use cascades?", a: "Amplification + regulation points." },
    ],
  ),
  mk(4, "4.3", "Signal Transduction Pathways",
    "G-protein coupled receptors, receptor tyrosine kinases, ion channels.",
    [
      "GPCRs: ligand → G protein → enzyme → second messenger (cAMP).",
      "RTKs: dimerize, autophosphorylate, trigger cascades (MAP kinase).",
      "Ligand-gated ion channels: fast, direct (e.g., acetylcholine at NMJ).",
      "Second messengers: cAMP, Ca²⁺, IP₃.",
    ],
    "What happens when epinephrine binds its GPCR?",
    "Activates Gs → adenylyl cyclase → cAMP → PKA → phosphorylates targets → glucose release.",
    [
      { q: "GPCR downstream second messenger often?", a: "cAMP" },
      { q: "RTK example?", a: "Insulin receptor, EGFR" },
      { q: "Ligand-gated channels?", a: "Fast, direct (neurotransmitter receptors)." },
      { q: "Common second messengers?", a: "cAMP, Ca²⁺, IP₃" },
      { q: "Why phosphorylation cascades?", a: "Amplify and regulate signaling." },
    ],
  ),
  mk(4, "4.4", "Feedback",
    "Negative feedback stabilizes; positive feedback amplifies.",
    [
      "Negative: output inhibits its own production (homeostasis).",
      "Positive: output amplifies production (childbirth, blood clotting).",
      "Feedback regulates enzymes, hormones, pathways.",
      "Most physiological systems use negative feedback.",
    ],
    "Blood glucose regulation — feedback type?",
    "Negative — high glucose → insulin → uptake → glucose drops → insulin drops.",
    [
      { q: "Negative feedback?", a: "Output inhibits production — stabilizes system." },
      { q: "Positive feedback?", a: "Output amplifies production." },
      { q: "Blood glucose?", a: "Negative feedback." },
      { q: "Childbirth contractions?", a: "Positive feedback." },
      { q: "Common purpose of negative feedback?", a: "Homeostasis." },
    ],
  ),
  mk(4, "4.5", "Cell Cycle",
    "G1 → S → G2 → M. Interphase + mitosis.",
    [
      "G1: cell grows.",
      "S: DNA replicates.",
      "G2: prepares for division.",
      "M (mitosis + cytokinesis): PMAT (prophase, metaphase, anaphase, telophase).",
      "Checkpoints at G1/S, G2/M, spindle (M).",
    ],
    "Which phase has DNA replication?",
    "S phase (Synthesis) — each chromosome becomes 2 sister chromatids.",
    [
      { q: "Cell cycle phases?", a: "G1, S, G2, M" },
      { q: "When does DNA replicate?", a: "S phase." },
      { q: "Mitosis phases?", a: "PMAT: Prophase, Metaphase, Anaphase, Telophase." },
      { q: "Cytokinesis?", a: "Splits cytoplasm (after mitosis)." },
      { q: "G0?", a: "Non-dividing resting state." },
    ],
  ),
  mk(4, "4.6", "Regulation of Cell Cycle",
    "Cyclins and CDKs drive cycle. Checkpoints halt if damage detected.",
    [
      "CDKs: Cyclin-Dependent Kinases activate when bound to cyclins.",
      "MPF (M-phase promoting factor): cyclin B + CDK1 triggers mitosis.",
      "Checkpoints: G1/S (commitment), G2/M, spindle.",
      "p53: tumor suppressor triggers apoptosis if DNA damaged.",
      "Cancer: loss of checkpoint control (proto-oncogenes, tumor suppressors).",
    ],
    "What does p53 do?",
    "Acts at G1 checkpoint: detects DNA damage, halts cycle, triggers repair or apoptosis. Mutated in ~50% of cancers.",
    [
      { q: "Cyclin-CDK?", a: "Complex that phosphorylates to drive cell cycle." },
      { q: "G1 checkpoint?", a: "Commits to division; detects damage." },
      { q: "p53 role?", a: "Guardian — halts cycle or triggers apoptosis." },
      { q: "Cancer cause?", a: "Loss of cell cycle control." },
      { q: "Proto-oncogene?", a: "Normal gene promoting growth; mutated → oncogene." },
    ],
  ),
  mk(5, "5.1", "Meiosis",
    "Two divisions → 4 haploid gametes; crossing over and independent assortment create variation.",
    [
      "Meiosis I: homologous pairs separate (reduction division).",
      "Meiosis II: sister chromatids separate (like mitosis).",
      "Crossing over in prophase I.",
      "Produces 4 genetically unique haploid cells.",
    ],
    "What are the two sources of variation in meiosis?",
    "Crossing over (prophase I) and independent assortment of homologous pairs (metaphase I).",
    [
      { q: "Meiosis products?", a: "4 haploid gametes." },
      { q: "Crossing over when?", a: "Prophase I" },
      { q: "Reduction division?", a: "Meiosis I (2n → n)." },
      { q: "Independent assortment?", a: "Homologs sort randomly in metaphase I." },
      { q: "Meiosis II resembles?", a: "Mitosis (sister chromatids separate)." },
    ],
  ),
  mk(5, "5.2", "Meiosis and Genetic Diversity",
    "Independent assortment + crossing over + random fertilization = enormous variation.",
    [
      "Independent assortment: 2²³ combinations in human gametes (~8 million).",
      "Crossing over: new allele combos on same chromosome.",
      "Random fertilization multiplies variation.",
      "Variation is raw material for evolution.",
    ],
    "How many chromosome combinations in human gametes without crossing over?",
    "2²³ ≈ 8.4 million (23 homologous pairs sort independently).",
    [
      { q: "Human chromosome pairs?", a: "23" },
      { q: "Gamete combinations (no crossing over)?", a: "2²³ ≈ 8.4M" },
      { q: "Crossing over occurs when?", a: "Prophase I" },
      { q: "Random fertilization?", a: "Any sperm × any egg." },
      { q: "Variation's role?", a: "Raw material for natural selection." },
    ],
  ),
  mk(5, "5.3", "Mendelian Genetics",
    "Mendel's laws: segregation, independent assortment. Dominant, recessive, Punnett squares.",
    [
      "Law of segregation: alleles separate in gametes.",
      "Law of independent assortment: alleles for different genes sort independently.",
      "Dominant (B) vs recessive (b).",
      "Homozygous (BB, bb) vs heterozygous (Bb).",
      "Punnett square predicts ratios.",
    ],
    "Cross Bb × Bb. Offspring genotype ratio?",
    "1 BB : 2 Bb : 1 bb.",
    [
      { q: "Law of segregation?", a: "Alleles separate into different gametes." },
      { q: "Law of independent assortment?", a: "Different genes assort independently." },
      { q: "Bb × Bb genotype ratio?", a: "1:2:1" },
      { q: "Bb × Bb phenotype ratio?", a: "3:1 (dominant:recessive)" },
      { q: "Test cross?", a: "Unknown × homozygous recessive." },
    ],
  ),
  mk(5, "5.4", "Non-Mendelian Genetics",
    "Incomplete dominance, codominance, multiple alleles, sex-linkage, polygenic, epistasis.",
    [
      "Incomplete dominance: blend (red + white = pink).",
      "Codominance: both expressed (AB blood).",
      "Multiple alleles: ABO blood (A, B, O).",
      "Sex-linked (X): colorblindness, hemophilia.",
      "Polygenic: height, skin color.",
      "Epistasis: one gene masks another.",
    ],
    "Why do males show X-linked recessive traits more?",
    "Only one X — a single recessive allele is expressed (no dominant copy to mask).",
    [
      { q: "Incomplete dominance?", a: "Heterozygote shows intermediate phenotype." },
      { q: "Codominance?", a: "Both alleles expressed (AB blood)." },
      { q: "Multiple alleles example?", a: "ABO blood (3 alleles)." },
      { q: "X-linked inheritance?", a: "Gene on X chromosome; males more affected by recessive." },
      { q: "Epistasis?", a: "One gene masks expression of another." },
    ],
  ),
  mk(5, "5.5", "Environmental Effects on Phenotype",
    "Phenotype = genotype + environment. Examples: temperature, nutrition, pH.",
    [
      "Same genotype can yield different phenotypes across environments.",
      "Siamese cats: temperature-sensitive allele (cooler extremities darker).",
      "Hydrangea flower color: soil pH.",
      "Nutrition affects growth, development.",
    ],
    "Why do Siamese cats have dark ears/feet/tail?",
    "Temperature-sensitive tyrosinase: active in cooler extremities, inactive in warmer body core.",
    [
      { q: "Phenotype formula?", a: "Genotype + Environment + (GxE)" },
      { q: "Siamese cats?", a: "Temperature-sensitive enzyme produces pigment only in cool spots." },
      { q: "Hydrangea flower color?", a: "Depends on soil pH." },
      { q: "Human example?", a: "Twins develop differently with differing diets/environments." },
      { q: "Monozygotic twins identical?", a: "Nearly identical genotype; phenotype differs with environment." },
    ],
  ),
  mk(6, "6.1", "DNA and RNA Structure",
    "DNA: double helix, antiparallel, A-T/G-C. RNA: single strand, A-U/G-C.",
    [
      "Nucleotide = sugar + phosphate + base.",
      "DNA: deoxyribose + {A, T, G, C}.",
      "RNA: ribose + {A, U, G, C}.",
      "Antiparallel: one strand 5'→3', other 3'→5'.",
      "Watson and Crick (Franklin's data) proposed double helix 1953.",
    ],
    "Why is DNA antiparallel?",
    "DNA polymerase requires 5'→3' extension; complementary strands must run opposite for both to templates.",
    [
      { q: "DNA bases?", a: "A, T, G, C" },
      { q: "RNA bases?", a: "A, U, G, C" },
      { q: "Antiparallel?", a: "Strands run opposite 5'→3' directions." },
      { q: "Pairing rules?", a: "A-T (DNA), A-U (RNA), G-C" },
      { q: "Who + whose data?", a: "Watson + Crick, using Rosalind Franklin's X-ray." },
    ],
  ),
  mk(6, "6.2", "DNA Replication",
    "Semiconservative. Helicase, primase, DNA polymerase, ligase. Leading/lagging strands.",
    [
      "Semiconservative (Meselson-Stahl): each new DNA has one old + one new strand.",
      "Helicase unwinds; primase makes RNA primers.",
      "DNA polymerase extends 5'→3' only.",
      "Leading strand: continuous. Lagging strand: Okazaki fragments.",
      "Ligase joins fragments. Telomerase extends ends in germ/stem cells.",
    ],
    "Why is the lagging strand synthesized in fragments?",
    "DNA pol only extends 5'→3'. Since strands are antiparallel and replication fork moves one direction, one strand must be made in pieces (Okazaki fragments) running 'backward.'",
    [
      { q: "Replication model?", a: "Semiconservative" },
      { q: "Direction of DNA pol?", a: "5' → 3' only" },
      { q: "Leading strand?", a: "Continuous synthesis toward fork." },
      { q: "Lagging strand?", a: "Okazaki fragments (discontinuous)." },
      { q: "What joins fragments?", a: "DNA ligase." },
    ],
  ),
  mk(6, "6.3", "Transcription and RNA Processing",
    "DNA → mRNA via RNA polymerase. 5' cap, poly-A tail, splicing remove introns.",
    [
      "Transcription: RNA pol reads template 3'→5', builds mRNA 5'→3'.",
      "Eukaryotes: 5' cap, 3' poly-A tail, splicing removes introns.",
      "Exons = expressed; introns = removed.",
      "Alternative splicing: one gene → multiple proteins.",
    ],
    "Why are eukaryotic genes often larger than their mRNAs?",
    "They contain introns (removed during splicing). Only exons end up in mature mRNA.",
    [
      { q: "Who transcribes DNA?", a: "RNA polymerase" },
      { q: "5' cap?", a: "Protects mRNA; helps ribosome binding." },
      { q: "Poly-A tail?", a: "Protects mRNA; affects stability." },
      { q: "Intron?", a: "Non-coding region removed from mRNA." },
      { q: "Exon?", a: "Coding region retained in mature mRNA." },
    ],
  ),
  mk(6, "6.4", "Translation",
    "mRNA → protein at ribosome. tRNA anticodons match mRNA codons; amino acids linked.",
    [
      "Codon: 3 mRNA bases = 1 amino acid. 64 codons, 20 aa (redundancy).",
      "Start codon: AUG (Met). Stop codons: UAA, UAG, UGA.",
      "tRNA anticodon matches codon; charged with specific aa.",
      "Ribosome: A (acceptor), P (peptidyl), E (exit) sites.",
    ],
    "How many amino acids from 300-base mRNA?",
    "~100 (3 bases per codon), minus potential start/stop.",
    [
      { q: "Start codon?", a: "AUG (Met)" },
      { q: "Stop codons?", a: "UAA, UAG, UGA" },
      { q: "Ribosome sites?", a: "A, P, E" },
      { q: "tRNA charging?", a: "Amino acyl-tRNA synthetase adds correct amino acid." },
      { q: "Genetic code redundant?", a: "Yes — multiple codons per amino acid." },
    ],
  ),
  mk(6, "6.5", "Regulation of Gene Expression",
    "Transcription factors, operons (prokaryotes), epigenetics (eukaryotes).",
    [
      "Prokaryotes: operons (trp, lac) — gene clusters with shared promoter.",
      "Eukaryotes: transcription factors bind promoters/enhancers.",
      "Epigenetics: methylation (off), acetylation (on) of histones.",
      "Most gene regulation is at transcription level.",
    ],
    "How does the lac operon work?",
    "Normally OFF (repressor bound); lactose binds repressor → falls off → RNA pol transcribes → enzymes break lactose.",
    [
      { q: "Operon?", a: "Prokaryotic gene cluster with shared promoter/operator." },
      { q: "Lac operon condition?", a: "Lactose present, glucose absent." },
      { q: "Trp operon?", a: "Repressible; Trp binds and activates repressor." },
      { q: "Epigenetic mark for OFF?", a: "DNA methylation / histone deacetylation." },
      { q: "Epigenetic mark for ON?", a: "Histone acetylation." },
    ],
  ),
  mk(6, "6.6", "Gene Expression and Cell Specialization",
    "All cells have same DNA; different gene expression makes different cell types.",
    [
      "Differential gene expression drives specialization.",
      "Transcription factors determine cell fate.",
      "Stem cells: pluripotent → specialized.",
      "Signaling + epigenetics reinforce cell identity.",
    ],
    "Why does a muscle cell express different proteins than a nerve cell?",
    "Different transcription factors active → different genes expressed, even though both cells have the same DNA.",
    [
      { q: "Cell specialization driven by?", a: "Differential gene expression." },
      { q: "Why same DNA, different cells?", a: "Different subsets of genes expressed." },
      { q: "Pluripotent stem cells?", a: "Can become any cell type." },
      { q: "Master regulators?", a: "Transcription factors that trigger cell fate." },
      { q: "Epigenetic inheritance?", a: "Methylation patterns passed to daughter cells." },
    ],
  ),
  mk(6, "6.7", "Mutations",
    "Changes in DNA: point (silent, missense, nonsense), frameshift (insertion/deletion).",
    [
      "Point mutations: substitution.",
      "Silent: no amino acid change.",
      "Missense: different aa (may affect function).",
      "Nonsense: stop codon (truncated protein).",
      "Frameshift: insertion/deletion shifts reading frame → major change.",
      "Mutations can be helpful, neutral, or harmful.",
    ],
    "Which is worse: a substitution or a single-base insertion?",
    "Usually the insertion — it shifts the reading frame, altering ALL downstream amino acids.",
    [
      { q: "Silent mutation?", a: "No amino acid change." },
      { q: "Missense?", a: "Different amino acid." },
      { q: "Nonsense?", a: "Codon becomes stop → truncated protein." },
      { q: "Frameshift?", a: "Insertion/deletion shifts reading frame." },
      { q: "Germline vs somatic?", a: "Germline passed to offspring; somatic isn't." },
    ],
  ),
  mk(6, "6.8", "Biotechnology",
    "Tools: PCR, gel electrophoresis, CRISPR, cloning, GMOs.",
    [
      "PCR: amplify DNA using primers, Taq polymerase, thermocycling.",
      "Gel electrophoresis: separates DNA by size (smaller = faster).",
      "CRISPR-Cas9: targeted genome editing.",
      "Cloning: reproduce identical DNA (or organism).",
      "GMOs: genetically modified organisms (e.g., Bt corn, golden rice).",
    ],
    "Why use a thermostable polymerase (Taq) in PCR?",
    "PCR cycles include denaturation at ~95°C; Taq (from Thermus aquaticus) survives these temperatures.",
    [
      { q: "PCR purpose?", a: "Amplify specific DNA sequences." },
      { q: "Gel electrophoresis separates by?", a: "Size (smaller moves farther)." },
      { q: "CRISPR-Cas9?", a: "Programmable DNA-cutting system." },
      { q: "Restriction enzymes?", a: "Cut DNA at specific sequences." },
      { q: "GMO example?", a: "Bt corn, golden rice, disease-resistant crops." },
    ],
  ),
  mk(7, "7.1", "Introduction to Natural Selection",
    "Darwin: variation + heritability + differential reproduction = adaptation.",
    [
      "Variation in traits within a population.",
      "Traits are heritable.",
      "Some traits improve survival/reproduction.",
      "Those traits become more common over generations.",
    ],
    "What are Darwin's four conditions for natural selection?",
    "1) Variation 2) Heritability 3) Differential survival/reproduction 4) Overproduction of offspring.",
    [
      { q: "Darwin's key insight?", a: "Descent with modification via natural selection." },
      { q: "Selection pressure?", a: "Environmental factor affecting survival." },
      { q: "Fitness?", a: "Reproductive success (not strength)." },
      { q: "Adaptation?", a: "Trait that enhances fitness in a given environment." },
      { q: "Darwin's finches?", a: "Beak shapes adapted to food sources." },
    ],
  ),
  mk(7, "7.2", "Natural Selection",
    "Directional, stabilizing, disruptive selection reshape populations.",
    [
      "Directional: shifts mean one way (e.g., antibiotic resistance rising).",
      "Stabilizing: favors mean, selects against extremes (e.g., human birth weight).",
      "Disruptive: favors both extremes, not the middle (e.g., small + large beaks).",
      "Sexual selection: mate choice drives traits (peacock tails).",
    ],
    "Why did moth coloration shift during Industrial Revolution?",
    "Directional selection — dark moths survived on soot-covered trees, pale moths eaten. Pollution → dark allele favored.",
    [
      { q: "Directional selection?", a: "Mean shifts one way." },
      { q: "Stabilizing?", a: "Favors mean; selects against extremes." },
      { q: "Disruptive?", a: "Favors both extremes; mean decreases." },
      { q: "Sexual selection?", a: "Mate preference drives trait evolution." },
      { q: "Peppered moth example?", a: "Directional selection under pollution." },
    ],
  ),
  mk(7, "7.3", "Artificial Selection",
    "Humans breed for desired traits — speeds up trait change.",
    [
      "Artificial: human-chosen breeding (dogs, crops).",
      "Natural: environment selects.",
      "Both produce descent with modification.",
      "Artificial selection supports Darwin's argument.",
    ],
    "How did wolves become dogs?",
    "Artificial selection — humans bred for tameness, companionship, specific work tasks over thousands of years.",
    [
      { q: "Artificial selection?", a: "Humans choose which individuals reproduce." },
      { q: "Natural vs artificial?", a: "Nature vs human chooses the criterion." },
      { q: "Supports Darwin?", a: "Shows rapid trait change possible." },
      { q: "Examples?", a: "Dog breeds, modern cattle, corn from teosinte." },
      { q: "Time scale?", a: "Much faster than most natural selection." },
    ],
  ),
  mk(7, "7.4", "Population Genetics",
    "Population = gene pool of interbreeding individuals. Evolution is allele frequency change.",
    [
      "Gene pool: all alleles in a population.",
      "Allele frequency = allele count / total alleles.",
      "Evolution at population level = Δ allele frequencies over generations.",
      "Microevolution: small-scale allele shifts; macroevolution: species-level.",
    ],
    "What is the unit of evolution?",
    "The population (not the individual). Individuals don't evolve; populations do.",
    [
      { q: "Gene pool?", a: "Total alleles in a population." },
      { q: "Evolution defined?", a: "Change in allele frequencies over time." },
      { q: "Microevolution?", a: "Small-scale allele shifts." },
      { q: "Macroevolution?", a: "Large-scale changes (species-level)." },
      { q: "Unit of evolution?", a: "Population, not individual." },
    ],
  ),
  mk(7, "7.5", "Hardy–Weinberg Equilibrium",
    "Null model: p² + 2pq + q² = 1; p + q = 1. Conditions: no mutation, no migration, no selection, random mating, large pop.",
    [
      "p² + 2pq + q² = 1 (genotype freqs); p + q = 1 (allele freqs).",
      "Five conditions for equilibrium.",
      "Violations → evolution occurs.",
      "If q² = 0.09, q = 0.3; p = 0.7; heterozygote freq = 2(0.7)(0.3) = 0.42.",
    ],
    "9% of population has recessive disease. What fraction are carriers?",
    "q² = 0.09 → q = 0.3. p = 0.7. Carriers (2pq) = 2(0.7)(0.3) = 0.42 or 42%.",
    [
      { q: "H-W equation?", a: "p² + 2pq + q² = 1" },
      { q: "Five H-W conditions?", a: "No mutation, no migration, no selection, random mating, large pop." },
      { q: "q² = 0.04; q?", a: "0.2" },
      { q: "p + q = ?", a: "1" },
      { q: "2pq represents?", a: "Heterozygote frequency." },
    ],
  ),
  mk(7, "7.6", "Evidence of Evolution",
    "Fossils, anatomical similarity, biogeography, molecular, observed evolution.",
    [
      "Fossil record: transitional forms, sequence of life.",
      "Homologous structures: same origin, different function (vertebrate forelimbs).",
      "Analogous: same function, different origin (convergent evolution).",
      "Vestigial: reduced structures (whale pelvis).",
      "Molecular: DNA/protein similarity tracks relatedness.",
    ],
    "Why are bat wings and whale flippers homologous?",
    "Both derived from the same ancestral vertebrate forelimb — same bone structure, different functions (flight vs swimming).",
    [
      { q: "Homologous structures?", a: "Same origin, different function." },
      { q: "Analogous?", a: "Same function, different origin (convergent)." },
      { q: "Vestigial?", a: "Reduced structure from ancestor." },
      { q: "Molecular evidence?", a: "DNA/protein sequence similarity." },
      { q: "Transitional fossil?", a: "Intermediate form between ancestor and descendant." },
    ],
  ),
  mk(7, "7.7", "Common Ancestry",
    "All life shares DNA, ribosomes, ATP, core metabolism — evidence of single origin.",
    [
      "Universal genetic code (with minor exceptions).",
      "ATP as energy currency everywhere.",
      "Ribosomes universal.",
      "Core metabolism (glycolysis) in all life.",
    ],
    "What evidence suggests all life shares a common ancestor?",
    "Shared universal genetic code, ATP, ribosomes, and fundamental metabolic pathways (glycolysis).",
    [
      { q: "Universal features of life?", a: "DNA code, ATP, ribosomes, glycolysis." },
      { q: "LUCA?", a: "Last Universal Common Ancestor." },
      { q: "Three domains?", a: "Bacteria, Archaea, Eukarya." },
      { q: "Whose cells have nuclei?", a: "Eukaryotes only." },
      { q: "Three-domain proposer?", a: "Carl Woese (using ribosomal RNA)." },
    ],
  ),
  mk(7, "7.8", "Continuing Evolution",
    "Evolution is ongoing — antibiotic resistance, HIV drug resistance, insect pesticide resistance.",
    [
      "Evolution isn't history; it's happening now.",
      "Antibiotic resistance in bacteria (rapid).",
      "HIV mutates faster than immune system.",
      "Pesticide resistance in insects.",
    ],
    "Why is antibiotic resistance an example of continuing evolution?",
    "Bacteria vary in resistance; antibiotic kills sensitive ones; resistant ones reproduce; resistance becomes common.",
    [
      { q: "Continuing evolution example?", a: "Antibiotic resistance in bacteria." },
      { q: "Why so fast in bacteria?", a: "Short generation time, large population, horizontal gene transfer." },
      { q: "HIV evolution?", a: "High mutation rate outpaces immune response." },
      { q: "Pesticide resistance?", a: "Insects with resistance alleles survive and reproduce." },
      { q: "Is evolution directional?", a: "No — responds to current selection pressures." },
    ],
  ),
  mk(7, "7.9", "Phylogeny",
    "Evolutionary tree showing relationships. Cladograms based on shared derived characteristics.",
    [
      "Clade: common ancestor + all descendants.",
      "Shared derived trait (synapomorphy) defines a clade.",
      "Parsimony: fewest changes preferred.",
      "Molecular clocks estimate divergence times.",
    ],
    "What does a node in a cladogram represent?",
    "A common ancestor — descendants share inherited (derived) characteristics.",
    [
      { q: "Cladogram?", a: "Tree based on shared derived characteristics." },
      { q: "Clade?", a: "Common ancestor + ALL descendants." },
      { q: "Synapomorphy?", a: "Shared derived trait defining a clade." },
      { q: "Outgroup?", a: "Closely related but not in the clade of interest." },
      { q: "Molecular clock?", a: "Uses mutation rate to estimate divergence times." },
    ],
  ),
  mk(7, "7.10", "Speciation",
    "New species form via reproductive isolation: allopatric, sympatric.",
    [
      "Species concept: reproductively isolated group.",
      "Allopatric: geographic isolation.",
      "Sympatric: same area; different niches, polyploidy, behavior.",
      "Prezygotic (behavior, habitat, gametic) vs postzygotic (hybrid inviability, sterility) barriers.",
    ],
    "Why are mules sterile?",
    "Postzygotic barrier — horse-donkey hybrid has unpaired chromosomes that fail in meiosis.",
    [
      { q: "Allopatric speciation?", a: "Geographic separation leads to new species." },
      { q: "Sympatric speciation?", a: "Same area; polyploidy or niche shift." },
      { q: "Prezygotic barrier?", a: "Prevents fertilization." },
      { q: "Postzygotic barrier?", a: "Hybrid inviable or sterile." },
      { q: "Polyploidy?", a: "Extra chromosome sets — instant speciation." },
    ],
  ),
  mk(7, "7.11", "Variations in Populations",
    "Variation from mutation + recombination + migration. Selection acts on variation.",
    [
      "Mutation: raw source of variation.",
      "Recombination: shuffles existing alleles.",
      "Gene flow: migration brings new alleles.",
      "Genetic drift: random allele changes, stronger in small populations.",
      "Bottleneck and founder effects reduce diversity.",
    ],
    "Why is genetic drift more powerful in small populations?",
    "Random sampling has bigger effects on allele frequencies when few individuals contribute to next generation.",
    [
      { q: "Sources of variation?", a: "Mutation, recombination, gene flow." },
      { q: "Genetic drift?", a: "Random changes in allele frequency." },
      { q: "Bottleneck?", a: "Population crash → reduced diversity." },
      { q: "Founder effect?", a: "Small group founds new population with limited alleles." },
      { q: "When does drift matter most?", a: "Small populations." },
    ],
  ),
  mk(7, "7.12", "Origins of Life on Earth",
    "Earth ~4.6 Bya. Primordial soup, RNA world, endosymbiosis, photosynthesis enriched atmosphere.",
    [
      "Miller-Urey (1953): abiotic amino acid synthesis under early Earth conditions.",
      "RNA world hypothesis: RNA both stored info and catalyzed reactions.",
      "Prokaryotes ~3.5 Bya.",
      "Oxygenic photosynthesis → O₂ buildup (Great Oxygenation Event ~2.4 Bya).",
      "Endosymbiosis led to eukaryotes.",
    ],
    "Why is the RNA world hypothesis compelling?",
    "RNA can both carry genetic information AND catalyze reactions (ribozymes) — could have been both gene and enzyme before DNA/protein split emerged.",
    [
      { q: "Miller-Urey showed?", a: "Abiotic synthesis of amino acids possible." },
      { q: "RNA world?", a: "Early life used RNA for info + catalysis." },
      { q: "Ribozyme?", a: "Catalytically active RNA." },
      { q: "Great Oxygenation Event?", a: "Photosynthesis added O₂ to atmosphere (~2.4 Bya)." },
      { q: "Endosymbiosis?", a: "Engulfed bacteria became mitochondria/chloroplasts." },
    ],
  ),
  mk(8, "8.1", "Responses to the Environment",
    "Organisms respond to stimuli via behavior (ethology), physiology, and evolution.",
    [
      "Innate vs learned behavior.",
      "Kinesis: nondirectional response to stimulus.",
      "Taxis: directional (phototaxis, chemotaxis).",
      "Circadian rhythms: internal clocks.",
    ],
    "Difference between taxis and kinesis?",
    "Taxis = directional (toward/away from stimulus). Kinesis = random activity changes based on stimulus intensity.",
    [
      { q: "Innate behavior?", a: "Genetically programmed." },
      { q: "Learned behavior?", a: "Modified by experience." },
      { q: "Taxis?", a: "Directional response to stimulus." },
      { q: "Kinesis?", a: "Nondirectional activity change." },
      { q: "Circadian rhythm?", a: "~24-hour internal cycle." },
    ],
  ),
  mk(8, "8.2", "Energy Flow Through Ecosystems",
    "Energy flows one-way through food chains; ~10% transferred per trophic level.",
    [
      "Producers → primary consumers → secondary → tertiary → decomposers.",
      "~10% rule: most energy lost as heat between levels.",
      "Energy pyramid narrows upward.",
      "Biomass pyramid usually follows energy pyramid.",
    ],
    "Why are top predators rare?",
    "Only ~10% of energy transfers per trophic level, so sustaining top predators requires massive producer biomass.",
    [
      { q: "10% rule?", a: "Only ~10% of energy transfers per trophic level." },
      { q: "Producers?", a: "Autotrophs (plants, algae, cyanobacteria)." },
      { q: "Decomposers?", a: "Bacteria, fungi — recycle nutrients." },
      { q: "Why pyramid narrows?", a: "Energy loss at each step." },
      { q: "Gross vs net primary productivity?", a: "Gross = total energy captured; net = after respiration." },
    ],
  ),
  mk(8, "8.3", "Population Ecology",
    "Populations grow exponentially then logistically as resources limit.",
    [
      "Exponential: dN/dt = rN (unlimited).",
      "Logistic: dN/dt = rN(1 − N/K), K = carrying capacity.",
      "r = per capita growth rate.",
      "Real populations fluctuate around K.",
    ],
    "Why does logistic growth level off?",
    "As population approaches carrying capacity K, competition for limited resources slows growth until births = deaths.",
    [
      { q: "Exponential growth equation?", a: "dN/dt = rN" },
      { q: "Logistic growth?", a: "dN/dt = rN(1 − N/K)" },
      { q: "K?", a: "Carrying capacity." },
      { q: "r?", a: "Per capita growth rate." },
      { q: "Real populations?", a: "Fluctuate around K due to environmental variation." },
    ],
  ),
  mk(8, "8.4", "Effect of Density on Populations",
    "Density-dependent (disease, competition) vs density-independent (weather) limits.",
    [
      "Density-dependent: effect increases with density (disease, competition, predation).",
      "Density-independent: effect independent of density (extreme weather, fire).",
      "Both shape population size.",
      "K-selected vs r-selected life histories respond differently.",
    ],
    "Is a flood density-dependent or density-independent?",
    "Density-independent — kills whether density is high or low.",
    [
      { q: "Density-dependent factor?", a: "Effect scales with density (disease, competition)." },
      { q: "Density-independent factor?", a: "Effect independent of density (weather, fire)." },
      { q: "K-selected species?", a: "Few offspring, high parental care." },
      { q: "r-selected species?", a: "Many offspring, little care." },
      { q: "Example of density-dependent?", a: "Disease transmission." },
    ],
  ),
  mk(8, "8.5", "Community Ecology",
    "Interactions: competition, predation, symbiosis (mutualism, commensalism, parasitism).",
    [
      "Competition: both harmed (-/-).",
      "Predation, parasitism: one gains, one loses (+/-).",
      "Mutualism: both gain (+/+).",
      "Commensalism: one gains, other unaffected (+/0).",
      "Niche: functional role.",
      "Competitive exclusion: two species can't share identical niche.",
    ],
    "Example of mutualism?",
    "Mycorrhizae: fungus helps plant absorb nutrients; plant provides sugars to fungus.",
    [
      { q: "Mutualism?", a: "Both benefit (+/+)" },
      { q: "Commensalism?", a: "One benefits, other unaffected (+/0)" },
      { q: "Parasitism?", a: "One benefits, other harmed (+/-)" },
      { q: "Niche?", a: "Species' role in community." },
      { q: "Competitive exclusion?", a: "Two species can't share identical niche." },
    ],
  ),
  mk(8, "8.6", "Biodiversity",
    "Measured at genetic, species, and ecosystem levels. Higher diversity → more resilience.",
    [
      "Genetic diversity: alleles within species.",
      "Species diversity: number and evenness.",
      "Ecosystem diversity: habitats and ecosystems.",
      "Keystone species: disproportionate impact (sea otters, wolves).",
    ],
    "What's a keystone species?",
    "A species with disproportionately large effect on community relative to its abundance (e.g., sea otters controlling sea urchins → kelp forests thrive).",
    [
      { q: "Three levels of biodiversity?", a: "Genetic, species, ecosystem." },
      { q: "Keystone species?", a: "Disproportionate impact relative to abundance." },
      { q: "Example of keystone?", a: "Sea otter, wolf, beaver." },
      { q: "Species richness?", a: "Number of species." },
      { q: "Species evenness?", a: "How equal abundance across species." },
    ],
  ),
  mk(8, "8.7", "Disruptions in Ecosystems",
    "Human activities + natural events: climate change, invasive species, pollution, habitat loss.",
    [
      "Habitat destruction: #1 driver of extinction.",
      "Climate change: shifting ranges, timing, ocean acidification.",
      "Invasive species: outcompete natives.",
      "Pollution: toxins, eutrophication, ocean plastics.",
      "Conservation: protected areas, restoration, regulation.",
    ],
    "Why do invasive species often dominate?",
    "Lack of natural predators/competitors/diseases in the new environment allows unchecked growth.",
    [
      { q: "Leading cause of extinction?", a: "Habitat loss." },
      { q: "Climate change effects?", a: "Range shifts, phenology shifts, ocean acidification." },
      { q: "Invasive species example?", a: "Zebra mussels, Burmese python, kudzu." },
      { q: "Eutrophication?", a: "Nutrient enrichment → algal blooms → dead zones." },
      { q: "Conservation strategy?", a: "Protected areas, restoration, regulation." },
    ],
  ),
];
