import type { Lesson } from "@/lib/topics";

/** AP Computer Science A — one Lesson per CED topic across all 10 units (55 topics). */

const CSA = "https://runestone.academy/ns/books/published/csawesome/index.html";

const U = {
  1: "Primitive Types",
  2: "Using Objects",
  3: "Boolean Expressions and if Statements",
  4: "Iteration",
  5: "Writing Classes",
  6: "Array",
  7: "ArrayList",
  8: "2D Array",
  9: "Inheritance",
  10: "Recursion",
};

const mk = (
  unit: keyof typeof U,
  id: string,
  title: string,
  blurb: string,
  keyIdeas: string[],
  sampleProblem: string,
  sampleWalkthrough: string,
  flashcards: { q: string; a: string }[]
): Lesson => ({
  slug: `csa-${id.replace(".", "-")}`,
  title,
  courses: [{ courseSlug: "ap-cs-a", unitNumber: unit, unitTitle: U[unit] }],
  blurb,
  keyIdeas,
  sampleProblem,
  sampleWalkthrough,
  flashcards,
  links: [{ title: "CSAwesome", url: CSA, source: "CSAwesome" }],
});

export const AP_CS_A_LESSONS: Lesson[] = [
  mk(1, "1.1", "Why Programming? Why Java?",
    "Java: compiled, statically-typed, OOP, runs on JVM (write once, run anywhere).",
    [
      "Compiled to bytecode, run on JVM.",
      "Statically typed (must declare types).",
      "Object-oriented (classes, inheritance, polymorphism).",
      "Portable — JVM available on most platforms.",
    ],
    "What does Java's 'write once, run anywhere' mean?",
    "Compile to bytecode; bytecode runs on any platform with a JVM — no recompilation needed.",
    [
      { q: "Java compiled to?", a: "Bytecode (.class files)" },
      { q: "JVM?", a: "Java Virtual Machine — runs bytecode" },
      { q: "Java typing?", a: "Statically typed" },
      { q: "Java paradigm?", a: "Object-oriented" },
      { q: "File extension?", a: ".java (source), .class (bytecode)" },
    ],
  ),
  mk(1, "1.2", "Variables and Data Types",
    "Primitive types: int, double, boolean, char. Must declare type.",
    [
      "int: 32-bit integer.",
      "double: 64-bit float.",
      "boolean: true/false.",
      "char: single character ('a').",
      "String (not primitive) for text.",
    ],
    "Declare an int variable named count and set to 5.",
    "int count = 5;",
    [
      { q: "Four primitive types in AP?", a: "int, double, boolean, char" },
      { q: "int range?", a: "~-2.1B to 2.1B (32-bit)" },
      { q: "double vs float?", a: "double is 64-bit (AP uses double)" },
      { q: "boolean values?", a: "true or false" },
      { q: "String — primitive?", a: "No — reference type" },
    ],
  ),
  mk(1, "1.3", "Expressions and Assignment Statements",
    "Arithmetic: + − * / %. Integer vs. double division.",
    [
      "int / int = int (truncates).",
      "int / double = double.",
      "% = modulus (remainder).",
      "Operator precedence: * / % before + −.",
      "Parentheses override.",
    ],
    "7 / 2 in Java?",
    "3 (integer division truncates, doesn't round).",
    [
      { q: "7 / 2 in int?", a: "3 (truncated)" },
      { q: "7.0 / 2?", a: "3.5" },
      { q: "7 % 3?", a: "1" },
      { q: "Order of operations?", a: "* / % first, then + −" },
      { q: "Int promoted to double when?", a: "When mixed in expression" },
    ],
  ),
  mk(1, "1.4", "Compound Assignment Operators",
    "+=, -=, *=, /=, %=, ++, -- shortcuts.",
    [
      "x += 5 same as x = x + 5.",
      "x++ post-increment (use then add).",
      "++x pre-increment (add then use).",
      "Works for *, /, %, - too.",
    ],
    "int x = 5; x += 3;. Value of x?",
    "8 (equivalent to x = x + 3).",
    [
      { q: "x += 5?", a: "x = x + 5" },
      { q: "x++?", a: "x = x + 1 (post: use then increment)" },
      { q: "++x?", a: "x = x + 1 (pre: increment then use)" },
      { q: "x *= 2?", a: "x = x * 2" },
      { q: "x -= 1 alternative?", a: "x-- or --x" },
    ],
  ),
  mk(1, "1.5", "Casting and Ranges of Variables",
    "(int) and (double) cast. int range ~±2.1B; overflow silent.",
    [
      "Cast: (type) value.",
      "int → double: automatic widening.",
      "double → int: explicit cast; truncates.",
      "Integer overflow: wraps without warning.",
      "Math.abs, Math.max, Math.min common.",
    ],
    "(int) 3.7?",
    "3 (truncates decimal, doesn't round).",
    [
      { q: "Cast syntax?", a: "(type) value" },
      { q: "(int) 3.9?", a: "3 (truncates)" },
      { q: "Widening?", a: "int → double (automatic)" },
      { q: "Narrowing?", a: "double → int (explicit cast)" },
      { q: "Integer overflow?", a: "Wraps around silently" },
    ],
  ),
  mk(2, "2.1", "Objects: Instances of Classes",
    "Object = instance of class. Class is a blueprint.",
    [
      "Class: template/blueprint.",
      "Object: instance of a class.",
      "Reference variable: holds object address.",
      "Stack (primitives) vs. heap (objects).",
    ],
    "Is String str = 'hello' an object?",
    "Yes — String is a class; str is a reference to a String object.",
    [
      { q: "Class?", a: "Blueprint for objects" },
      { q: "Object?", a: "Instance of a class" },
      { q: "Reference variable?", a: "Holds address of object on heap" },
      { q: "Where primitives stored?", a: "Stack" },
      { q: "Where objects stored?", a: "Heap" },
    ],
  ),
  mk(2, "2.2", "Creating and Storing Objects (Instantiation)",
    "new keyword creates object. Constructor initializes it.",
    [
      "new ClassName(args) creates object.",
      "Calls constructor.",
      "Returns reference to new object.",
      "Null = no object assigned.",
    ],
    "Create a new String: String s = new String(\"hi\");",
    "Allocates memory on heap, runs String constructor with \"hi\", returns reference stored in s.",
    [
      { q: "new keyword?", a: "Creates object instance" },
      { q: "Constructor?", a: "Initializes new object" },
      { q: "Null?", a: "No object assigned" },
      { q: "String literal?", a: "Special — can omit new" },
      { q: "Multiple references?", a: "Multiple variables can point to same object" },
    ],
  ),
  mk(2, "2.3", "Calling a Void Method",
    "object.method(); runs but returns nothing.",
    [
      "void: no return value.",
      "Call with object.method() syntax.",
      "Static methods: ClassName.method().",
      "Often perform side effects (print, modify).",
    ],
    "What does System.out.println(\"Hi\") do?",
    "Calls println (void method) on System.out; prints 'Hi' with newline; returns nothing.",
    [
      { q: "void return type?", a: "Nothing returned" },
      { q: "Method call syntax?", a: "object.methodName(args)" },
      { q: "Static method call?", a: "ClassName.method()" },
      { q: "System.out.println?", a: "Print line (void method)" },
      { q: "Dot operator?", a: "Access method or field" },
    ],
  ),
  mk(2, "2.4", "Calling a Void Method with Parameters",
    "Pass arguments in parentheses. Type must match parameter.",
    [
      "Parameter: variable in method signature.",
      "Argument: value passed in.",
      "Types must match.",
      "Java passes by value (copies for primitives; copies references for objects).",
    ],
    "void greet(String name) called as greet(\"Alice\")?",
    "Passes \"Alice\" as the name parameter; method body can use it.",
    [
      { q: "Parameter vs argument?", a: "Parameter in signature; argument passed." },
      { q: "Java parameter passing?", a: "Pass by value (copies)" },
      { q: "For objects?", a: "Reference copied — can modify object" },
      { q: "Type mismatch?", a: "Compile error" },
      { q: "Order matters?", a: "Yes — positional" },
    ],
  ),
  mk(2, "2.5", "Calling a Non-void Method",
    "Returns value; use or store it.",
    [
      "Non-void methods return a value.",
      "Store result: int x = obj.method();",
      "Can use in expression or chain: obj.a().b().",
      "Return type declared in signature.",
    ],
    "int len = \"hello\".length();. Value of len?",
    "5 — length() returns number of characters.",
    [
      { q: "Non-void method?", a: "Returns a value" },
      { q: "Store return?", a: "int x = obj.method();" },
      { q: "Chain calls?", a: "obj.a().b() — if a returns object with b()" },
      { q: "Return type?", a: "In method signature" },
      { q: "length() of \"hello\"?", a: "5" },
    ],
  ),
  mk(2, "2.6", "String Objects: Concatenation, Literals, and More",
    "Strings are immutable; + concatenates.",
    [
      "+ concatenates strings (or string + anything).",
      "Immutable: can't change existing String; creates new one.",
      "Literals: \"text\" are String objects.",
      "equals() for content; == for reference.",
    ],
    "\"a\" + 1 in Java?",
    "\"a1\" — int converted to String and concatenated.",
    [
      { q: "String concatenation?", a: "+ operator" },
      { q: "Strings immutable?", a: "Yes — modifications make new Strings" },
      { q: "\"a\" + 1?", a: "\"a1\"" },
      { q: "Compare content?", a: "s1.equals(s2)" },
      { q: "== for Strings?", a: "Compares references, not content" },
    ],
  ),
  mk(2, "2.7", "String Methods",
    "length, substring, indexOf, equals, compareTo, charAt.",
    [
      "length(): # of characters.",
      "substring(start, end): substring from start (inclusive) to end (exclusive).",
      "indexOf(ch): position of character (-1 if not found).",
      "equals(s): content equality.",
      "compareTo(s): -/0/+ based on alphabetical.",
      "charAt(i): char at index i.",
    ],
    "\"Programming\".substring(0, 4)?",
    "\"Prog\" — from index 0 to 3 inclusive.",
    [
      { q: "length()?", a: "Number of characters" },
      { q: "substring(s, e)?", a: "Chars from index s (inc) to e (exc)" },
      { q: "indexOf(c)?", a: "First index of c or -1" },
      { q: "charAt(i)?", a: "Character at index i" },
      { q: "compareTo returns?", a: "Negative, 0, or positive (alphabetical)" },
    ],
  ),
  mk(2, "2.8", "Wrapper Classes: Integer and Double",
    "Wrap primitives in objects. Autoboxing/unboxing automatic.",
    [
      "Integer: object wrapping int.",
      "Double: object wrapping double.",
      "Autoboxing: int → Integer automatic.",
      "Unboxing: Integer → int automatic.",
      "Needed for collections (ArrayList<Integer>).",
    ],
    "ArrayList<int> — legal?",
    "No — use ArrayList<Integer>. Collections need objects.",
    [
      { q: "Integer class?", a: "Wrapper for int" },
      { q: "Double class?", a: "Wrapper for double" },
      { q: "Autoboxing?", a: "Primitive → wrapper automatically" },
      { q: "Unboxing?", a: "Wrapper → primitive" },
      { q: "Why need wrappers?", a: "Collections (ArrayList) need objects" },
    ],
  ),
  mk(2, "2.9", "Using the Math Class",
    "Static methods: abs, pow, sqrt, random, max, min.",
    [
      "Static — call as Math.method().",
      "Math.abs(x): absolute value.",
      "Math.pow(b, e): b^e (returns double).",
      "Math.sqrt(x): square root.",
      "Math.random(): [0, 1).",
      "Math.max/min(a, b).",
    ],
    "Generate random integer 1-10 inclusive.",
    "(int)(Math.random() * 10) + 1",
    [
      { q: "Math class?", a: "Static utility methods" },
      { q: "Math.pow returns?", a: "double" },
      { q: "Math.random() range?", a: "[0.0, 1.0)" },
      { q: "Random int 0-9?", a: "(int)(Math.random() * 10)" },
      { q: "Math.abs?", a: "Absolute value" },
    ],
  ),
  mk(3, "3.1", "Boolean Expressions",
    "Comparisons: ==, !=, <, >, <=, >=. Return boolean.",
    [
      "==, != : equality (primitives).",
      "For String use .equals().",
      "< > <= >= : comparison.",
      "Return true or false.",
    ],
    "5 > 3 && 2 < 1 evaluates to?",
    "false — second part is false.",
    [
      { q: "Equality for primitives?", a: "==" },
      { q: "Equality for Strings?", a: ".equals()" },
      { q: "Logical AND?", a: "&&" },
      { q: "Logical OR?", a: "||" },
      { q: "NOT?", a: "!" },
    ],
  ),
  mk(3, "3.2", "if Statements and Control Flow",
    "if (condition) { ... } executes block if true.",
    [
      "if (condition) { block }.",
      "Condition must be boolean.",
      "Block runs if true; skipped otherwise.",
      "Without braces: only next statement.",
    ],
    "Write if statement printing 'positive' when x > 0.",
    "if (x > 0) { System.out.println(\"positive\"); }",
    [
      { q: "if syntax?", a: "if (condition) { ... }" },
      { q: "Condition type?", a: "boolean" },
      { q: "No braces?", a: "Only next statement in if block" },
      { q: "Block?", a: "Code in { }" },
      { q: "False condition?", a: "Block skipped" },
    ],
  ),
  mk(3, "3.3", "if-else Statements",
    "if-else: two-way branch.",
    [
      "if (cond) {A} else {B}.",
      "A runs if true; B if false.",
      "Exactly one block runs.",
      "Indent for clarity.",
    ],
    "Print 'pos' if x > 0, else 'non-pos'.",
    "if (x > 0) System.out.println(\"pos\"); else System.out.println(\"non-pos\");",
    [
      { q: "if-else syntax?", a: "if (cond) {A} else {B}" },
      { q: "Blocks that run?", a: "Exactly one" },
      { q: "else without if?", a: "Syntax error" },
      { q: "Ternary alternative?", a: "cond ? A : B" },
      { q: "Style?", a: "Use braces and indent" },
    ],
  ),
  mk(3, "3.4", "else if Statements",
    "Multiple conditions in sequence.",
    [
      "if ... else if ... else chain.",
      "First true branch runs; rest skipped.",
      "Order matters — check most specific first.",
      "else is optional.",
    ],
    "Grade assignment: 90+=A, 80+=B, else F.",
    "if (g >= 90) grade=\"A\"; else if (g >= 80) grade=\"B\"; else grade=\"F\";",
    [
      { q: "else if chain?", a: "Sequential condition check" },
      { q: "Blocks that run?", a: "First true, at most one" },
      { q: "Order important?", a: "Yes — check specific first" },
      { q: "else optional?", a: "Yes" },
      { q: "switch alternative?", a: "For equality checks on single value" },
    ],
  ),
  mk(3, "3.5", "Compound Boolean Expressions",
    "&&, || combine conditions. Short-circuit evaluation.",
    [
      "&& : AND (both true).",
      "|| : OR (either true).",
      "Short-circuit: stops evaluating when result known.",
      "Use for safe checks: if (obj != null && obj.method())",
    ],
    "Why does 'if (x != 0 && 10/x > 2)' not throw error when x=0?",
    "Short-circuit: x != 0 is false → && result is false; 10/x never evaluated.",
    [
      { q: "&& operator?", a: "Logical AND" },
      { q: "|| operator?", a: "Logical OR" },
      { q: "Short-circuit?", a: "Stop evaluating when result known" },
      { q: "&& when first false?", a: "Skip second operand" },
      { q: "|| when first true?", a: "Skip second operand" },
    ],
  ),
  mk(3, "3.6", "Equivalent Boolean Expressions",
    "De Morgan's laws and simplifications.",
    [
      "!(A && B) ≡ !A || !B.",
      "!(A || B) ≡ !A && !B.",
      "Simplify conditions for clarity.",
      "!(x < 5) equivalent to x >= 5.",
    ],
    "Simplify: !(x > 0 && y < 10).",
    "x <= 0 || y >= 10 (De Morgan's + negation).",
    [
      { q: "De Morgan's (AND)?", a: "!(A && B) ≡ !A || !B" },
      { q: "De Morgan's (OR)?", a: "!(A || B) ≡ !A && !B" },
      { q: "!(x < 5)?", a: "x >= 5" },
      { q: "!(x == 3)?", a: "x != 3" },
      { q: "Why simplify?", a: "Clarity, avoid bugs" },
    ],
  ),
  mk(3, "3.7", "Comparing Objects",
    "== compares references; equals() compares content.",
    [
      "== : same object (reference).",
      ".equals() : content equality.",
      "Strings: always use .equals() for content.",
      "null check before .equals().",
    ],
    "\"cat\" == new String(\"cat\") — true or false?",
    "false — == compares references, not content. Use .equals().",
    [
      { q: "== for objects?", a: "Reference equality" },
      { q: ".equals() for objects?", a: "Content equality (if properly implemented)" },
      { q: "String compare?", a: ".equals()" },
      { q: "Before .equals()?", a: "null-check to avoid NullPointerException" },
      { q: "\"cat\" == \"cat\" (literals)?", a: "true (same interned literal)" },
    ],
  ),
  mk(4, "4.1", "while Loops",
    "while (cond) { ... } repeats while condition true.",
    [
      "Check condition before each iteration.",
      "If false initially, body never runs.",
      "Must update variable to avoid infinite loop.",
      "Common for 'unknown count'.",
    ],
    "Print 1 to 5 with a while loop.",
    "int i=1; while (i<=5) { System.out.println(i); i++; }",
    [
      { q: "while loop syntax?", a: "while (cond) { ... }" },
      { q: "When check condition?", a: "Before each iteration" },
      { q: "Infinite loop?", a: "Condition never becomes false" },
      { q: "Body runs minimum?", a: "0 times" },
      { q: "Use case?", a: "Unknown number of iterations" },
    ],
  ),
  mk(4, "4.2", "for Loops",
    "for (init; cond; update) — common for counting.",
    [
      "for (init; cond; update) { body }.",
      "Check cond before each; update after each.",
      "Equivalent to while with extra syntax.",
      "Best for known number of iterations.",
    ],
    "for loop printing 0 to 9.",
    "for (int i = 0; i < 10; i++) System.out.println(i);",
    [
      { q: "for loop parts?", a: "init; cond; update" },
      { q: "When update?", a: "After each iteration" },
      { q: "When check cond?", a: "Before each iteration" },
      { q: "Equivalent while?", a: "while with manual init and update" },
      { q: "Best for?", a: "Known iteration count" },
    ],
  ),
  mk(4, "4.3", "Developing Algorithms Using Strings",
    "Traverse with for loop or charAt. Count chars, reverse, palindrome.",
    [
      "Iterate indices 0 to length() - 1.",
      "charAt(i) gets character.",
      "Can build new String by concatenation.",
      "substring slices.",
    ],
    "Count 'a's in a String s.",
    "int count=0; for (int i=0; i<s.length(); i++) if (s.charAt(i)=='a') count++;",
    [
      { q: "String traversal?", a: "for loop with charAt" },
      { q: "last index?", a: "length() - 1" },
      { q: "Build new String?", a: "Concatenation or StringBuilder" },
      { q: "Slice a String?", a: "substring(start, end)" },
      { q: "Case-insensitive compare?", a: ".equalsIgnoreCase()" },
    ],
  ),
  mk(4, "4.4", "Nested Iteration",
    "Loops inside loops. Common for 2D data.",
    [
      "Outer loop × inner loop = total iterations.",
      "Used for 2D arrays, pattern printing.",
      "Watch out for variable name conflicts.",
      "Performance: O(n×m).",
    ],
    "Print multiplication table 1-5.",
    "for (int i=1; i<=5; i++) { for (int j=1; j<=5; j++) System.out.print(i*j + \" \"); System.out.println(); }",
    [
      { q: "Nested loop total?", a: "Outer × Inner iterations" },
      { q: "Common use?", a: "2D arrays, pattern printing" },
      { q: "Complexity?", a: "O(n×m)" },
      { q: "Inner loop variable?", a: "Use different name (j)" },
      { q: "Watch for?", a: "Variable conflicts, off-by-one" },
    ],
  ),
  mk(4, "4.5", "Informal Code Analysis",
    "Count operations to understand runtime.",
    [
      "Count iterations / operations.",
      "Big O describes growth.",
      "Single loop O(n); nested O(n²).",
      "AP uses informal counting.",
    ],
    "How many iterations: for (int i=0; i<n; i++) for (int j=0; j<n; j++)?",
    "n² iterations — nested quadratic.",
    [
      { q: "Single loop iterations?", a: "O(n) — linear" },
      { q: "Nested loop both n?", a: "O(n²) — quadratic" },
      { q: "for(int i=0; i<n; i++) for(int j=0; j<i; j++)?", a: "~n²/2 — still O(n²)" },
      { q: "Code analysis goal?", a: "Understand runtime behavior" },
      { q: "AP expectation?", a: "Count iterations informally" },
    ],
  ),
  mk(5, "5.1", "Anatomy of a Class",
    "Class has fields (state), constructors, methods (behavior).",
    [
      "Fields: instance variables.",
      "Constructors: initialize new objects.",
      "Methods: define behavior.",
      "Access: private/public.",
    ],
    "Basic class skeleton:",
    "public class Dog { private String name; public Dog(String n) { name = n; } public String getName() { return name; } }",
    [
      { q: "Fields?", a: "Instance variables storing state" },
      { q: "Constructor?", a: "Initializes object; name = class name" },
      { q: "Method?", a: "Defines behavior" },
      { q: "Access modifiers?", a: "public, private (AP)" },
      { q: "Default access field visibility?", a: "private recommended" },
    ],
  ),
  mk(5, "5.2", "Constructors",
    "Same name as class; no return type; initializes object state.",
    [
      "Same name as class.",
      "No return type.",
      "Can be overloaded (multiple).",
      "this(args) calls another constructor.",
      "Default no-arg if none defined.",
    ],
    "Dog constructor accepting name and age:",
    "public Dog(String name, int age) { this.name = name; this.age = age; }",
    [
      { q: "Constructor name?", a: "Same as class" },
      { q: "Return type?", a: "None (not even void)" },
      { q: "Overloading?", a: "Multiple constructors with different signatures" },
      { q: "this(args)?", a: "Calls another constructor" },
      { q: "No constructor written?", a: "Default no-arg provided" },
    ],
  ),
  mk(5, "5.3", "Documentation with Comments",
    "/* */ block, // line, /** Javadoc */.",
    [
      "// single-line comment.",
      "/* multi */ block comment.",
      "/** */ Javadoc for documentation.",
      "Tags: @param, @return, @author.",
    ],
    "Write Javadoc for getName() returning name.",
    "/** Returns the dog's name. @return the name */\npublic String getName() { return name; }",
    [
      { q: "Line comment?", a: "//" },
      { q: "Block comment?", a: "/* */" },
      { q: "Javadoc?", a: "/** */" },
      { q: "@param tag?", a: "Describes parameter" },
      { q: "@return tag?", a: "Describes return value" },
    ],
  ),
  mk(5, "5.4", "Accessor Methods",
    "Getters return field values. Convention: getX().",
    [
      "Getter: returns field.",
      "Convention: getName(), getAge().",
      "boolean: isX() or hasX().",
      "Typically public.",
    ],
    "Accessor for field 'age':",
    "public int getAge() { return age; }",
    [
      { q: "Accessor?", a: "Method returning field (getter)" },
      { q: "Naming convention?", a: "getFieldName()" },
      { q: "Boolean getter?", a: "isX() or hasX()" },
      { q: "Visibility?", a: "public" },
      { q: "Why use getters?", a: "Encapsulation — control access" },
    ],
  ),
  mk(5, "5.5", "Mutator Methods",
    "Setters modify field values. Convention: setX(val).",
    [
      "Setter: modifies field.",
      "Convention: setX(val).",
      "Typically void return.",
      "Can validate input.",
    ],
    "Mutator for age:",
    "public void setAge(int age) { this.age = age; }",
    [
      { q: "Mutator?", a: "Method modifying field (setter)" },
      { q: "Naming?", a: "setFieldName(value)" },
      { q: "Return type?", a: "Usually void" },
      { q: "this.field?", a: "Refers to current object's field" },
      { q: "Validation?", a: "Can check parameter before assign" },
    ],
  ),
  mk(5, "5.6", "Writing Methods",
    "Method signature: access, return, name, parameters.",
    [
      "Signature: public/private return name(params).",
      "Body in braces.",
      "return statement for non-void.",
      "Parameters: types + names.",
    ],
    "Method summing two ints:",
    "public int sum(int a, int b) { return a + b; }",
    [
      { q: "Method signature parts?", a: "Access, return type, name, parameters" },
      { q: "Return type void?", a: "No return value" },
      { q: "return statement?", a: "Exits method with value" },
      { q: "Parameter types?", a: "Required in Java" },
      { q: "Return type match?", a: "Must match declared type" },
    ],
  ),
  mk(5, "5.7", "Static Variables and Methods",
    "Belong to class, not instance. Access: ClassName.field.",
    [
      "static: belongs to class.",
      "Access: ClassName.staticMember.",
      "Shared across instances.",
      "Cannot use 'this' in static.",
    ],
    "Math.PI and Math.sqrt() — why can we use without 'new Math()'?",
    "They're static — belong to Math class, no instance needed.",
    [
      { q: "static field?", a: "Shared across all instances" },
      { q: "static method?", a: "Called on class, not instance" },
      { q: "Access syntax?", a: "ClassName.member" },
      { q: "this in static?", a: "Not allowed (no instance)" },
      { q: "Example?", a: "Math.PI, System.out" },
    ],
  ),
  mk(5, "5.8", "Scope and Access",
    "Variable visibility: local (in method), instance (in object), class (static).",
    [
      "Local: declared in method.",
      "Instance: declared in class.",
      "Static: on class.",
      "Inner scope shadows outer.",
      "private: class-only; public: anywhere.",
    ],
    "What happens if I declare a local variable with same name as instance variable?",
    "Local shadows instance; use this.name to access instance explicitly.",
    [
      { q: "Local variable?", a: "Inside method, accessible only there" },
      { q: "Instance variable?", a: "Field of object" },
      { q: "Static variable?", a: "Class-level (one copy for all instances)" },
      { q: "Shadowing?", a: "Local with same name hides outer" },
      { q: "private access?", a: "Only in same class" },
    ],
  ),
  mk(5, "5.9", "this Keyword",
    "Refers to current object. Disambiguates fields from parameters.",
    [
      "this = current object.",
      "this.field: instance field.",
      "Useful when parameter/field share name.",
      "this(args): call another constructor.",
    ],
    "Why write 'this.name = name'?",
    "Disambiguates: right 'name' is parameter, left is instance field.",
    [
      { q: "this refers to?", a: "Current object" },
      { q: "this.field?", a: "Instance field (explicit)" },
      { q: "Use case?", a: "Parameter shadows field" },
      { q: "this(args)?", a: "Call another constructor" },
      { q: "In static method?", a: "Illegal (no instance)" },
    ],
  ),
  mk(5, "5.10", "Ethical and Social Implications of Computing Systems",
    "Privacy, security, bias, intellectual property concerns.",
    [
      "Privacy: data collection concerns.",
      "Security: vulnerabilities, hacking.",
      "Algorithmic bias: perpetuates discrimination.",
      "Intellectual property: copyright, patents.",
    ],
    "How might a hiring algorithm become biased?",
    "Training data reflects past hiring biases; algorithm learns and reproduces them against same demographics.",
    [
      { q: "Privacy concerns?", a: "Data collection, surveillance" },
      { q: "Algorithmic bias?", a: "Model inherits biases from training data" },
      { q: "IP types?", a: "Copyright, patent, trademark" },
      { q: "Example of bias?", a: "Facial recognition misidentifying minorities" },
      { q: "Mitigation?", a: "Diverse data, testing, transparency" },
    ],
  ),
  mk(6, "6.1", "Array Creation and Access",
    "int[] arr = new int[5]; arr[i] access.",
    [
      "Declaration: type[] name.",
      "Creation: new type[size].",
      "Index 0 to length-1.",
      "Default: 0 for numbers, null for objects, false for boolean.",
    ],
    "int[] arr = new int[3]; arr[0]?",
    "0 (default value for int).",
    [
      { q: "Array declaration?", a: "type[] name" },
      { q: "Array creation?", a: "new type[size]" },
      { q: "First index?", a: "0" },
      { q: "Last index?", a: "length - 1" },
      { q: "Length property?", a: "arr.length (no parens)" },
    ],
  ),
  mk(6, "6.2", "Traversing Arrays",
    "for loop with index; enhanced for loop for read-only.",
    [
      "for (int i=0; i<arr.length; i++).",
      "Read arr[i] or modify arr[i].",
      "Enhanced for: for (int x : arr) — read-only.",
      "Visit each once.",
    ],
    "Print all elements of arr:",
    "for (int i = 0; i < arr.length; i++) System.out.println(arr[i]);",
    [
      { q: "Traversal loop?", a: "for (int i=0; i<arr.length; i++)" },
      { q: "Enhanced for?", a: "for (type x : arr)" },
      { q: "Enhanced for — modify?", a: "Can't reassign array element" },
      { q: "arr.length?", a: "Size of array" },
      { q: "ArrayIndexOutOfBoundsException?", a: "Access index >= length" },
    ],
  ),
  mk(6, "6.3", "Enhanced for Loop for Arrays",
    "for (type x : arr) reads each element.",
    [
      "Cleaner when you don't need index.",
      "Read-only for modification.",
      "Works on arrays and Collections.",
      "Cannot modify the array itself.",
    ],
    "Sum all elements using enhanced for:",
    "int sum=0; for (int x : arr) sum += x;",
    [
      { q: "Enhanced for syntax?", a: "for (type x : arr)" },
      { q: "Read-only?", a: "Can't reassign arr index" },
      { q: "When to use?", a: "When don't need index" },
      { q: "Works on?", a: "Arrays and Collections" },
      { q: "Alternative?", a: "Regular for loop" },
    ],
  ),
  mk(6, "6.4", "Developing Algorithms Using Arrays",
    "Find min/max, sum, linear search, sorting.",
    [
      "Min/max: track best so far.",
      "Sum: accumulate.",
      "Linear search: check each.",
      "Selection sort, insertion sort (common AP).",
    ],
    "Find max in arr:",
    "int max = arr[0]; for (int i=1; i<arr.length; i++) if (arr[i] > max) max = arr[i];",
    [
      { q: "Find max?", a: "Track best so far through loop" },
      { q: "Linear search?", a: "Check each element" },
      { q: "Selection sort?", a: "Repeatedly find minimum and swap" },
      { q: "Array traversal direction?", a: "Usually left to right (index 0 up)" },
      { q: "Edge cases?", a: "Empty array, duplicates" },
    ],
  ),
  mk(7, "7.1", "Introduction to ArrayList",
    "Dynamic-size list: ArrayList<Integer> list = new ArrayList<>();",
    [
      "Resizable unlike array.",
      "Generic: ArrayList<Type>.",
      "Imports: import java.util.ArrayList;.",
      "Elements are objects (no primitives — use wrappers).",
    ],
    "Create an ArrayList of Strings:",
    "ArrayList<String> list = new ArrayList<>();",
    [
      { q: "ArrayList vs array?", a: "Dynamic size vs fixed" },
      { q: "ArrayList of ints?", a: "ArrayList<Integer> — wrapper" },
      { q: "Import?", a: "java.util.ArrayList" },
      { q: "Create empty?", a: "new ArrayList<>()" },
      { q: "Why wrapper?", a: "ArrayList requires object types" },
    ],
  ),
  mk(7, "7.2", "ArrayList Methods",
    "add, get, set, remove, size, contains.",
    [
      "add(x): append.",
      "add(i, x): insert at index.",
      "get(i): retrieve.",
      "set(i, x): replace.",
      "remove(i): delete and shift.",
      "size(): count.",
      "contains(x): true/false.",
    ],
    "Add 'hi' then retrieve it:",
    "list.add(\"hi\"); String s = list.get(0);",
    [
      { q: "Append?", a: "add(x)" },
      { q: "Insert?", a: "add(index, x)" },
      { q: "Get?", a: "get(index)" },
      { q: "Replace?", a: "set(index, x)" },
      { q: "Size?", a: "size() (with parens)" },
    ],
  ),
  mk(7, "7.3", "Traversing ArrayLists",
    "for (int i=0; i<list.size(); i++) or enhanced for.",
    [
      "Use size() not length.",
      "Index 0 to size()-1.",
      "Enhanced for works too.",
      "Careful removing during iteration.",
    ],
    "Sum an ArrayList<Integer>:",
    "int sum=0; for (int x : list) sum += x;",
    [
      { q: "ArrayList size method?", a: "size()" },
      { q: "Array length?", a: "length (no parens)" },
      { q: "Last index?", a: "size() - 1" },
      { q: "Remove during iteration?", a: "Dangerous — shifts indices" },
      { q: "Enhanced for?", a: "for (type x : list)" },
    ],
  ),
  mk(7, "7.4", "Developing Algorithms Using ArrayLists",
    "Iterate and modify carefully; consider iterating backwards when removing.",
    [
      "Traverse backwards when removing.",
      "Use contains to check membership.",
      "Accumulate results in new list.",
      "ArrayList<ArrayList<Type>> for 2D.",
    ],
    "Remove all negative numbers from ArrayList<Integer>:",
    "for (int i=list.size()-1; i>=0; i--) if (list.get(i) < 0) list.remove(i);",
    [
      { q: "Iterate when removing?", a: "Backward (avoid index shift bugs)" },
      { q: "contains method?", a: "Returns true if present" },
      { q: "2D ArrayList?", a: "ArrayList<ArrayList<Type>>" },
      { q: "Build result list?", a: "Accumulate in new ArrayList" },
      { q: "Why backward removal?", a: "Prevents index shift issues" },
    ],
  ),
  mk(7, "7.5", "Searching",
    "Linear: check each. Binary: on sorted, halve each time.",
    [
      "Linear search: O(n), works on any array.",
      "Binary search: O(log n), requires SORTED array.",
      "Linear: check each element.",
      "Binary: compare to middle, recurse on half.",
    ],
    "Best search for sorted array of 1M items?",
    "Binary search — O(log n) ~20 comparisons vs. linear's potential 1M.",
    [
      { q: "Linear search complexity?", a: "O(n)" },
      { q: "Binary search complexity?", a: "O(log n)" },
      { q: "Binary search requires?", a: "Sorted array" },
      { q: "Linear requires?", a: "Nothing (works on unsorted)" },
      { q: "Binary strategy?", a: "Compare to middle, halve" },
    ],
  ),
  mk(7, "7.6", "Sorting",
    "Selection sort: find min, swap. Insertion sort: build sorted section.",
    [
      "Selection: find min in rest, swap with current. O(n²).",
      "Insertion: insert next element into sorted prefix. O(n²).",
      "Both in-place and simple.",
      "More complex: merge sort, quick sort (not on AP).",
    ],
    "How does selection sort work?",
    "Find min in unsorted portion; swap with first unsorted; repeat. After n-1 passes, sorted.",
    [
      { q: "Selection sort?", a: "Find min, swap with current position" },
      { q: "Insertion sort?", a: "Insert each new element into sorted prefix" },
      { q: "Both complexity?", a: "O(n²)" },
      { q: "In-place?", a: "Yes — constant extra space" },
      { q: "Not on AP?", a: "Merge sort, quicksort" },
    ],
  ),
  mk(7, "7.7", "Ethical Issues Around Data Collection",
    "Consent, privacy, purpose limitation, security.",
    [
      "Consent: users should agree to data collection.",
      "Privacy: protect personal info.",
      "Purpose limitation: use data only for stated purpose.",
      "Security: prevent breaches.",
      "GDPR (EU), CCPA (CA) regulations.",
    ],
    "What's the main privacy concern with health app data?",
    "Sensitive personal health data could be shared with insurers, employers, or breached — harming users.",
    [
      { q: "Consent?", a: "Users agree to data collection" },
      { q: "Purpose limitation?", a: "Use data only for stated purpose" },
      { q: "GDPR?", a: "EU data protection regulation" },
      { q: "CCPA?", a: "California consumer privacy act" },
      { q: "Security breach?", a: "Unauthorized access to protected data" },
    ],
  ),
  mk(8, "8.1", "2D Arrays",
    "int[][] grid = new int[rows][cols]; access grid[r][c].",
    [
      "Declare: type[][] name.",
      "Create: new type[rows][cols].",
      "Access: arr[row][col].",
      "Rectangular (most common) or jagged.",
    ],
    "Create a 3x4 int 2D array; set element at row 1, col 2 to 7.",
    "int[][] grid = new int[3][4]; grid[1][2] = 7;",
    [
      { q: "2D array declaration?", a: "type[][] name" },
      { q: "Create 3x4?", a: "new type[3][4]" },
      { q: "Access row r col c?", a: "arr[r][c]" },
      { q: "Rows in grid?", a: "grid.length" },
      { q: "Cols in row r?", a: "grid[r].length" },
    ],
  ),
  mk(8, "8.2", "Traversing 2D Arrays",
    "Row-major: outer rows, inner cols. Nested for loops.",
    [
      "Nested for: rows then cols.",
      "Row-major traversal (typical).",
      "grid.length = rows; grid[r].length = cols in row r.",
      "Enhanced for works: outer over arrays, inner over elements.",
    ],
    "Sum all elements in 2D array grid:",
    "int sum=0; for (int r=0; r<grid.length; r++) for (int c=0; c<grid[r].length; c++) sum += grid[r][c];",
    [
      { q: "Row-major traversal?", a: "Outer rows, inner cols" },
      { q: "Column-major?", a: "Outer cols, inner rows" },
      { q: "grid.length?", a: "Number of rows" },
      { q: "grid[r].length?", a: "Number of cols in row r" },
      { q: "Enhanced for 2D?", a: "Outer over arrays; inner over elements" },
    ],
  ),
  mk(9, "9.1", "Creating Superclasses and Subclasses",
    "class Sub extends Super. Sub inherits fields and methods.",
    [
      "extends: subclass inherits from superclass.",
      "Single inheritance in Java.",
      "Subclass inherits public/protected members.",
      "Can add new members and override.",
    ],
    "Declare Dog extending Animal:",
    "public class Dog extends Animal { ... }",
    [
      { q: "extends keyword?", a: "Declares superclass" },
      { q: "Single inheritance?", a: "One direct parent in Java" },
      { q: "Inherit what?", a: "Public and protected members" },
      { q: "private members?", a: "Not directly accessible in subclass" },
      { q: "Add members in subclass?", a: "Yes — new fields and methods allowed" },
    ],
  ),
  mk(9, "9.2", "Writing Constructors for Subclasses",
    "super(args) calls parent constructor. Must be first line.",
    [
      "super(args): calls parent constructor.",
      "Must be first line in subclass constructor.",
      "Default super() if not specified.",
      "Subclass constructor initializes own fields after.",
    ],
    "Dog constructor calling Animal(String name):",
    "public Dog(String name, String breed) { super(name); this.breed = breed; }",
    [
      { q: "Call parent constructor?", a: "super(args)" },
      { q: "Position?", a: "First line of subclass constructor" },
      { q: "If not called?", a: "Implicit super() added" },
      { q: "After super?", a: "Initialize own fields" },
      { q: "super vs this?", a: "super = parent; this = current class" },
    ],
  ),
  mk(9, "9.3", "Overriding Methods",
    "Subclass provides new implementation. @Override annotation.",
    [
      "Same signature as parent method.",
      "@Override: optional but recommended.",
      "Specialization of parent behavior.",
      "Dynamic dispatch at runtime.",
    ],
    "Override speak() in Dog:",
    "@Override public String speak() { return \"Woof!\"; }",
    [
      { q: "Override?", a: "Redefine inherited method" },
      { q: "@Override?", a: "Annotation marking override" },
      { q: "Signature match?", a: "Must match parent's" },
      { q: "Overloading vs overriding?", a: "Overload: different sig; override: same sig in subclass" },
      { q: "Why override?", a: "Specialize behavior for subclass" },
    ],
  ),
  mk(9, "9.4", "super Keyword",
    "super.method() calls parent version; super(args) for constructor.",
    [
      "super.method(): call parent's version.",
      "super(args): parent constructor.",
      "Useful when extending vs. replacing behavior.",
      "this.method() for current class.",
    ],
    "Override but also use parent's behavior:",
    "public void foo() { super.foo(); /* additional */ }",
    [
      { q: "super.method()?", a: "Call parent's version" },
      { q: "Extend vs replace?", a: "super calls parent first, then add" },
      { q: "this vs super?", a: "this: current class; super: parent" },
      { q: "super in static?", a: "Not allowed" },
      { q: "Chain super?", a: "Cannot chain super.super." },
    ],
  ),
  mk(9, "9.5", "Creating References Using Inheritance Hierarchies",
    "Parent reference can hold subclass object. Animal a = new Dog();",
    [
      "Reference type determines accessible methods at compile time.",
      "Object type determines which override runs (runtime).",
      "Animal a = new Dog(); can call Animal methods.",
      "Polymorphism in action.",
    ],
    "Animal a = new Dog(); a.speak() calls which?",
    "Dog's speak() — dynamic dispatch uses actual object type.",
    [
      { q: "Animal a = new Dog()?", a: "Valid — upcasting" },
      { q: "Which methods callable?", a: "Those in reference type (Animal)" },
      { q: "Which override runs?", a: "Based on actual object (Dog)" },
      { q: "Dog d = new Animal()?", a: "Compile error unless explicit cast" },
      { q: "Downcasting?", a: "(Dog) a — risky; needs correct type" },
    ],
  ),
  mk(9, "9.6", "Polymorphism",
    "Same method call, different behavior based on object type.",
    [
      "Polymorphism = many forms.",
      "Runtime dispatch chooses method.",
      "Enables generic code handling related types.",
      "Override-based.",
    ],
    "Why is polymorphism useful?",
    "Write code that works with any subtype: loop through Animals, each speak()s its own way.",
    [
      { q: "Polymorphism means?", a: "Many forms — same call, different behavior" },
      { q: "Runtime dispatch?", a: "Actual method determined at runtime" },
      { q: "Enables?", a: "Generic code for related types" },
      { q: "Depends on?", a: "Inheritance and overriding" },
      { q: "Example?", a: "Array of Animals, each speak() differently" },
    ],
  ),
  mk(9, "9.7", "Object Superclass",
    "All classes inherit from Object. Methods: equals, toString, hashCode.",
    [
      "Object is root of all classes.",
      "Inherited methods: equals(), toString(), hashCode().",
      "Often override for meaningful behavior.",
      "Default toString(): class name + hash.",
    ],
    "Why override toString()?",
    "Default prints class name + memory hash. Custom toString() gives meaningful description.",
    [
      { q: "Object class?", a: "Ultimate superclass of all classes" },
      { q: "Inherited methods?", a: "equals, toString, hashCode" },
      { q: "Default toString?", a: "ClassName@hash" },
      { q: "Override toString for?", a: "Meaningful string representation" },
      { q: "Default equals?", a: "Reference equality (==)" },
    ],
  ),
  mk(10, "10.1", "Recursion",
    "Method calls itself. Base case stops recursion; recursive step reduces problem.",
    [
      "Base case: simplest scenario, returns directly.",
      "Recursive case: calls self with smaller problem.",
      "Must converge to base case.",
      "Uses stack; can cause StackOverflowError.",
    ],
    "Recursive factorial:",
    "public int fact(int n) { if (n <= 1) return 1; return n * fact(n-1); }",
    [
      { q: "Base case?", a: "Terminating condition" },
      { q: "Recursive case?", a: "Method calls itself with smaller input" },
      { q: "Without base case?", a: "Infinite recursion, StackOverflowError" },
      { q: "factorial(0) and (1)?", a: "Both 1 (base case)" },
      { q: "Recursion on stack?", a: "Each call uses stack frame" },
    ],
  ),
  mk(10, "10.2", "Recursive Searching and Sorting",
    "Binary search, merge sort naturally recursive.",
    [
      "Binary search recursion: check middle, recurse on half.",
      "Merge sort: divide, sort halves, merge.",
      "Both O(log n) and O(n log n) respectively.",
      "Elegant expressions of divide-and-conquer.",
    ],
    "Recursive binary search:",
    "int bs(int[] a, int k, int lo, int hi) { if (lo>hi) return -1; int m=(lo+hi)/2; if (a[m]==k) return m; if (a[m]<k) return bs(a,k,m+1,hi); return bs(a,k,lo,m-1); }",
    [
      { q: "Binary search complexity?", a: "O(log n)" },
      { q: "Merge sort complexity?", a: "O(n log n)" },
      { q: "Binary search base case?", a: "lo > hi (not found) or arr[mid] == target" },
      { q: "Divide and conquer?", a: "Split problem, solve parts, combine" },
      { q: "Why recursion suits?", a: "Natural for divide-and-conquer" },
    ],
  ),
];
