import type { Lesson } from "@/lib/topics";

/** AP Computer Science Principles — one Lesson per CED topic across 5 Big Ideas (35 topics). */

const CSP = "https://apcentral.collegeboard.org/courses/ap-computer-science-principles";

const U = {
  1: "Big Idea 1: Creative Development",
  2: "Big Idea 2: Data",
  3: "Big Idea 3: Algorithms and Programming",
  4: "Big Idea 4: Computer Systems and Networks",
  5: "Big Idea 5: Impact of Computing",
};

const mk = (
  unit: keyof typeof U,
  id: string,
  title: string,
  blurb: string,
  keyIdeas: string[],
  sampleProblem: string,
  sampleWalkthrough: string,
  flashcards: { q: string; a: string }[]
): Lesson => ({
  slug: `csp-${id.replace(".", "-")}`,
  title,
  courses: [{ courseSlug: "ap-cs-principles", unitNumber: unit, unitTitle: U[unit] }],
  blurb,
  keyIdeas,
  sampleProblem,
  sampleWalkthrough,
  flashcards,
  links: [{ title: "AP CSP (College Board)", url: CSP, source: "College Board" }],
});

export const AP_CS_PRINCIPLES_LESSONS: Lesson[] = [
  mk(1, "1.1", "Collaboration",
    "Software is built in teams. Clear communication and version control essential.",
    ["Team-based development.", "Pair programming, code review.", "Version control (Git).", "Clear communication reduces bugs."],
    "Why use version control in a team?",
    "Tracks changes, enables collaboration, lets you revert mistakes.",
    [{q:"Version control example?",a:"Git / GitHub"},{q:"Pair programming?",a:"Two devs, one keyboard"},{q:"Code review?",a:"Teammate checks your code before merge"},{q:"Why collaborate?",a:"Better ideas, catch bugs, divide work"},{q:"Tool for team communication?",a:"Slack, Discord, Teams"}],
  ),
  mk(1, "1.2", "Program Function and Purpose",
    "Purpose: why the program exists. Function: what it does.",
    ["Purpose: problem being solved.", "Function: specific behaviors.", "Users drive requirements.", "Consider multiple stakeholders."],
    "What's the difference between purpose and function?",
    "Purpose = why (problem solved). Function = what (what it does / how it works).",
    [{q:"Program purpose?",a:"The problem it solves"},{q:"Program function?",a:"What it does mechanically"},{q:"User input?",a:"Data from users (text, clicks, sensor)"},{q:"User-centered design?",a:"Design driven by user needs"},{q:"Stakeholders?",a:"Anyone affected by program"}],
  ),
  mk(1, "1.3", "Program Design and Development",
    "Iterative: investigate, design, prototype, test, refine.",
    ["Iterative process.", "Investigate → design → prototype → test → refine.", "Problem decomposition.", "Feedback drives revisions."],
    "Why iterative design?",
    "Complex problems rarely solved in one pass — iteration refines toward a better solution.",
    [{q:"Iterative process?",a:"Cycle of design, build, test, refine"},{q:"Problem decomposition?",a:"Break complex problem into smaller pieces"},{q:"Prototype?",a:"Early rough version"},{q:"User feedback?",a:"Informs revisions"},{q:"Waterfall vs agile?",a:"Waterfall linear; agile iterative"}],
  ),
  mk(1, "1.4", "Identifying and Correcting Errors",
    "Syntax (compile), runtime (execution), logic (wrong output) errors.",
    ["Syntax errors: compiler catches.", "Runtime errors: crash during execution.", "Logic errors: runs but wrong output.", "Debug with print statements, tests, debugger."],
    "Program runs but gives wrong answer. Error type?",
    "Logic error — syntax and runtime OK, but logic is flawed.",
    [{q:"Syntax error?",a:"Invalid code structure"},{q:"Runtime error?",a:"Crashes during execution (division by 0, null)"},{q:"Logic error?",a:"Runs but produces wrong result"},{q:"Debugging tools?",a:"Print statements, debugger, unit tests"},{q:"Hardest to find?",a:"Logic errors (no crash signal)"}],
  ),
  mk(2, "2.1", "Binary Numbers",
    "Base 2 (0, 1). n bits represent 2^n values.",
    ["Base 2 place values: 1, 2, 4, 8, 16...", "n bits = 2^n values (0 to 2^n − 1).", "8 bits = 1 byte = 256 values.", "Convert via repeated division or place values."],
    "Convert 13 to binary.",
    "13 = 8 + 4 + 1 = 1101₂.",
    [{q:"Base 2 digits?",a:"0 and 1"},{q:"8 bits (1 byte)?",a:"256 values"},{q:"n bits?",a:"2^n values"},{q:"Binary 1010?",a:"10 in decimal"},{q:"16 in binary?",a:"10000"}],
  ),
  mk(2, "2.2", "Data Compression",
    "Lossless: no info lost (ZIP). Lossy: some info lost (JPEG, MP3).",
    ["Lossless: exact reconstruction possible.", "Lossy: smaller files but can't fully reconstruct.", "Lossless examples: ZIP, PNG, FLAC.", "Lossy examples: JPEG, MP3, MP4."],
    "Is JPEG lossless or lossy?",
    "Lossy — sacrifices image detail for smaller files.",
    [{q:"Lossless?",a:"Exact reconstruction possible"},{q:"Lossy?",a:"Smaller but some info lost"},{q:"Lossless examples?",a:"ZIP, PNG, FLAC"},{q:"Lossy examples?",a:"JPEG, MP3, MP4"},{q:"Tradeoff?",a:"Size vs. fidelity"}],
  ),
  mk(2, "2.3", "Extracting Information from Data",
    "Filter, sort, summarize to find patterns.",
    ["Filter: find relevant subset.", "Sort: order data.", "Summarize: mean, count, trends.", "Patterns inform decisions."],
    "You have sales data. How to find top-selling product?",
    "Group by product, sum sales, sort descending, take top.",
    [{q:"Data extraction operations?",a:"Filter, sort, aggregate"},{q:"Filter?",a:"Select matching records"},{q:"Aggregate?",a:"Summarize (sum, count, avg)"},{q:"Visualization purpose?",a:"Identify patterns visually"},{q:"Big data?",a:"Datasets too large for single-machine processing"}],
  ),
  mk(2, "2.4", "Using Programs with Data",
    "Clean, transform, analyze data programmatically.",
    ["Cleaning: handle missing, bad, inconsistent data.", "Transforming: restructure for analysis.", "Analyze with algorithms.", "Libraries handle common tasks."],
    "Why clean data first?",
    "Dirty data leads to wrong results — garbage in, garbage out.",
    [{q:"Data cleaning?",a:"Fix missing/bad values"},{q:"GIGO?",a:"Garbage In, Garbage Out"},{q:"Common dirty data?",a:"Missing values, duplicates, format errors"},{q:"Transform example?",a:"Reshape, normalize, encode"},{q:"Libraries?",a:"Pandas, spreadsheet tools, etc."}],
  ),
  mk(3, "3.1", "Variables and Assignments",
    "Variables store values; assignment operator ← puts value in variable.",
    ["Variable: named storage.", "Assignment: x ← value.", "Can reassign.", "Type depends on value."],
    "What does x ← 5 mean?",
    "Store 5 in variable named x.",
    [{q:"Variable?",a:"Named storage for a value"},{q:"Assignment operator?",a:"← (CSP pseudocode)"},{q:"Can reassign?",a:"Yes"},{q:"Data types?",a:"Number, string, boolean, list"},{q:"Immutable?",a:"Values like strings in some languages"}],
  ),
  mk(3, "3.2", "Data Abstraction",
    "Lists and other structures hide low-level details.",
    ["Abstraction = hiding complexity.", "Use high-level operations.", "Lists: ordered collection.", "Makes programs cleaner."],
    "How does abstraction help programmers?",
    "Work with high-level concepts (list, map) without re-implementing low-level details each time.",
    [{q:"Data abstraction?",a:"Hide implementation, expose interface"},{q:"List?",a:"Ordered collection"},{q:"Procedure?",a:"Named block of code (procedure abstraction)"},{q:"Why abstract?",a:"Reduce complexity, reuse code"},{q:"CSP pseudocode list?",a:"a ← [1, 2, 3]"}],
  ),
  mk(3, "3.3", "Mathematical Expressions",
    "Arithmetic with +, -, *, /, MOD. Order of operations.",
    ["+, -, *, /, MOD (%).", "Parentheses override.", "Division: may be integer or decimal.", "Compound: (a + b) * c."],
    "7 MOD 3?",
    "1 (remainder of 7/3).",
    [{q:"MOD operator?",a:"Remainder after division"},{q:"7 MOD 3?",a:"1"},{q:"Order of ops?",a:"Parens, */MOD, +-"},{q:"Integer vs decimal division?",a:"Depends on language"},{q:"Compound expression?",a:"Combines multiple operators"}],
  ),
  mk(3, "3.4", "Strings",
    "Sequence of characters. Concatenation, substring, length.",
    ["Ordered sequence of characters.", "Concatenate with +.", "Substring: extract portion.", "Length: count chars.", "Indexed starting at 1 in CSP."],
    "CSP substring(\"Computing\", 1, 4)?",
    "\"Comp\" — characters from index 1 to 4 (1-based inclusive).",
    [{q:"String?",a:"Sequence of characters"},{q:"Concatenation?",a:"Join strings"},{q:"CSP indexing?",a:"1-based"},{q:"Length?",a:"Count of characters"},{q:"Substring?",a:"Portion of string"}],
  ),
  mk(3, "3.5", "Boolean Expressions",
    "Evaluate to true or false. Comparison (==, !=, <, >, ≤, ≥).",
    ["Boolean = true or false.", "Comparison operators.", "NOT, AND, OR combine.", "Used in conditionals."],
    "NOT (5 > 3)?",
    "false — 5 > 3 is true; NOT inverts.",
    [{q:"Boolean values?",a:"true, false"},{q:"Comparison ops?",a:"==, !=, <, >, ≤, ≥"},{q:"Logical NOT?",a:"Invert: NOT(true) = false"},{q:"Logical AND?",a:"Both must be true"},{q:"Logical OR?",a:"Either true"}],
  ),
  mk(3, "3.6", "Conditionals",
    "IF (cond) { A } ELSE { B } branches execution.",
    ["IF branches based on boolean.", "ELSE optional.", "Decision trees.", "Test one path at a time."],
    "Write CSP conditional for pass/fail at 60.",
    "IF (score ≥ 60) DISPLAY(\"pass\") ELSE DISPLAY(\"fail\").",
    [{q:"IF syntax?",a:"IF (cond) { block }"},{q:"ELSE?",a:"Runs if IF false"},{q:"Condition type?",a:"Boolean"},{q:"One block runs?",a:"Yes (exactly one)"},{q:"Purpose?",a:"Choose action based on state"}],
  ),
  mk(3, "3.7", "Nested Conditionals",
    "IF inside IF. Handles multi-branch logic.",
    ["Can nest IFs for multi-way branching.", "ELSE IF for cleaner multi-way.", "Watch indentation.", "Order matters."],
    "Grade: A (90+), B (80+), C (70+), else F.",
    "IF (s≥90) \"A\" ELSE IF (s≥80) \"B\" ELSE IF (s≥70) \"C\" ELSE \"F\"",
    [{q:"Nested IF?",a:"IF inside IF"},{q:"ELSE IF?",a:"Multi-way branching"},{q:"Order of checks?",a:"First true wins"},{q:"Clearer alternative?",a:"SWITCH / CASE in some languages"},{q:"Most specific first?",a:"Usually yes"}],
  ),
  mk(3, "3.8", "Iteration",
    "REPEAT n TIMES, REPEAT UNTIL, FOR EACH — loops for repetition.",
    ["Fixed count: REPEAT n TIMES.", "Condition-based: REPEAT UNTIL.", "Over list: FOR EACH.", "Avoid infinite loops."],
    "Print 1 to 10.",
    "REPEAT 10 TIMES { DISPLAY(i); i ← i + 1 } (with i starting at 1)",
    [{q:"REPEAT n TIMES?",a:"Fixed iteration count"},{q:"REPEAT UNTIL?",a:"Loops until condition true"},{q:"FOR EACH?",a:"Iterate over collection"},{q:"Infinite loop?",a:"Condition never becomes true"},{q:"WHILE?",a:"Similar to REPEAT UNTIL"}],
  ),
  mk(3, "3.9", "Developing Algorithms",
    "Algorithm = steps to solve a problem. Design via decomposition.",
    ["Algorithm: finite steps to solve problem.", "Decomposition: break down.", "Sequencing, selection, iteration.", "Verify correctness."],
    "Algorithm to find max in list.",
    "Start max = first. For each element, if element > max, set max = element. Return max.",
    [{q:"Algorithm?",a:"Finite sequence of steps"},{q:"Three basic structures?",a:"Sequence, selection, iteration"},{q:"Decomposition?",a:"Break complex into simple"},{q:"Verify correctness?",a:"Test, trace, reason about logic"},{q:"Equivalence?",a:"Different algorithms can solve same problem"}],
  ),
  mk(3, "3.10", "Lists",
    "Ordered collections. Access by index. Append, insert, remove.",
    ["List = ordered collection.", "1-based indexing in CSP.", "Common ops: APPEND, INSERT, REMOVE.", "Length function.", "Can contain any data type."],
    "Given list [4, 7, 2, 9], what's list[3]?",
    "2 (1-based: position 3 is 2).",
    [{q:"List?",a:"Ordered collection"},{q:"CSP indexing?",a:"1-based"},{q:"APPEND?",a:"Add to end"},{q:"INSERT?",a:"Add at specific position"},{q:"LENGTH?",a:"Count of items"}],
  ),
  mk(3, "3.11", "Binary Search",
    "Efficient search on SORTED lists. Halve each time.",
    ["Requires sorted list.", "Check middle; if match, done.", "If target less, search left half.", "If target greater, search right half.", "O(log n) time."],
    "Binary search for 7 in [1, 3, 5, 7, 9].",
    "Middle is 5. 7 > 5, search right half [7, 9]. Middle is 7. Found.",
    [{q:"Binary search requires?",a:"Sorted list"},{q:"Strategy?",a:"Halve each step"},{q:"Complexity?",a:"O(log n)"},{q:"Linear search complexity?",a:"O(n)"},{q:"Benefit?",a:"Much faster on large sorted data"}],
  ),
  mk(3, "3.12", "Calling Procedures",
    "Procedures: named reusable code blocks. Parameters pass data in.",
    ["Procedure = named code block.", "Parameters: inputs.", "Return: output (optional).", "Call: procedureName(args).", "Abstraction via procedures."],
    "Call a procedure areaSquare(s) where s = 4.",
    "areaSquare(4) — procedure computes 4² = 16, returns.",
    [{q:"Procedure?",a:"Named reusable code block"},{q:"Parameter?",a:"Input to procedure"},{q:"Argument?",a:"Actual value passed in"},{q:"Return?",a:"Output value (optional)"},{q:"Purpose?",a:"Reuse and abstraction"}],
  ),
  mk(3, "3.13", "Developing Procedures",
    "Define procedures for clarity and reuse.",
    ["Name: descriptive verb.", "Parameters: necessary inputs.", "Body: steps.", "Return: result if needed.", "Single responsibility principle."],
    "Procedure to compute rectangle area:",
    "PROCEDURE area(w, h) { RETURN w * h }",
    [{q:"Procedure design?",a:"Name, parameters, body, optional return"},{q:"Single responsibility?",a:"One procedure does one thing"},{q:"Why break into procedures?",a:"Reuse, clarity, testability"},{q:"Parameter count?",a:"Usually few; many = refactor"},{q:"Naming?",a:"Descriptive verbs"}],
  ),
  mk(3, "3.14", "Libraries",
    "Libraries provide pre-built procedures. APIs define access.",
    ["Library: collection of procedures.", "API: defined access points.", "Save time; use tested code.", "Import to use."],
    "Why use a library for sorting?",
    "Well-tested, fast, reusable — no need to reinvent.",
    [{q:"Library?",a:"Collection of reusable procedures"},{q:"API?",a:"Application Programming Interface"},{q:"Why use libraries?",a:"Save time, tested code, leverage experts"},{q:"Import?",a:"Include library in program"},{q:"Open-source library?",a:"Freely available with source (e.g., NumPy)"}],
  ),
  mk(3, "3.15", "Random Values",
    "RANDOM(a, b) returns random integer in [a, b].",
    ["RANDOM(a, b) → integer in [a, b].", "Essential for simulations, games.", "Uses: picking, sampling, simulation.", "Uniform distribution (equal chance)."],
    "Simulate a dice roll.",
    "RANDOM(1, 6) gives a uniformly random integer from 1 to 6.",
    [{q:"RANDOM(1,10)?",a:"Integer from 1 to 10 inclusive, uniform"},{q:"Distribution?",a:"Uniform (each value equally likely)"},{q:"Use cases?",a:"Games, simulations, sampling"},{q:"Pseudo-random?",a:"Deterministic algorithm; appears random"},{q:"Seeding?",a:"Control random sequence for reproducibility"}],
  ),
  mk(3, "3.16", "Simulations",
    "Programs model real-world systems. Track outcomes statistically.",
    ["Model reality using rules and randomness.", "Many trials to see averages.", "Weather, epidemics, economics all simulated.", "Limitations: assumptions matter."],
    "Monte Carlo estimate of π?",
    "Random points in unit square. Fraction inside unit circle × 4 ≈ π. More samples = better estimate.",
    [{q:"Simulation?",a:"Program modeling real-world system"},{q:"Monte Carlo?",a:"Random-sampling approach"},{q:"Benefits?",a:"Test scenarios without real-world cost"},{q:"Limitations?",a:"Assumptions drive results"},{q:"Uses?",a:"Weather, epidemics, economics, physics"}],
  ),
  mk(3, "3.17", "Algorithmic Efficiency",
    "Growth rate with input size. Polynomial (fast) vs. exponential (slow).",
    ["Efficiency: time/space vs. input size.", "Polynomial (O(n²), O(n log n)): tractable.", "Exponential (O(2^n)): intractable for large n.", "Big O describes growth."],
    "Which is more efficient on 1M items: O(n²) or O(n log n)?",
    "O(n log n) — for n=10⁶, log n ≈ 20, so n log n ≈ 2×10⁷, vs n² = 10¹².",
    [{q:"Efficiency?",a:"How time/space scales with input"},{q:"Polynomial time?",a:"Tractable"},{q:"Exponential time?",a:"Intractable for large inputs"},{q:"Big O notation?",a:"Describes growth rate"},{q:"Common orders?",a:"O(1), O(log n), O(n), O(n log n), O(n²), O(2^n)"}],
  ),
  mk(3, "3.18", "Undecidable Problems",
    "Some problems can't be solved by any algorithm (halting problem).",
    ["Undecidable: no algorithm can solve.", "Halting problem: can't decide if any program halts on any input.", "Fundamental limit.", "Different from hard problems — truly impossible."],
    "What's the halting problem?",
    "Given program P and input I, will P halt on I? Proved undecidable by Turing — no general algorithm can answer.",
    [{q:"Decidable?",a:"Algorithm exists to solve"},{q:"Undecidable?",a:"No algorithm can solve"},{q:"Halting problem?",a:"Decide if program halts on input"},{q:"Proved by?",a:"Alan Turing (1936)"},{q:"Difference from hard?",a:"Hard = slow; undecidable = impossible"}],
  ),
  mk(4, "4.1", "The Internet",
    "Network of networks. TCP/IP, packet switching, routing.",
    ["Network of networks.", "Packet switching: data in chunks.", "TCP/IP: protocols.", "Routing: path through network.", "Redundancy: multiple paths."],
    "Why use packet switching?",
    "More efficient than circuit switching; multiple users share bandwidth; failures routed around.",
    [{q:"Internet?",a:"Global network of networks"},{q:"Packet switching?",a:"Data split into packets, routed independently"},{q:"TCP/IP?",a:"Core internet protocols"},{q:"IP address?",a:"Unique device identifier"},{q:"Router?",a:"Directs packets between networks"}],
  ),
  mk(4, "4.2", "Fault Tolerance",
    "Network continues despite failures. Redundancy key.",
    ["Multiple paths to destination.", "Packets retry if lost.", "DNS has multiple servers.", "Cloud services replicate data."],
    "Why does the Internet keep working when a server fails?",
    "Redundancy: alternate paths, backup servers, packet retries automatically handle failures.",
    [{q:"Fault tolerance?",a:"System works despite failures"},{q:"Redundancy?",a:"Multiple copies or paths"},{q:"Packet lost?",a:"TCP retries"},{q:"DNS redundancy?",a:"Multiple DNS servers"},{q:"Cloud reliability?",a:"Data replicated across servers/regions"}],
  ),
  mk(4, "4.3", "Parallel and Distributed Computing",
    "Parallel: many tasks simultaneously. Distributed: across multiple machines.",
    ["Parallel: multi-core CPU, GPU.", "Distributed: across network.", "Speeds up large tasks.", "Overhead: coordination, communication.", "Amdahl's law: speedup limited by sequential portion."],
    "Why can't we always make programs n× faster with n processors?",
    "Amdahl's law: sequential portions limit speedup. Coordination adds overhead.",
    [{q:"Parallel computing?",a:"Multiple tasks at once (same machine)"},{q:"Distributed computing?",a:"Tasks across multiple machines"},{q:"Speedup?",a:"Time sequential / time parallel"},{q:"Amdahl's law?",a:"Sequential portion limits speedup"},{q:"Example?",a:"GPU rendering, MapReduce, cluster computing"}],
  ),
  mk(5, "5.1", "Beneficial and Harmful Effects",
    "Technology has both positive and negative impacts; context matters.",
    ["Beneficial: communication, access to info, medicine.", "Harmful: misuse, addiction, privacy loss.", "Same technology both.", "Design choices shape impact."],
    "Social media — beneficial or harmful?",
    "Both: connects people, spreads info, but also misinformation, addiction, mental health effects.",
    [{q:"Dual-use technology?",a:"Same tech can help or harm"},{q:"Beneficial examples?",a:"Medical imaging, education access, communication"},{q:"Harmful examples?",a:"Deepfakes, surveillance, addiction"},{q:"Context matters?",a:"Same tool, different uses"},{q:"Who decides?",a:"Society, designers, policy"}],
  ),
  mk(5, "5.2", "Digital Divide",
    "Unequal access to technology by geography, wealth, age.",
    ["Unequal access causes inequity.", "Geographic, economic, generational divides.", "Education, employment impacted.", "Efforts: broadband programs, digital literacy."],
    "Why does the digital divide worsen inequality?",
    "Those without access fall behind in education, jobs, healthcare — compounding existing disadvantages.",
    [{q:"Digital divide?",a:"Unequal access to digital technology"},{q:"Causes?",a:"Geography, income, age, education"},{q:"Effects?",a:"Education/employment gaps"},{q:"Solutions?",a:"Broadband, digital literacy programs"},{q:"Pandemic impact?",a:"Exposed divide (remote learning inequities)"}],
  ),
  mk(5, "5.3", "Computing Bias",
    "Algorithms can inherit biases from data or designers.",
    ["Bias sources: training data, developers, feedback loops.", "Examples: facial recognition errors, hiring algorithms.", "Mitigation: diverse data, testing, transparency.", "Legal/ethical implications."],
    "How can a hiring algorithm be biased?",
    "Trained on past hiring data that reflects bias → learns and perpetuates that bias against same groups.",
    [{q:"Algorithmic bias?",a:"Unfair outcomes from algorithm"},{q:"Source of bias?",a:"Data, designers, feedback loops"},{q:"Facial recognition example?",a:"Higher error for darker skin"},{q:"Mitigation?",a:"Diverse data, audits, testing"},{q:"Impact?",a:"Discrimination in hiring, lending, policing"}],
  ),
  mk(5, "5.4", "Crowdsourcing",
    "Harness many people via internet for data, tasks, funding.",
    ["Distributed problem-solving.", "Examples: Wikipedia, OpenStreetMap, Mechanical Turk, Kickstarter.", "Benefits: diverse input, scale.", "Risks: quality, exploitation."],
    "Is Wikipedia an example of crowdsourcing?",
    "Yes — millions contribute content, creating the world's largest encyclopedia.",
    [{q:"Crowdsourcing?",a:"Distributed contribution from many people"},{q:"Wikipedia?",a:"Crowdsourced encyclopedia"},{q:"Kickstarter?",a:"Crowdsourced funding"},{q:"Benefits?",a:"Scale, diverse expertise, cost"},{q:"Risks?",a:"Quality, exploitation of volunteers"}],
  ),
  mk(5, "5.5", "Legal and Ethical Concerns",
    "Copyright, plagiarism, licensing, CFAA.",
    ["Copyright: protects creative works.", "Fair use: limited without permission.", "Creative Commons: open licensing.", "Computer Fraud and Abuse Act: US hacking law.", "Plagiarism: presenting others' work as own."],
    "What's Creative Commons?",
    "Licensing framework for creators to share works with specified permissions (attribution, noncommercial, etc.).",
    [{q:"Copyright?",a:"Legal protection for creative works"},{q:"Fair use?",a:"Limited use without permission (education, criticism)"},{q:"Creative Commons?",a:"Open licensing framework"},{q:"Plagiarism?",a:"Presenting others' work as your own"},{q:"CFAA?",a:"US anti-hacking law"}],
  ),
  mk(5, "5.6", "Safe Computing",
    "Protect devices and data: passwords, updates, phishing awareness.",
    ["Strong unique passwords; 2FA.", "Software updates patch security.", "Phishing: deceptive attempts to get info.", "Malware: viruses, ransomware.", "HTTPS: encrypted connections."],
    "How does HTTPS protect you?",
    "Encrypts data between browser and server — eavesdroppers can't read traffic.",
    [{q:"Strong password?",a:"Long, unique, complex"},{q:"2FA?",a:"Two-factor authentication (adds a second proof)"},{q:"Phishing?",a:"Deceptive attempt to obtain info"},{q:"HTTPS?",a:"Encrypted HTTP"},{q:"Keep software updated?",a:"Yes — patches security vulnerabilities"}],
  ),
];
