import type { Lesson } from "@/lib/topics";

/** AP Chemistry — one Lesson per CED topic across all 9 units (81 topics). */

const KA = "https://www.khanacademy.org/science/ap-chemistry";

const U = {
  1: "Atomic Structure and Properties",
  2: "Molecular and Ionic Compound Structure and Properties",
  3: "Intermolecular Forces and Properties",
  4: "Chemical Reactions",
  5: "Kinetics",
  6: "Thermodynamics",
  7: "Equilibrium",
  8: "Acids and Bases",
  9: "Applications of Thermodynamics",
};

const mk = (
  unit: keyof typeof U,
  id: string,
  title: string,
  blurb: string,
  keyIdeas: string[],
  sampleProblem: string,
  sampleWalkthrough: string,
  flashcards: { q: string; a: string }[]
): Lesson => ({
  slug: `chem-${id.replace(".", "-")}`,
  title,
  courses: [{ courseSlug: "ap-chemistry", unitNumber: unit, unitTitle: U[unit] }],
  blurb,
  keyIdeas,
  sampleProblem,
  sampleWalkthrough,
  flashcards,
  links: [{ title: "AP Chemistry", url: KA, source: "Khan Academy" }],
});

export const AP_CHEMISTRY_LESSONS: Lesson[] = [
  mk(1, "1.1", "Moles and Molar Mass",
    "Mole = 6.022×10²³ particles. Molar mass (g/mol) = sum of atomic masses.",
    [
      "1 mole = Avogadro's # = 6.022×10²³ particles.",
      "Molar mass = grams per mole = g/mol.",
      "n = mass/molar mass.",
      "Use as conversion factor between mass, moles, particles.",
    ],
    "How many moles in 36.0 g H₂O?",
    "n = 36/18 = 2.0 mol. H₂O molar mass = 2(1) + 16 = 18 g/mol.",
    [
      { q: "Avogadro's number?", a: "6.022×10²³" },
      { q: "Moles from mass?", a: "n = mass/molar mass" },
      { q: "Molar mass H₂O?", a: "18 g/mol" },
      { q: "Molar mass CO₂?", a: "44 g/mol" },
      { q: "Particles from moles?", a: "# = n × Avogadro" },
    ],
  ),
  mk(1, "1.2", "Mass Spectroscopy of Elements",
    "Mass spectrum shows isotope masses and abundances; weighted average = atomic mass.",
    [
      "Ionize, accelerate, deflect by mass/charge.",
      "Peaks = isotopes; height ∝ abundance.",
      "Atomic mass = Σ(isotope mass × fractional abundance).",
      "Used to identify elements and molecules.",
    ],
    "Element X: 75% mass 35 amu, 25% mass 37 amu. Average atomic mass?",
    "(0.75)(35) + (0.25)(37) = 26.25 + 9.25 = 35.5 amu (chlorine).",
    [
      { q: "Mass spectrum x-axis?", a: "Mass-to-charge ratio (m/z)" },
      { q: "Mass spectrum y-axis?", a: "Relative abundance" },
      { q: "Atomic mass formula?", a: "Σ(mass × fractional abundance)" },
      { q: "Chlorine isotopes?", a: "Cl-35 (~76%), Cl-37 (~24%)" },
      { q: "Why peak heights?", a: "Proportional to isotope abundance." },
    ],
  ),
  mk(1, "1.3", "Elemental Composition of Pure Substances",
    "Mass %, empirical formula from % composition.",
    [
      "% element = (mass element / mass sample) × 100.",
      "Empirical formula: simplest whole-number ratio.",
      "Molecular formula: actual (multiple of empirical).",
      "Find empirical: divide each % by molar mass, normalize.",
    ],
    "40% C, 6.7% H, 53.3% O by mass. Empirical formula?",
    "Moles per 100g: C 40/12=3.33, H 6.7/1=6.7, O 53.3/16=3.33. Divide by smallest (3.33): CH₂O.",
    [
      { q: "Empirical formula?", a: "Simplest whole-number ratio." },
      { q: "Molecular formula?", a: "Actual count (multiple of empirical)." },
      { q: "Find empirical from %?", a: "Divide each % by molar mass, normalize to smallest." },
      { q: "Ratio to integers tip?", a: "Multiply by 2, 3, 4... if needed." },
      { q: "C₂H₄O₂ empirical?", a: "CH₂O" },
    ],
  ),
  mk(1, "1.4", "Composition of Mixtures",
    "Mixtures are non-stoichiometric combinations; use mass/mole fractions.",
    [
      "Pure substance: fixed composition; mixture: varies.",
      "Mass fraction = m_component / m_total.",
      "Mole fraction X = n_component / n_total.",
      "ΣX_i = 1.",
    ],
    "10 g salt in 90 g water. Mass % salt?",
    "10/100 = 10%.",
    [
      { q: "Mass fraction?", a: "m_i / m_total" },
      { q: "Mole fraction?", a: "n_i / n_total" },
      { q: "Sum of mole fractions?", a: "1" },
      { q: "Mixture vs compound?", a: "Mixture: varies; compound: fixed." },
      { q: "Homogeneous vs heterogeneous?", a: "Uniform vs non-uniform composition." },
    ],
  ),
  mk(1, "1.5", "Atomic Structure and Electron Configuration",
    "Electrons fill subshells per Aufbau, Pauli, Hund's rules.",
    [
      "Order: 1s, 2s, 2p, 3s, 3p, 4s, 3d, 4p, 5s, 4d…",
      "Pauli: max 2 e⁻ per orbital, opposite spins.",
      "Hund: fill degenerate orbitals singly before pairing.",
      "Valence e⁻ determine chemistry.",
    ],
    "Fe electron configuration?",
    "Fe (Z=26): 1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 3d⁶ or [Ar]4s² 3d⁶.",
    [
      { q: "Aufbau principle?", a: "Fill lowest energy first." },
      { q: "Pauli exclusion?", a: "Max 2 e⁻/orbital, opposite spins." },
      { q: "Hund's rule?", a: "Fill singly before pairing." },
      { q: "Ne configuration?", a: "1s² 2s² 2p⁶" },
      { q: "Noble-gas shorthand for Na?", a: "[Ne] 3s¹" },
    ],
  ),
  mk(1, "1.6", "Photoelectron Spectroscopy",
    "PES: photon ejects electron; ejection energy reveals shells/subshells.",
    [
      "Photon energy − binding energy = kinetic energy of ejected e⁻.",
      "Peaks at binding energies; peak height ∝ # of e⁻.",
      "Inner shells require more energy to eject.",
      "Distinguishes 1s from 2s from 2p, etc.",
    ],
    "N atom PES: peaks at 410, 31, 15 eV. Interpret.",
    "Three subshells: 1s (410 eV, 2 e⁻), 2s (31, 2 e⁻), 2p (15, 3 e⁻). Matches N (1s²2s²2p³).",
    [
      { q: "PES measures?", a: "Binding energies of electrons." },
      { q: "Peak height ∝?", a: "Number of electrons in that shell/subshell." },
      { q: "Higher BE means?", a: "More tightly bound (inner shell)." },
      { q: "1s peak for N?", a: "~410 eV" },
      { q: "Useful for?", a: "Confirming electron configuration." },
    ],
  ),
  mk(1, "1.7", "Periodic Trends",
    "Atomic radius, IE, EN, EA — shaped by Z_eff and shielding.",
    [
      "Atomic radius: ↓ across period, ↑ down group.",
      "Ionization energy: ↑ across, ↓ down (opposite radius).",
      "Electronegativity: ↑ across, ↓ down (F highest).",
      "Shielding: core electrons reduce attraction of outer electrons.",
    ],
    "Rank atomic radii: Na, Mg, K.",
    "K > Na > Mg (K furthest down group; Mg smaller than Na within period).",
    [
      { q: "Atomic radius trend?", a: "Decreases across period, increases down group." },
      { q: "IE trend?", a: "Increases across period, decreases down group." },
      { q: "EN trend?", a: "Increases across, decreases down." },
      { q: "Most electronegative element?", a: "F" },
      { q: "Why IE increases across?", a: "Higher Z_eff pulls electrons tighter." },
    ],
  ),
  mk(1, "1.8", "Valence Electrons and Ionic Compounds",
    "Metals lose, nonmetals gain e⁻ to reach noble-gas configurations.",
    [
      "Valence = outermost e⁻; determines bonding.",
      "Metals → cations (lose e⁻); nonmetals → anions (gain).",
      "Ionic compound = cation + anion (overall neutral).",
      "Lattice: 3D array held by ionic bonds.",
    ],
    "Na + Cl → ?",
    "Na loses 1 e⁻ (→ Na⁺, [Ne]); Cl gains 1 e⁻ (→ Cl⁻, [Ar]). Form NaCl.",
    [
      { q: "Valence electrons?", a: "Outermost shell electrons." },
      { q: "Metals form?", a: "Cations (lose e⁻)" },
      { q: "Nonmetals form?", a: "Anions (gain e⁻)" },
      { q: "NaCl ratio?", a: "1:1" },
      { q: "Octet rule?", a: "8 valence e⁻ gives stability." },
    ],
  ),
  mk(2, "2.1", "Types of Chemical Bonds",
    "Ionic (metal + nonmetal), covalent (nonmetal + nonmetal), metallic (metal + metal).",
    [
      "Ionic: transfer e⁻; large ΔEN (>1.7).",
      "Polar covalent: unequal sharing (0.4 < ΔEN < 1.7).",
      "Nonpolar covalent: equal sharing (ΔEN < 0.4).",
      "Metallic: sea of delocalized e⁻.",
    ],
    "Is HCl ionic or covalent?",
    "Polar covalent (ΔEN ≈ 1.0 between H and Cl).",
    [
      { q: "Ionic bond?", a: "Electron transfer (metal + nonmetal)." },
      { q: "Covalent bond?", a: "Electron sharing (nonmetals)." },
      { q: "Polar covalent cutoff?", a: "0.4 < ΔEN < 1.7" },
      { q: "Metallic bond?", a: "Sea of delocalized electrons." },
      { q: "NaCl vs HCl?", a: "NaCl ionic; HCl polar covalent." },
    ],
  ),
  mk(2, "2.2", "Intramolecular Force and Potential Energy",
    "PE curve: bond length minimum; bond energy = depth of well.",
    [
      "Attraction from electron-nucleus; repulsion from nuclei.",
      "Equilibrium bond length at PE minimum.",
      "Bond energy = energy to break bond.",
      "Shorter bonds generally stronger.",
    ],
    "Why doesn't H₂ collapse to zero bond length?",
    "Nuclear-nuclear repulsion dominates at short distances; equilibrium where net force is zero.",
    [
      { q: "Bond length at?", a: "PE minimum." },
      { q: "Bond energy?", a: "Energy to break bond (well depth)." },
      { q: "Short bonds?", a: "Generally stronger." },
      { q: "Double bond vs single?", a: "Shorter, stronger." },
      { q: "At zero distance?", a: "Infinite repulsion." },
    ],
  ),
  mk(2, "2.3", "Structure of Ionic Solids",
    "Ionic solids form crystal lattices — alternating cations/anions.",
    [
      "Lattice energy: energy released when ions form solid.",
      "Higher lattice energy: smaller ions, higher charges.",
      "Coulombic: F ∝ q₁q₂/r².",
      "Ionic solids: high MP, brittle, conduct when molten.",
    ],
    "Which has higher lattice energy: NaCl or MgO?",
    "MgO — higher charges (2+/2−) and smaller ions → stronger Coulombic attraction.",
    [
      { q: "Lattice energy increases with?", a: "Higher charges, smaller ions." },
      { q: "Ionic solids conduct?", a: "Only when molten or dissolved." },
      { q: "Ionic solids brittle?", a: "Yes — slipping layers misaligns charges." },
      { q: "Coulomb's law?", a: "F ∝ q₁q₂/r²" },
      { q: "Highest lattice energy: NaCl, MgO, Al₂O₃?", a: "Al₂O₃" },
    ],
  ),
  mk(2, "2.4", "Structure of Metals and Alloys",
    "Metallic bonding: cations in sea of delocalized electrons. Alloys mix metals.",
    [
      "Delocalized e⁻ explain conductivity, malleability.",
      "Substitutional alloy: similar-sized atoms replace (brass).",
      "Interstitial alloy: small atoms fit in gaps (steel).",
      "Alloys: tunable properties.",
    ],
    "Why are metals ductile?",
    "Metal cations can slide past each other in the sea of delocalized electrons without breaking directional bonds.",
    [
      { q: "Metallic bonding?", a: "Cations + sea of delocalized electrons." },
      { q: "Why do metals conduct?", a: "Free electrons move easily." },
      { q: "Substitutional alloy?", a: "Similar-sized atoms replace." },
      { q: "Interstitial alloy?", a: "Small atoms fill gaps (e.g., C in steel)." },
      { q: "Why ductile?", a: "Non-directional metallic bonds allow deformation." },
    ],
  ),
  mk(2, "2.5", "Lewis Diagrams",
    "Show bonding and lone pairs. Octet rule (with exceptions).",
    [
      "Count valence e⁻, draw skeleton, complete octets.",
      "Central atom usually least EN (not H).",
      "Exceptions: H (2), B/Al (6), expanded octets (S, P, Xe).",
      "Formal charge = V − L − B/2.",
    ],
    "Lewis structure of CO₂?",
    "O=C=O (linear); 2 double bonds; lone pairs on each O.",
    [
      { q: "Octet rule?", a: "Atoms want 8 valence electrons." },
      { q: "H valence?", a: "2 (duet rule)." },
      { q: "Formal charge?", a: "V − L − B/2" },
      { q: "Central atom?", a: "Usually least electronegative (not H)." },
      { q: "Expanded octet elements?", a: "S, P, Xe, Cl (with d-orbitals)." },
    ],
  ),
  mk(2, "2.6", "Resonance and Formal Charge",
    "Resonance: multiple valid Lewis structures averaged. Formal charge guides best structure.",
    [
      "Resonance structures: different e⁻ positions, same skeleton.",
      "Real structure = hybrid (weighted average).",
      "Best structure: smallest formal charges.",
      "Negative charge on most EN atom.",
    ],
    "Draw resonance structures for NO₃⁻.",
    "Three equivalent structures: double bond on each O in turn, single bonds to others. Real structure = average with bond order 4/3.",
    [
      { q: "Resonance?", a: "Multiple valid Lewis structures averaged." },
      { q: "Real molecule?", a: "Hybrid of resonance forms." },
      { q: "Best Lewis structure?", a: "Smallest |formal charges|." },
      { q: "Formal charge formula?", a: "Valence − lone pair e⁻ − shared/2" },
      { q: "NO₃⁻ bond order?", a: "4/3 ≈ 1.33" },
    ],
  ),
  mk(2, "2.7", "VSEPR and Bond Hybridization",
    "VSEPR: e⁻ pairs repel; geometry minimizes repulsion. Hybridization matches.",
    [
      "Count electron domains (bonded + lone pairs).",
      "2 = linear (sp), 3 = trigonal planar (sp²), 4 = tetrahedral (sp³).",
      "Lone pairs repel more than bonded pairs.",
      "Molecular shape describes atoms only; electron geometry includes lone pairs.",
    ],
    "H₂O molecular geometry?",
    "4 electron domains (2 bonds, 2 lone pairs) → tetrahedral electron geometry; bent molecular shape. sp³ hybridization.",
    [
      { q: "4 domains e-geometry?", a: "Tetrahedral" },
      { q: "3 domains?", a: "Trigonal planar" },
      { q: "2 domains?", a: "Linear" },
      { q: "H₂O shape?", a: "Bent (2 lone pairs on O)" },
      { q: "NH₃ hybridization?", a: "sp³" },
    ],
  ),
  mk(3, "3.1", "Intermolecular Forces",
    "IMFs: dispersion (all), dipole-dipole (polar), H-bonding (N/O/F-H), ion-dipole.",
    [
      "Dispersion (LDFs): temporary dipoles; all molecules.",
      "Dipole-dipole: polar molecules.",
      "H-bonding: H directly bonded to N, O, or F.",
      "Ion-dipole: ionic in polar solvent (strongest).",
      "Order: ion-dipole > H-bond > dipole-dipole > LDF.",
    ],
    "Why does H₂O boil higher than H₂S?",
    "H₂O has hydrogen bonding (O-H); H₂S doesn't — only dipole-dipole and LDF. Stronger IMFs → higher BP.",
    [
      { q: "Types of IMFs?", a: "LDF, dipole-dipole, H-bond, ion-dipole" },
      { q: "H-bond requires?", a: "H bonded directly to N, O, or F" },
      { q: "Which is strongest?", a: "Ion-dipole (then H-bond)." },
      { q: "LDFs increase with?", a: "Molar mass (more electrons)." },
      { q: "Why H₂O unusual?", a: "Strong H-bonds → high BP, surface tension, cohesion." },
    ],
  ),
  mk(3, "3.2", "Properties of Solids",
    "Ionic, covalent network, molecular, metallic solids differ by bonding.",
    [
      "Ionic: high MP, brittle, conducts when molten.",
      "Covalent network (diamond, SiO₂): very high MP, hard, nonconductor.",
      "Molecular (ice, sugar): low MP, poor conductor.",
      "Metallic: high MP, malleable, conducts.",
    ],
    "Why does diamond have such a high MP?",
    "Covalent network: all atoms covalently bonded in 3D — need to break strong covalent bonds to melt.",
    [
      { q: "Ionic solid example?", a: "NaCl" },
      { q: "Covalent network?", a: "Diamond, SiO₂" },
      { q: "Molecular solid?", a: "Ice, dry ice, sugar" },
      { q: "Metallic solid?", a: "Cu, Fe" },
      { q: "Which has lowest MP?", a: "Molecular solids." },
    ],
  ),
  mk(3, "3.3", "Solids, Liquids, and Gases",
    "Phase differences reflect particle spacing, motion, IMFs.",
    [
      "Solid: fixed shape/volume; particles vibrate.",
      "Liquid: fixed volume, takes shape of container.",
      "Gas: fills container; weak IMFs.",
      "Phase changes: melt, freeze, vaporize, condense, sublime, deposit.",
    ],
    "Why is a gas compressible but a liquid isn't?",
    "Gas particles have lots of space between them; liquid particles are already closely packed.",
    [
      { q: "Solid particle motion?", a: "Vibrate in place." },
      { q: "Liquid particle motion?", a: "Flow, slide past each other." },
      { q: "Gas particle motion?", a: "Fast, random, mostly free." },
      { q: "Vaporization?", a: "Liquid → gas" },
      { q: "Sublimation?", a: "Solid → gas (skip liquid)." },
    ],
  ),
  mk(3, "3.4", "Ideal Gas Law",
    "PV = nRT. R = 0.0821 L·atm/(mol·K).",
    [
      "P in atm, V in L, n in mol, T in K.",
      "R = 0.0821 L·atm/(mol·K).",
      "T must be in Kelvin always.",
      "Combined gas law: P₁V₁/T₁ = P₂V₂/T₂.",
    ],
    "1 mol gas at 273 K, 1 atm. V?",
    "V = nRT/P = (1)(0.0821)(273)/1 = 22.4 L (STP molar volume).",
    [
      { q: "Ideal gas law?", a: "PV = nRT" },
      { q: "R value?", a: "0.0821 L·atm/(mol·K)" },
      { q: "STP?", a: "273 K, 1 atm" },
      { q: "Molar volume at STP?", a: "22.4 L" },
      { q: "T units?", a: "Kelvin" },
    ],
  ),
  mk(3, "3.5", "Kinetic Molecular Theory",
    "Gas particles: negligible volume, random motion, elastic collisions. Speed distribution.",
    [
      "Gas particles have negligible volume (compared to container).",
      "No IMFs; elastic collisions.",
      "KE_avg ∝ T (same T → same avg KE).",
      "Lighter particles move faster at same T.",
      "Maxwell-Boltzmann distribution describes speeds.",
    ],
    "At same T, which moves faster: H₂ or O₂?",
    "Same avg KE → ½mv²; smaller m (H₂) → larger v. H₂ moves faster.",
    [
      { q: "KE_avg depends on?", a: "Temperature only." },
      { q: "Elastic collision?", a: "No KE lost." },
      { q: "Lighter molecules?", a: "Move faster at same T." },
      { q: "Maxwell-Boltzmann?", a: "Speed distribution of gas molecules." },
      { q: "KE = ?", a: "(3/2)kT per molecule" },
    ],
  ),
  mk(3, "3.6", "Deviation from Ideal Gas Law",
    "Real gases deviate at high P, low T (when IMFs and volume matter).",
    [
      "High P: particle volume ≠ negligible.",
      "Low T: IMFs attract particles.",
      "Polar molecules deviate more (stronger IMFs).",
      "van der Waals equation corrects.",
    ],
    "Why do real gases deviate from ideal behavior?",
    "At high pressure, molecular volume is not negligible; at low temperature, intermolecular attractions matter.",
    [
      { q: "Ideal gas assumes?", a: "Negligible volume, no IMFs." },
      { q: "Real gas deviates when?", a: "High P and low T." },
      { q: "Polar gases?", a: "Deviate more." },
      { q: "Van der Waals?", a: "Corrects for molecular size and IMFs." },
      { q: "At low P, high T?", a: "Nearly ideal." },
    ],
  ),
  mk(3, "3.7", "Solutions and Mixtures",
    "Solute dissolves in solvent. Molarity M = moles/L.",
    [
      "Solution = homogeneous mixture.",
      "Molarity = mol solute / L solution.",
      "Molality = mol solute / kg solvent.",
      "Dilution: M₁V₁ = M₂V₂.",
    ],
    "Dilute 25 mL of 2 M HCl to 100 mL. New M?",
    "M₂ = (2)(25)/100 = 0.5 M.",
    [
      { q: "Molarity?", a: "mol solute / L solution" },
      { q: "Molality?", a: "mol solute / kg solvent" },
      { q: "Dilution equation?", a: "M₁V₁ = M₂V₂" },
      { q: "Solution vs pure?", a: "Solution has solute + solvent." },
      { q: "Saturated solution?", a: "Equilibrium dissolved and undissolved." },
    ],
  ),
  mk(3, "3.8", "Representations of Solutions",
    "Drawings show dissociated ions for ionic compounds; molecules for molecular.",
    [
      "Ionic compound in water: full dissociation (NaCl → Na⁺ + Cl⁻).",
      "Molecular compound: stays intact (sugar, ethanol).",
      "Strong vs weak electrolytes.",
      "Hydrated ions: water molecules surround.",
    ],
    "What do you draw for NaCl dissolved in water?",
    "Separate Na⁺ and Cl⁻ ions, each surrounded by water molecules (hydration shell).",
    [
      { q: "Ionic solutes do what?", a: "Dissociate into ions." },
      { q: "Molecular solutes?", a: "Stay intact." },
      { q: "Strong electrolyte?", a: "Dissociates completely." },
      { q: "Weak electrolyte?", a: "Dissociates partially." },
      { q: "Hydration?", a: "Water molecules surround ions." },
    ],
  ),
  mk(3, "3.9", "Separation of Solutions and Mixtures (Chromatography)",
    "Components separate by different affinities for stationary/mobile phases.",
    [
      "Mobile phase carries samples; stationary phase retards.",
      "Compounds distribute based on affinity.",
      "Paper, TLC, column, GC, HPLC.",
      "R_f = distance moved / solvent front distance.",
    ],
    "Compound moves 3 cm; solvent front 10 cm. R_f?",
    "R_f = 3/10 = 0.30.",
    [
      { q: "R_f value?", a: "distance compound / distance solvent" },
      { q: "Mobile phase?", a: "What carries samples." },
      { q: "Stationary phase?", a: "Solid or liquid on solid that retards." },
      { q: "Higher R_f means?", a: "Compound moves farther (less interaction with stationary)." },
      { q: "Chromatography purpose?", a: "Separate components of mixture." },
    ],
  ),
  mk(3, "3.10", "Solubility",
    "'Like dissolves like.' Polar dissolves polar; nonpolar dissolves nonpolar.",
    [
      "Polar solutes in polar solvents.",
      "Nonpolar solutes in nonpolar solvents.",
      "Ionic in polar (water).",
      "Most solids: solubility increases with T.",
      "Gases: solubility decreases with T, increases with P (Henry's Law).",
    ],
    "Will oil dissolve in water?",
    "No — oil is nonpolar; water is polar. 'Like dissolves like.'",
    [
      { q: "Like dissolves like?", a: "Polar in polar; nonpolar in nonpolar." },
      { q: "Henry's Law?", a: "Gas solubility ∝ P" },
      { q: "Gas solubility and T?", a: "Decreases with T." },
      { q: "Ionic compounds dissolve in?", a: "Water (polar)." },
      { q: "Hexane dissolves?", a: "Nonpolar compounds (e.g., oil)." },
    ],
  ),
  mk(3, "3.11", "Spectroscopy and the Electromagnetic Spectrum",
    "Light absorption/emission reveals molecular structure.",
    [
      "Spectrum: radio, microwave, IR, visible, UV, X-ray, gamma (low→high E).",
      "IR: molecular vibrations.",
      "UV-Vis: electronic transitions.",
      "Microwave: rotation.",
      "E = hν = hc/λ.",
    ],
    "Why does chlorophyll look green?",
    "Absorbs red and blue; reflects/transmits green.",
    [
      { q: "E of photon?", a: "E = hν = hc/λ" },
      { q: "IR reveals?", a: "Molecular vibrations / functional groups." },
      { q: "UV-Vis reveals?", a: "Electronic transitions (conjugation)." },
      { q: "Complementary color?", a: "Transmitted color." },
      { q: "High E light?", a: "Short λ (UV, X-ray)." },
    ],
  ),
  mk(3, "3.12", "Photoelectric Effect",
    "Photons with E > work function eject e⁻. E_kinetic = hν − φ.",
    [
      "Einstein (1905) explained using photons.",
      "No e⁻ ejected below threshold frequency.",
      "Above threshold: more intensity → more e⁻ (same KE per e⁻).",
      "Higher ν → higher KE per e⁻.",
      "Supports particle nature of light.",
    ],
    "If work function of Na = 2.3 eV and photon = 4 eV, ejected e⁻ KE?",
    "KE = 4 − 2.3 = 1.7 eV.",
    [
      { q: "Work function φ?", a: "Min energy to eject e⁻." },
      { q: "Einstein equation?", a: "KE = hν − φ" },
      { q: "Below threshold ν?", a: "No e⁻ ejected (intensity irrelevant)." },
      { q: "Support for?", a: "Particle (photon) nature of light." },
      { q: "Increasing intensity above threshold?", a: "More e⁻ ejected (same KE per)." },
    ],
  ),
  mk(3, "3.13", "Beer-Lambert Law",
    "A = εbc. Absorbance ∝ concentration at given λ.",
    [
      "A = absorbance (unitless).",
      "ε = molar absorptivity (L/mol·cm).",
      "b = path length (cm).",
      "c = concentration (mol/L).",
      "Used for quantitative colorimetry.",
    ],
    "ε=1500, b=1 cm, c=0.001 M. A?",
    "A = (1500)(1)(0.001) = 1.5.",
    [
      { q: "Beer-Lambert Law?", a: "A = εbc" },
      { q: "Plot A vs c?", a: "Linear; slope = εb" },
      { q: "What does A measure?", a: "Light absorbed by sample." },
      { q: "Unitless?", a: "A (but ε has units)" },
      { q: "Purpose?", a: "Determine unknown concentration." },
    ],
  ),
  mk(4, "4.1", "Introduction for Reactions",
    "Reactions: reactants → products. Conserved: atoms, mass, charge.",
    [
      "Write reactants → products.",
      "Balance to conserve atoms.",
      "States: (s), (l), (g), (aq).",
      "Arrow type: → irreversible; ⇌ equilibrium.",
    ],
    "Balance H₂ + O₂ → H₂O.",
    "2H₂ + O₂ → 2H₂O.",
    [
      { q: "Balanced equation conserves?", a: "Atoms of each element." },
      { q: "States of matter labels?", a: "(s), (l), (g), (aq)" },
      { q: "⇌?", a: "Reversible / equilibrium." },
      { q: "Coefficient represents?", a: "Moles (or molecules)." },
      { q: "Subscript represents?", a: "Atoms in one molecule." },
    ],
  ),
  mk(4, "4.2", "Net Ionic Equations",
    "Keep only species that change. Drop spectator ions.",
    [
      "Complete ionic: show all dissolved ions.",
      "Net ionic: drop spectator ions.",
      "Spectator: doesn't change state or charge.",
      "Conservation: mass + charge.",
    ],
    "AgNO₃(aq) + NaCl(aq) → AgCl(s) + NaNO₃(aq). Net ionic?",
    "Ag⁺ + Cl⁻ → AgCl(s). Na⁺ and NO₃⁻ are spectators.",
    [
      { q: "Spectator ion?", a: "Ion unchanged through reaction." },
      { q: "Net ionic equation?", a: "Only species actually changing." },
      { q: "Balanced for?", a: "Mass AND charge." },
      { q: "Strong electrolytes in solution?", a: "Show as separate ions." },
      { q: "Precipitate in net ionic?", a: "Keep as solid unit (e.g., AgCl(s))." },
    ],
  ),
  mk(4, "4.3", "Representations of Reactions",
    "Particle diagrams, equations, word descriptions all model reactions.",
    [
      "Macroscopic: what you see (color, state).",
      "Particulate: atoms/ions in motion.",
      "Symbolic: balanced equation.",
      "All three views must be consistent.",
    ],
    "Explain what a particle diagram for NaCl dissolving shows.",
    "Shows individual Na⁺ and Cl⁻ ions surrounded by water molecules (hydration shells) — no intact NaCl.",
    [
      { q: "Three levels?", a: "Macroscopic, particulate, symbolic." },
      { q: "Particulate level?", a: "Atoms, molecules, ions in motion." },
      { q: "Why all three?", a: "Each reveals different info." },
      { q: "Symbolic?", a: "Balanced chemical equation." },
      { q: "Macroscopic?", a: "What you observe with eyes." },
    ],
  ),
  mk(4, "4.4", "Physical and Chemical Changes",
    "Physical: phase/appearance change; chemical: new substance formed.",
    [
      "Physical: melting, dissolving, breaking, phase changes.",
      "Chemical: combustion, rusting, decomposition, acid-base.",
      "Signs of chemical change: color change, gas, ppt, temp change.",
      "Mass conserved in both.",
    ],
    "Is ice melting a physical or chemical change?",
    "Physical — H₂O remains H₂O, just changes phase.",
    [
      { q: "Physical change examples?", a: "Melting, boiling, dissolving." },
      { q: "Chemical change examples?", a: "Burning, rusting, cooking." },
      { q: "Signs of chemical change?", a: "Color change, gas, ppt, heat/light." },
      { q: "Mass in chemical change?", a: "Conserved." },
      { q: "Does mass change in chemical reactions?", a: "No — Law of Conservation of Mass." },
    ],
  ),
  mk(4, "4.5", "Stoichiometry",
    "Use moles as the bridge. Limiting reactant, theoretical/percent yield.",
    [
      "Balance equation; compute moles; use ratio.",
      "Limiting reactant: runs out first.",
      "Theoretical yield: from stoichiometry.",
      "% yield = (actual/theoretical) × 100.",
    ],
    "2H₂ + O₂ → 2H₂O. From 4 mol H₂ and 3 mol O₂, how much H₂O?",
    "Need 2H₂ per O₂. 4 H₂ pairs with 2 O₂ → O₂ in excess. Limiting = H₂. 4 mol H₂O.",
    [
      { q: "Limiting reactant?", a: "Reactant that runs out first, limits product." },
      { q: "Theoretical yield?", a: "Max product from limiting reactant." },
      { q: "% yield?", a: "(actual/theoretical) × 100" },
      { q: "Mole ratio source?", a: "Balanced equation coefficients." },
      { q: "Excess reactant?", a: "Left over after limiting runs out." },
    ],
  ),
  mk(4, "4.6", "Introduction to Titration",
    "Titrant reacts with analyte; equivalence = stoichiometric.",
    [
      "Titrant of known concentration.",
      "Analyte of unknown concentration.",
      "Indicator signals endpoint (near equivalence).",
      "M_a V_a = M_b V_b (for 1:1 stoichiometry).",
    ],
    "25 mL HCl titrated with 20 mL of 0.1 M NaOH. HCl molarity?",
    "M_HCl × 25 = 0.1 × 20 → M_HCl = 0.08 M.",
    [
      { q: "Equivalence point?", a: "Moles acid = moles base (stoichiometric)." },
      { q: "Endpoint?", a: "Indicator changes color — approximates equivalence." },
      { q: "1:1 stoich relation?", a: "M_a V_a = M_b V_b" },
      { q: "What titrates a weak acid?", a: "Strong base (NaOH)." },
      { q: "Indicator choice?", a: "Changes color near equivalence pH." },
    ],
  ),
  mk(4, "4.7", "Types of Chemical Reactions",
    "Synthesis, decomposition, single/double replacement, combustion, precipitation, acid-base, redox.",
    [
      "Synthesis: A + B → AB.",
      "Decomposition: AB → A + B.",
      "Single replacement: A + BC → AC + B.",
      "Double replacement: AB + CD → AD + CB.",
      "Combustion: hydrocarbon + O₂ → CO₂ + H₂O.",
    ],
    "Classify: Zn + CuSO₄ → ZnSO₄ + Cu.",
    "Single replacement — Zn displaces Cu (also redox).",
    [
      { q: "Synthesis?", a: "A + B → AB" },
      { q: "Decomposition?", a: "AB → A + B" },
      { q: "Single replacement?", a: "A + BC → AC + B" },
      { q: "Double replacement?", a: "AB + CD → AD + CB" },
      { q: "Combustion products?", a: "CO₂ + H₂O (with hydrocarbon)" },
    ],
  ),
  mk(4, "4.8", "Introduction to Acid-Base Reactions",
    "Brønsted-Lowry: acid donates H⁺; base accepts H⁺.",
    [
      "Acid + Base → salt + water (often).",
      "Conjugate acid-base pairs differ by one H⁺.",
      "Strong acids/bases fully dissociate.",
      "Weak ones partially dissociate.",
    ],
    "Identify conjugate pair: HCl + H₂O → H₃O⁺ + Cl⁻.",
    "HCl/Cl⁻ and H₂O/H₃O⁺ are the two conjugate pairs.",
    [
      { q: "Brønsted-Lowry acid?", a: "H⁺ donor" },
      { q: "Brønsted-Lowry base?", a: "H⁺ acceptor" },
      { q: "Conjugate pair?", a: "Species differ by one H⁺." },
      { q: "Strong acid?", a: "Fully dissociates (HCl, HNO₃, H₂SO₄)." },
      { q: "Strong base?", a: "Fully dissociates (NaOH, KOH)." },
    ],
  ),
  mk(4, "4.9", "Oxidation-Reduction (Redox) Reactions",
    "Redox: electrons transferred. OIL RIG. Oxidation states track.",
    [
      "Oxidation: lose e⁻ (OIL).",
      "Reduction: gain e⁻ (RIG).",
      "Oxidizing agent: causes oxidation (gets reduced).",
      "Reducing agent: causes reduction (gets oxidized).",
      "Balance: half-reactions method.",
    ],
    "Zn + Cu²⁺ → Zn²⁺ + Cu. Which is oxidized?",
    "Zn (0 → +2, loses e⁻). Cu²⁺ is reduced (+2 → 0).",
    [
      { q: "Oxidation?", a: "Losing electrons (OIL)" },
      { q: "Reduction?", a: "Gaining electrons (RIG)" },
      { q: "Oxidizing agent?", a: "Gets reduced; takes electrons." },
      { q: "Reducing agent?", a: "Gets oxidized; gives electrons." },
      { q: "Half-reaction method?", a: "Split redox into oxidation and reduction halves." },
    ],
  ),
  mk(5, "5.1", "Reaction Rate",
    "Rate = change in concentration per time. Depends on concentration, T, surface area, catalyst.",
    [
      "Rate = −Δ[A]/Δt (for reactant) = Δ[P]/Δt (for product).",
      "Rate depends on concentration, T, catalyst, surface area.",
      "Instantaneous rate: slope at a point.",
      "Average rate: Δ[X]/Δt over interval.",
    ],
    "[A] drops from 0.50 to 0.40 M in 10 s. Average rate?",
    "Rate = 0.10/10 = 0.010 M/s.",
    [
      { q: "Rate definition?", a: "Δ[]/Δt" },
      { q: "Factors affecting rate?", a: "Concentration, T, catalyst, surface area." },
      { q: "Units of rate?", a: "M/s (mol/L/s)" },
      { q: "Instantaneous rate?", a: "Slope of tangent." },
      { q: "Average rate?", a: "Total change / total time." },
    ],
  ),
  mk(5, "5.2", "Introduction to Rate Law",
    "Rate = k[A]^m[B]^n. Order: m, n, or m+n. k = rate constant.",
    [
      "Rate = k[A]^m[B]^n.",
      "m, n determined experimentally (not from coefficients).",
      "Order in A = m; overall order = m + n.",
      "k has units depending on total order.",
    ],
    "Rate doubles when [A] doubles, same when [B] doubles. Order?",
    "Order in A = 1, order in B = 0. Overall = 1. Rate law: rate = k[A].",
    [
      { q: "Rate law form?", a: "rate = k[A]^m[B]^n" },
      { q: "Order determined from?", a: "Experiment (NOT coefficients)." },
      { q: "Zero order in B?", a: "Rate unchanged when [B] changes." },
      { q: "First order?", a: "Rate doubles when concentration doubles." },
      { q: "Second order?", a: "Rate ×4 when concentration doubles." },
    ],
  ),
  mk(5, "5.3", "Concentration Changes Over Time",
    "Integrated rate laws: 0-order, 1st-order, 2nd-order.",
    [
      "0-order: [A] = [A]₀ − kt; linear plot.",
      "1st-order: ln[A] = ln[A]₀ − kt; ln plot linear.",
      "2nd-order: 1/[A] = 1/[A]₀ + kt; 1/[A] linear.",
      "Half-life 1st-order: t½ = 0.693/k (constant).",
    ],
    "t½ for first-order with k = 0.1 s⁻¹?",
    "t½ = 0.693/0.1 = 6.93 s.",
    [
      { q: "0-order integrated?", a: "[A] = [A]₀ − kt" },
      { q: "1st-order integrated?", a: "ln[A] = ln[A]₀ − kt" },
      { q: "2nd-order integrated?", a: "1/[A] = 1/[A]₀ + kt" },
      { q: "1st-order half-life?", a: "t½ = 0.693/k" },
      { q: "Straight-line plot for 1st order?", a: "ln[A] vs t" },
    ],
  ),
  mk(5, "5.4", "Elementary Reactions",
    "Single-step reactions. Order matches molecularity.",
    [
      "Elementary step = single collision.",
      "Order equals molecularity.",
      "Unimolecular: A → products, rate = k[A].",
      "Bimolecular: A + B → products, rate = k[A][B].",
    ],
    "Is 2A → products elementary?",
    "If elementary, rate = k[A]² — must be verified experimentally.",
    [
      { q: "Elementary step?", a: "Single reaction step (one collision)." },
      { q: "Unimolecular?", a: "Single molecule rearranges." },
      { q: "Bimolecular?", a: "Two molecules collide." },
      { q: "Termolecular?", a: "Three-body collision (rare)." },
      { q: "Rate of elementary?", a: "Matches coefficients (unlike overall reaction)." },
    ],
  ),
  mk(5, "5.5", "Collision Model",
    "Reactions need effective collisions: sufficient energy and proper orientation.",
    [
      "Rate ∝ collisions × fraction with energy ≥ Ea × fraction with right geometry.",
      "Higher T: more collisions and more energetic collisions.",
      "Catalyst: lowers Ea.",
      "Arrhenius: k = A·e^(−Ea/RT).",
    ],
    "Why does T increase rate?",
    "More molecules have KE ≥ Ea, so fraction of effective collisions rises exponentially.",
    [
      { q: "Effective collision?", a: "Sufficient energy + proper orientation." },
      { q: "Activation energy (Ea)?", a: "Minimum energy for reaction." },
      { q: "Arrhenius equation?", a: "k = A·e^(−Ea/RT)" },
      { q: "Catalyst effect?", a: "Lowers Ea." },
      { q: "Temperature effect?", a: "Rate rises exponentially with T." },
    ],
  ),
  mk(5, "5.6", "Reaction Energy Profile",
    "Plot E vs reaction progress. Shows Ea and ΔH (exo/endo).",
    [
      "X-axis: reaction progress.",
      "Y-axis: potential energy.",
      "Peak = transition state (activated complex).",
      "Ea = peak − reactants.",
      "ΔH = products − reactants.",
    ],
    "Exothermic reaction: products vs reactants energy?",
    "Products lower than reactants (ΔH < 0).",
    [
      { q: "Transition state?", a: "Highest-E point on profile." },
      { q: "Ea?", a: "Peak − reactants energy." },
      { q: "ΔH?", a: "Products − reactants." },
      { q: "Exothermic?", a: "Products lower (ΔH < 0)." },
      { q: "Endothermic?", a: "Products higher (ΔH > 0)." },
    ],
  ),
  mk(5, "5.7", "Introduction to Reaction Mechanisms",
    "Mechanism: series of elementary steps producing overall reaction.",
    [
      "Elementary steps sum to overall reaction.",
      "Intermediates appear/disappear (not in overall).",
      "Rate-determining step (RDS): slowest.",
      "Overall rate law from RDS.",
    ],
    "Mechanism: A + B → X (slow); X + C → D (fast). Rate law?",
    "RDS is slow step: rate = k[A][B].",
    [
      { q: "Mechanism?", a: "Series of elementary steps." },
      { q: "Intermediate?", a: "Formed then consumed (not in overall)." },
      { q: "Rate-determining step?", a: "Slowest step; governs overall rate." },
      { q: "Summed elementary = ?", a: "Overall reaction." },
      { q: "Catalyst?", a: "Speeds rate, not consumed." },
    ],
  ),
  mk(5, "5.8", "Reaction Mechanism and Rate Law",
    "Infer rate law from RDS of proposed mechanism.",
    [
      "RDS = slowest step; its rate law determines overall.",
      "If RDS is first: rate law = k[reactants_of_RDS].",
      "If RDS has an intermediate: substitute using earlier fast equilibrium.",
      "Check: proposed mechanism must reproduce experimentally observed rate law.",
    ],
    "Mechanism: 2A ⇌ X (fast eq); X + B → products (slow). Rate law?",
    "RDS: rate = k₂[X][B]. From fast eq: K = [X]/[A]² → [X] = K[A]². So rate = k₂K[A]²[B].",
    [
      { q: "Mechanism consistent if?", a: "Predicted rate law matches experiment." },
      { q: "Sub for intermediate using?", a: "Preceding fast equilibrium." },
      { q: "RDS defines?", a: "Rate law form." },
      { q: "Intermediate in rate law?", a: "No — substitute it out." },
      { q: "Fast pre-equilibrium?", a: "Equal forward/reverse rates before slow step." },
    ],
  ),
  mk(5, "5.9", "Steady-State Approximation",
    "Intermediate concentration constant: rate of formation = rate of consumption.",
    [
      "d[intermediate]/dt ≈ 0.",
      "Set formation rate = consumption rate.",
      "Solve for [intermediate] and substitute.",
      "Alternative to fast pre-equilibrium when latter doesn't apply.",
    ],
    "When is steady-state approximation valid?",
    "When the intermediate is consumed as fast as it's made, so its concentration stays low and roughly constant.",
    [
      { q: "Steady-state approximation?", a: "d[int]/dt ≈ 0" },
      { q: "When valid?", a: "Intermediate consumed rapidly." },
      { q: "Alternative?", a: "Fast pre-equilibrium approximation." },
      { q: "Use it to?", a: "Find rate law when pre-equilibrium doesn't apply." },
      { q: "Does it change mechanism?", a: "No — just how we derive rate law." },
    ],
  ),
  mk(5, "5.10", "Multistep Reaction Energy Profile",
    "Multiple steps = multiple peaks; tallest barrier = RDS; valleys = intermediates.",
    [
      "Each elementary step has its own Ea and ΔH.",
      "Intermediate = local minimum between peaks.",
      "Transition state = each peak.",
      "RDS = highest peak.",
    ],
    "A two-step reaction. Which step is rate-determining?",
    "The one with the higher activation energy peak.",
    [
      { q: "Two-step profile?", a: "Two peaks, one valley." },
      { q: "Intermediates where?", a: "In valleys between peaks." },
      { q: "RDS = ?", a: "Highest peak (tallest Ea)." },
      { q: "Overall ΔH?", a: "Final products − initial reactants." },
      { q: "Transition states at?", a: "Each peak." },
    ],
  ),
  mk(5, "5.11", "Catalysis",
    "Catalysts lower Ea by providing alternate pathway. Not consumed.",
    [
      "Catalyst: lowers Ea, speeds rate both directions equally.",
      "Heterogeneous: different phase (e.g., solid catalyst, gas reactants).",
      "Homogeneous: same phase (e.g., acid catalyst in aqueous).",
      "Enzymes: biological catalysts.",
      "Catalyst does NOT change ΔH or equilibrium constant.",
    ],
    "Does a catalyst affect K_eq?",
    "No — catalyst speeds forward and reverse equally; equilibrium position unchanged.",
    [
      { q: "Catalyst effect?", a: "Lowers Ea → faster rate." },
      { q: "Does catalyst shift equilibrium?", a: "No — both directions sped equally." },
      { q: "Heterogeneous catalyst?", a: "Different phase from reactants." },
      { q: "Homogeneous catalyst?", a: "Same phase as reactants." },
      { q: "Enzyme?", a: "Biological catalyst (protein)." },
    ],
  ),
  mk(6, "6.1", "Endothermic and Exothermic Processes",
    "Exo: releases energy (ΔH<0). Endo: absorbs (ΔH>0).",
    [
      "Exothermic: surroundings warm up; system loses energy.",
      "Endothermic: surroundings cool; system gains energy.",
      "Bond breaking absorbs E; bond forming releases E.",
      "Net: energy balance of bond changes.",
    ],
    "Ice melting: endo or exo?",
    "Endothermic — absorbs heat from surroundings to break H-bonds in ice.",
    [
      { q: "Exothermic ΔH?", a: "Negative (< 0)" },
      { q: "Endothermic ΔH?", a: "Positive (> 0)" },
      { q: "Bond breaking?", a: "Absorbs energy." },
      { q: "Bond making?", a: "Releases energy." },
      { q: "Combustion is usually?", a: "Exothermic." },
    ],
  ),
  mk(6, "6.2", "Energy Diagrams",
    "Plot PE vs progress. Show reactants, products, Ea, ΔH.",
    [
      "Reactants start at given E; products end at given E.",
      "Peak(s) = activation barriers.",
      "Exothermic profile: products lower.",
      "Endothermic: products higher.",
    ],
    "Draw an energy diagram for an endothermic reaction.",
    "Reactants low; peak (Ea) in middle; products higher than reactants (ΔH > 0).",
    [
      { q: "Reactants on y-axis?", a: "Left side, starting E level." },
      { q: "Products?", a: "Right side, ending E level." },
      { q: "Peak = ?", a: "Transition state / activation barrier." },
      { q: "Exo profile?", a: "Products lower." },
      { q: "Catalyst on diagram?", a: "Lowers the peak." },
    ],
  ),
  mk(6, "6.3", "Heat Transfer and Thermal Equilibrium",
    "q = mcΔT. At equilibrium, T_final same for both objects.",
    [
      "q = heat (J); positive if absorbed.",
      "q = mcΔT.",
      "c = specific heat (J/g·°C).",
      "Thermal equilibrium: T's equal; net heat flow = 0.",
    ],
    "50 g water heated 10°C. q?",
    "q = (50)(4.18)(10) = 2090 J.",
    [
      { q: "q = ?", a: "mcΔT" },
      { q: "c?", a: "Specific heat (J/g·°C)" },
      { q: "c of water?", a: "4.18 J/g·°C" },
      { q: "Thermal equilibrium?", a: "T's equal; net heat flow zero." },
      { q: "q positive?", a: "Heat absorbed." },
    ],
  ),
  mk(6, "6.4", "Heat Capacity and Calorimetry",
    "Calorimeter: measures q. Coffee-cup or bomb.",
    [
      "Heat capacity C = q/ΔT (J/°C); specific heat c = C/m.",
      "Coffee-cup (constant P): q = ΔH.",
      "Bomb (constant V): q = ΔU.",
      "Insulated: q_system = −q_surroundings.",
    ],
    "50 g metal at 100°C dropped in 200 g water at 20°C. Final T = 23°C. c_metal?",
    "q_water = q_metal (mag). (200)(4.18)(3) = (50)(c)(77). c = 2508/3850 = 0.65 J/g·°C.",
    [
      { q: "Coffee-cup gives?", a: "q at constant P = ΔH" },
      { q: "Bomb gives?", a: "q at constant V = ΔU" },
      { q: "Calorimetry principle?", a: "q_system = −q_surroundings (insulated)" },
      { q: "Heat capacity?", a: "C = q/ΔT" },
      { q: "Specific heat?", a: "c = C/m" },
    ],
  ),
  mk(6, "6.5", "Energy of Phase Changes",
    "Phase change absorbs/releases energy at constant T. ΔH_fus, ΔH_vap.",
    [
      "T constant during phase change.",
      "ΔH_fus: melting.",
      "ΔH_vap: vaporization (usually larger than fus).",
      "q = n × ΔH for phase change; q = mcΔT for T change.",
    ],
    "Heat 10 g ice at 0°C to water at 0°C. ΔH_fus = 334 J/g.",
    "q = (10)(334) = 3340 J.",
    [
      { q: "During phase change T?", a: "Constant." },
      { q: "ΔH_fus?", a: "Heat of fusion (melting)." },
      { q: "ΔH_vap?", a: "Heat of vaporization." },
      { q: "Which is larger?", a: "ΔH_vap > ΔH_fus (usually)." },
      { q: "q for phase change?", a: "n × ΔH" },
    ],
  ),
  mk(6, "6.6", "Introduction to Enthalpy of Reaction",
    "ΔH_rxn = H_products − H_reactants. At constant P = q.",
    [
      "ΔH = H_products − H_reactants.",
      "ΔH < 0: exothermic; ΔH > 0: endothermic.",
      "State function: path-independent.",
      "Per mole of reaction.",
    ],
    "ΔH for 2H₂ + O₂ → 2H₂O is −484 kJ. Energy from burning 1 mol H₂?",
    "From 2H₂ → 2H₂O: −484 kJ. Per mol H₂: −242 kJ.",
    [
      { q: "ΔH sign exothermic?", a: "Negative" },
      { q: "ΔH at constant P?", a: "Equals q" },
      { q: "State function?", a: "Depends only on initial/final states." },
      { q: "ΔH reversed reaction?", a: "Sign flipped." },
      { q: "Per mole of?", a: "Reaction as written." },
    ],
  ),
  mk(6, "6.7", "Bond Enthalpies",
    "ΔH ≈ Σ(bonds broken) − Σ(bonds formed). Approximate.",
    [
      "Bond enthalpy: energy to break bond in gas phase.",
      "ΔH ≈ Σ(bonds broken) − Σ(bonds formed).",
      "Positive for breaking (absorbs); negative for forming (releases).",
      "Only approximate; use Hess's law for accuracy.",
    ],
    "Estimate ΔH for H₂ + Cl₂ → 2HCl. BE: H-H=436, Cl-Cl=243, H-Cl=432.",
    "Break: 436 + 243 = 679. Form: 2(432) = 864. ΔH ≈ 679 − 864 = −185 kJ.",
    [
      { q: "Bond enthalpy?", a: "Energy to break bond in gas phase." },
      { q: "ΔH from BEs?", a: "Σ broken − Σ formed" },
      { q: "Breaking absorbs?", a: "Yes (positive)." },
      { q: "Forming releases?", a: "Yes (negative)." },
      { q: "Accuracy?", a: "Approximate — avg over molecules." },
    ],
  ),
  mk(6, "6.8", "Enthalpy of Formation",
    "ΔH_f°: formation from elements in standard states. Tabulated.",
    [
      "ΔH_f° = 0 for element in standard state.",
      "ΔH_rxn° = Σ n_products·ΔH_f°(products) − Σ n_reactants·ΔH_f°(reactants).",
      "Standard state: 25°C, 1 atm, most stable form.",
      "Widely tabulated.",
    ],
    "ΔH_rxn for CO + ½O₂ → CO₂. ΔH_f°: CO=−111, CO₂=−394, O₂=0.",
    "ΔH = (−394) − (−111 + 0) = −283 kJ/mol.",
    [
      { q: "ΔH_f° of element in standard state?", a: "0" },
      { q: "Formula?", a: "Σ n·ΔH_f°(prod) − Σ n·ΔH_f°(react)" },
      { q: "Standard state conditions?", a: "25°C, 1 atm, most stable form." },
      { q: "Units?", a: "kJ/mol" },
      { q: "ΔH_f° of O₂(g)?", a: "0" },
    ],
  ),
  mk(6, "6.9", "Hess's Law",
    "If reaction = sum of steps, ΔH = sum of ΔH's. Path-independent.",
    [
      "Enthalpy is state function.",
      "Add equations → add ΔH's.",
      "Reverse equation → flip sign of ΔH.",
      "Multiply equation → multiply ΔH.",
    ],
    "Given A → B (ΔH₁ = 100) and B → C (ΔH₂ = −40), find A → C.",
    "A → C: ΔH = 100 + (−40) = 60 kJ.",
    [
      { q: "Hess's Law?", a: "ΔH path-independent; sum step ΔH's." },
      { q: "Reverse reaction ΔH?", a: "Negate." },
      { q: "Multiply by 2 ΔH?", a: "Multiply by 2." },
      { q: "State function?", a: "Depends only on states, not path." },
      { q: "Use for?", a: "Computing ΔH of hard-to-measure reactions." },
    ],
  ),
  mk(7, "7.1", "Introduction to Equilibrium",
    "Forward rate = reverse rate; concentrations constant. Dynamic balance.",
    [
      "Reached when forward = reverse rate.",
      "Dynamic: reactions continue, net change = 0.",
      "[reactants] and [products] don't change (but aren't equal).",
      "Depends on T.",
    ],
    "Does equilibrium mean [reactants] = [products]?",
    "No — it means rates are equal. Concentrations can be very different.",
    [
      { q: "Equilibrium condition?", a: "Forward rate = reverse rate." },
      { q: "Dynamic?", a: "Reactions continue, but net change = 0." },
      { q: "Depends on T?", a: "Yes." },
      { q: "Are concentrations equal?", a: "No — just constant." },
      { q: "Closed vs open system?", a: "Equilibrium needs closed system." },
    ],
  ),
  mk(7, "7.2", "Direction of Reversible Reactions",
    "Reversible: ⇌. Reaction proceeds to minimize Gibbs free energy.",
    [
      "Reversible: both directions possible.",
      "Irreversible: one direction only (products released/consumed).",
      "Direction toward equilibrium: net reaction minimizes G.",
      "Approaches equilibrium from either side.",
    ],
    "How do you know which direction?",
    "Compare Q to K: Q < K → forward; Q > K → reverse; Q = K → equilibrium.",
    [
      { q: "Reversible reaction arrow?", a: "⇌" },
      { q: "Q?", a: "Reaction quotient (same form as K, current concs)." },
      { q: "Q < K means?", a: "Proceeds forward." },
      { q: "Q > K means?", a: "Proceeds reverse." },
      { q: "Q = K?", a: "At equilibrium." },
    ],
  ),
  mk(7, "7.3", "Reaction Quotient and Equilibrium Constant",
    "K = [products]/[reactants]^coeffs. Q = same form, any moment.",
    [
      "K_eq: at equilibrium (fixed for given T).",
      "Q: any instant; compare to K.",
      "Pure solids, liquids omitted from K expression.",
      "K_c (concentrations), K_p (partial pressures).",
    ],
    "For N₂ + 3H₂ ⇌ 2NH₃, write K.",
    "K = [NH₃]²/([N₂][H₂]³).",
    [
      { q: "K expression?", a: "[products]^coef / [reactants]^coef" },
      { q: "Omit from K?", a: "Pure solids and liquids (activity = 1)." },
      { q: "K_c vs K_p?", a: "Concentrations vs partial pressures." },
      { q: "Q form?", a: "Same as K with current concs." },
      { q: "Large K means?", a: "Favors products." },
    ],
  ),
  mk(7, "7.4", "Calculating the Equilibrium Constant",
    "Plug equilibrium concentrations into K expression. Use ICE table for setup.",
    [
      "Set up ICE (Initial, Change, Equilibrium) table.",
      "Fill known values; use stoichiometry for changes.",
      "Substitute equilibrium row into K.",
      "Units usually omitted.",
    ],
    "H₂ + I₂ ⇌ 2HI. At equilibrium: [H₂]=[I₂]=0.2, [HI]=1.6. K?",
    "K = (1.6)² / ((0.2)(0.2)) = 2.56/0.04 = 64.",
    [
      { q: "ICE?", a: "Initial, Change, Equilibrium" },
      { q: "Use stoichiometry for?", a: "Changes (C row)." },
      { q: "Plug what into K?", a: "Equilibrium row." },
      { q: "Units?", a: "Usually omitted." },
      { q: "Large K?", a: "Products favored." },
    ],
  ),
  mk(7, "7.5", "Magnitude of the Equilibrium Constant",
    "K > 1: products favored. K < 1: reactants favored. K >> 1: nearly complete.",
    [
      "K > 1: products favored (K < 1 means reactants).",
      "K >> 1 (e.g., 10⁵): essentially complete.",
      "K << 1 (e.g., 10⁻⁵): essentially no reaction.",
      "K ≈ 1: comparable amounts.",
    ],
    "K = 10⁶. Interpret.",
    "Very products-favored — essentially complete reaction.",
    [
      { q: "K > 1?", a: "Products favored." },
      { q: "K < 1?", a: "Reactants favored." },
      { q: "K >> 1?", a: "Nearly complete forward." },
      { q: "K near 1?", a: "Significant amounts of both." },
      { q: "K depends on?", a: "Temperature only." },
    ],
  ),
  mk(7, "7.6", "Properties of the Equilibrium Constant",
    "Reverse reaction: K' = 1/K. Multiply coefficients by n: K' = K^n. Sum reactions: multiply K's.",
    [
      "Reverse: K_rev = 1/K.",
      "Multiply coefficients by n: K_new = K^n.",
      "Sum reactions: multiply K's.",
      "K_c and K_p related: K_p = K_c(RT)^Δn.",
    ],
    "Rxn A has K = 4. Reverse K?",
    "K_rev = 1/4 = 0.25.",
    [
      { q: "Reverse K?", a: "1/K" },
      { q: "Doubled coefficients K?", a: "K²" },
      { q: "Summed reactions K?", a: "Product of individual K's." },
      { q: "K_p vs K_c?", a: "K_p = K_c(RT)^Δn" },
      { q: "Δn?", a: "Moles gaseous products − moles gaseous reactants." },
    ],
  ),
  mk(7, "7.7", "Calculating Equilibrium Concentrations",
    "Given K and initial, use ICE + quadratic (or approximation) to find equilibrium.",
    [
      "Set up ICE table.",
      "Express eq concentrations with variable x (change).",
      "Plug into K expression.",
      "Small-x approximation if K << 1 (check validity at end).",
    ],
    "Initial [A] = 0.1, K = 4×10⁻⁴ for A ⇌ B + C. Find [B] = x.",
    "x²/(0.1 − x) ≈ x²/0.1 = 4×10⁻⁴. x² = 4×10⁻⁵, x ≈ 6.3×10⁻³. OK since x << 0.1.",
    [
      { q: "Small-x approx valid when?", a: "x < 5% of initial (K << 1)." },
      { q: "If K not small?", a: "Solve the quadratic." },
      { q: "ICE steps?", a: "Initial → Change (±x·coef) → Equilibrium" },
      { q: "Check approximation?", a: "Compare x to initial; should be < 5%." },
      { q: "K > 1 approach?", a: "May need reverse approach or full quadratic." },
    ],
  ),
  mk(7, "7.8", "Representations of Equilibrium",
    "Particle diagrams, concentration vs time plots show equilibrium.",
    [
      "Particle diagram: show mix of reactants and products.",
      "Conc-vs-time: levels off at equilibrium.",
      "Equilibrium does NOT mean equal concentrations.",
      "Forward and reverse arrows signal reversibility.",
    ],
    "On a [A] vs t plot, how can you tell equilibrium is reached?",
    "Curves level off (horizontal); concentrations stop changing.",
    [
      { q: "Equilibrium diagram?", a: "Mixed reactants and products, consistent proportions." },
      { q: "Plot equilibrium signal?", a: "Horizontal lines." },
      { q: "Equal concentrations at eq?", a: "Not required — just constant." },
      { q: "Reversibility arrow?", a: "⇌" },
      { q: "Particle ratio at eq?", a: "Reflects K value." },
    ],
  ),
  mk(7, "7.9", "Introduction to Le Châtelier's Principle",
    "Stress equilibrium → shifts to counteract the stress.",
    [
      "Add reactant → shifts forward.",
      "Add product → shifts reverse.",
      "Compress (less V) → shifts toward fewer moles gas.",
      "Heat endothermic reaction → shifts forward.",
    ],
    "N₂ + 3H₂ ⇌ 2NH₃ (exo). Effect of raising T?",
    "Shifts reverse (breaks NH₃) — favors endothermic direction.",
    [
      { q: "Le Châtelier's Principle?", a: "System responds to counteract stress." },
      { q: "Add reactant?", a: "Shifts forward." },
      { q: "Decrease volume?", a: "Shifts toward fewer moles gas." },
      { q: "Heat exothermic?", a: "Shifts reverse." },
      { q: "Catalyst?", a: "No shift — reaches eq faster." },
    ],
  ),
  mk(7, "7.10", "Reaction Quotient and Le Châtelier's Principle",
    "Q vs K: Q < K → forward; Q > K → reverse.",
    [
      "Q compared to K predicts direction.",
      "Concentration change: recompute Q, compare to K.",
      "System moves toward Q = K.",
      "Links Le Châtelier to quantitative K.",
    ],
    "K = 10, Q = 5 after adding reactant. Direction?",
    "Q < K → proceeds forward (makes more products).",
    [
      { q: "Q < K?", a: "Forward" },
      { q: "Q > K?", a: "Reverse" },
      { q: "Q = K?", a: "Equilibrium" },
      { q: "Adding product?", a: "Increases Q." },
      { q: "Adding reactant?", a: "Decreases Q." },
    ],
  ),
  mk(7, "7.11", "Introduction to Solubility Equilibria",
    "K_sp: equilibrium for dissolution. Larger K_sp = more soluble.",
    [
      "K_sp = [cation]^a[anion]^b for MX_n dissolution.",
      "Omit pure solid.",
      "Larger K_sp → more soluble.",
      "Calculate molar solubility from K_sp.",
    ],
    "AgCl K_sp = 1.8×10⁻¹⁰. Molar solubility?",
    "[Ag⁺][Cl⁻] = s² = 1.8×10⁻¹⁰ → s = 1.3×10⁻⁵ M.",
    [
      { q: "K_sp?", a: "Solubility product constant." },
      { q: "K_sp expression?", a: "[cation][anion] (no solid)." },
      { q: "Larger K_sp?", a: "More soluble." },
      { q: "AgCl K_sp?", a: "s² (both ions at s)." },
      { q: "CaF₂ K_sp?", a: "[Ca²⁺][F⁻]² = s(2s)² = 4s³" },
    ],
  ),
  mk(7, "7.12", "Common-Ion Effect",
    "Adding common ion shifts equilibrium, reduces solubility.",
    [
      "Add ion already in equilibrium → system shifts to reduce it.",
      "Decreases solubility of sparingly soluble salt.",
      "Le Châtelier in action.",
      "Common in buffer preparation.",
    ],
    "Solubility of AgCl in pure water vs. in 0.1 M NaCl solution?",
    "Lower in NaCl — adding Cl⁻ shifts AgCl(s) ⇌ Ag⁺ + Cl⁻ left (reduces dissolving).",
    [
      { q: "Common ion effect?", a: "Adding common ion decreases solubility." },
      { q: "Why?", a: "Shifts dissolution equilibrium back." },
      { q: "Apply Le Châtelier?", a: "Yes — stress is added ion." },
      { q: "Use?", a: "Selective precipitation." },
      { q: "Solubility in pure water vs salt solution?", a: "Higher in water." },
    ],
  ),
  mk(7, "7.13", "pH and Solubility",
    "Insoluble bases/oxides dissolve in acid; insoluble acids/salts of weak acids dissolve at high pH.",
    [
      "Metal hydroxides: more soluble in acid.",
      "Salts of weak acids: more soluble in acid (H⁺ consumes anion).",
      "Salts with Cl⁻, NO₃⁻, SO₄²⁻ etc.: pH-insensitive usually.",
      "Common in environmental / mineral chemistry.",
    ],
    "Is CaCO₃ more soluble in acid or base?",
    "More soluble in acid — H⁺ consumes CO₃²⁻ (forming HCO₃⁻ and CO₂), pulling equilibrium forward.",
    [
      { q: "CaCO₃ solubility in acid?", a: "Higher — H⁺ removes CO₃²⁻." },
      { q: "Al(OH)₃ in acid?", a: "More soluble." },
      { q: "NaCl solubility pH-sensitive?", a: "No." },
      { q: "Why pH sensitivity?", a: "H⁺ or OH⁻ reacts with ion." },
      { q: "Application?", a: "Mineral dissolution, acid rain, digestion." },
    ],
  ),
  mk(7, "7.14", "Free Energy of Dissolution",
    "ΔG_dissolution = ΔH − TΔS. Spontaneous if ΔG < 0.",
    [
      "Dissolving requires ΔG < 0.",
      "ΔH_soln: may be + or −.",
      "ΔS_soln: usually positive (more disorder).",
      "T can shift spontaneity.",
    ],
    "NH₄NO₃ dissolving absorbs heat; still spontaneous. Why?",
    "ΔS positive; TΔS > ΔH (endothermic but entropy wins).",
    [
      { q: "ΔG formula?", a: "ΔH − TΔS" },
      { q: "Dissolution ΔS?", a: "Usually positive." },
      { q: "Endothermic dissolution?", a: "Spontaneous if TΔS > ΔH." },
      { q: "Temperature effect?", a: "T can change sign of ΔG." },
      { q: "Relation to K_sp?", a: "ΔG° = −RT ln K_sp" },
    ],
  ),
  mk(8, "8.1", "Introduction to Acids and Bases",
    "Brønsted-Lowry: H⁺ donor/acceptor. Conjugate pairs differ by H⁺.",
    [
      "B-L acid: H⁺ donor.",
      "B-L base: H⁺ acceptor.",
      "Conjugate base: acid after losing H⁺.",
      "Water: amphiprotic (acts as both).",
    ],
    "Conjugate base of HSO₄⁻?",
    "SO₄²⁻ (loses H⁺).",
    [
      { q: "B-L acid?", a: "Proton (H⁺) donor" },
      { q: "B-L base?", a: "Proton (H⁺) acceptor" },
      { q: "Conjugate base?", a: "Acid minus H⁺." },
      { q: "Amphiprotic?", a: "Can be acid or base (like water)." },
      { q: "HCl conjugate base?", a: "Cl⁻" },
    ],
  ),
  mk(8, "8.2", "pH and pOH of Strong Acids and Bases",
    "pH = −log[H⁺]. pH + pOH = 14 at 25°C.",
    [
      "pH = −log[H₃O⁺]; pOH = −log[OH⁻].",
      "pH + pOH = 14 (at 25°C).",
      "Strong acids dissociate fully: [H⁺] = [acid].",
      "Strong bases: [OH⁻] = [base] (×2 for Ba(OH)₂).",
    ],
    "pH of 0.01 M HCl?",
    "[H⁺] = 0.01. pH = −log(0.01) = 2.",
    [
      { q: "pH?", a: "−log[H₃O⁺]" },
      { q: "pOH?", a: "−log[OH⁻]" },
      { q: "pH + pOH (25°C)?", a: "14" },
      { q: "pH of 0.1 M NaOH?", a: "pOH = 1; pH = 13" },
      { q: "Strong acid dissociation?", a: "100%" },
    ],
  ),
  mk(8, "8.3", "Weak Acid and Base Equilibria",
    "Weak acids partially dissociate; K_a = [H⁺][A⁻]/[HA].",
    [
      "HA ⇌ H⁺ + A⁻ with K_a.",
      "pK_a = −log K_a.",
      "Small K_a → weak acid.",
      "Similar for weak bases: K_b, pK_b.",
    ],
    "0.1 M HA with K_a = 1×10⁻⁵. [H⁺]?",
    "K_a ≈ x²/0.1 = 10⁻⁵ → x² = 10⁻⁶ → x = 10⁻³ = [H⁺]. pH = 3.",
    [
      { q: "K_a expression?", a: "[H⁺][A⁻]/[HA]" },
      { q: "Smaller K_a?", a: "Weaker acid." },
      { q: "Weak acid percent dissociation?", a: "<100%, depends on K_a and [HA]." },
      { q: "pK_a?", a: "−log K_a" },
      { q: "K_w?", a: "K_a × K_b for conjugate pair = 10⁻¹⁴" },
    ],
  ),
  mk(8, "8.4", "Acid-Base Reactions and Buffers",
    "Buffer: weak acid + conjugate base (or weak base + conjugate acid). Resists pH change.",
    [
      "Buffers contain HA + A⁻ (or B + BH⁺).",
      "Absorb added acid or base.",
      "Henderson-Hasselbalch: pH = pK_a + log([A⁻]/[HA]).",
      "Work best when [HA] ≈ [A⁻] (pH near pK_a).",
    ],
    "Buffer with pK_a = 4.7, [A⁻]/[HA] = 1. pH?",
    "pH = 4.7 + log(1) = 4.7.",
    [
      { q: "Buffer?", a: "Weak acid + conjugate base (or weak base + conjugate acid)." },
      { q: "H-H equation?", a: "pH = pK_a + log([A⁻]/[HA])" },
      { q: "Best buffer pH?", a: "Near pK_a" },
      { q: "Resists?", a: "pH change when acid/base added." },
      { q: "Example?", a: "Acetic acid / acetate." },
    ],
  ),
  mk(8, "8.5", "Acid-Base Titrations",
    "Strong/strong: pH=7 at equivalence. Weak acid/strong base: pH>7 at equivalence.",
    [
      "Strong acid + strong base: equivalence at pH 7.",
      "Weak acid + strong base: equivalence pH > 7; half-eq pH = pK_a.",
      "Weak base + strong acid: equivalence pH < 7.",
      "Buffer region around half-equivalence.",
    ],
    "Titrate weak acid (pK_a = 5) with NaOH. pH at half-equivalence?",
    "pH = pK_a = 5 (H-H: [A⁻] = [HA] → log = 0).",
    [
      { q: "Strong acid + strong base equivalence pH?", a: "7" },
      { q: "Weak acid + strong base equivalence pH?", a: "> 7" },
      { q: "Half-equivalence pH?", a: "= pK_a (weak acid)" },
      { q: "Weak base + strong acid equivalence pH?", a: "< 7" },
      { q: "Why indicator choice matters?", a: "Color change must match equivalence pH." },
    ],
  ),
  mk(8, "8.6", "Molecular Structure of Acids and Bases",
    "Structure affects strength. Oxyacids: more O = stronger; down halide column, HX stronger.",
    [
      "Oxyacids: stronger with more O (HClO₄ > HClO).",
      "HX acidity: HI > HBr > HCl > HF (bond strength decreases down).",
      "Carboxylic acids: R−COOH weakly acidic.",
      "Amines: weak bases (have N lone pair).",
    ],
    "Rank: HClO, HClO₂, HClO₃, HClO₄.",
    "Stronger with more O: HClO < HClO₂ < HClO₃ < HClO₄.",
    [
      { q: "Oxyacids acidity trend?", a: "More O → stronger." },
      { q: "HX acidity trend?", a: "HI > HBr > HCl > HF" },
      { q: "Why HI strongest HX?", a: "Weaker H-I bond → easier to dissociate." },
      { q: "Carboxylic acid?", a: "R-COOH, weak acid." },
      { q: "Amines?", a: "Weak bases (N lone pair accepts H⁺)." },
    ],
  ),
  mk(8, "8.7", "pH and pKa",
    "pK_a directly measures acid strength. Lower pK_a = stronger acid.",
    [
      "pK_a = −log K_a.",
      "Lower pK_a → stronger acid.",
      "pK_a range useful: 0-14.",
      "Conjugate: pK_a + pK_b = 14.",
    ],
    "HNO₂ has pK_a = 3.4. Is it stronger or weaker than acetic acid (pK_a 4.7)?",
    "HNO₂ stronger (lower pK_a).",
    [
      { q: "pK_a?", a: "−log K_a" },
      { q: "Lower pK_a means?", a: "Stronger acid." },
      { q: "pK_a + pK_b?", a: "14 (conjugate pair, at 25°C)" },
      { q: "Strong acid pK_a?", a: "< 0" },
      { q: "Weak acid pK_a range?", a: "Roughly 2-14." },
    ],
  ),
  mk(8, "8.8", "Properties of Buffers",
    "Buffer capacity: amount of acid/base buffer can absorb. Best when [HA] ≈ [A⁻].",
    [
      "Buffer capacity ∝ [HA] + [A⁻].",
      "Best buffering when [HA] ≈ [A⁻] (pH near pK_a).",
      "Useful range: pK_a ± 1.",
      "Overwhelmed beyond capacity.",
    ],
    "0.1 M HA / 0.1 M A⁻ has what buffering range?",
    "pK_a ± 1 (pH range of ~2 units around pK_a).",
    [
      { q: "Buffer capacity?", a: "Amount of acid/base absorbed without major pH change." },
      { q: "Best buffer pH?", a: "pK_a" },
      { q: "Useful range?", a: "pK_a ± 1" },
      { q: "More concentrated buffer?", a: "Higher capacity." },
      { q: "Buffer fails when?", a: "Added acid/base > capacity." },
    ],
  ),
  mk(8, "8.9", "Henderson-Hasselbalch Equation",
    "pH = pK_a + log([A⁻]/[HA]). Directly computes buffer pH.",
    [
      "pH = pK_a + log([A⁻]/[HA]).",
      "At [A⁻] = [HA]: pH = pK_a.",
      "10× ratio shift: 1 pH unit.",
      "Valid when approximations hold (not at extremes).",
    ],
    "pK_a = 4.7, [A⁻] = 0.2, [HA] = 0.1. pH?",
    "pH = 4.7 + log(0.2/0.1) = 4.7 + log(2) = 4.7 + 0.30 = 5.0.",
    [
      { q: "H-H formula?", a: "pH = pK_a + log([A⁻]/[HA])" },
      { q: "[A⁻] = [HA] pH?", a: "pK_a" },
      { q: "Ratio 10:1 shifts pH?", a: "+1 unit" },
      { q: "Valid when?", a: "Both [HA] and [A⁻] not too small/large." },
      { q: "Use for?", a: "Buffer prep, titration at buffer region." },
    ],
  ),
  mk(8, "8.10", "Buffer Capacity",
    "Capacity depends on total [HA] + [A⁻] and ratio.",
    [
      "Capacity ∝ total concentration.",
      "Maximum when [HA] = [A⁻].",
      "Near extremes (ratio far from 1): capacity falls.",
      "Overwhelmed if added acid/base exceeds capacity.",
    ],
    "Which has higher capacity: 0.01 M or 0.1 M buffer (same pH)?",
    "0.1 M — more total buffer = more capacity.",
    [
      { q: "Buffer capacity ∝?", a: "Total concentration of buffer pair." },
      { q: "Max capacity ratio?", a: "1:1" },
      { q: "Dilute buffer?", a: "Lower capacity." },
      { q: "Useful buffer range?", a: "pK_a ± 1 (ratio 1/10 to 10)" },
      { q: "Overwhelmed buffer?", a: "pH changes sharply." },
    ],
  ),
  mk(9, "9.1", "Introduction to Entropy",
    "Entropy S = measure of disorder / dispersal of energy.",
    [
      "Higher S: more microstates, more disorder.",
      "Gas > liquid > solid (S trend).",
      "ΔS > 0: increase in disorder.",
      "At 0 K, perfect crystal S = 0 (third law).",
    ],
    "Predict ΔS for H₂O(l) → H₂O(g).",
    "ΔS > 0 — gas has more disorder than liquid.",
    [
      { q: "Entropy symbol?", a: "S" },
      { q: "Gas vs liquid vs solid S?", a: "Gas > liquid > solid" },
      { q: "ΔS > 0?", a: "Increase in disorder." },
      { q: "Third law of thermodynamics?", a: "S = 0 for perfect crystal at 0 K." },
      { q: "Units of S?", a: "J/(mol·K)" },
    ],
  ),
  mk(9, "9.2", "Absolute Entropy and Entropy Change",
    "S° tabulated. ΔS_rxn = ΣS°(products) − ΣS°(reactants).",
    [
      "S° (standard molar entropy) at 25°C, 1 atm.",
      "ΔS_rxn° = ΣnS°(prod) − ΣnS°(react).",
      "Larger molecules, gases → higher S.",
      "Units: J/(mol·K).",
    ],
    "ΔS for 2H₂O(l) → 2H₂(g) + O₂(g) qualitatively?",
    "ΔS > 0 — more moles of gas produced.",
    [
      { q: "ΔS_rxn formula?", a: "Σ n S°(prod) − Σ n S°(react)" },
      { q: "More moles gas products?", a: "ΔS > 0" },
      { q: "S° for solid vs gas?", a: "Gas higher." },
      { q: "Complex molecule S?", a: "Higher than simple." },
      { q: "Units?", a: "J/(mol·K)" },
    ],
  ),
  mk(9, "9.3", "Gibbs Free Energy and Thermodynamic Favorability",
    "ΔG = ΔH − TΔS. ΔG < 0 → spontaneous.",
    [
      "ΔG < 0: spontaneous (thermodynamically favorable).",
      "ΔG > 0: nonspontaneous.",
      "ΔG = 0: equilibrium.",
      "Depends on T.",
    ],
    "ΔH = +50, ΔS = +0.1 kJ/(mol·K). At what T is ΔG = 0?",
    "ΔG = 50 − T(0.1) = 0 → T = 500 K.",
    [
      { q: "ΔG formula?", a: "ΔH − TΔS" },
      { q: "ΔG < 0?", a: "Spontaneous (favorable)." },
      { q: "ΔG = 0?", a: "Equilibrium." },
      { q: "ΔH<0, ΔS>0?", a: "Spontaneous at all T." },
      { q: "ΔH>0, ΔS<0?", a: "Nonspontaneous at all T." },
    ],
  ),
  mk(9, "9.4", "Thermodynamic and Kinetic Control",
    "Some reactions are thermodynamically favored but kinetically slow.",
    [
      "Thermodynamic: ΔG governs spontaneity.",
      "Kinetic: Ea governs speed.",
      "Slow thermo-favorable: diamond → graphite.",
      "Fast kinetic but thermodynamically unfavored: burning non-stoichiometric mixtures.",
    ],
    "Why is diamond stable at room T even though graphite is more stable?",
    "ΔG favors graphite but activation energy for the conversion is extremely high — kinetic barrier.",
    [
      { q: "Thermodynamic control?", a: "ΔG determines reaction direction." },
      { q: "Kinetic control?", a: "Reaction path with lowest Ea, even if not lowest ΔG." },
      { q: "Diamond/graphite?", a: "Graphite thermodynamically preferred; diamond kinetically stable." },
      { q: "Unfavorable ΔG?", a: "Nonspontaneous." },
      { q: "Fast but not spontaneous?", a: "Possible — catalyst helps reach eq but doesn't change eq." },
    ],
  ),
  mk(9, "9.5", "Free Energy and Equilibrium",
    "ΔG° = −RT ln K. Ties free energy to equilibrium constant.",
    [
      "ΔG° = −RT ln K.",
      "ΔG° < 0 → K > 1 (products favored).",
      "ΔG° > 0 → K < 1 (reactants favored).",
      "ΔG = ΔG° + RT ln Q under non-standard conditions.",
    ],
    "ΔG° = −10 kJ/mol at 298 K. K?",
    "K = exp(−ΔG°/RT) = exp(10,000/(8.314·298)) ≈ 55.",
    [
      { q: "ΔG° K relation?", a: "ΔG° = −RT ln K" },
      { q: "ΔG° < 0 means?", a: "K > 1" },
      { q: "K at ΔG° = 0?", a: "K = 1" },
      { q: "ΔG = ?", a: "ΔG° + RT ln Q" },
      { q: "At equilibrium?", a: "ΔG = 0; Q = K" },
    ],
  ),
  mk(9, "9.6", "Coupled Reactions",
    "Nonspontaneous reaction driven by coupling with spontaneous. Essential in biology (ATP).",
    [
      "Add ΔG's for coupled reactions.",
      "Biology: ATP hydrolysis drives endergonic reactions.",
      "Net reaction spontaneous if total ΔG < 0.",
      "Example: glucose + Pi → glucose-6-P (ΔG>0) coupled to ATP hydrolysis (ΔG<<0).",
    ],
    "How does ATP hydrolysis drive biosynthesis?",
    "ATP → ADP + Pi is very exergonic; pairing it with endergonic synthesis makes overall ΔG < 0.",
    [
      { q: "Coupled reactions add?", a: "ΔG's." },
      { q: "Spontaneous overall?", a: "Sum ΔG < 0." },
      { q: "ATP hydrolysis ΔG?", a: "~−30 kJ/mol (very exergonic)." },
      { q: "Biology example?", a: "ATP drives sugar phosphorylation." },
      { q: "Hess's law role?", a: "Allows summing ΔG across steps." },
    ],
  ),
  mk(9, "9.7", "Galvanic (Voltaic) and Electrolytic Cells",
    "Galvanic: spontaneous redox → electricity. Electrolytic: electricity → nonspontaneous reaction.",
    [
      "Galvanic: spontaneous; makes electricity. E_cell > 0.",
      "Electrolytic: nonspontaneous; uses electricity.",
      "Anode: oxidation (negative in galvanic, + in electrolytic).",
      "Cathode: reduction.",
      "Salt bridge maintains neutrality in galvanic.",
    ],
    "Zn/Cu galvanic cell. Which is anode?",
    "Zn — higher oxidation tendency, oxidized: Zn → Zn²⁺ + 2e⁻.",
    [
      { q: "Galvanic cell?", a: "Spontaneous redox → electricity." },
      { q: "Electrolytic cell?", a: "Electricity → nonspontaneous reaction." },
      { q: "Anode?", a: "Oxidation site." },
      { q: "Cathode?", a: "Reduction site." },
      { q: "Salt bridge?", a: "Completes circuit; balances charge." },
    ],
  ),
  mk(9, "9.8", "Cell Potential and Free Energy",
    "ΔG = −nFE. Larger E, more negative ΔG.",
    [
      "ΔG° = −nFE°_cell.",
      "n = moles e⁻ transferred.",
      "F = 96,485 C/mol.",
      "E° > 0 → spontaneous (galvanic).",
    ],
    "n=2, E°=1.10 V. ΔG°?",
    "ΔG° = −nFE° = −(2)(96,485)(1.10) ≈ −212,000 J/mol = −212 kJ/mol.",
    [
      { q: "ΔG° and E° relation?", a: "ΔG° = −nFE°" },
      { q: "E° > 0 means?", a: "Spontaneous (galvanic)." },
      { q: "F?", a: "Faraday constant = 96,485 C/mol" },
      { q: "n?", a: "Moles electrons transferred (balance redox)." },
      { q: "E° < 0?", a: "Nonspontaneous; electrolytic." },
    ],
  ),
  mk(9, "9.9", "Cell Potential Under Nonstandard Conditions",
    "Nernst: E = E° − (RT/nF) ln Q. At 25°C: E = E° − (0.0592/n) log Q.",
    [
      "Nernst equation for non-standard conditions.",
      "E = E° − (0.0592/n) log Q at 25°C.",
      "Q changes during reaction → E decreases toward 0.",
      "At equilibrium: E = 0, Q = K.",
    ],
    "E° = 1.10 V, n = 2, Q = 100. E at 25°C?",
    "E = 1.10 − (0.0592/2) log(100) = 1.10 − (0.0296)(2) = 1.10 − 0.0592 = 1.04 V.",
    [
      { q: "Nernst (25°C)?", a: "E = E° − (0.0592/n) log Q" },
      { q: "At equilibrium?", a: "E = 0, Q = K" },
      { q: "E vs E°?", a: "E non-standard, E° at standard." },
      { q: "Q increases, E?", a: "Decreases." },
      { q: "Q decreases, E?", a: "Increases." },
    ],
  ),
  mk(9, "9.10", "Electrolysis and Faraday's Law",
    "Charge Q = It; moles e⁻ = Q/F. Mass deposited via stoichiometry.",
    [
      "Electrolysis: force nonspontaneous reaction.",
      "Q (charge) = I (current) × t (time).",
      "Moles e⁻ = Q / F = It/F.",
      "Mass = (moles e⁻ / n) × molar mass.",
    ],
    "Electrolyze CuSO₄ at 2.0 A for 30 min. Mass Cu deposited?",
    "Q = 2(1800) = 3600 C. mol e⁻ = 3600/96,485 = 0.0373. n=2 for Cu²⁺. mol Cu = 0.01867. Mass = 0.01867(63.5) = 1.19 g.",
    [
      { q: "Charge Q?", a: "I × t" },
      { q: "Moles e⁻?", a: "Q / F" },
      { q: "F?", a: "96,485 C/mol" },
      { q: "Mass deposited?", a: "(mol e⁻ / n) × M" },
      { q: "Electrolysis purpose?", a: "Drive nonspontaneous redox (plating, purification)." },
    ],
  ),
];
