import type { Lesson } from "@/lib/topics";

/** AP Environmental Science — one Lesson per CED topic across all 9 units (80 topics). */

const KA = "https://www.khanacademy.org/science/ap-environmental-science";

const U = {
  1: "The Living World: Ecosystems",
  2: "The Living World: Biodiversity",
  3: "Populations",
  4: "Earth Systems and Resources",
  5: "Land and Water Use",
  6: "Energy Resources and Consumption",
  7: "Atmospheric Pollution",
  8: "Aquatic and Terrestrial Pollution",
  9: "Global Change",
};

const mk = (
  unit: keyof typeof U,
  id: string,
  title: string,
  blurb: string,
  keyIdeas: string[],
  sampleProblem: string,
  sampleWalkthrough: string,
  flashcards: { q: string; a: string }[]
): Lesson => ({
  slug: `apes-${id.replace(".", "-")}`,
  title,
  courses: [{ courseSlug: "ap-environmental", unitNumber: unit, unitTitle: U[unit] }],
  blurb,
  keyIdeas,
  sampleProblem,
  sampleWalkthrough,
  flashcards,
  links: [{ title: "AP Environmental", url: KA, source: "Khan Academy" }],
});

export const AP_ENVIRONMENTAL_LESSONS: Lesson[] = [
  mk(1, "1.1", "Introduction to Ecosystems",
    "Ecosystem = biotic + abiotic. Living and nonliving parts interact.",
    ["Biotic: living (plants, animals, microbes).", "Abiotic: nonliving (water, soil, light, temp).", "Ecosystem: biotic + abiotic interacting.", "Biosphere: all life on Earth."],
    "Is sunlight biotic or abiotic?",
    "Abiotic — nonliving but essential to the ecosystem's primary productivity.",
    [{q:"Biotic?",a:"Living components."},{q:"Abiotic?",a:"Nonliving (sunlight, water, temp)."},{q:"Ecosystem?",a:"Biotic + abiotic interactions."},{q:"Biosphere?",a:"All living things on Earth."},{q:"Community vs ecosystem?",a:"Community = all organisms; ecosystem adds abiotic."}],
  ),
  mk(1, "1.2", "Terrestrial Biomes",
    "Biomes determined by temperature and precipitation.",
    ["Tundra: cold, dry, permafrost.", "Taiga: coniferous forest, cold winters.", "Temperate deciduous: 4 seasons.", "Tropical rainforest: warm, wet, most biodiverse.", "Desert: <25 cm rain; grassland: moderate precip."],
    "Which biome has the highest biodiversity?",
    "Tropical rainforest — warm temp + high precipitation support enormous species richness.",
    [{q:"Climate drivers of biome?",a:"Temperature + precipitation."},{q:"Tundra feature?",a:"Permafrost."},{q:"Tropical rainforest biodiversity?",a:"Highest on Earth."},{q:"Desert precipitation?",a:"<25 cm/year."},{q:"Taiga = ?",a:"Boreal coniferous forest."}],
  ),
  mk(1, "1.3", "Aquatic Biomes",
    "Freshwater (lake, river, wetland) and marine (ocean, estuary, coral reef).",
    ["Freshwater: <1% salt.", "Estuaries: mix fresh + salt; highly productive.", "Coral reefs: warm, shallow, biodiverse.", "Open ocean zones: photic vs aphotic."],
    "Why are estuaries so productive?",
    "Nutrient-rich mixing of fresh and salt water supports abundant life; transition habitat for many species.",
    [{q:"Estuary?",a:"Where fresh meets salt water."},{q:"Coral reef needs?",a:"Warm, shallow, clear water."},{q:"Photic zone?",a:"Sunlight penetrates for photosynthesis."},{q:"Freshwater salinity?",a:"<1%."},{q:"Wetland function?",a:"Flood control, water filtration, biodiversity."}],
  ),
  mk(1, "1.4", "The Carbon Cycle",
    "Reservoirs: atmosphere, oceans, biomass, sediments. Moves by photosynthesis, respiration, combustion.",
    ["Photosynthesis: CO₂ → biomass.", "Respiration + decomposition: biomass → CO₂.", "Fossil fuel combustion: ancient C → atmosphere.", "Oceans absorb CO₂ (→ acidification)."],
    "Human activity that most disrupts carbon cycle?",
    "Burning fossil fuels — releases long-buried carbon fast, increasing atmospheric CO₂.",
    [{q:"Largest carbon reservoir?",a:"Sedimentary rocks (long-term); oceans (active)."},{q:"Photosynthesis moves C?",a:"From atmosphere to biomass."},{q:"Respiration?",a:"From biomass back to atmosphere."},{q:"Fossil fuel combustion?",a:"Adds ancient C to atmosphere."},{q:"Ocean uptake consequence?",a:"Acidification."}],
  ),
  mk(1, "1.5", "The Nitrogen Cycle",
    "N₂ → NH₃/NO₃⁻ via fixation; denitrification returns N₂.",
    ["Fixation: N₂ → NH₃ (bacteria, lightning).", "Nitrification: NH₃ → NO₂⁻ → NO₃⁻.", "Assimilation by plants.", "Ammonification and denitrification release N."],
    "Why do plants need N-fixing bacteria?",
    "Atmospheric N₂ is unusable; bacteria convert it to NH₃, which plants take up for proteins and nucleic acids.",
    [{q:"Nitrogen fixation?",a:"N₂ → NH₃ (bacteria or lightning)."},{q:"Nitrification?",a:"NH₃ → NO₃⁻"},{q:"Denitrification?",a:"NO₃⁻ → N₂ (back to atmosphere)."},{q:"Eutrophication cause?",a:"Excess N (and P) fertilizer runoff."},{q:"Assimilation?",a:"Plants take up N."}],
  ),
  mk(1, "1.6", "The Phosphorus Cycle",
    "No atmospheric phase. Weathering from rocks → soil/water → organisms.",
    ["No gaseous phase.", "Slowly cycles from rocks through weathering.", "Often limiting nutrient in freshwater.", "Excess P causes eutrophication."],
    "Why does P cycle more slowly than C or N?",
    "No atmospheric pool — P moves only through rocks, water, and organisms; weathering is slow.",
    [{q:"Gaseous P?",a:"No — phosphorus has no atmospheric phase."},{q:"P source?",a:"Weathering of rocks."},{q:"P in biology?",a:"ATP, DNA, membranes."},{q:"P often limiting in?",a:"Freshwater systems."},{q:"Excess P effect?",a:"Eutrophication (algal blooms)."}],
  ),
  mk(1, "1.7", "The Hydrologic (Water) Cycle",
    "Evaporation, condensation, precipitation, runoff, infiltration.",
    ["Evaporation → clouds → precipitation.", "Runoff returns to oceans/rivers.", "Groundwater recharge via infiltration.", "Most fresh water locked in ice."],
    "Where is most of Earth's fresh water?",
    "Glaciers and polar ice caps (~69% of freshwater); only ~1% is accessible surface water.",
    [{q:"Evaporation?",a:"Liquid → vapor."},{q:"Transpiration?",a:"Plant release of water vapor."},{q:"Runoff?",a:"Surface flow to water bodies."},{q:"Infiltration?",a:"Water enters groundwater."},{q:"Freshwater % of all water?",a:"~2.5%"}],
  ),
  mk(1, "1.8", "Primary Productivity",
    "Rate at which producers capture energy. GPP vs NPP.",
    ["GPP: total energy fixed.", "NPP = GPP − respiration; what's available to consumers.", "Higher in warm/wet areas.", "Measure: g biomass/m²/year."],
    "Which ecosystem has highest NPP per area?",
    "Tropical rainforests and estuaries — warm, wet, high biodiversity.",
    [{q:"GPP?",a:"Gross Primary Productivity (total energy fixed)."},{q:"NPP?",a:"Net Primary Productivity = GPP − respiration."},{q:"Highest NPP biome?",a:"Tropical rainforest."},{q:"NPP units?",a:"g/m²/year (biomass)."},{q:"Why matters?",a:"Sets energy available to entire food web."}],
  ),
  mk(1, "1.9", "Trophic Levels",
    "Producers → primary consumers → secondary → tertiary → decomposers.",
    ["Trophic level 1: producers (autotrophs).", "2: herbivores.", "3: carnivores.", "Decomposers: bacteria, fungi."],
    "What trophic level are humans eating salad?",
    "Primary consumer (level 2) — eating plants.",
    [{q:"Producer?",a:"Autotroph (plants, algae, cyanobacteria)."},{q:"Primary consumer?",a:"Herbivore (eats producers)."},{q:"Secondary consumer?",a:"Carnivore eating herbivores."},{q:"Tertiary consumer?",a:"Top predator."},{q:"Decomposer?",a:"Breaks down dead matter (fungi, bacteria)."}],
  ),
  mk(1, "1.10", "Energy Flow and the 10% Rule",
    "~10% of energy transfers per trophic level. Most lost as heat.",
    ["~10% transfers up each trophic level.", "Rest lost as metabolic heat.", "Limits food chain length (~4-5 levels).", "Energy pyramid always narrows upward."],
    "If producers have 10,000 kcal, how much reaches tertiary?",
    "10,000 × 0.1 × 0.1 × 0.1 = 10 kcal.",
    [{q:"10% rule?",a:"~10% energy transfers per trophic level."},{q:"Why limited chain length?",a:"Insufficient energy for additional levels."},{q:"Energy lost as?",a:"Metabolic heat."},{q:"Top predator energy?",a:"Very little reaches them."},{q:"Energy pyramid shape?",a:"Narrows toward top."}],
  ),
  mk(1, "1.11", "Food Chains and Food Webs",
    "Food chain: linear. Food web: interconnected chains.",
    ["Food chain: simple linear sequence.", "Food web: realistic, interconnected.", "Most organisms occupy multiple roles.", "Keystone species disproportionately affect web."],
    "Why is a food web more realistic than a food chain?",
    "Organisms eat and are eaten by multiple species; web captures the actual complexity.",
    [{q:"Food chain vs web?",a:"Chain linear, web interconnected."},{q:"Keystone species?",a:"Disproportionately large impact on web."},{q:"Top predator?",a:"Apex of food web."},{q:"Omnivore?",a:"Eats producers AND consumers."},{q:"Removing keystone?",a:"Web collapses."}],
  ),
  mk(2, "2.1", "Introduction to Biodiversity",
    "Biodiversity: genetic, species, ecosystem. Higher → more resilience.",
    ["Genetic: allele variation within species.", "Species: variety of species.", "Ecosystem: variety of habitats.", "Higher biodiversity = more resilient."],
    "Why is genetic diversity important?",
    "More alleles = better ability to adapt to disease, climate change, other stressors.",
    [{q:"Three levels of biodiversity?",a:"Genetic, species, ecosystem."},{q:"Most biodiverse biome?",a:"Tropical rainforest."},{q:"Why matter?",a:"Resilience, ecosystem services, ethics."},{q:"Threats?",a:"Habitat loss, climate, invasives, pollution."},{q:"Measures?",a:"Richness + evenness."}],
  ),
  mk(2, "2.2", "Ecosystem Services",
    "Nature's free services: provisioning, regulating, cultural, supporting.",
    ["Provisioning: food, water, timber.", "Regulating: climate, water filtration, pollination.", "Cultural: recreation, aesthetics.", "Supporting: nutrient cycling, soil formation."],
    "Bees pollinate crops. Which service?",
    "Regulating — pollination is a supporting/regulating service.",
    [{q:"Provisioning?",a:"Material goods (food, timber, water)."},{q:"Regulating?",a:"Pollination, water filtration, climate."},{q:"Cultural?",a:"Recreation, spiritual."},{q:"Supporting?",a:"Soil, nutrient cycling."},{q:"Economic value?",a:"Trillions $/year globally."}],
  ),
  mk(2, "2.3", "Island Biogeography",
    "Island species counts: balance of immigration vs. extinction. Bigger, closer islands have more.",
    ["Immigration rate ↓ as species accumulate.", "Extinction rate ↑ with more species.", "Balance gives equilibrium species number.", "Larger islands: more species (more habitat).", "Closer islands: higher immigration → more species."],
    "Compare: large vs small island of same distance.",
    "Large has more species (lower extinction, more habitat).",
    [{q:"Immigration rate trend?",a:"Decreases as species accumulate."},{q:"Extinction rate trend?",a:"Increases with more species."},{q:"Larger island?",a:"More species (lower extinction)."},{q:"Closer island?",a:"More species (higher immigration)."},{q:"Application?",a:"Protected area design."}],
  ),
  mk(2, "2.4", "Ecological Tolerance",
    "Species have optimum ranges for abiotic factors; limits define zones of stress/intolerance.",
    ["Range of tolerance: conditions species can survive.", "Optimum zone: thrives.", "Zone of stress: survives but poorly.", "Zone of intolerance: can't survive."],
    "Why do polar bears struggle in warm climates?",
    "Their tolerance for temperature peaks at cold conditions — warm is zone of stress or intolerance.",
    [{q:"Range of tolerance?",a:"Environmental conditions species can survive in."},{q:"Optimum zone?",a:"Where species thrives."},{q:"Stress zone?",a:"Survives but struggles."},{q:"Intolerance zone?",a:"Cannot survive."},{q:"Limiting factor?",a:"One that constrains population most."}],
  ),
  mk(2, "2.5", "Natural Disruptions to Ecosystems",
    "Fires, storms, floods, volcanoes, droughts shape ecosystems.",
    ["Periodic fires maintain grasslands.", "Volcanic eruptions devastate but enrich soil.", "Droughts/floods shift species composition.", "Most ecosystems adapted to some disruption."],
    "Why do some ecosystems benefit from fire?",
    "Periodic fire clears accumulated fuel, recycles nutrients, and promotes fire-adapted species.",
    [{q:"Fire-adapted ecosystems?",a:"Grasslands, chaparral, pine forests."},{q:"Volcanic benefit?",a:"Rich mineral soil eventually."},{q:"Disturbance regime?",a:"Typical frequency/intensity of disruptions."},{q:"Intermediate disturbance hypothesis?",a:"Moderate disturbance maximizes diversity."},{q:"Examples of disruptions?",a:"Fire, flood, storm, disease."}],
  ),
  mk(2, "2.6", "Adaptations",
    "Natural selection produces structural, physiological, and behavioral adaptations.",
    ["Structural: body form (camouflage, armor).", "Physiological: internal processes (hibernation, salt glands).", "Behavioral: actions (migration, courtship).", "Result of evolution over generations."],
    "Is penguin huddling an adaptation?",
    "Yes — behavioral adaptation for warmth in cold environments.",
    [{q:"Adaptation?",a:"Trait improving survival/reproduction."},{q:"Structural example?",a:"Cactus spines."},{q:"Physiological example?",a:"Hibernation."},{q:"Behavioral example?",a:"Bird migration."},{q:"Mechanism?",a:"Natural selection over generations."}],
  ),
  mk(2, "2.7", "Ecological Succession",
    "Primary: bare rock → community. Secondary: disturbed → recovered. Pioneer → climax.",
    ["Primary: starts from bare rock (no soil).", "Secondary: after disturbance, soil remains.", "Pioneer species colonize first.", "Climax community stable endpoint (in theory)."],
    "After a wildfire, is the recovery primary or secondary succession?",
    "Secondary — soil is intact, so vegetation returns faster than primary succession.",
    [{q:"Primary succession?",a:"Starts from bare rock (no soil)."},{q:"Secondary succession?",a:"After disturbance (soil intact)."},{q:"Pioneer species?",a:"First colonizers (lichen, moss)."},{q:"Climax community?",a:"Stable final (theoretical) community."},{q:"Example of primary?",a:"After glacier retreat."}],
  ),
  mk(3, "3.1", "Generalist and Specialist Species",
    "Generalist: flexible niche; specialist: narrow niche. Specialists more extinction-prone.",
    ["Generalist: varied diet, habitat.", "Specialist: specific requirements.", "Generalists more resilient to change.", "Specialists more vulnerable to extinction."],
    "Panda is a generalist or specialist?",
    "Specialist — eats almost exclusively bamboo; highly vulnerable to bamboo decline.",
    [{q:"Generalist?",a:"Flexible niche, varied diet/habitat."},{q:"Specialist?",a:"Narrow niche, specific requirements."},{q:"Panda, koala?",a:"Specialists."},{q:"Raccoon, coyote?",a:"Generalists."},{q:"Extinction risk?",a:"Specialists higher."}],
  ),
  mk(3, "3.2", "K-Selected and r-Selected Species",
    "K: few offspring, high care. r: many offspring, little care.",
    ["K-selected: stable environments, few large offspring, parental care.", "r-selected: variable environments, many small offspring.", "K: large mammals. r: insects, weeds.", "Tradeoff between quantity and quality."],
    "Humans — K or r selected?",
    "K — few offspring, high parental care, long gestation.",
    [{q:"K-selected?",a:"Few offspring, high care (large mammals)."},{q:"r-selected?",a:"Many offspring, little care (insects)."},{q:"Humans?",a:"K-selected."},{q:"Mosquitoes?",a:"r-selected."},{q:"Tradeoff?",a:"Quality vs quantity."}],
  ),
  mk(3, "3.3", "Survivorship Curves",
    "Type I: high early survival (humans). II: constant (birds). III: high early death (insects).",
    ["Type I: K-selected; dropoff late.", "Type II: constant mortality.", "Type III: r-selected; most die young.", "Reflects life history strategy."],
    "Which curve fits sea turtles?",
    "Type III — lay many eggs, very few hatchlings survive to adulthood.",
    [{q:"Type I curve?",a:"Most die in old age (humans)."},{q:"Type II?",a:"Constant mortality (many birds)."},{q:"Type III?",a:"Most die young (insects, fish)."},{q:"K-selected curve?",a:"Type I typically."},{q:"r-selected curve?",a:"Type III typically."}],
  ),
  mk(3, "3.4", "Carrying Capacity",
    "K = maximum sustainable population. Resource-limited.",
    ["Determined by resource availability.", "Logistic growth levels at K.", "Overshoot can degrade K.", "Varies by environment over time."],
    "What happens when population exceeds K?",
    "Overshoot → resource depletion → population crash, possibly lowering K permanently.",
    [{q:"Carrying capacity (K)?",a:"Max sustainable population."},{q:"Set by?",a:"Resource availability."},{q:"Overshoot?",a:"Population > K temporarily."},{q:"Consequence of overshoot?",a:"Resource depletion, crash, maybe lower K."},{q:"Does K change?",a:"Yes — with environment and resource availability."}],
  ),
  mk(3, "3.5", "Population Growth and Resource Availability",
    "Exponential → logistic as resources run out. Rule of 70 estimates doubling time.",
    ["Exponential: unlimited resources (rare).", "Logistic: approaches K.", "Doubling time ≈ 70/(% growth rate).", "Human population currently slowing."],
    "Population growing at 2%/year. Doubling time?",
    "70/2 = 35 years.",
    [{q:"Exponential growth?",a:"J-shaped; unlimited resources."},{q:"Logistic growth?",a:"S-shaped; resources limit."},{q:"Rule of 70?",a:"Doubling time ≈ 70/% growth rate."},{q:"Human growth rate?",a:"~1% (and slowing)."},{q:"When does logistic level?",a:"At K (carrying capacity)."}],
  ),
  mk(3, "3.6", "Age Structure Diagrams",
    "Show population age/sex distribution; predict future growth.",
    ["Wide base: young → fast growth.", "Even: stable population.", "Narrow base: aging/declining.", "Dependency ratio: young+old vs working-age."],
    "Pyramid with wide base indicates what future?",
    "Rapid population growth — many young people entering reproductive years.",
    [{q:"Wide base diagram?",a:"Fast-growing population."},{q:"Rectangular shape?",a:"Stable population."},{q:"Inverted (narrow bottom)?",a:"Declining population (e.g., Japan)."},{q:"Dependency ratio?",a:"Young + old / working age."},{q:"Used for?",a:"Predicting population dynamics."}],
  ),
  mk(3, "3.7", "Total Fertility Rate",
    "TFR = avg children per woman. Replacement ~2.1.",
    ["TFR > 2.1: population growing.", "TFR < 2.1: population shrinking (ignoring migration).", "Replacement = 2.1 (2 parents + slight mortality margin).", "Varies with education, wealth, culture."],
    "TFR = 1.5. Population grows or declines?",
    "Declines (below replacement rate of 2.1).",
    [{q:"TFR?",a:"Avg # children per woman."},{q:"Replacement TFR?",a:"~2.1"},{q:"TFR > 2.1?",a:"Population grows."},{q:"TFR < 2.1?",a:"Population shrinks."},{q:"Factors lowering TFR?",a:"Education, wealth, access to contraception."}],
  ),
  mk(3, "3.8", "Human Population Dynamics",
    "Population 8B; growth slowing; distribution uneven.",
    ["Global pop ~8 billion (2023).", "Growth slowing — peak ~10 billion by 2080.", "Highest growth: sub-Saharan Africa.", "Aging populations: Japan, Europe, China."],
    "Where is human population growing fastest today?",
    "Sub-Saharan Africa — high TFR plus improving health care lowering child mortality.",
    [{q:"Current human population?",a:"~8 billion (2023)."},{q:"Peak expected?",a:"~10 billion around 2080."},{q:"Fastest-growing region?",a:"Sub-Saharan Africa."},{q:"Aging countries?",a:"Japan, Italy, South Korea."},{q:"Demographic drag?",a:"Too few working-age to support elderly."}],
  ),
  mk(3, "3.9", "Demographic Transition",
    "4 stages: pre-industrial → transitional → industrial → post-industrial.",
    ["Stage 1: high birth/death (pre-industrial).", "Stage 2: death drops (transitional → population explodes).", "Stage 3: birth drops (industrial).", "Stage 4: low birth/death (post-industrial; stable or shrinking)."],
    "Why does population explode in stage 2?",
    "Death rate drops (medicine, sanitation) before birth rate adjusts — leads to rapid natural increase.",
    [{q:"Demographic transition model stages?",a:"4: pre-industrial, transitional, industrial, post-industrial."},{q:"Stage 2 features?",a:"High birth, falling death → explosion."},{q:"Stage 4?",a:"Low birth AND death; stable."},{q:"When did West pass through?",a:"19th-20th centuries."},{q:"Trigger for transition?",a:"Industrialization, public health."}],
  ),
  mk(4, "4.1", "Plate Tectonics",
    "Lithosphere plates move on asthenosphere. Convergent, divergent, transform boundaries.",
    ["Plates driven by mantle convection.", "Convergent: subduction (ocean-continent) or mountains (continent-continent).", "Divergent: mid-ocean ridges, rift valleys.", "Transform: lateral sliding (San Andreas).", "Earthquakes, volcanoes at boundaries."],
    "Why are the Andes tall?",
    "Convergent oceanic-continental boundary: Nazca plate subducts under South American plate, creating volcanic mountain range.",
    [{q:"Convergent boundary?",a:"Plates collide; subduction or mountain building."},{q:"Divergent boundary?",a:"Plates separate; mid-ocean ridge or rift valley."},{q:"Transform boundary?",a:"Plates slide laterally."},{q:"Hotspot example?",a:"Hawaii (not on plate boundary)."},{q:"Where most earthquakes?",a:"Plate boundaries (Ring of Fire)."}],
  ),
  mk(4, "4.2", "Soil Formation and Erosion",
    "Soil forms from weathered rock + organic matter. Erosion removes topsoil.",
    ["Horizons: O (organic), A (topsoil), B (subsoil), C (weathered rock).", "Forms slowly; erodes quickly.", "Erosion accelerated by farming, deforestation.", "Dust Bowl (1930s): classic soil erosion disaster."],
    "Which soil horizon is most fertile?",
    "A horizon (topsoil) — rich in organic matter, where most plant roots live.",
    [{q:"Soil horizons?",a:"O, A, B, C"},{q:"Most fertile horizon?",a:"A (topsoil)"},{q:"Parent material?",a:"C horizon (weathered rock)."},{q:"Soil formation rate?",a:"Very slow (cm/century)."},{q:"Dust Bowl cause?",a:"Over-farming + drought → massive erosion."}],
  ),
  mk(4, "4.3", "Soil Composition and Properties",
    "Texture: sand, silt, clay. Affects water retention and drainage.",
    ["Sand: large particles, drains fast.", "Silt: medium.", "Clay: fine, holds water and nutrients.", "Loam: ideal mix.", "pH, nutrients, organic matter also matter."],
    "Which soil type drains fastest?",
    "Sandy soil — large particles allow water to pass through quickly.",
    [{q:"Soil textures?",a:"Sand, silt, clay."},{q:"Best for most crops?",a:"Loam (balanced)."},{q:"Clay property?",a:"Holds water and nutrients, poor drainage."},{q:"Sand property?",a:"Drains fast, low nutrients."},{q:"Soil pH measures?",a:"Acidity/alkalinity."}],
  ),
  mk(4, "4.4", "Earth's Atmosphere",
    "Layers: troposphere (weather), stratosphere (ozone), mesosphere, thermosphere.",
    ["Troposphere: 0-12 km; weather.", "Stratosphere: 12-50 km; ozone layer.", "Mesosphere: 50-80 km.", "Thermosphere: 80+ km; auroras."],
    "Where does weather occur?",
    "Troposphere — the lowest layer, where most air, water vapor, and weather exist.",
    [{q:"Troposphere?",a:"Lowest layer; weather."},{q:"Stratosphere?",a:"Ozone layer; planes fly here."},{q:"Ozone layer protects?",a:"From UV radiation."},{q:"Mesosphere?",a:"Meteors burn up."},{q:"Thermosphere?",a:"Auroras; ISS orbits."}],
  ),
  mk(4, "4.5", "Global Wind Patterns",
    "Hadley, Ferrel, polar cells. Coriolis effect curves winds.",
    ["Unequal heating → wind.", "Hadley cells: 0-30° lat; trade winds.", "Ferrel: 30-60°; westerlies.", "Polar: 60-90°; polar easterlies.", "Coriolis: curves winds right (N hemisphere)."],
    "Why are trade winds in the tropics called 'easterlies'?",
    "Air moves from equator at 30°N, curving right due to Coriolis — blowing from east.",
    [{q:"Three atmospheric cells?",a:"Hadley, Ferrel, Polar."},{q:"Coriolis effect?",a:"Curves winds (right in N hem, left in S)."},{q:"Deserts at?",a:"~30° lat (Hadley cell descending air)."},{q:"Prevailing winds at US?",a:"Westerlies."},{q:"Jet stream?",a:"High-altitude westerly wind (Ferrel-Polar boundary)."}],
  ),
  mk(4, "4.6", "Watersheds",
    "Watershed = area draining to a common water body.",
    ["Defined by topographic divides.", "Water quality depends on land use.", "Runoff carries pollutants downstream.", "Wetlands filter within watersheds."],
    "Why does upstream land use affect downstream water?",
    "Runoff from upstream carries sediment, pollutants, nutrients downstream.",
    [{q:"Watershed?",a:"Land draining to common water body."},{q:"Drainage divide?",a:"Topographic ridge separating watersheds."},{q:"Land use effect?",a:"Pollutants in runoff reach the water body."},{q:"Wetland role?",a:"Filter water, reduce flooding."},{q:"Largest US watershed?",a:"Mississippi River basin."}],
  ),
  mk(4, "4.7", "Solar Radiation and Earth's Seasons",
    "Earth's tilt (23.5°) causes seasons.",
    ["Axial tilt: 23.5°.", "Summer: tilted toward sun, more direct sunlight.", "Winter: tilted away.", "Equinoxes: equal day/night.", "Solstices: longest/shortest day."],
    "Why is it summer in the Northern Hemisphere in June?",
    "N Hemisphere tilted toward sun; more direct rays and longer daylight hours.",
    [{q:"Tilt angle?",a:"23.5°"},{q:"Summer cause?",a:"Hemisphere tilted toward sun."},{q:"Equinox?",a:"Equal day/night (March/Sept)."},{q:"Solstice?",a:"Longest or shortest day (June/Dec)."},{q:"Tropics latitude?",a:"±23.5°"}],
  ),
  mk(4, "4.8", "Earth's Geography and Climate",
    "Latitude, altitude, proximity to water, ocean currents shape climate.",
    ["Latitude: lower = warmer.", "Altitude: higher = cooler (~6.5°C/km).", "Ocean proximity: moderates temperature.", "Rain shadows: dry on leeward side of mountain."],
    "Why is Seattle milder in winter than inland Minneapolis?",
    "Pacific Ocean moderates temperature; inland areas have wider temperature range.",
    [{q:"Latitude effect?",a:"Lower latitude warmer."},{q:"Altitude effect?",a:"Higher = cooler (~6.5°C/km)."},{q:"Ocean effect?",a:"Moderates temperature extremes."},{q:"Rain shadow?",a:"Dry area on leeward side of mountain."},{q:"Maritime vs continental climate?",a:"Maritime moderate; continental extreme."}],
  ),
  mk(4, "4.9", "El Niño and La Niña",
    "ENSO shifts Pacific trade winds, affecting global weather.",
    ["El Niño: weak trade winds, warm Pacific.", "La Niña: strong winds, cool Pacific.", "Affect global precipitation, hurricanes.", "Cycles every 2-7 years."],
    "What's the atmospheric effect of El Niño on the US?",
    "Warmer winters in the North; wetter in the Southwest; fewer Atlantic hurricanes.",
    [{q:"El Niño?",a:"Weak trade winds, warm eastern Pacific."},{q:"La Niña?",a:"Strong winds, cool eastern Pacific."},{q:"ENSO cycle?",a:"Every 2-7 years."},{q:"Global impact?",a:"Shifts rainfall, storms, temperatures worldwide."},{q:"Walker circulation?",a:"Normal Pacific wind pattern."}],
  ),
  mk(5, "5.1", "The Tragedy of the Commons",
    "Shared resources get overexploited because individuals benefit while costs are shared.",
    ["Commons: shared resource (ocean fish, air, grazing).", "Individuals exploit for personal gain.", "Costs distributed; benefits concentrated.", "Solutions: regulation, privatization, community management."],
    "Overfishing is a textbook tragedy of the commons. Why?",
    "Each fisherman benefits from catching more; the cost (depletion) is shared by all.",
    [{q:"Tragedy of the commons?",a:"Shared resource overused."},{q:"Why happens?",a:"Individual gain, shared cost."},{q:"Common examples?",a:"Overfishing, air pollution, grazing land."},{q:"Solution types?",a:"Regulation, privatization, community rules."},{q:"Hardin (1968)?",a:"Popularized concept."}],
  ),
  mk(5, "5.2", "Clearcutting",
    "Removing all trees in an area. Cheap but destroys ecosystem and causes erosion.",
    ["Removes all trees at once.", "Cheaper than selective cutting.", "Destroys habitat, causes soil erosion.", "Leads to sediment runoff, water quality issues."],
    "Alternative to clearcutting?",
    "Selective cutting — removes only some trees, preserving forest structure.",
    [{q:"Clearcutting?",a:"All trees removed from an area."},{q:"Downsides?",a:"Erosion, habitat loss, water quality."},{q:"Selective cutting?",a:"Removes only certain trees."},{q:"Benefits of clearcutting?",a:"Efficiency, certain species regeneration."},{q:"Erosion risk?",a:"Very high after clearcutting."}],
  ),
  mk(5, "5.3", "The Green Revolution",
    "1940s-70s increase in food production via high-yield seeds, synthetic fertilizers, pesticides, irrigation.",
    ["High-yield varieties (HYVs) — especially wheat, rice.", "Mass fertilizer and pesticide use.", "Irrigation expansion.", "Doubled/tripled yields, averted famines.", "Tradeoffs: environmental, socioeconomic."],
    "Who's the 'father' of the Green Revolution?",
    "Norman Borlaug — developed high-yield wheat varieties; Nobel Peace Prize 1970.",
    [{q:"Green Revolution period?",a:"1940s-70s."},{q:"Key developments?",a:"HYVs, fertilizers, pesticides, irrigation."},{q:"Father of?",a:"Norman Borlaug."},{q:"Tradeoffs?",a:"Fertilizer runoff, pesticide resistance, monoculture, small farmers squeezed."},{q:"Averted?",a:"Massive famines in South Asia."}],
  ),
  mk(5, "5.4", "Impacts of Agricultural Practices",
    "Tilling, fertilizer, pesticide, monoculture all have environmental costs.",
    ["Tilling: erosion, SOC loss.", "Fertilizer: runoff → eutrophication.", "Pesticide: resistance, non-target harm, bioaccumulation.", "Monoculture: vulnerability to pests/diseases."],
    "Why is monoculture risky?",
    "One disease can wipe out entire crop (Irish Potato Famine).",
    [{q:"Tilling effect?",a:"Soil erosion, SOC loss."},{q:"Fertilizer runoff?",a:"Eutrophication, dead zones."},{q:"Pesticide resistance?",a:"Survivors reproduce."},{q:"Monoculture risk?",a:"Disease can devastate."},{q:"No-till agriculture?",a:"Reduces erosion."}],
  ),
  mk(5, "5.5", "Irrigation Methods",
    "Flood (inefficient), drip (efficient), furrow, spray, sub-surface.",
    ["Flood: wasteful, saline buildup.", "Drip: very efficient, expensive.", "Furrow: moderate efficiency.", "Spray: moderate, evaporation losses.", "Waterlogging and salinization from poor management."],
    "Which irrigation method is most water-efficient?",
    "Drip irrigation — delivers water directly to roots.",
    [{q:"Most efficient irrigation?",a:"Drip."},{q:"Least efficient?",a:"Flood."},{q:"Salinization?",a:"Salt buildup in soil from evaporating irrigation water."},{q:"Waterlogging?",a:"Poor drainage → root suffocation."},{q:"Aquifer depletion?",a:"Pumping faster than recharge."}],
  ),
  mk(5, "5.6", "Pest Control Methods",
    "Chemical, biological, IPM, cultural. Tradeoffs.",
    ["Chemical pesticides: fast but cause resistance.", "Biological: natural predators.", "Cultural: crop rotation, resistant varieties.", "IPM: integrated approach."],
    "How does IPM reduce pesticide use?",
    "Combines biological, cultural, and minimal chemical controls — uses pesticides only when needed.",
    [{q:"IPM?",a:"Integrated Pest Management."},{q:"Biological control?",a:"Use natural predators."},{q:"Pesticide resistance?",a:"Evolves from heavy use."},{q:"Cultural control?",a:"Crop rotation, habitat management."},{q:"Silent Spring?",a:"Rachel Carson's 1962 book on pesticides."}],
  ),
  mk(5, "5.7", "Meat Production Methods",
    "Factory farming (CAFOs) efficient but polluting. Grass-fed less efficient per acre.",
    ["CAFOs: high output, pollution (waste, methane).", "Grass-fed: lower impact per animal but lower density.", "Meat has higher footprint than plants.", "Antibiotic use in CAFOs → resistance."],
    "Why does beef have higher environmental footprint than chicken?",
    "Cattle digestion emits methane; more feed/water per kg meat; longer lifespan.",
    [{q:"CAFO?",a:"Concentrated Animal Feeding Operation."},{q:"Methane source?",a:"Cow digestion (enteric fermentation)."},{q:"Meat types by footprint?",a:"Beef > pork > chicken."},{q:"Antibiotic resistance?",a:"From CAFO antibiotic use."},{q:"Manure issue?",a:"Water pollution, methane."}],
  ),
  mk(5, "5.8", "Impacts of Overfishing",
    "Catching fish faster than they reproduce → population collapse.",
    ["Bycatch: non-target species killed.", "Trawling: seafloor destruction.", "Atlantic cod: famous collapse (1992).", "Solutions: quotas, MPAs, aquaculture."],
    "Why did Atlantic cod populations collapse?",
    "Decades of overfishing exceeded reproductive rates; populations couldn't recover.",
    [{q:"Overfishing?",a:"Catch > reproduction rate."},{q:"Bycatch?",a:"Unintended species caught."},{q:"Bottom trawling?",a:"Drag net along seafloor — destructive."},{q:"Atlantic cod collapse year?",a:"1992"},{q:"Solution?",a:"Quotas, protected areas, sustainable methods."}],
  ),
  mk(5, "5.9", "Impacts of Mining",
    "Surface mining, strip mining, mountaintop removal. Acid mine drainage.",
    ["Surface mining: strip land.", "Subsurface: tunnels, safer environmentally in some ways.", "Mountaintop removal: extreme surface method.", "Acid mine drainage: sulfide + water → sulfuric acid.", "Tailings: toxic waste."],
    "What is acid mine drainage?",
    "Sulfide minerals exposed by mining react with water + O₂ to form sulfuric acid, contaminating waterways.",
    [{q:"Strip mining?",a:"Remove surface layers to expose resource."},{q:"Mountaintop removal?",a:"Blast off top of mountain."},{q:"Acid mine drainage?",a:"Sulfuric acid from exposed sulfides."},{q:"Tailings?",a:"Toxic mining waste."},{q:"Reclamation?",a:"Restoring mined land."}],
  ),
  mk(5, "5.10", "Impacts of Urbanization",
    "Urbanization: habitat loss, runoff, heat island, air quality issues.",
    ["Impervious surfaces: more runoff, less infiltration.", "Urban heat island: cities warmer than surroundings.", "Air quality: traffic, industry.", "Habitat fragmentation."],
    "Why are cities warmer than rural areas?",
    "Impervious dark surfaces absorb heat; less vegetation for evapotranspiration; anthropogenic heat from AC, cars, etc.",
    [{q:"Urban heat island?",a:"Cities warmer than rural."},{q:"Why warmer?",a:"Impervious surfaces, less vegetation, anthropogenic heat."},{q:"Impervious surface effect?",a:"Increases runoff, reduces groundwater recharge."},{q:"Habitat fragmentation?",a:"Breaking up continuous habitat."},{q:"Mitigation?",a:"Green roofs, trees, permeable pavement."}],
  ),
  mk(5, "5.11", "Ecological Footprints",
    "Measure of environmental impact in land area required.",
    ["Footprint = land/resources consumed.", "US: ~7 global ha/person.", "Global avg: ~2.8; sustainable: ~1.6.", "We're using ~1.7 Earths' worth annually."],
    "Why does the US have a larger footprint than India?",
    "Higher consumption of energy, meat, manufactured goods, larger homes, more cars.",
    [{q:"Ecological footprint?",a:"Area of land required to support consumption."},{q:"US avg footprint?",a:"~7 global ha."},{q:"Sustainable?",a:"~1.6 (at current global pop)."},{q:"Consumption drivers?",a:"Energy, meat, material goods."},{q:"Lower footprint?",a:"Renewables, plant-based diet, efficiency."}],
  ),
  mk(5, "5.12", "Introduction to Sustainability",
    "Meeting present needs without compromising future generations.",
    ["Brundtland definition (1987).", "Pillars: environmental, social, economic.", "Triple bottom line.", "Resource use ≤ regeneration."],
    "What is the 'three pillars' model of sustainability?",
    "Environmental, social, and economic — all three must be balanced for true sustainability.",
    [{q:"Brundtland definition?",a:"Meet present needs without compromising future generations."},{q:"Three pillars?",a:"Environmental, social, economic."},{q:"Triple bottom line?",a:"People, planet, profit."},{q:"Unsustainable rate?",a:"Use > regeneration."},{q:"SDGs?",a:"UN Sustainable Development Goals (17)."}],
  ),
  mk(5, "5.13", "Methods to Reduce Urban Runoff",
    "Green infrastructure: rain gardens, permeable pavement, green roofs.",
    ["Rain gardens capture runoff.", "Permeable pavement allows infiltration.", "Green roofs reduce heat, absorb water.", "Reduces pollution reaching waterways."],
    "How do green roofs help?",
    "Absorb rainwater, insulate buildings, cool cities, reduce runoff and pollution.",
    [{q:"Rain garden?",a:"Planted depression that absorbs runoff."},{q:"Permeable pavement?",a:"Allows water through to ground."},{q:"Green roof?",a:"Vegetated roof, absorbs water and heat."},{q:"Bioswale?",a:"Landscape feature filtering runoff."},{q:"Urban benefit?",a:"Reduces flooding, heat, pollution."}],
  ),
  mk(5, "5.14", "Integrated Pest Management",
    "Combines biological, cultural, physical, and minimal chemical methods.",
    ["Monitor pest levels before acting.", "Use multiple methods sequentially.", "Pesticides only as last resort.", "Reduces resistance and environmental impact."],
    "Why does IPM use less pesticide?",
    "Monitors pest levels and uses non-chemical methods first; pesticides applied only when needed and in targeted ways.",
    [{q:"IPM core?",a:"Combine biological, cultural, chemical methods."},{q:"IPM benefit?",a:"Reduces resistance and environmental impact."},{q:"Economic threshold?",a:"Pest density where control action is warranted."},{q:"Chemical in IPM?",a:"Last resort, targeted."},{q:"Biological control example?",a:"Ladybugs for aphids."}],
  ),
  mk(5, "5.15", "Sustainable Agriculture",
    "Maintains productivity without depleting resources.",
    ["No-till: reduces erosion and SOC loss.", "Crop rotation: reduces pests, builds soil.", "Cover crops: protect soil.", "Organic: no synthetic fertilizers/pesticides.", "Agroforestry: trees in crop systems."],
    "How does crop rotation help?",
    "Breaks pest cycles, balances nutrient use, improves soil structure.",
    [{q:"No-till?",a:"Planting without plowing — reduces erosion."},{q:"Cover crop?",a:"Plants grown to protect/enrich soil."},{q:"Crop rotation?",a:"Changing crops each year."},{q:"Organic agriculture?",a:"No synthetic chemicals."},{q:"Agroforestry?",a:"Trees + crops."}],
  ),
  mk(5, "5.16", "Aquaculture",
    "Farming fish, shellfish, aquatic plants. Can relieve pressure on wild stocks.",
    ["Alleviates wild fishing pressure.", "Fed species (salmon) often worse for environment than filter-feeders (shellfish).", "Disease, pollution, escapes are concerns.", "Sustainable practices developing."],
    "Why is shellfish aquaculture generally more sustainable than salmon?",
    "Shellfish filter water naturally and don't need feed; salmon require fish-based feed and can pollute.",
    [{q:"Aquaculture?",a:"Farming aquatic species."},{q:"Shellfish farming impact?",a:"Generally beneficial (filtering water)."},{q:"Salmon farming concerns?",a:"Feed sources, disease, escapes."},{q:"Benefit?",a:"Reduce pressure on wild stocks."},{q:"Net-pen issues?",a:"Waste, disease spread, escapees."}],
  ),
  mk(5, "5.17", "Sustainable Forestry",
    "Selective cutting, replanting, long rotation, certification (FSC).",
    ["Selective cutting leaves forest intact.", "Replanting essential.", "FSC certification marks sustainable wood.", "Clearcutting sometimes used for specific species."],
    "What does FSC certification indicate?",
    "Forest Stewardship Council verifies wood is from sustainably managed forests.",
    [{q:"Selective cutting?",a:"Removes certain trees, keeps forest intact."},{q:"Clearcutting?",a:"All trees removed at once."},{q:"FSC?",a:"Forest Stewardship Council certification for sustainable wood."},{q:"Reforestation?",a:"Replanting trees after harvest."},{q:"Rotation period?",a:"Time between harvests on same land."}],
  ),
  mk(6, "6.1", "Renewable and Nonrenewable Resources",
    "Renewable: replenished naturally. Nonrenewable: finite.",
    ["Renewable: solar, wind, hydro, geothermal, biomass.", "Nonrenewable: coal, oil, natural gas, uranium.", "Some (biomass) renewable only if used sustainably.", "Fossil fuels formed over millions of years."],
    "Is nuclear energy renewable?",
    "Uranium is nonrenewable; nuclear is low-carbon but fuel is finite.",
    [{q:"Renewable energy?",a:"Replenished naturally (solar, wind, hydro)."},{q:"Nonrenewable?",a:"Fossil fuels, uranium."},{q:"Biomass?",a:"Renewable if used sustainably."},{q:"Fossil fuel formation?",a:"Millions of years from ancient organic matter."},{q:"Nuclear — renewable?",a:"No — uranium is finite."}],
  ),
  mk(6, "6.2", "Global Energy Consumption",
    "Fossil fuels still ~80% globally. Growing renewable share.",
    ["Global energy: mostly fossil fuels (~80%).", "Renewables ~20% (mostly hydro).", "Developing nations increasing rapidly.", "Per-capita varies dramatically."],
    "Which countries use most energy per capita?",
    "Wealthy industrialized: US, Canada, Saudi Arabia, Gulf states top the list.",
    [{q:"Global fossil fuel share?",a:"~80%"},{q:"Renewable share?",a:"~20% (mostly hydro)."},{q:"Highest per-capita user?",a:"Iceland (hydro/geothermal), or US/Canada for total."},{q:"Growth trend?",a:"Renewables growing fastest; fossil still dominant."},{q:"Developing nations?",a:"Rapidly increasing energy use."}],
  ),
  mk(6, "6.3", "Fuel Types and Uses",
    "Coal: electricity, industry. Oil: transport. Natural gas: electricity, heat.",
    ["Coal: cheap, dirty (CO₂, SO₂, mercury).", "Oil: high energy density, transport.", "Natural gas: cleanest fossil fuel (less CO₂).", "Uses depend on energy density and infrastructure."],
    "Why is oil dominant in transportation?",
    "High energy density, easily portable (liquid), existing infrastructure.",
    [{q:"Coal used for?",a:"Electricity, industry."},{q:"Oil used for?",a:"Transportation."},{q:"Natural gas?",a:"Electricity, heat, industry."},{q:"Dirtiest fossil fuel?",a:"Coal."},{q:"Cleanest fossil fuel?",a:"Natural gas."}],
  ),
  mk(6, "6.4", "Distribution of Natural Energy Resources",
    "Fossil fuels concentrated in specific regions.",
    ["Oil: Middle East, Russia, US, Venezuela.", "Coal: US, Russia, China, Australia.", "Natural gas: Russia, US, Middle East.", "Geopolitical implications."],
    "Why is the Middle East strategically important?",
    "Holds majority of easily accessible conventional oil reserves; supply disruptions affect global prices.",
    [{q:"Oil concentrated where?",a:"Middle East, Russia, US, Venezuela."},{q:"Coal concentrated where?",a:"US, Russia, China, Australia."},{q:"US shale revolution?",a:"Fracking made US top oil/gas producer."},{q:"OPEC?",a:"Organization of Petroleum Exporting Countries."},{q:"Geopolitical impact?",a:"Supply affects global economy."}],
  ),
  mk(6, "6.5", "Fossil Fuels",
    "Coal, oil, natural gas formed from ancient organic matter. Burning releases CO₂.",
    ["All release CO₂ when burned.", "Sulfur in coal → SO₂ → acid rain.", "Mercury in coal → biomagnification.", "Extraction impacts: mining, drilling, spills."],
    "Which fossil fuel produces the least CO₂ per unit energy?",
    "Natural gas (methane) — about half of coal's emissions per kWh.",
    [{q:"Fossil fuel origins?",a:"Ancient organic matter over millions of years."},{q:"CO₂ emissions ranking?",a:"Coal > oil > natural gas (per unit energy)."},{q:"Coal sulfur issue?",a:"SO₂ emissions → acid rain."},{q:"Fracking?",a:"Hydraulic fracturing for shale gas/oil."},{q:"Oil spills?",a:"Major aquatic pollution."}],
  ),
  mk(6, "6.6", "Nuclear Power",
    "Fission of U-235 produces heat → steam → electricity. No CO₂.",
    ["Fission: U-235 splits → heat + neutrons.", "No CO₂ during operation.", "Waste radioactive for thousands of years.", "Accidents: Chernobyl (1986), Fukushima (2011).", "Fuel: uranium (nonrenewable)."],
    "Why is nuclear considered low-carbon but not renewable?",
    "No CO₂ during operation, but uranium fuel is finite.",
    [{q:"Nuclear fission?",a:"Heavy nucleus splits, releasing energy."},{q:"Fuel?",a:"Uranium (U-235 enriched)."},{q:"Major advantage?",a:"No CO₂, high energy density."},{q:"Major concern?",a:"Radioactive waste, accidents."},{q:"Famous accidents?",a:"Chernobyl 1986, Fukushima 2011."}],
  ),
  mk(6, "6.7", "Energy from Biomass",
    "Burning organic matter (wood, crops, waste) for heat/electricity.",
    ["Renewable if regrowth matches use.", "Common globally (cooking in developing world).", "Biofuels: ethanol (corn), biodiesel.", "Air pollution from burning.", "Deforestation if overharvested."],
    "Is corn ethanol sustainable?",
    "Contested — uses fossil inputs, land competition with food; modest net energy gain.",
    [{q:"Biomass?",a:"Organic matter for energy."},{q:"Biofuels?",a:"Ethanol (corn, sugarcane), biodiesel."},{q:"Renewable if?",a:"Regrowth matches use rate."},{q:"Concern?",a:"Deforestation, land-use change, air pollution."},{q:"Brazilian sugarcane ethanol?",a:"More efficient than US corn ethanol."}],
  ),
  mk(6, "6.8", "Solar Energy",
    "PV and concentrated solar. Cost has dropped dramatically.",
    ["Photovoltaic (PV): sunlight → electricity.", "Concentrated solar: mirrors focus heat.", "No emissions during operation.", "Intermittent — needs storage or backup.", "PV cost down ~90% since 2010."],
    "Why is solar intermittent, and how can we compensate?",
    "No sun at night or cloudy days. Solutions: batteries, transmission, mix with other sources, demand response.",
    [{q:"Photovoltaic?",a:"Direct sunlight to electricity."},{q:"Concentrated solar?",a:"Mirrors focus sun to heat fluid."},{q:"Cost trend?",a:"~90% lower since 2010."},{q:"Intermittency solution?",a:"Storage, mix, transmission."},{q:"Operating emissions?",a:"None."}],
  ),
  mk(6, "6.9", "Hydroelectric Power",
    "Flowing water spins turbines. ~16% of global electricity.",
    ["Dams store water; turbines generate.", "No CO₂ during operation.", "Impacts: ecosystem disruption, displacement, methane from reservoirs.", "Large hydro capacity near maxed out.", "Run-of-river less disruptive."],
    "Why do dams sometimes emit greenhouse gases?",
    "Flooded vegetation decomposes anaerobically in reservoirs, releasing methane.",
    [{q:"Hydropower share of global electricity?",a:"~16%"},{q:"Major environmental impact?",a:"Ecosystem disruption, displacement."},{q:"Methane source?",a:"Decaying vegetation in reservoirs."},{q:"Run-of-river?",a:"Uses natural flow, less disruptive."},{q:"World's largest dam?",a:"Three Gorges (China)."}],
  ),
  mk(6, "6.10", "Geothermal Energy",
    "Earth's heat: direct use or electricity via steam.",
    ["Hot water from ground → heating/electricity.", "Available where Earth's heat near surface (Iceland, CA, NZ).", "Low emissions.", "Limited geography."],
    "Why is Iceland a geothermal pioneer?",
    "Located on a tectonic plate boundary — abundant near-surface heat and hot springs.",
    [{q:"Geothermal?",a:"Earth's heat → energy."},{q:"Emissions?",a:"Very low."},{q:"Iceland's use?",a:"Most heating and much electricity."},{q:"Geography limitation?",a:"Requires accessible geothermal heat."},{q:"Heat pump?",a:"Uses ground's stable temp for heating/cooling."}],
  ),
  mk(6, "6.11", "Hydrogen Fuel Cell",
    "H₂ + O₂ → H₂O + electricity. Clean if H₂ made cleanly.",
    ["Fuel cells convert H₂ + O₂ to electricity + water.", "Clean at point of use.", "H₂ production: mostly from natural gas (not clean).", "Green H₂: electrolysis with renewables."],
    "Why isn't hydrogen automatically clean?",
    "Most H₂ comes from natural gas (steam reforming) — emits CO₂. Only 'green' H₂ from renewables is truly clean.",
    [{q:"Hydrogen fuel cell?",a:"H₂ + O₂ → H₂O + electricity"},{q:"Emissions at use?",a:"Only water."},{q:"Most H₂ made from?",a:"Natural gas (with CO₂ emissions)."},{q:"Green hydrogen?",a:"H₂ from renewable electrolysis."},{q:"Used in?",a:"Some vehicles, industrial heat."}],
  ),
  mk(6, "6.12", "Wind Energy",
    "Wind turbines convert kinetic energy to electricity. Growing fast.",
    ["Turbine blades → rotation → generator.", "No emissions.", "Intermittent — wind isn't constant.", "Bird/bat deaths; sound concerns.", "Offshore wind growing."],
    "Why is offshore wind attractive?",
    "Stronger, steadier winds than onshore; no land-use conflict; larger turbines possible.",
    [{q:"Wind energy?",a:"Turbines convert wind kinetic energy to electricity."},{q:"Operating emissions?",a:"None."},{q:"Intermittency?",a:"Wind varies."},{q:"Concerns?",a:"Birds, noise, aesthetics."},{q:"Offshore wind?",a:"Stronger, steadier winds."}],
  ),
  mk(6, "6.13", "Energy Conservation",
    "Using less energy for same service. Usually cheapest option.",
    ["Efficiency: doing same with less.", "Conservation: doing less.", "Payback periods usually short.", "LEDs, insulation, efficient HVAC.", "CAFE standards for cars."],
    "What's the difference between efficiency and conservation?",
    "Efficiency: better technology for same service. Conservation: changing behavior to use less.",
    [{q:"Efficiency?",a:"Same service with less energy."},{q:"Conservation?",a:"Using less energy."},{q:"LED vs incandescent?",a:"LED uses ~10% as much energy."},{q:"CAFE standards?",a:"US fuel-economy rules for cars."},{q:"Payback period?",a:"Time to recoup efficiency investment."}],
  ),
  mk(7, "7.1", "Introduction to Air Pollution",
    "Primary: emitted directly. Secondary: formed in atmosphere.",
    ["Primary pollutants: CO, SO₂, NOx, particulates, VOCs.", "Secondary: ozone (O₃), acid rain.", "Sources: burning fossil fuels, industry, transport.", "Clean Air Act (1970) regulates major pollutants."],
    "What's the difference between primary and secondary pollutants?",
    "Primary are emitted directly (e.g., SO₂); secondary form in atmosphere (e.g., ozone from NOx + VOCs + sunlight).",
    [{q:"Primary pollutant?",a:"Emitted directly."},{q:"Secondary?",a:"Formed in atmosphere."},{q:"Criteria pollutants?",a:"CO, SO₂, NO₂, O₃, PM, Pb."},{q:"Clean Air Act?",a:"1970 US law regulating air pollutants."},{q:"Sources?",a:"Burning fossil fuels, industry, vehicles."}],
  ),
  mk(7, "7.2", "Photochemical Smog",
    "NOx + VOCs + sunlight → ozone and other oxidants. Worst in cities.",
    ["Needs: NOx, VOCs, sunlight, stagnant air.", "Ozone irritates lungs.", "Worst in LA, Mexico City, Beijing.", "Reduce by: fewer vehicles, cleaner fuels, catalytic converters."],
    "Why is LA famous for smog?",
    "Millions of cars (NOx, VOCs), warm sunlight, surrounded by mountains (stagnant air).",
    [{q:"Photochemical smog ingredients?",a:"NOx + VOCs + sunlight"},{q:"Produces?",a:"Ground-level ozone."},{q:"Health effect?",a:"Lung irritation, asthma."},{q:"LA smog cause?",a:"Cars + sunlight + basin topography."},{q:"Reduce smog?",a:"Cleaner fuels, catalytic converters, fewer cars."}],
  ),
  mk(7, "7.3", "Thermal Inversion",
    "Warm air layer traps cool polluted air below.",
    ["Normally, warm air rises, mixing pollutants.", "Inversion: warm layer above cool traps pollutants.", "Common in valleys.", "Can cause severe smog events (London 1952)."],
    "Why does thermal inversion worsen air pollution?",
    "Traps polluted air near ground; pollutants can't disperse vertically.",
    [{q:"Thermal inversion?",a:"Warm air above cool; traps pollution."},{q:"Normal atmosphere?",a:"Cools with altitude, mixes vertically."},{q:"Valley inversions common?",a:"Yes — topography contributes."},{q:"Famous event?",a:"Great Smog of London 1952 (~12,000 deaths)."},{q:"Impact on smog?",a:"Traps pollutants, worsens air quality."}],
  ),
  mk(7, "7.4", "Atmospheric CO2 and Particulates",
    "CO₂ is a greenhouse gas; PM2.5 damages lungs.",
    ["CO₂: long-lived GHG, drives warming.", "PM2.5: fine particles, lung/heart damage.", "Sources: combustion, fires, dust.", "WHO: air pollution major cause of premature death."],
    "Why is PM2.5 particularly dangerous?",
    "Small enough to penetrate deep into lungs and even bloodstream; linked to heart and lung disease.",
    [{q:"PM2.5?",a:"Particulate matter <2.5 μm diameter."},{q:"Why dangerous?",a:"Enters deep lungs, bloodstream."},{q:"CO₂ lifetime in atmosphere?",a:"Hundreds to thousands of years."},{q:"CO₂ natural level?",a:"~280 ppm pre-industrial; now ~420 ppm."},{q:"Sources?",a:"Combustion, fires, dust, industry."}],
  ),
  mk(7, "7.5", "Indoor Air Pollutants",
    "Often worse than outdoor: radon, asbestos, smoke, VOCs.",
    ["Radon: radioactive gas from soil — lung cancer.", "Asbestos: fibers, lung disease.", "Secondhand smoke: dangerous.", "VOCs: paints, furniture, cleaning products.", "Combustion: gas stoves, wood burning."],
    "What's the second-leading cause of lung cancer in the US?",
    "Radon — seeps from ground into basements and homes.",
    [{q:"Radon?",a:"Radioactive gas from soil; lung cancer."},{q:"Asbestos?",a:"Fibrous mineral; lung disease."},{q:"VOCs indoor sources?",a:"Paints, furniture, cleaners."},{q:"Best ventilation?",a:"Open windows; HVAC filters."},{q:"Secondhand smoke?",a:"Causes cancer and lung disease in nonsmokers."}],
  ),
  mk(7, "7.6", "Reduction of Air Pollutants",
    "Catalytic converters, scrubbers, electrostatic precipitators, regulations.",
    ["Catalytic converters: reduce car exhaust (CO, NOx, VOCs).", "Scrubbers: remove SO₂ from stacks.", "Electrostatic precipitators: remove particulates.", "Fuel switching: coal → gas → renewables."],
    "What does a catalytic converter do?",
    "Catalyzes conversion of toxic exhaust (CO, NOx, unburned HCs) to CO₂, H₂O, N₂.",
    [{q:"Catalytic converter?",a:"Reduces car exhaust pollution."},{q:"Scrubber?",a:"Removes SO₂ from smokestacks."},{q:"Electrostatic precipitator?",a:"Removes particulates using static charge."},{q:"Clean Air Act?",a:"Sets emission limits."},{q:"Fuel switching?",a:"Moving from dirtier to cleaner fuels."}],
  ),
  mk(7, "7.7", "Acid Rain",
    "SO₂ + NOx + water → H₂SO₄, HNO₃. Damages lakes, forests, buildings.",
    ["SO₂ (coal) → sulfuric acid.", "NOx (cars, industry) → nitric acid.", "Kills fish in lakes (pH < 5).", "Damages forests, stone buildings.", "Scrubbers and Clean Air Act have reduced it."],
    "Why did acid rain affect Scandinavian lakes?",
    "Acid rain from UK/German industry carried by westerlies; thin soils with little buffering capacity.",
    [{q:"Acid rain pH?",a:"<5.6 (below natural rain)."},{q:"Sources?",a:"SO₂ from coal, NOx from vehicles."},{q:"Effect on lakes?",a:"Kills fish, insects."},{q:"Effect on trees?",a:"Damages leaves, weakens immune."},{q:"Reduction?",a:"Scrubbers, cleaner fuels, regulation."}],
  ),
  mk(7, "7.8", "Noise Pollution",
    "Loud or persistent sound affecting health, wildlife.",
    ["Sources: traffic, industry, construction.", "Effects: hearing loss, stress, sleep disruption.", "Wildlife: affects communication, navigation.", "Measured in decibels (dB)."],
    "Why is noise pollution bad for whales?",
    "Shipping and sonar disrupt communication and navigation; can cause strandings.",
    [{q:"Noise pollution?",a:"Harmful or excessive sound."},{q:"Health effects?",a:"Hearing loss, stress, sleep."},{q:"Wildlife effect?",a:"Communication disruption (whales, birds)."},{q:"Units?",a:"Decibels (dB)."},{q:"Solutions?",a:"Barriers, zoning, quieter technology."}],
  ),
  mk(8, "8.1", "Sources of Pollution",
    "Point source: from specific location. Nonpoint: diffuse.",
    ["Point source: factory pipe, power plant.", "Nonpoint: agricultural runoff, urban runoff.", "Point sources easier to regulate.", "Nonpoint major source of water pollution."],
    "Runoff from farms — point or nonpoint?",
    "Nonpoint — comes from many diffuse sources, hard to regulate.",
    [{q:"Point source?",a:"Specific identifiable location (pipe, stack)."},{q:"Nonpoint?",a:"Diffuse sources (runoff)."},{q:"Easier to regulate?",a:"Point sources."},{q:"Biggest water pollution?",a:"Nonpoint (agricultural runoff)."},{q:"Clean Water Act targets?",a:"Primarily point sources."}],
  ),
  mk(8, "8.2", "Human Impacts on Ecosystems",
    "HIPPO: Habitat, Invasive, Pollution, Population, Overharvesting.",
    ["Habitat loss: #1 extinction driver.", "Invasive species: displace natives.", "Pollution: air, water, soil.", "Population growth: increases all others.", "Overharvesting: fishing, hunting, logging."],
    "What is 'HIPPO'?",
    "Acronym for top threats: Habitat loss, Invasives, Pollution, Population, Overharvesting.",
    [{q:"HIPPO?",a:"Habitat, Invasives, Pollution, Population, Overharvesting."},{q:"Top extinction driver?",a:"Habitat loss."},{q:"Invasive species?",a:"Non-native causing ecological/economic harm."},{q:"Population connection?",a:"Drives other threats."},{q:"Overharvesting example?",a:"Atlantic cod, bluefin tuna."}],
  ),
  mk(8, "8.3", "Endocrine Disruptors",
    "Chemicals that mimic or block hormones.",
    ["Examples: BPA, phthalates, PCBs, pesticides.", "Effects: reproductive, developmental.", "Low doses can have big effects.", "Ubiquitous in modern environment."],
    "Why are endocrine disruptors concerning?",
    "Even low doses can disrupt hormone-driven development — reproductive issues, cancer risks.",
    [{q:"Endocrine disruptor?",a:"Chemical that mimics or blocks hormones."},{q:"Examples?",a:"BPA, phthalates, DDT, PCBs."},{q:"Effects?",a:"Reproductive, developmental issues."},{q:"Wildlife example?",a:"Frog deformities."},{q:"Where found?",a:"Plastics, pesticides, industrial chemicals."}],
  ),
  mk(8, "8.4", "Human Impacts on Wetlands and Mangroves",
    "Drained for development; lose flood control, biodiversity.",
    ["50% of wetlands lost globally.", "Lost flood control, water filtration.", "Mangroves: coastal protection from storms.", "Restoration possible but slow."],
    "What do wetlands provide?",
    "Flood control, water filtration, habitat, carbon storage, recreation.",
    [{q:"Wetland services?",a:"Flood control, filtration, habitat, carbon."},{q:"% lost globally?",a:"~50%."},{q:"Mangrove role?",a:"Coastal protection from storms."},{q:"Causes of loss?",a:"Drainage for farming, development."},{q:"Restoration?",a:"Possible but expensive and slow."}],
  ),
  mk(8, "8.5", "Eutrophication",
    "Excess nutrients → algal bloom → die-off → decomposition → O₂ depletion → dead zone.",
    ["Excess N, P from runoff.", "Algal bloom.", "Algae die, decompose.", "Decomposition consumes O₂.", "Fish die; dead zone.", "Gulf of Mexico has major dead zone from Mississippi runoff."],
    "Why does excess fertilizer create dead zones?",
    "Nutrients → algae bloom → die → decomposers consume O₂ → hypoxic water → fish die.",
    [{q:"Eutrophication cause?",a:"Excess N and P."},{q:"Stages?",a:"Bloom → die-off → decomposition → O₂ depletion."},{q:"Gulf dead zone?",a:"From Mississippi River nutrient runoff."},{q:"Cultural eutrophication?",a:"Human-accelerated version."},{q:"Prevention?",a:"Buffer strips, reduced fertilizer."}],
  ),
  mk(8, "8.6", "Thermal Pollution",
    "Heated water discharge reduces O₂, disrupts ecosystems.",
    ["Power plants discharge warm water.", "Warm water holds less O₂.", "Alters species composition.", "Thermal shock during restart events.", "Cooling towers mitigate."],
    "Why does warm water threaten aquatic life?",
    "Warm water holds less dissolved O₂; species with high O₂ needs (cold-water fish) suffocate.",
    [{q:"Thermal pollution source?",a:"Power plant cooling water."},{q:"Main effect?",a:"Reduced dissolved O₂."},{q:"Cold-water fish effect?",a:"Can't survive."},{q:"Mitigation?",a:"Cooling towers, ponds."},{q:"Nuclear vs fossil thermal impact?",a:"Both similar (steam cycle)."}],
  ),
  mk(8, "8.7", "Persistent Organic Pollutants (POPs)",
    "Long-lasting organic chemicals that bioaccumulate.",
    ["Examples: DDT, PCBs, dioxins.", "Don't break down easily.", "Travel globally via air, water.", "Bioaccumulate up food chain.", "Stockholm Convention (2001) restricts."],
    "Why did DDT threaten bald eagles?",
    "Bioaccumulated in fish → eagles ate fish → DDT concentrated in eagles → thin eggshells → chick deaths.",
    [{q:"POPs?",a:"Persistent Organic Pollutants."},{q:"Examples?",a:"DDT, PCBs, dioxins."},{q:"Why problematic?",a:"Don't break down; bioaccumulate; travel globally."},{q:"DDT ban?",a:"US 1972, Stockholm Convention 2001."},{q:"Bioaccumulation?",a:"Buildup in organism over time."}],
  ),
  mk(8, "8.8", "Bioaccumulation and Biomagnification",
    "Bioaccumulation: within organism. Biomagnification: up food chain.",
    ["Bioaccumulation: toxin stored in tissue over time.", "Biomagnification: concentration increases up trophic levels.", "Fat-soluble toxins (DDT, PCBs, Hg) common culprits.", "Top predators most affected."],
    "Why are top predators most affected by biomagnification?",
    "Each trophic level concentrates toxins ~10×; apex predators accumulate 10⁴-10⁵ times the water concentration.",
    [{q:"Bioaccumulation?",a:"Buildup in individual organism."},{q:"Biomagnification?",a:"Concentration up trophic levels."},{q:"Magnification factor per level?",a:"~10×"},{q:"Most affected?",a:"Top predators (eagles, tuna, orcas)."},{q:"Common culprits?",a:"DDT, PCBs, methylmercury."}],
  ),
  mk(8, "8.9", "Solid Waste Disposal",
    "Landfill, incineration, recycling, composting.",
    ["Landfill: most US waste; leachate and methane.", "Incineration: reduces volume; air pollution.", "Recycling: saves energy; limits on what's recyclable.", "Composting: organic matter → soil amendment.", "E-waste growing problem."],
    "Why is methane produced at landfills?",
    "Anaerobic decomposition of organic waste produces methane (potent GHG).",
    [{q:"Most US waste goes to?",a:"Landfills."},{q:"Landfill issues?",a:"Leachate, methane."},{q:"Leachate?",a:"Contaminated liquid from landfill."},{q:"Incineration concern?",a:"Air pollution, ash disposal."},{q:"E-waste?",a:"Electronics — hazardous if not recycled."}],
  ),
  mk(8, "8.10", "Waste Reduction Methods",
    "Reduce, reuse, recycle (3 Rs). Extended producer responsibility.",
    ["Reduce: use less.", "Reuse: again for same/different purpose.", "Recycle: reprocess materials.", "Compost: organic waste.", "Producer responsibility: manufacturers take back products."],
    "Which is best: reduce, reuse, or recycle?",
    "Reduce is best (no waste created); reuse second; recycle third (still energy-intensive).",
    [{q:"3 Rs hierarchy?",a:"Reduce > Reuse > Recycle."},{q:"Composting?",a:"Organic decomposition → soil."},{q:"Extended producer responsibility?",a:"Manufacturer responsible for product end-of-life."},{q:"Why reduce best?",a:"No waste created."},{q:"Recycling drawbacks?",a:"Energy, contamination issues."}],
  ),
  mk(8, "8.11", "Sewage Treatment",
    "Primary: physical. Secondary: biological. Tertiary: chemical/advanced.",
    ["Primary: screens, settling removes solids.", "Secondary: bacteria decompose organic matter.", "Tertiary: removes nutrients, pathogens.", "Septic systems treat waste at small scale."],
    "What's removed in each sewage treatment stage?",
    "Primary: solids. Secondary: dissolved organic matter. Tertiary: nutrients and pathogens.",
    [{q:"Primary treatment?",a:"Physical removal of solids."},{q:"Secondary?",a:"Biological (bacteria) decomposition."},{q:"Tertiary?",a:"Advanced: nutrients, pathogens removed."},{q:"Septic system?",a:"On-site treatment, common rural."},{q:"Dechlorination?",a:"Before discharge to prevent aquatic harm."}],
  ),
  mk(8, "8.12", "Lethal Dose 50% (LD50)",
    "Dose that kills 50% of test population. Measures acute toxicity.",
    ["LD50 lower = more toxic.", "Expressed as mg/kg body weight.", "Varies by species, route of exposure.", "Chronic toxicity separate concern."],
    "Does low LD50 mean more or less toxic?",
    "More toxic — less dose needed to kill.",
    [{q:"LD50?",a:"Lethal dose for 50% of test organisms."},{q:"Lower LD50?",a:"More toxic."},{q:"Units?",a:"mg/kg body weight."},{q:"Acute vs chronic?",a:"Short-term vs long-term exposure."},{q:"Common route?",a:"Oral, dermal, inhalation."}],
  ),
  mk(8, "8.13", "Dose Response Curve",
    "Plot response vs dose. Threshold: lowest dose causing effect.",
    ["X: dose. Y: % responding.", "Threshold: minimum dose for effect.", "LD50: 50% mortality point.", "Linear (no-threshold) models used for some carcinogens."],
    "What's the 'threshold dose'?",
    "The lowest dose at which any effect appears — below this, no observable response.",
    [{q:"Dose-response curve?",a:"Plot of biological response vs dose."},{q:"Threshold?",a:"Lowest dose producing effect."},{q:"LD50?",a:"Dose killing 50% of subjects."},{q:"No-threshold model?",a:"Effect at any dose (carcinogens)."},{q:"Shape?",a:"Often sigmoidal (S-curve)."}],
  ),
  mk(8, "8.14", "Pollution and Human Health",
    "Air, water, soil pollution → cardiovascular, respiratory, cancer, birth defects.",
    ["Air pollution: asthma, heart disease, lung cancer.", "Water pollution: diarrheal disease, especially in developing countries.", "Soil/chemical: cancers, birth defects.", "Vulnerable groups: children, elderly, poor."],
    "Which groups are most vulnerable to pollution?",
    "Children, elderly, pregnant women, poor communities near pollution sources.",
    [{q:"Air pollution deaths/year?",a:"~7 million (WHO)."},{q:"Waterborne disease?",a:"Diarrheal, cholera, typhoid."},{q:"Vulnerable groups?",a:"Children, elderly, poor."},{q:"Environmental justice?",a:"Disproportionate pollution burden on marginalized communities."},{q:"Chronic effects?",a:"Cancer, birth defects, developmental issues."}],
  ),
  mk(8, "8.15", "Pathogens and Infectious Diseases",
    "Pathogens spread via water, air, vectors, direct contact.",
    ["Waterborne: cholera, typhoid, Giardia.", "Vector-borne: malaria (mosquito), Lyme (tick).", "Airborne: TB, flu, COVID-19.", "Food-borne: Salmonella, E. coli.", "Climate change shifting vector ranges."],
    "How could climate change spread malaria?",
    "Warmer temperatures extend mosquito range to higher latitudes/altitudes.",
    [{q:"Waterborne disease example?",a:"Cholera, Giardia, typhoid."},{q:"Vector-borne?",a:"Malaria, Lyme, West Nile."},{q:"Airborne?",a:"Flu, TB, COVID-19."},{q:"Climate and disease?",a:"Warming shifts vector ranges."},{q:"Zoonotic?",a:"Transmitted from animals (Ebola, SARS)."}],
  ),
  mk(9, "9.1", "Stratospheric Ozone Depletion",
    "CFCs break down ozone. Antarctic ozone hole. Montreal Protocol fixed it.",
    ["CFCs release Cl radicals in stratosphere.", "Cl destroys O₃.", "Antarctic ozone hole discovered 1985.", "Montreal Protocol (1987) banned CFCs.", "Ozone layer now recovering."],
    "What was the Montreal Protocol?",
    "1987 treaty phasing out CFCs — most successful environmental treaty; ozone layer is recovering.",
    [{q:"Ozone depletion cause?",a:"CFCs (chlorofluorocarbons)."},{q:"Ozone hole discovered when?",a:"1985 (Antarctic)."},{q:"Montreal Protocol?",a:"1987 treaty phasing out CFCs."},{q:"Ozone recovery?",a:"Expected by 2060-70."},{q:"Why ozone matters?",a:"Absorbs UV radiation."}],
  ),
  mk(9, "9.2", "Reducing Ozone Depletion",
    "Montreal Protocol success. HFCs replaced but are GHGs; now also phasing out.",
    ["Montreal Protocol (1987) phased out CFCs.", "HCFCs interim; also being phased out.", "HFCs replaced but are potent GHGs.", "Kigali Amendment (2016) phases out HFCs."],
    "Why is the Montreal Protocol considered a success?",
    "Nearly universal ratification; CFCs dramatically reduced; ozone layer healing — the model environmental treaty.",
    [{q:"Montreal Protocol target?",a:"CFCs (ozone-depleting)."},{q:"HCFCs?",a:"Interim replacement; being phased out."},{q:"HFCs?",a:"Replaced CFCs; but potent GHGs."},{q:"Kigali Amendment?",a:"2016 phase-out of HFCs."},{q:"Success factors?",a:"Universal ratification, clear science, alternatives available."}],
  ),
  mk(9, "9.3", "The Greenhouse Effect",
    "GHGs trap heat, warm planet. Natural + enhanced by humans.",
    ["Incoming solar radiation heats Earth.", "Earth radiates infrared.", "GHGs absorb IR, re-emit — trapping heat.", "Without it, Earth would be ~33°C colder.", "Human emissions enhance it → warming."],
    "What's the difference between natural and enhanced greenhouse effect?",
    "Natural maintains livable climate; enhanced (from human GHGs) warms Earth further.",
    [{q:"Greenhouse effect basics?",a:"GHGs trap infrared radiation."},{q:"Main GHGs?",a:"CO₂, CH₄, N₂O, water vapor, ozone."},{q:"Earth without GHGs?",a:"~33°C colder (frozen)."},{q:"Enhanced greenhouse?",a:"Human emissions intensify natural effect."},{q:"Why IR trapped?",a:"GHG molecules absorb specific IR wavelengths."}],
  ),
  mk(9, "9.4", "Increases in the Greenhouse Gases",
    "CO₂: 280 → 420 ppm. CH₄ doubled. Human-caused.",
    ["Pre-industrial CO₂: 280 ppm; now 420 ppm.", "Methane ~2.5× pre-industrial.", "N₂O from agriculture, industry.", "F-gases from refrigerants/industry.", "Fossil fuels + deforestation main drivers."],
    "Which greenhouse gas is most abundant from human activity?",
    "CO₂ — from burning fossil fuels and deforestation.",
    [{q:"Pre-industrial CO₂?",a:"~280 ppm."},{q:"Current CO₂?",a:"~420 ppm (rising)."},{q:"Methane per-molecule warming?",a:"~28× CO₂ over 100 years."},{q:"Methane sources?",a:"Livestock, rice, landfills, leaks."},{q:"N₂O source?",a:"Agricultural fertilizer, industry."}],
  ),
  mk(9, "9.5", "Global Climate Change",
    "Global average temperature ~1.2°C above pre-industrial. Sea level rising, extreme weather.",
    ["~1.2°C warming since pre-industrial.", "Sea level rising (thermal expansion + ice melt).", "Extreme weather more frequent.", "Arctic warming faster than global average.", "Paris Agreement aims <1.5°C."],
    "What does '1.5°C' mean in climate policy?",
    "Paris Agreement goal to limit warming to 1.5°C above pre-industrial to avoid worst climate impacts.",
    [{q:"Current warming?",a:"~1.2°C since pre-industrial."},{q:"Paris Agreement target?",a:"Limit to 1.5-2°C."},{q:"Sea level rise causes?",a:"Thermal expansion + ice melt."},{q:"Arctic warming rate?",a:"~3-4× global average."},{q:"IPCC?",a:"Intergovernmental Panel on Climate Change — UN body."}],
  ),
  mk(9, "9.6", "Ocean Warming",
    "Oceans absorbed ~90% of warming. Stratification, coral bleaching, storm intensification.",
    ["Oceans absorb 90%+ of added heat.", "Ocean stratification reduces mixing.", "Coral bleaching at elevated temps.", "Hurricanes intensify with warmer water.", "Species migrate poleward."],
    "Why is coral bleaching happening?",
    "Warm water stresses coral → expels symbiotic algae → loses color and energy source → dies if sustained.",
    [{q:"Ocean heat absorption?",a:"~90% of excess heat."},{q:"Coral bleaching cause?",a:"Warm water expels zooxanthellae."},{q:"Stratification effect?",a:"Reduces mixing, nutrient distribution."},{q:"Storm intensification?",a:"Warm water fuels stronger hurricanes."},{q:"Species response?",a:"Migrate poleward or to depth."}],
  ),
  mk(9, "9.7", "Ocean Acidification",
    "CO₂ + H₂O → H₂CO₃ lowers pH, dissolves shells.",
    ["Ocean pH dropped ~0.1 (30% more H⁺).", "CO₂ + H₂O ⇌ H₂CO₃.", "Harms coral, shellfish, pteropods.", "Shells dissolve faster.", "Affects entire food web."],
    "Why is ocean acidification harmful to shellfish?",
    "Lower pH makes it harder to build calcium carbonate shells; can even dissolve existing shells.",
    [{q:"Ocean acidification?",a:"Decrease in ocean pH from CO₂."},{q:"pH change?",a:"~0.1 lower (30% more H⁺)."},{q:"Reaction?",a:"CO₂ + H₂O ⇌ H₂CO₃"},{q:"Affected organisms?",a:"Shellfish, coral, pteropods."},{q:"Long-term effect?",a:"Food web disruption."}],
  ),
  mk(9, "9.8", "Invasive Species",
    "Non-native species displacing natives, disrupting ecosystems.",
    ["Introduction: intentional or accidental.", "Lack natural controls (predators, diseases).", "Displace natives, ecosystem damage.", "Examples: zebra mussels, Burmese python, kudzu, emerald ash borer.", "Prevention cheaper than eradication."],
    "Why are Burmese pythons a problem in Florida?",
    "No natural predators; decimating native mammal populations in Everglades.",
    [{q:"Invasive species?",a:"Non-native causing ecological/economic harm."},{q:"Why successful?",a:"No natural predators/diseases."},{q:"US examples?",a:"Zebra mussels, Burmese python, kudzu, Asian carp."},{q:"Intro pathway?",a:"Ballast water, ornamental, accidental."},{q:"Best approach?",a:"Prevention."}],
  ),
  mk(9, "9.9", "Endangered Species",
    "Species at risk of extinction. IUCN Red List categorizes.",
    ["IUCN Red List classifications.", "Extinction rates 100-1000× background.", "US Endangered Species Act (1973).", "Keystone species loss especially damaging.", "Captive breeding, habitat protection."],
    "What was the Endangered Species Act's goal?",
    "To protect and recover threatened/endangered species via habitat protection and regulations.",
    [{q:"IUCN Red List?",a:"Global extinction-risk classifications."},{q:"Current extinction rate?",a:"100-1000× natural background."},{q:"US ESA year?",a:"1973"},{q:"CITES?",a:"Treaty regulating trade in endangered species."},{q:"Recovery example?",a:"Bald eagle, gray wolf, California condor."}],
  ),
  mk(9, "9.10", "Human Impacts on Biodiversity",
    "HIPPO threats plus climate change accelerate extinctions. 6th mass extinction.",
    ["Sixth mass extinction underway.", "HIPPO threats combine.", "Climate change compounds.", "Extinction rates 100-1000× background.", "Conservation: protected areas, species recovery, habitat restoration."],
    "What makes the current extinction event different from past ones?",
    "Caused by one species (humans); extremely rapid; affecting most ecosystems globally.",
    [{q:"Sixth mass extinction?",a:"Current human-caused extinction event."},{q:"HIPPO?",a:"Habitat, Invasives, Pollution, Population, Overharvesting."},{q:"Conservation strategies?",a:"Protected areas, recovery programs, habitat restoration."},{q:"Biodiversity hotspots?",a:"Regions with high endemism and high threat."},{q:"SDG relevant?",a:"SDG 14 (life below water), 15 (life on land)."}],
  ),
];
