import type { Lesson } from "@/lib/topics";

/** AP European History — one Lesson per CED topic across all 9 units (86 topics). */

const KA = "https://www.khanacademy.org/humanities/world-history";

const U: Record<number, string> = {
  1: "Renaissance and Exploration (c. 1450-1648)",
  2: "Age of Reformation (c. 1450-1648)",
  3: "Absolutism and Constitutionalism (c. 1648-1815)",
  4: "Scientific, Philosophical, and Political Developments (c. 1648-1815)",
  5: "Conflict, Crisis, and Reaction in the Late 18th Century",
  6: "Industrialization and Its Effects (c. 1815-1914)",
  7: "19th-Century Perspectives and Political Developments",
  8: "20th-Century Global Conflicts (c. 1914-present)",
  9: "Cold War and Contemporary Europe (c. 1914-present)",
};

const mk = (
  unit: number,
  id: string,
  title: string,
  blurb: string,
  keyIdeas: string[],
  sampleProblem: string,
  sampleWalkthrough: string,
  flashcards: { q: string; a: string }[]
): Lesson => ({
  slug: `apeuro-${id.replace(".", "-")}`,
  title,
  courses: [{ courseSlug: "ap-euro-history", unitNumber: unit, unitTitle: U[unit] }],
  blurb,
  keyIdeas,
  sampleProblem,
  sampleWalkthrough,
  flashcards,
  links: [{ title: "AP European History", url: KA, source: "Khan Academy" }],
});

export const AP_EURO_HISTORY_LESSONS: Lesson[] = [
  mk(1, "1.1", "Contextualizing Renaissance and Discovery",
    "Italy emerges from medieval stagnation. Humanism, commercial wealth, political fragmentation.",
    ["Italian city-states (Venice, Florence) commercial wealth.", "Recovery of classical learning.", "Medici banking in Florence.", "Humanism emphasized individual and secular themes.", "Fragmentation of Italy."],
    "SAQ: Briefly explain ONE factor enabling the Italian Renaissance.",
    "Italian city-states like Florence and Venice accumulated commercial wealth from Mediterranean trade — financing patronage of artists (Medici of Florence) and funding humanist scholarship that recovered classical Greek and Roman texts.",
    [{q:"Italian Renaissance period?",a:"~1300-1600"},{q:"Medici role?",a:"Florence banking + art patronage"},{q:"Humanism?",a:"Focus on individual, classical learning, secular themes"},{q:"Italy political?",a:"Fragmented city-states"},{q:"Venice wealth source?",a:"Mediterranean trade"}],
  ),
  mk(1, "1.2", "Italian Renaissance",
    "Revival of classical learning, humanism, individualism. Artists: Leonardo, Michelangelo, Raphael. Machiavelli's The Prince.",
    ["Classical revival.", "Humanism: Petrarch, Pico della Mirandola.", "Artists: Leonardo, Michelangelo, Raphael.", "Machiavelli's The Prince (1513).", "Patronage (Medici, papal).", "Individual potential celebrated."],
    "SAQ: Briefly explain ONE achievement of the Italian Renaissance.",
    "Machiavelli's The Prince (1513) broke from medieval moral political theory by arguing rulers should be guided by realpolitik ('ends justify means') rather than Christian ethics — a founding text of modern political science.",
    [{q:"Machiavelli work?",a:"The Prince (1513)"},{q:"Leonardo works?",a:"Last Supper, Mona Lisa"},{q:"Michelangelo?",a:"David, Sistine Chapel"},{q:"Humanist?",a:"Petrarch (father), Erasmus"},{q:"Perspective in art?",a:"Linear perspective (Brunelleschi)"}],
  ),
  mk(1, "1.3", "Northern Renaissance",
    "Christian humanism (Erasmus), printing, Flemish art (van Eyck, Dürer). More northern European focus.",
    ["Christian humanism: Erasmus, Thomas More.", "Printing (Gutenberg 1450s).", "Flemish painters: van Eyck, Dürer.", "Utopia (Thomas More 1516).", "More religious emphasis than Italian Renaissance.", "Spread to France, Germany, England, Netherlands."],
    "SAQ: Briefly explain ONE feature of the Northern Renaissance.",
    "Erasmus (Dutch humanist) synthesized classical learning with Christian ethics, seeking to reform the Church from within. His In Praise of Folly (1509) satirized clerical corruption and paved intellectual ground for the Reformation — though Erasmus himself remained Catholic.",
    [{q:"Erasmus?",a:"Dutch Christian humanist"},{q:"Thomas More?",a:"English humanist (Utopia 1516)"},{q:"Dürer?",a:"German Renaissance artist"},{q:"Christian humanism?",a:"Combined classical + Christian ethics"},{q:"Brueghel?",a:"Flemish painter"}],
  ),
  mk(1, "1.4", "Printing",
    "Gutenberg's press (1450s) revolutionized learning, spread Reformation, democratized access.",
    ["Gutenberg's moveable type (1450s).", "Print culture spread rapidly.", "Bible printing.", "Pamphlet wars of Reformation.", "Literacy grew.", "Transformed intellectual life."],
    "SAQ: Briefly explain ONE impact of the printing press.",
    "Luther's 95 Theses (1517) spread rapidly through Europe via Gutenberg's printing press — within weeks they had been translated and reprinted across German lands. Without printing, the Reformation likely could not have overwhelmed Catholic authorities so quickly.",
    [{q:"Gutenberg's press?",a:"1450s Germany"},{q:"First major book?",a:"Gutenberg Bible"},{q:"Impact on Reformation?",a:"Enabled rapid spread of Luther's ideas"},{q:"Latin vs vernacular?",a:"Vernacular grew with printing"},{q:"Literacy trend?",a:"Rose sharply post-1500"}],
  ),
  mk(1, "1.5", "New Monarchies",
    "England, France, Spain centralized power c. 1450-1550. Consolidated armies, taxation, legal systems.",
    ["Ferdinand + Isabella unified Spain (1479), Reconquista (1492).", "Henry VII (Tudor) ended Wars of Roses.", "Louis XI centralized France.", "Increased taxation + standing armies.", "Reduced noble power.", "HRE remained fragmented."],
    "SAQ: Briefly explain ONE feature of New Monarchies.",
    "Ferdinand and Isabella's marriage (1469) unified Spain, completed the Reconquista (1492), and centralized authority through Catholicism (Spanish Inquisition 1478) and strengthened bureaucracy — creating the template for early modern European absolutism.",
    [{q:"Spain unified?",a:"Ferdinand + Isabella (1469)"},{q:"Reconquista complete?",a:"1492"},{q:"England monarch?",a:"Henry VII after Wars of Roses"},{q:"France monarch?",a:"Louis XI"},{q:"HRE status?",a:"Stayed fragmented"}],
  ),
  mk(1, "1.6", "Technology and Exploration",
    "Portuguese caravels, compass, astrolabe. Discovery of Americas (1492), Cape of Good Hope (1488), India (1498).",
    ["Caravel + compass + astrolabe enabled voyages.", "Prince Henry of Portugal (early 15th c.) sponsored exploration.", "Dias: Cape of Good Hope (1488).", "Columbus (1492).", "Da Gama to India (1498).", "Magellan circumnavigation (1519-22)."],
    "SAQ: Briefly explain ONE motive for European exploration.",
    "Ottoman control of Mediterranean trade routes pushed Iberian states to find alternate sea routes to Asian spices — Portugal around Africa (da Gama 1498), Spain westward (Columbus 1492). Religious motivation (spreading Christianity) also played a role.",
    [{q:"Portuguese pioneer?",a:"Prince Henry the Navigator"},{q:"Columbus year?",a:"1492"},{q:"Da Gama to India?",a:"1498"},{q:"Magellan circumnavigation?",a:"1519-22"},{q:"Caravel?",a:"Portuguese ocean ship"}],
  ),
  mk(1, "1.7", "Columbian Exchange, Commercial Revolution, and Mercantilism",
    "Silver flood → Price Revolution. Mercantilism: state-managed trade. Joint-stock companies (VOC 1602).",
    ["Silver from Potosí (1545+) flooded Europe → Price Revolution inflation.", "Columbian Exchange transformed ecology and diets.", "Commercial Revolution: banking, insurance, joint-stock.", "Mercantilism: state-managed export-positive trade.", "VOC (1602), EIC (1600)."],
    "SAQ: Briefly explain ONE economic impact of overseas exploration.",
    "The flood of New World silver (from Potosí after 1545) into Europe caused the 'Price Revolution' — sustained inflation that hurt landlords on fixed rents, enriched merchant classes, and destabilized traditional economies for decades.",
    [{q:"Potosí silver?",a:"1545+ globalized economy"},{q:"Price Revolution?",a:"European inflation from silver"},{q:"Mercantilism?",a:"State-managed export-positive trade"},{q:"VOC?",a:"Dutch East India Company (1602)"},{q:"Joint-stock?",a:"New corporate form"}],
  ),
  mk(1, "1.8", "Causation in the Renaissance and Age of Discovery",
    "Medieval commercial revival + fall of Constantinople (1453) + technology + state competition drove Renaissance + exploration.",
    ["Causes: commercial wealth, classical recovery, printing, technology, state competition.", "Effects: Renaissance culture, Atlantic empires, global trade networks, Reformation background."],
    "LEQ: Evaluate causes of the Age of Exploration.",
    "Economic motives (Asian spices, gold), religious motives (Christianity + anti-Islamic sentiment), political (state competition), and technological (caravel, compass) converged. Ottoman blockade made alternate routes essential; Iberian states, recently unified and religiously crusading, were positioned to act first. Results fundamentally transformed Europe and created the Atlantic World.",
    [{q:"Cause of Renaissance?",a:"Italian commercial wealth + classical recovery + humanism"},{q:"Cause of Exploration?",a:"Ottoman blockade + technology + state competition"},{q:"Effect?",a:"Atlantic empires + global trade + Reformation background"},{q:"Periodization?",a:"1450-1648"},{q:"End marker?",a:"Peace of Westphalia 1648"}],
  ),
  mk(2, "2.1", "Contextualizing 16th- and 17th-Century Challenges and Developments",
    "Reformation + religious wars + scientific revolution + absolutism emerging.",
    ["Protestant Reformation (1517+).", "Catholic Counter-Reformation.", "Religious wars (1540s-1648).", "Scientific Revolution.", "Absolutist states forming.", "Commercial Revolution expanding."],
    "SAQ: Briefly describe ONE challenge of 16th-17th c. Europe.",
    "The Protestant Reformation shattered Catholic unity and unleashed over a century of religious warfare. The Thirty Years War (1618-48) alone killed ~1/3 of German population. Religious conflict reshaped political order until the Peace of Westphalia (1648) established state sovereignty.",
    [{q:"Reformation start?",a:"1517 Luther"},{q:"Peace of Westphalia?",a:"1648"},{q:"Thirty Years War?",a:"1618-48"},{q:"Religious wars period?",a:"1540s-1648"},{q:"Absolutism emerging?",a:"By 17th c."}],
  ),
  mk(2, "2.2", "Luther and the Protestant Reformation",
    "Luther's 95 Theses (1517). Justification by faith, scripture alone. Supported by German princes.",
    ["Luther's 95 Theses (Oct 31, 1517).", "Sola fide, sola scriptura.", "Diet of Worms (1521) declared Luther outlaw.", "Vernacular Bible translation.", "German princes protected Luther for political reasons.", "Peasants' Revolt (1524-25) Luther condemned."],
    "SAQ: Briefly explain ONE cause of the Reformation.",
    "Luther (1517) protested indulgences — Church's sale of pardons — arguing salvation came by faith alone (sola fide), not good works or Church sacraments. His 95 Theses + vernacular Bible translations + printing press support spread rapidly, challenging Catholic Church monopoly on salvation.",
    [{q:"95 Theses year?",a:"1517"},{q:"Luther's core doctrines?",a:"Sola fide, sola scriptura"},{q:"Diet of Worms?",a:"1521"},{q:"Indulgences?",a:"Church pardons Luther attacked"},{q:"Peasants' Revolt?",a:"1524-25"}],
  ),
  mk(2, "2.3", "Protestant Reformation Beyond Germany",
    "Calvin in Geneva (predestination). Zwingli in Zurich. Anglican in England (Henry VIII). Anabaptists radical.",
    ["Zwingli in Zurich (1520s).", "Calvin in Geneva (predestination, Institutes 1536).", "Anglican: Henry VIII (Act of Supremacy 1534) — political break.", "Anabaptists: adult baptism, radical.", "Spread across Europe."],
    "SAQ: Briefly explain ONE form of Protestantism beyond Lutheranism.",
    "Calvinism, founded by John Calvin in Geneva, taught predestination (God has preordained salvation/damnation), rigorous moral discipline, and theocratic government. Spread to Netherlands, Scotland (Presbyterianism), France (Huguenots), New England (Puritans) — reshaping European culture.",
    [{q:"Calvin in?",a:"Geneva"},{q:"Calvin's Institutes?",a:"1536"},{q:"Predestination?",a:"God preordains salvation"},{q:"Henry VIII break?",a:"Act of Supremacy 1534"},{q:"Anabaptists?",a:"Radical reformers, adult baptism"}],
  ),
  mk(2, "2.4", "Wars of Religion",
    "French Wars of Religion (1562-98), Dutch Revolt (1568+), Thirty Years War (1618-48). Peace of Westphalia 1648.",
    ["French Wars of Religion (Huguenots vs. Catholics).", "St. Bartholomew's Day Massacre (1572).", "Edict of Nantes (1598, Henry IV): toleration.", "Dutch Revolt against Spain.", "Thirty Years War (1618-48): began religious, became political.", "Peace of Westphalia (1648): state sovereignty."],
    "SAQ: Briefly explain ONE consequence of religious wars.",
    "The Peace of Westphalia (1648) ended the Thirty Years War and established key principles: state sovereignty, cuius regio eius religio (ruler's religion), and territorial boundaries. It marks the emergence of the modern state system and effectively ended the era of religious wars in Europe.",
    [{q:"French Wars of Religion?",a:"1562-98"},{q:"Edict of Nantes?",a:"1598 Huguenot toleration"},{q:"Thirty Years War?",a:"1618-48"},{q:"Peace of Westphalia?",a:"1648 — state sovereignty"},{q:"St. Bartholomew's Day?",a:"1572 massacre"}],
  ),
  mk(2, "2.5", "The Catholic Reformation",
    "Council of Trent (1545-63), Jesuits (Loyola 1540), Inquisition, Index of Forbidden Books.",
    ["Council of Trent (1545-63) reformed Catholic doctrine.", "Jesuits founded by Loyola (1540) — education, missions.", "Roman Inquisition, Index of Forbidden Books.", "Baroque art served Counter-Reformation.", "Reaffirmed Catholic practices challenged by Protestants."],
    "SAQ: Briefly explain ONE Catholic Reformation response.",
    "The Jesuits (Society of Jesus, 1540), founded by Ignatius Loyola, became the Counter-Reformation's educational and missionary shock troops. They established schools across Europe, reclaimed territories for Catholicism (Poland), and evangelized globally (China, Japan, Americas) — reinvigorating Catholic practice.",
    [{q:"Council of Trent?",a:"1545-63 Catholic reform"},{q:"Jesuits founder?",a:"Ignatius Loyola (1540)"},{q:"Index?",a:"List of forbidden books"},{q:"Baroque art?",a:"Grand, emotional, served Counter-Reformation"},{q:"Jesuits focus?",a:"Education, missions"}],
  ),
  mk(2, "2.6", "16th-Century Society and Politics",
    "Witch hunts, family as economic unit, population growth, inflation. Nobles, peasants, townspeople.",
    ["Witch hunts intensified (1560-1650).", "Population growth until Thirty Years War.", "Three Estates: nobility, clergy, commoners.", "Family = economic unit.", "Women's roles: housewife, childbearing, some trades."],
    "SAQ: Briefly explain ONE feature of 16th-c. society.",
    "European witch hunts intensified between 1560-1650, resulting in ~60,000 executions across Europe — mostly elderly women accused of demonic pacts. Religious anxiety of the Reformation era, economic stress, and misogyny combined to produce this wave of persecution.",
    [{q:"Witch hunts peak?",a:"1560-1650"},{q:"Executions estimate?",a:"~60,000 across Europe"},{q:"Three Estates?",a:"Nobility, clergy, commoners"},{q:"Family as?",a:"Economic unit"},{q:"Primogeniture?",a:"Inheritance to eldest son"}],
  ),
  mk(2, "2.7", "Art of the 16th Century",
    "Mannerism after High Renaissance. Baroque emerged in Counter-Reformation (Caravaggio, Bernini).",
    ["Mannerism: tension, distortion (El Greco, Parmigianino).", "Baroque: dramatic, emotional, grand (Caravaggio, Bernini).", "Baroque served Counter-Reformation propaganda.", "Northern masters: Brueghel, Dürer.", "Protestant art: Rembrandt later, more secular."],
    "SAQ: Briefly explain ONE 16th-17th c. artistic development.",
    "Baroque art (Caravaggio, Bernini) used dramatic lighting, emotional intensity, and grand theatrical compositions to serve Counter-Reformation purposes — making Catholic doctrine emotionally compelling and reasserting the Church's grandeur against Protestant austerity.",
    [{q:"Mannerism?",a:"Post-Renaissance distortion"},{q:"Baroque?",a:"Dramatic, emotional, grand"},{q:"Bernini?",a:"Italian baroque sculptor (St. Peter's)"},{q:"Caravaggio?",a:"Dramatic lighting"},{q:"Counter-Reformation aesthetic?",a:"Baroque"}],
  ),
  mk(2, "2.8", "Causation in the Age of Reformation and the Wars of Religion",
    "Reformation → religious wars → Peace of Westphalia (1648) → state sovereignty.",
    ["Reformation + printing + state competition caused religious wars.", "Effects: state sovereignty at Westphalia, decline of Church political power, religious pluralism in Europe, early modern state system."],
    "LEQ: Evaluate effects of the Protestant Reformation.",
    "Transformative: shattered Christian unity (permanent denominational split), enabled political-religious violence (Thirty Years War ~8M dead), established state sovereignty at Westphalia, promoted literacy via vernacular Bibles, and ultimately forced religious toleration as the only workable solution after century of war.",
    [{q:"Reformation effects?",a:"Religious pluralism, wars, state sovereignty, literacy"},{q:"Westphalia?",a:"1648 state sovereignty"},{q:"Thirty Years War dead?",a:"~8M"},{q:"Periodization?",a:"1450-1648"},{q:"Vernacular Bible impact?",a:"Literacy rose"}],
  ),
  mk(3, "3.1", "Contextualizing State Building",
    "17th-18th c.: absolutism vs constitutionalism. Louis XIV vs. English Glorious Revolution.",
    ["Absolutism: Louis XIV 'L'état, c'est moi.'", "Constitutionalism: English response.", "Peace of Westphalia (1648) established state system.", "Scientific Revolution.", "Commercial expansion."],
    "SAQ: Briefly describe ONE political development c. 1648-1815.",
    "France's Louis XIV exemplified absolutism — centralized power at Versailles, suppressed nobility, weakened parlements, revoked Edict of Nantes (1685). England's Glorious Revolution (1688) took the opposite path: parliamentary supremacy, Bill of Rights, limits on monarchs.",
    [{q:"Absolutism exemplar?",a:"Louis XIV of France"},{q:"Constitutionalism exemplar?",a:"Post-1688 England"},{q:"Westphalia year?",a:"1648"},{q:"Period dates?",a:"1648-1815"},{q:"Scientific Revolution?",a:"Contemporary"}],
  ),
  mk(3, "3.2", "The English Civil War and the Glorious Revolution",
    "Parliament vs. Charles I → Civil War (1642-49) → Cromwell republic → Restoration (1660) → Glorious Revolution (1688).",
    ["Charles I vs Parliament.", "Civil War (1642-49).", "Charles I executed (1649).", "Cromwell's Commonwealth.", "Restoration (1660, Charles II).", "James II Catholic.", "Glorious Revolution (1688): William + Mary invited.", "Bill of Rights (1689)."],
    "SAQ: Briefly explain ONE effect of the Glorious Revolution.",
    "The 1688 Glorious Revolution established parliamentary supremacy: Parliament invited William and Mary, who accepted the English Bill of Rights (1689) limiting royal power. This cemented constitutional monarchy as the English model — inspiring Locke's Two Treatises (1689) and later revolutions.",
    [{q:"English Civil War?",a:"1642-49"},{q:"Charles I executed?",a:"1649"},{q:"Restoration year?",a:"1660"},{q:"Glorious Revolution?",a:"1688"},{q:"English Bill of Rights?",a:"1689"}],
  ),
  mk(3, "3.3", "Continuities and Changes to Economic Practice and Development",
    "Enclosure, agricultural revolution, wage labor, commercial capitalism. Economic crises drove change.",
    ["Enclosure movement: common lands privatized.", "Agricultural Revolution: rotations, new crops.", "Cottage industry (putting-out system).", "Wage labor grew.", "Commercial capitalism expanded.", "17th-c. general crisis."],
    "SAQ: Briefly explain ONE economic change c. 1648-1815.",
    "The British Agricultural Revolution (late 17th-18th c.) improved yields through crop rotation (Townshend's four-field), enclosure, selective breeding, and seed drills — enabling population growth that later supported industrialization.",
    [{q:"Enclosure?",a:"Privatization of common lands"},{q:"Agricultural Revolution?",a:"Rotations + enclosure + new crops"},{q:"Cottage industry?",a:"Rural textile production"},{q:"17th-c. crisis?",a:"Economic/political disruption mid-century"},{q:"Four-field rotation?",a:"Townshend"}],
  ),
  mk(3, "3.4", "Economic Development and Mercantilism",
    "Mercantilist state-managed trade. Commercial rivalries. Colbert in France.",
    ["Mercantilism: state-managed positive trade balance.", "Colbert in France built colonial empire, canals, roads.", "Navigation Acts (England 1651+).", "Chartered companies (VOC, EIC).", "Commercial wars."],
    "SAQ: Briefly explain ONE mercantilist policy.",
    "Colbert, Louis XIV's minister, actively developed French industry (Gobelins tapestry factories), built canals (Canal du Midi), expanded colonies, and pursued export-positive trade — the classic mercantilist program. Though France's economy grew, it couldn't match British commercial and industrial leadership.",
    [{q:"Mercantilism?",a:"State-managed positive trade balance"},{q:"Colbert?",a:"French finance minister"},{q:"Navigation Acts?",a:"English 1651+"},{q:"VOC?",a:"Dutch East India Company"},{q:"EIC?",a:"English East India Company"}],
  ),
  mk(3, "3.5", "The Dutch Golden Age",
    "Netherlands: republic, commercial dominance, VOC, tulip mania, religious tolerance.",
    ["Dutch Republic: Northern Netherlands independence (1648).", "VOC dominated spice trade.", "Bank of Amsterdam, stock exchange.", "Religious tolerance.", "Rembrandt, Vermeer painting.", "Tulip mania (1630s) early speculation bubble."],
    "SAQ: Briefly explain ONE feature of the Dutch Golden Age.",
    "Amsterdam became the world's first modern financial capital with the Bank of Amsterdam (1609) and the world's first stock exchange. Combined with Dutch commercial dominance through the VOC, this made the Netherlands disproportionately wealthy for a small republican state.",
    [{q:"Dutch independence?",a:"1648 from Spain"},{q:"VOC dominated?",a:"Spice trade"},{q:"Bank of Amsterdam?",a:"1609"},{q:"Dutch artists?",a:"Rembrandt, Vermeer"},{q:"Tulip mania?",a:"1630s speculative bubble"}],
  ),
  mk(3, "3.6", "Balance of Power",
    "European diplomacy prevented hegemony. Louis XIV's wars, War of Spanish Succession (1701-14), Treaty of Utrecht.",
    ["Louis XIV's wars (1667-1715).", "War of Spanish Succession (1701-14).", "Treaty of Utrecht (1713): Bourbon kept Spain but not France.", "Balance of power doctrine.", "Diplomatic alliances."],
    "SAQ: Briefly explain ONE balance of power conflict.",
    "The War of Spanish Succession (1701-14) pitted France + Spain vs. Grand Alliance (Austria, England, Netherlands). At the Treaty of Utrecht (1713), Louis XIV's grandson kept Spanish throne but France and Spain could never unite — preserving European balance of power against French hegemony.",
    [{q:"War of Spanish Succession?",a:"1701-14"},{q:"Treaty of Utrecht?",a:"1713"},{q:"Louis XIV wars?",a:"1667-1715"},{q:"Balance of power?",a:"Diplomatic equilibrium"},{q:"Grand Alliance?",a:"Anti-French coalition"}],
  ),
  mk(3, "3.7", "Absolutist Approaches to Power",
    "Louis XIV (Versailles, divine right). Habsburgs. Prussia (Hohenzollerns). Russia (Peter the Great).",
    ["Louis XIV (r. 1643-1715): Versailles, divine right, no Estates-General.", "Habsburg Austria: multi-ethnic empire.", "Prussia: Hohenzollerns, military state.", "Russia: Peter the Great (r. 1682-1725) westernized.", "Revoked Edict of Nantes (1685).", "Frederick William, Frederick II continued Prussia."],
    "SAQ: Briefly explain ONE absolutist monarch.",
    "Peter the Great (r. 1682-1725) westernized Russia by reforming the military on European lines, building St. Petersburg as a new capital (1703), modernizing bureaucracy (Table of Ranks 1722), and forcing the Orthodox Church under state control (Holy Synod 1721) — making Russia a major European power.",
    [{q:"Louis XIV reigned?",a:"1643-1715"},{q:"Peter the Great?",a:"1682-1725"},{q:"Versailles purpose?",a:"Controlled nobility, displayed power"},{q:"St. Petersburg?",a:"Founded 1703"},{q:"Revoked Edict of Nantes?",a:"1685 (expelled Huguenots)"}],
  ),
  mk(3, "3.8", "Comparison in the Age of Absolutism and Constitutionalism",
    "Compare Louis XIV absolutism vs English constitutionalism. Different paths to state-building.",
    ["France: absolutism + Catholicism + centralized fiscal-military state.", "England: constitutional monarchy + Parliament supremacy + Bill of Rights.", "Both strong states but different power distribution."],
    "LEQ: Compare absolutism and constitutionalism c. 1648-1815.",
    "Both built powerful states but distributed power differently. Louis XIV concentrated authority at Versailles: no Estates-General, subjugated nobility, unified religion. England's Glorious Revolution (1688) gave Parliament supremacy, created Bill of Rights (1689), and established that monarchs couldn't rule without parliamentary consent. Both models strengthened their states; England's eventually outperformed France commercially.",
    [{q:"France model?",a:"Absolutism"},{q:"England model?",a:"Constitutional monarchy"},{q:"Louis XIV location?",a:"Versailles"},{q:"Parliamentary supremacy?",a:"Post-1688 England"},{q:"Both?",a:"Strong states, different power distribution"}],
  ),
  mk(4, "4.1", "Contextualizing the Scientific Revolution and the Enlightenment",
    "Scientific method + Enlightenment rationality reshaped European thought.",
    ["Scientific Revolution: 16th-17th c.", "Enlightenment: 18th c.", "Reason, observation, natural laws.", "Challenged religious authority.", "Enlightenment ideas → revolutions."],
    "SAQ: Briefly describe ONE feature of 17th-18th c. intellectual life.",
    "The Scientific Revolution produced a new empirical methodology — Bacon's inductive method + Galileo's experimentation + Newton's mathematical physics (Principia 1687) unified heaven and earth under natural laws. This shifted European intellectual authority from Church + classical sources to observation and reason.",
    [{q:"Scientific Revolution period?",a:"16th-17th c."},{q:"Enlightenment period?",a:"18th c."},{q:"Method shift?",a:"To empirical observation + reason"},{q:"Newton's Principia?",a:"1687"},{q:"Enlightenment impact?",a:"Revolutions + modern thought"}],
  ),
  mk(4, "4.2", "The Scientific Revolution",
    "Copernicus (1543 heliocentric), Galileo, Kepler, Newton. Scientific method (Bacon).",
    ["Copernicus: heliocentric theory (De Revolutionibus 1543).", "Galileo: telescope observations, trial (1633).", "Kepler: planetary laws.", "Newton: Principia (1687), gravity + three laws.", "Bacon: inductive method.", "Descartes: rationalism, Cartesian doubt."],
    "SAQ: Briefly explain ONE Scientific Revolution advance.",
    "Isaac Newton's Principia Mathematica (1687) unified terrestrial and celestial mechanics under three laws of motion and universal gravitation. It became the template for scientific explanation — reducing natural phenomena to mathematical laws, a framework that dominated physics until Einstein (1905).",
    [{q:"Copernicus year?",a:"1543"},{q:"Galileo trial?",a:"1633"},{q:"Kepler?",a:"Planetary laws"},{q:"Newton's Principia?",a:"1687"},{q:"Bacon's method?",a:"Inductive (empirical)"}],
  ),
  mk(4, "4.3", "The Enlightenment",
    "Applied reason to society. Locke, Voltaire, Rousseau, Montesquieu, Diderot. Influenced revolutions.",
    ["Locke: natural rights, social contract.", "Voltaire: religious toleration.", "Montesquieu: separation of powers (1748).", "Rousseau: The Social Contract (1762).", "Diderot's Encyclopédie.", "Influenced American (1776), French (1789), Haitian (1791) revolutions."],
    "SAQ: Briefly explain ONE Enlightenment thinker's influence.",
    "Montesquieu's Spirit of the Laws (1748) argued that political liberty required separation of powers among legislative, executive, and judicial branches to prevent tyranny. This directly shaped the US Constitution (1787) and influenced constitution-writing worldwide.",
    [{q:"Locke's idea?",a:"Natural rights + social contract"},{q:"Montesquieu's work?",a:"Spirit of the Laws 1748"},{q:"Rousseau's work?",a:"Social Contract 1762"},{q:"Diderot's work?",a:"Encyclopédie"},{q:"Voltaire's causes?",a:"Religious toleration, free speech"}],
  ),
  mk(4, "4.4", "18th-Century Society and Demographics",
    "Population growth, family changes, consumer culture, Agricultural Revolution, urbanization.",
    ["Population grew (new foods, improved hygiene).", "Family size declining in some classes.", "Consumer revolution: tea, coffee, sugar, tobacco.", "Urbanization.", "Agricultural improvements."],
    "SAQ: Briefly explain ONE demographic change.",
    "European population grew from ~120M in 1700 to ~190M in 1800, driven by agricultural improvements (new crops like potato, better rotations), declining famine mortality, and improved hygiene — setting the stage for Industrial Revolution labor supply.",
    [{q:"Population 1700 vs 1800?",a:"~120M → 190M"},{q:"Potato impact?",a:"Major calorie source"},{q:"Consumer revolution?",a:"Tea, coffee, sugar, tobacco"},{q:"Urbanization trend?",a:"Cities grew"},{q:"Agricultural Revolution?",a:"Enabled pop growth"}],
  ),
  mk(4, "4.5", "18th-Century Culture and Arts",
    "Rococo (early), Neoclassicism (later). Musical high classical era: Bach, Mozart, Haydn.",
    ["Rococo: light, elegant, aristocratic (Fragonard, Watteau).", "Neoclassicism: classical austerity (David, after 1770).", "Music: Bach, Mozart, Haydn classical period.", "Salons: intellectual gatherings (often hosted by women).", "Novel emerged as form."],
    "SAQ: Briefly explain ONE 18th-c. cultural development.",
    "Salons hosted by wealthy women (Madame Geoffrin, Madame du Deffand) became central to French Enlightenment — gathering philosophes, aristocrats, and visiting thinkers to debate ideas. Women's salons created a sphere where Enlightenment thought circulated and developed.",
    [{q:"Rococo style?",a:"Light, aristocratic"},{q:"Neoclassicism?",a:"Classical austerity (later)"},{q:"Mozart, Haydn?",a:"Classical music"},{q:"Salons?",a:"Enlightenment gatherings"},{q:"Novel?",a:"New literary form"}],
  ),
  mk(4, "4.6", "Enlightened and Other Approaches to Power",
    "Enlightened despots: Frederick the Great, Catherine the Great, Joseph II — reformed but kept autocracy.",
    ["Frederick II of Prussia (r. 1740-86): religious toleration, legal reform.", "Catherine the Great (r. 1762-96): westernization, territorial expansion.", "Joseph II of Austria (r. 1765-90): radical reforms, mostly reversed.", "Reforms from above.", "Did NOT democratize."],
    "SAQ: Briefly explain ONE Enlightened Despot reform.",
    "Frederick the Great of Prussia (r. 1740-86) promoted religious toleration, abolished torture, reformed the legal code, and patronized Voltaire — while maintaining absolute power and expanding Prussia militarily. 'Enlightened' in attitude but never in structure.",
    [{q:"Frederick the Great?",a:"Prussia 1740-86"},{q:"Catherine the Great?",a:"Russia 1762-96"},{q:"Joseph II?",a:"Austria 1765-90"},{q:"Enlightened despot?",a:"Absolutist who applied Enlightenment ideas"},{q:"Did they democratize?",a:"No"}],
  ),
  mk(4, "4.7", "Causation in the Age of the Scientific Revolution and the Enlightenment",
    "Science + Enlightenment fed revolutions + modern thought.",
    ["Cause: Scientific Revolution's empirical method.", "Cause: Classical recovery + printing + commercial wealth.", "Effect: Enlightenment rationality.", "Effect: Political revolutions.", "Effect: Modern science, political theory, economics."],
    "LEQ: Evaluate effects of the Scientific Revolution and Enlightenment.",
    "Radically transformed European thought: empirical method replaced scholastic authority; natural law replaced divine right as political justification; secular reason became intellectual currency; Enlightenment ideas directly shaped the American, French, and Haitian Revolutions. The modern world — constitutional democracy, market economics, scientific method — draws its intellectual foundations from this era.",
    [{q:"Scientific method?",a:"Empirical observation + mathematical laws"},{q:"Enlightenment frame?",a:"Reason applied to society"},{q:"Revolutions inspired?",a:"American, French, Haitian"},{q:"Modern economics?",a:"Adam Smith (1776)"},{q:"Newton's legacy?",a:"Template for scientific theory"}],
  ),
  mk(5, "5.1", "Contextualizing 18th-Century States",
    "Rising commerce + colonial empires + state competition → Seven Years' War + revolutions.",
    ["Commercial expansion.", "Colonial rivalries (esp. Britain vs France).", "Seven Years' War (1756-63).", "American Revolution (1775-83).", "French Revolution (1789-99)."],
    "SAQ: Briefly explain ONE 18th-c. state development.",
    "Britain's victory over France in the Seven Years' War (1756-63) gave Britain Canada, India, and dominance in the Atlantic trade — but war debt led to colonial taxation that sparked American Revolution (1775-83). French war debt also triggered fiscal crisis → French Revolution (1789).",
    [{q:"Seven Years' War?",a:"1756-63"},{q:"Winner?",a:"Britain over France"},{q:"American Revolution?",a:"1775-83"},{q:"French Revolution?",a:"1789-99"},{q:"Period dates?",a:"~1648-1815"}],
  ),
  mk(5, "5.2", "The Rise of Global Markets",
    "Atlantic slave trade, commercial revolution, coffeehouses, consumer culture.",
    ["Atlantic slave trade ~12M Africans.", "Sugar, tobacco, cotton global commodities.", "Coffeehouses: public sphere.", "Financial Revolution (Bank of England 1694).", "Consumer goods spread."],
    "SAQ: Briefly explain ONE feature of the 18th-c. global economy.",
    "The Atlantic slave trade reached its peak in the 18th century (~6 million Africans transported that century alone). It integrated European finance, African labor, American plantations, and global markets — making sugar, tobacco, and cotton mass commodities that transformed European consumer culture.",
    [{q:"Atlantic slave trade peak?",a:"18th century"},{q:"Sugar source?",a:"Caribbean plantations"},{q:"Bank of England?",a:"1694"},{q:"Coffeehouses?",a:"Public sphere for discussion"},{q:"Consumer culture rose?",a:"Yes (sugar, tea, tobacco spread)"}],
  ),
  mk(5, "5.3", "Britain's Ascendency",
    "Britain emerged as leading power after 1763: commerce, navy, colonial empire.",
    ["Seven Years' War (1763) victory.", "Dominated Atlantic + Indian Ocean trade.", "Navigation Acts.", "Financial Revolution.", "Early Industrial Revolution.", "Lost American colonies (1783) but still dominant."],
    "SAQ: Briefly explain ONE factor in Britain's ascendance.",
    "Britain's combination of naval dominance, Bank of England (1694) financing, Atlantic colonial empire, and Agricultural Revolution positioned it for Industrial Revolution leadership. Even losing American colonies (1783) didn't dethrone Britain, which expanded in India, Africa, and the Pacific.",
    [{q:"Seven Years' War winner?",a:"Britain"},{q:"Bank of England?",a:"1694"},{q:"Navigation Acts?",a:"Regulated colonial trade for Britain"},{q:"Lost American colonies?",a:"1783"},{q:"Industrial Revolution start?",a:"Britain c. 1760"}],
  ),
  mk(5, "5.4", "The French Revolution",
    "Estates-General 1789 → National Assembly → Bastille → Declaration → Terror → Napoleon.",
    ["Fiscal crisis from war debt.", "Estates-General called 1789.", "Third Estate → National Assembly.", "Bastille stormed (July 14, 1789).", "Declaration of Rights of Man.", "Reign of Terror (1793-94) Robespierre.", "Napoleon rose."],
    "SAQ: Briefly explain ONE cause of the French Revolution.",
    "France's fiscal crisis, deepened by Seven Years' War and American War debts, forced Louis XVI to call Estates-General in 1789 — the first since 1614. Third Estate's demands for voting by head (not estate) led to formation of National Assembly (June 17, 1789) and revolutionary momentum.",
    [{q:"Estates-General called?",a:"1789 (first since 1614)"},{q:"Bastille stormed?",a:"July 14, 1789"},{q:"Declaration year?",a:"Aug 1789"},{q:"Reign of Terror?",a:"1793-94 (Robespierre)"},{q:"Sans-culottes?",a:"Radical Parisian workers"}],
  ),
  mk(5, "5.5", "The French Revolution's Effects",
    "Abolished feudalism, declared rights, spread across Europe. Terror, Napoleon, eventual restoration.",
    ["Feudalism abolished (Aug 1789).", "Declaration of Rights of Man.", "Constitutional monarchy → republic (1792).", "Louis XVI executed (1793).", "Women marched on Versailles; but women's rights limited.", "Napoleon's rise and fall."],
    "SAQ: Briefly explain ONE effect of the French Revolution.",
    "The French Revolution abolished feudalism (Aug 1789), issued the Declaration of Rights of Man, and executed Louis XVI (1793). Its principles — liberty, equality, fraternity — spread across Europe via Napoleonic conquests, transforming legal systems, abolishing serfdom, and inspiring future revolutions even after Bourbon restoration (1815).",
    [{q:"Feudalism abolished?",a:"Aug 1789"},{q:"Louis XVI executed?",a:"1793"},{q:"Reign of Terror deaths?",a:"~17,000 by guillotine"},{q:"Napoleonic Code?",a:"Spread revolutionary legal principles"},{q:"Olympe de Gouges?",a:"Women's rights advocate"}],
  ),
  mk(5, "5.6", "Napoleon's Rise, Dominance, and Defeat",
    "Consul 1799 → Emperor 1804. Conquered most of Europe. Defeated at Russia (1812) and Waterloo (1815).",
    ["Consul 1799 coup.", "Emperor 1804.", "Code Napoléon (1804).", "Continental System vs Britain.", "Invasion of Russia (1812) disaster.", "Waterloo (1815) final defeat.", "Spread revolutionary ideals."],
    "SAQ: Briefly explain ONE lasting legacy of Napoleon.",
    "The Code Napoléon (1804) codified revolutionary legal principles — equality before law, property rights, religious toleration, civil marriage — and was imposed across conquered Europe. It replaced patchwork feudal law with a coherent civil code; modified versions still form the basis of many European legal systems.",
    [{q:"Napoleon emperor?",a:"1804"},{q:"Code Napoléon?",a:"1804 civil code"},{q:"Russia invasion?",a:"1812 disaster"},{q:"Waterloo?",a:"June 1815"},{q:"Bourbon restoration?",a:"1814/1815"}],
  ),
  mk(5, "5.7", "The Congress of Vienna",
    "1815 post-Napoleonic settlement. Restored legitimate monarchs, balance of power, century of limited European wars.",
    ["Congress of Vienna (1814-15): Metternich, Castlereagh, Talleyrand.", "Restored legitimate monarchs.", "Balance of power.", "Conservative order.", "Largely held until 1914."],
    "SAQ: Briefly explain ONE achievement of the Congress of Vienna.",
    "Metternich (Austria) led the Congress of Vienna (1814-15) in restoring conservative monarchy, balancing major powers to prevent any single state's dominance, and containing revolutionary ideals. This Concert of Europe largely kept general European war at bay for a century — until 1914.",
    [{q:"Congress of Vienna?",a:"1814-15"},{q:"Metternich?",a:"Austrian leader"},{q:"Goals?",a:"Restore monarchs, balance power, contain revolution"},{q:"Concert of Europe?",a:"Conservative alliance post-1815"},{q:"Long peace until?",a:"1914"}],
  ),
  mk(5, "5.8", "Romanticism",
    "Early 19th c. reaction against Enlightenment rationalism. Emotion, nature, nationalism.",
    ["Reaction vs. Enlightenment reason.", "Emphasis on emotion, individual, nature, past.", "Writers: Wordsworth, Byron, Goethe.", "Artists: Friedrich, Delacroix, Turner.", "Music: Beethoven, later Wagner.", "Fed nationalism."],
    "SAQ: Briefly explain ONE feature of Romanticism.",
    "Romantic artists and writers (Wordsworth, Byron, Friedrich) reacted against Enlightenment rationalism by celebrating emotion, nature, the medieval past, and folk culture. This fed nationalism (interest in folk stories as national heritage) and inspired 1830s-40s revolutions.",
    [{q:"Romanticism reacted against?",a:"Enlightenment rationalism"},{q:"Romantic emphasis?",a:"Emotion, nature, past, folk"},{q:"Romantic writers?",a:"Wordsworth, Byron, Goethe"},{q:"Delacroix painting?",a:"Liberty Leading the People"},{q:"Beethoven?",a:"Bridged Classical and Romantic music"}],
  ),
  mk(5, "5.9", "Continuity and Change in the 18th Century",
    "Change: revolutions, Enlightenment. Continuities: social hierarchy, slavery (until 1807 UK).",
    ["Change: Enlightenment, political revolutions, Industrial Revolution beginning.", "Continuities: social hierarchy, patriarchy, slavery (until abolition)."],
    "LEQ: Evaluate changes in European political thought c. 1648-1815.",
    "Revolutionary: absolutism challenged by constitutionalism (1688), then by Enlightenment + American Revolution + French Revolution (1789). Natural rights and popular sovereignty replaced divine right as legitimating principles. Even after 1815 Restoration, revolutionary ideals persisted — erupting again in 1830, 1848, and beyond.",
    [{q:"18th c. key change?",a:"Revolutions spread natural-rights ideology"},{q:"Continuities?",a:"Social hierarchy, slavery (until 1807-88 abolition)"},{q:"Glorious Revolution?",a:"1688"},{q:"French Revolution?",a:"1789-99"},{q:"Restoration?",a:"1815"}],
  ),
  mk(6, "6.1", "Contextualizing Industrialization and Its Origins and Effects",
    "Industrial Revolution c. 1780-1914. Started Britain, spread continental Europe, transformed society.",
    ["Britain first (~1780).", "Spread to Belgium, France, Germany.", "2nd Industrial Revolution (1870+): steel, electricity.", "Vast social changes.", "Urbanization, class formation."],
    "SAQ: Briefly describe ONE feature of 19th-c. industrialization.",
    "Britain's combination of coal, capital from Atlantic trade, colonial markets, Agricultural Revolution surplus labor, stable government, and scientific culture enabled the world's first industrial economy. By 1850, Britain produced ~half of global coal and iron output.",
    [{q:"Industrial Revolution start?",a:"Britain c. 1780"},{q:"Spread order?",a:"Belgium → France → Germany → US → Russia/Japan"},{q:"2nd Industrial Revolution?",a:"1870+ steel, electricity"},{q:"Period dates?",a:"1815-1914"},{q:"Transformation?",a:"Economy + society + politics"}],
  ),
  mk(6, "6.2", "The Industrial Revolution Begins in Britain",
    "Coal, iron, textiles, steam. Watt's engine (1769), factory system, railway (1830s).",
    ["Textile innovations: jenny, mule, power loom.", "Watt's steam engine (1769).", "Iron + coal proximity.", "Factory system.", "Railway (1830s): Stephenson's Rocket.", "Great Divergence begins."],
    "SAQ: Briefly explain ONE factor in British industrialization.",
    "The Agricultural Revolution freed rural labor for factories while producing food surplus to feed urban workers; Atlantic trade capital financed machinery; proximity of coal and iron made industry efficient; stable government and science culture enabled innovation — all combining to produce Britain's unique early industrialization.",
    [{q:"Watt's engine?",a:"1769 separate condenser"},{q:"Spinning jenny?",a:"Hargreaves 1764"},{q:"Railway era start?",a:"1830s"},{q:"Britain's share of coal 1850?",a:"~50% world"},{q:"Factory system?",a:"Centralized wage labor"}],
  ),
  mk(6, "6.3", "Spread of Industry Throughout Europe",
    "Belgium first continental. France slower. Germany via Zollverein (1834) and post-1871 unification.",
    ["Belgium: first continental industrial (1830s).", "France: slower, smaller coal.", "Germany: Zollverein (1834) customs union → rapid industrialization post-1871.", "Italy lagged.", "Russia late and state-led."],
    "SAQ: Briefly explain ONE continental European industrialization.",
    "Germany's Zollverein customs union (1834) eliminated internal tariffs, linked German states economically, and accelerated railroad construction — laying economic foundation for 1871 political unification and rapid industrialization that made Germany Britain's chief economic rival by 1900.",
    [{q:"Belgium industrialized?",a:"1830s (first continental)"},{q:"Zollverein?",a:"1834 German customs union"},{q:"Germany unified?",a:"1871 (Bismarck)"},{q:"Russia late industrializer?",a:"State-led under Witte (1890s)"},{q:"France vs Britain?",a:"Slower industrial growth"}],
  ),
  mk(6, "6.4", "Second Industrial Revolution",
    "1870-1914. Steel (Bessemer 1856), electricity, chemicals, internal combustion, mass production.",
    ["Bessemer steel (1856).", "Electricity: Edison, Tesla, Siemens.", "Chemicals: dyes, fertilizers.", "Internal combustion: Otto, Benz.", "Telegraph (1844), telephone (1876), radio (1895).", "Mass production (Ford 1913)."],
    "SAQ: Briefly explain ONE Second Industrial Revolution technology.",
    "The Bessemer steel process (1856) made steel cheap and plentiful, enabling railroads, skyscrapers, ships, and weaponry at unprecedented scale. Germany's Krupp and America's Carnegie Steel became industrial giants, transforming the economic map.",
    [{q:"Bessemer process year?",a:"1856"},{q:"Edison invention?",a:"Light bulb (1879)"},{q:"Otto engine?",a:"1876"},{q:"Ford assembly line?",a:"1913"},{q:"Germany vs Britain?",a:"Germany leading 2nd Industrial Revolution"}],
  ),
  mk(6, "6.5", "Social Effects of Industrialization",
    "New classes: industrial bourgeoisie, proletariat, middle class. Urbanization, family changes.",
    ["New classes: industrial bourgeoisie (factory owners), proletariat (workers), middle class (professionals).", "Urbanization.", "Separate spheres ideology.", "Working conditions brutal.", "Child labor.", "Demographic transition."],
    "SAQ: Briefly explain ONE social effect of industrialization.",
    "Industrialization created a new working class (proletariat) that lived in crowded urban slums and labored 12-16 hour factory days — documented by Engels in The Condition of the Working Class in England (1845). These conditions fueled socialist movements, labor unions, and eventual reform legislation.",
    [{q:"New classes?",a:"Bourgeoisie, middle class, proletariat"},{q:"Urban slums documented?",a:"Engels 1845"},{q:"Separate spheres?",a:"Middle-class gender ideology"},{q:"Child labor?",a:"Common until regulations"},{q:"Demographic transition?",a:"Declining birth/death rates"}],
  ),
  mk(6, "6.6", "The Concert of Europe and European Conservatism",
    "Post-1815 conservative order: Metternich, Holy Alliance, suppression of liberalism and nationalism.",
    ["Concert of Europe: Austria, Prussia, Russia, Britain, later France.", "Metternich's leadership.", "Holy Alliance (1815) suppressed revolutions.", "Carlsbad Decrees (1819) in Germany.", "Conservative ideology dominant."],
    "SAQ: Briefly explain ONE feature of post-Napoleonic conservatism.",
    "Metternich's Concert of Europe used the Holy Alliance (Austria, Prussia, Russia — later France) to suppress liberal and nationalist uprisings across Europe — intervening in Spain (1823), Italy (1821), and resisting 1830 and 1848 revolutions. Conservative restoration largely held until 1848.",
    [{q:"Concert of Europe?",a:"Post-1815 conservative alliance"},{q:"Metternich?",a:"Austrian chancellor, leader"},{q:"Holy Alliance?",a:"Austria, Prussia, Russia (1815)"},{q:"Carlsbad Decrees?",a:"1819 Austria censorship in Germany"},{q:"Conservative goal?",a:"Maintain legitimate monarchy"}],
  ),
  mk(6, "6.7", "Reactions and Revolutions",
    "1830, 1848 revolutions. Liberal + nationalist demands. Mostly suppressed but seeds planted.",
    ["1830 French Revolution: July Days, Louis Philippe.", "Belgium independent (1830).", "1848 Year of Revolutions: Paris, Vienna, Berlin, Italian states.", "Liberal + nationalist demands.", "Short-term failure, long-term change."],
    "SAQ: Briefly explain ONE 19th-c. revolution.",
    "The 1848 Revolutions spread across Europe: liberals and nationalists demanded constitutional government, end of absolutism, national unification. Most were suppressed within a year, but they ended serfdom in Austria-Hungary, led to Second French Republic, and seeded later unification of Germany (1871) and Italy (1871).",
    [{q:"July Revolution year?",a:"1830 (France)"},{q:"Louis Philippe?",a:"'Citizen King' of France 1830-48"},{q:"1848 revolutions?",a:"Europe-wide liberal-nationalist uprising"},{q:"Outcome?",a:"Mostly suppressed short-term"},{q:"Long-term effects?",a:"Eventual unification + constitutional govts"}],
  ),
  mk(6, "6.8", "Ideologies of Change and Reform Movements",
    "Liberalism, nationalism, socialism, Marxism emerged as major modern ideologies.",
    ["Liberalism: individual rights, constitutional govt, free market.", "Nationalism: national self-determination.", "Conservatism: preserve order.", "Socialism: Owen, Fourier utopian; Marx Communist Manifesto (1848).", "Feminism emerging."],
    "SAQ: Briefly explain ONE 19th-c. ideology.",
    "Marxism, articulated in Marx and Engels' Communist Manifesto (1848) and Marx's Capital (1867), framed history as class struggle. It predicted workers (proletariat) would overthrow capitalists (bourgeoisie) to establish a classless society. It became globally influential — inspiring socialist parties, the Russian Revolution (1917), and Cold War politics.",
    [{q:"Liberalism principles?",a:"Individual rights + constitutional govt + market economy"},{q:"Nationalism?",a:"National self-determination"},{q:"Marxism founder?",a:"Karl Marx (with Engels)"},{q:"Communist Manifesto?",a:"1848"},{q:"Capital?",a:"Marx 1867"}],
  ),
  mk(6, "6.9", "19th-Century Social Reform",
    "Unions, factory acts, public health. Women's suffrage movement. Abolition.",
    ["Factory Acts (Britain 1833+) limited child labor, hours.", "Public Health Act (1848).", "Education Acts.", "Unions legalized (Britain 1871).", "Women's suffrage: NZ 1893, Australia 1902, UK 1918/28, US 1920.", "Abolition: UK slave trade 1807, slavery 1833."],
    "SAQ: Briefly explain ONE 19th-c. reform.",
    "Britain abolished the slave trade (1807) and slavery throughout the empire (1833), ending centuries of Atlantic slavery. The abolition movement — led by figures like William Wilberforce, Frederick Douglass, and formerly enslaved activists — combined religious, humanitarian, and economic arguments to achieve one of the century's major moral achievements.",
    [{q:"Factory Acts?",a:"Britain 1833+ protect workers"},{q:"British slave trade abolished?",a:"1807"},{q:"British slavery abolished?",a:"1833"},{q:"NZ women's suffrage?",a:"1893 (first)"},{q:"Trade unions legal?",a:"Britain 1871"}],
  ),
  mk(6, "6.10", "Institutional Responses and Reform",
    "Bismarck's social insurance (1883-89). Utilitarian reforms (Bentham, Mill).",
    ["Bismarck welfare (1883-89): health, accident, old-age insurance.", "Bentham + Mill utilitarianism.", "Progressive taxation.", "Compulsory education.", "Public health."],
    "SAQ: Briefly explain ONE institutional reform.",
    "Bismarck's social insurance (1883-89) established the world's first welfare state in Germany — offering health, accident, and old-age insurance. Aimed at undercutting socialist appeal (Bismarck's Anti-Socialist Laws 1878-90 banned socialist organizations), it set the template for 20th-century welfare states globally.",
    [{q:"Bismarck welfare years?",a:"1883-89"},{q:"Bentham?",a:"Utilitarianism ('greatest good for greatest number')"},{q:"Mill's work?",a:"On Liberty (1859)"},{q:"Compulsory education?",a:"Various European states 1870s+"},{q:"Why Bismarck welfare?",a:"Undercut socialism"}],
  ),
  mk(6, "6.11", "Causation in the Age of Industrialization",
    "Industrialization caused urbanization + class formation + imperialism + ideologies. Feedbacks shaped society.",
    ["Cause: Industrial Revolution.", "Effect: urbanization, new classes.", "Effect: reform and socialism.", "Effect: imperialism (raw materials + markets).", "Effect: World War I (1914)."],
    "LEQ: Evaluate industrialization's effects on European society.",
    "Revolutionary: created industrial bourgeoisie and proletariat; produced unprecedented wealth but also slums and class conflict; fueled nationalism, socialism, feminism, and imperialism. Urbanization transformed demographics. Reform gradually improved working conditions but inequality remained. Industrial economies fueled arms race and colonial competition that produced WWI (1914).",
    [{q:"Industrialization caused?",a:"Urbanization, class formation, ideologies, imperialism"},{q:"Working class response?",a:"Unions, socialism, Marxism"},{q:"Bourgeoisie rise?",a:"Factory owners, new elite"},{q:"Reform movements?",a:"Factory acts, suffrage, abolition"},{q:"Culminated in?",a:"WWI (1914)"}],
  ),
  mk(7, "7.1", "Contextualizing 19th-Century Perspectives and Political Developments",
    "Nationalism + new imperialism + Darwinism + modernism transformed Europe.",
    ["Nationalism rising: Italian (1871), German (1871) unification.", "Imperialism: Scramble for Africa (1880-1914).", "Darwin's Origin (1859) + Social Darwinism.", "Modernism in culture.", "Alliance system set stage for WWI."],
    "SAQ: Briefly describe ONE late 19th-c. political development.",
    "German unification (1871) under Bismarck's leadership made Germany Europe's strongest industrial-military power, upsetting the Concert of Europe balance. Germany's rise — combined with the alliance system that grew to manage it — created the geopolitical conditions for World War I.",
    [{q:"Italian unification?",a:"1871 (Cavour, Garibaldi)"},{q:"German unification?",a:"1871 (Bismarck)"},{q:"Darwin's Origin?",a:"1859"},{q:"Scramble for Africa?",a:"1880-1914"},{q:"Period dates?",a:"1815-1914"}],
  ),
  mk(7, "7.2", "Nationalism",
    "National self-determination ideology. Italian, German unification. Ethnic tensions in Austria-Hungary, Balkans.",
    ["Nationalism: shared language, history, culture, territory.", "Italian unification under Cavour + Garibaldi (1871).", "German unification under Bismarck (1871).", "Austria-Hungary multi-ethnic.", "Balkans 'powder keg.'"],
    "SAQ: Briefly explain ONE example of nationalism.",
    "German unification (1871) emerged from Bismarck's wars with Denmark (1864), Austria (1866), and France (1870-71). Proclamation of the German Empire at Versailles (Jan 18, 1871) unified most German-speaking states under Prussian leadership — and fundamentally upset European balance of power.",
    [{q:"Italian unification year?",a:"1871"},{q:"Italian leaders?",a:"Cavour + Garibaldi"},{q:"German unification year?",a:"1871"},{q:"German leader?",a:"Bismarck"},{q:"Austria-Hungary?",a:"Multi-ethnic empire"}],
  ),
  mk(7, "7.3", "National Unification and Diplomatic Tensions",
    "German unification shifted balance. Bismarck's alliances; after his dismissal (1890) system became unstable.",
    ["Bismarck's alliances: League of Three Emperors, Dual Alliance (1879), Triple Alliance (1882).", "Isolated France.", "Kaiser Wilhelm II dismissed Bismarck (1890).", "Franco-Russian Alliance (1894).", "Triple Entente (1907): France, Russia, UK."],
    "SAQ: Briefly explain ONE diplomatic tension c. 1870-1914.",
    "After Wilhelm II dismissed Bismarck (1890), Germany pursued a more aggressive foreign policy (Weltpolitik) that frightened Britain — sparking Anglo-German naval race. Franco-Russian Alliance (1894) + Anglo-French Entente (1904) + Triple Entente (1907) encircled Germany with hostile alliances, setting stage for WWI.",
    [{q:"Bismarck dismissed?",a:"1890 by Wilhelm II"},{q:"Triple Alliance?",a:"1882: Germany + Austria-Hungary + Italy"},{q:"Franco-Russian alliance?",a:"1894"},{q:"Triple Entente?",a:"1907: France + Russia + UK"},{q:"Weltpolitik?",a:"German aggressive world policy"}],
  ),
  mk(7, "7.4", "Darwinism, Social Darwinism",
    "Origin of Species (1859) revolutionized biology. Social Darwinism (Spencer) misapplied to nations/races.",
    ["Darwin's Origin (1859): natural selection.", "Descent of Man (1871).", "Social Darwinism: Spencer, Sumner.", "Justified imperialism + racism + laissez-faire.", "Eugenics movement (Galton)."],
    "SAQ: Briefly explain ONE impact of Darwinism.",
    "Social Darwinism misapplied natural selection to human societies, claiming European dominance proved 'racial fitness' and justifying imperialism, unrestricted capitalism, and later eugenics. Used to oppose social reform (dismissing poor as 'unfit') and rationalize colonial conquest — a dangerous distortion of Darwin's biological theory.",
    [{q:"Darwin's Origin?",a:"1859"},{q:"Natural selection?",a:"Differential survival/reproduction → evolution"},{q:"Social Darwinism?",a:"Misapplied Darwin to society"},{q:"Eugenics?",a:"Galton's 'improved breeding' movement"},{q:"Used to justify?",a:"Imperialism, racism, laissez-faire"}],
  ),
  mk(7, "7.5", "The Age of Progress and Modernity",
    "Faith in progress tempered by anxieties. Urban life, mass press, modernism in arts.",
    ["Urbanization continued.", "Mass press + popular culture.", "Modernism in arts: Impressionism → Cubism.", "Music: Wagner, Debussy, Stravinsky.", "Freud's psychoanalysis.", "Einstein's relativity (1905)."],
    "SAQ: Briefly explain ONE modernist development.",
    "Albert Einstein's 1905 papers revolutionized physics with special relativity and the photoelectric effect (Nobel 1921), challenging Newtonian certainties. Combined with Freud's psychoanalysis and atonal music, science and art together undermined 19th-century faith in rational progress.",
    [{q:"Impressionism?",a:"Monet, Manet (late 1860s+)"},{q:"Cubism?",a:"Picasso, Braque (1907+)"},{q:"Freud?",a:"Psychoanalysis (unconscious)"},{q:"Einstein's special relativity?",a:"1905"},{q:"Wagner?",a:"Late Romantic opera"}],
  ),
  mk(7, "7.6", "New Imperialism: Motivations and Methods",
    "1870-1914. Europeans colonized 80%+ of Africa and most of Asia. Economic + strategic + ideological motives.",
    ["Motivations: markets, raw materials, strategic (Suez 1869), Social Darwinism.", "Methods: Maxim gun (1884), quinine, steamships.", "Berlin Conference (1884-85) partitioned Africa.", "Indirect (British) vs direct (French) rule.", "Settler colonies (Algeria, S Africa)."],
    "SAQ: Briefly explain ONE motivation for European imperialism.",
    "Industrial Europe's demand for raw materials (rubber from Congo, cotton from Egypt, tin from Malaya) and captive markets drove imperial expansion after 1870. Hobson (1902) argued surplus capital sought overseas investment outlets; Lenin (1916) extended this to 'imperialism as late capitalism.'",
    [{q:"Berlin Conference?",a:"1884-85 partitioned Africa"},{q:"Maxim gun?",a:"1884 colonial military advantage"},{q:"Suez Canal?",a:"1869"},{q:"Indirect rule?",a:"British (co-opt local chiefs)"},{q:"Direct rule?",a:"French (French administrators)"}],
  ),
  mk(7, "7.7", "Imperialism's Global Effects",
    "Colonial economies, famines, resistance movements, migration, deepening racial hierarchies.",
    ["Colonial economies extractive.", "Indian famines (1876-78, 1896-1900) killed tens of millions.", "Resistance: Zulu, Boxer, Mahdist, Ghost Dance.", "Migration: ~30M Asian indentured, ~50M European.", "Imperial racial hierarchies."],
    "SAQ: Briefly explain ONE effect of European imperialism.",
    "Indian famines under British rule (1876-78, 1896-1900) killed tens of millions partly due to free-market export policies that continued grain exports during scarcity. These famines, along with deindustrialization of Indian textiles, illustrated the devastating impact of colonial extraction.",
    [{q:"Indian famines under British?",a:"1876-78, 1896-1900 (tens of millions dead)"},{q:"Maji Maji?",a:"German E. Africa rebellion 1905-07"},{q:"Amritsar Massacre?",a:"1919 (British troops in India)"},{q:"Boxer Rebellion?",a:"China 1899-1901"},{q:"Imperial migration?",a:"~80M global 1820-1914"}],
  ),
  mk(7, "7.8", "19th-Century Culture and Arts",
    "Realism (Dickens, Zola). Impressionism → post-Impressionism → Cubism. Music: Wagner, Debussy.",
    ["Realism: Dickens, Flaubert, Zola.", "Impressionism (Monet, Manet).", "Post-Impressionism (van Gogh, Cezanne).", "Cubism (1907+, Picasso).", "Music: Wagner, late Romantic → modernist (Debussy, Stravinsky).", "Naturalism."],
    "SAQ: Briefly explain ONE 19th-c. artistic movement.",
    "Impressionism (1860s-80s, Monet, Manet, Renoir) broke with academic tradition by painting en plein air, capturing fleeting light and color rather than formal composition. It scandalized critics at first but revolutionized European painting — paving way for Post-Impressionism and early 20th-century modernism.",
    [{q:"Realism?",a:"Dickens, Zola, Flaubert"},{q:"Impressionism?",a:"Monet, Manet, Renoir"},{q:"Van Gogh?",a:"Post-Impressionist"},{q:"Cubism pioneer?",a:"Picasso (1907+)"},{q:"Wagner?",a:"Late Romantic opera (Ring cycle)"}],
  ),
  mk(7, "7.9", "Causation in 19th-Century Perspectives and Political Developments",
    "Industrialization + nationalism + imperialism fed each other. Alliance system → WWI.",
    ["Industrialization + nationalism + imperialism interlinked.", "German unification (1871) upset balance.", "Alliance system managed, then failed.", "Scramble for Africa + Asian imperialism.", "Set stage for WWI (1914)."],
    "LEQ: Evaluate causes of WWI.",
    "Multi-causal: M.A.I.N. — Militarism (Anglo-German naval race), Alliances (Triple Alliance vs Triple Entente), Imperialism (colonial competition), Nationalism (Pan-Slavism, Pan-Germanism). Balkan Wars (1912-13) destabilized SE Europe. Assassination of Franz Ferdinand (June 28, 1914) triggered rapid mobilization cascade — the alliance system turned local crisis into general war within a week.",
    [{q:"M.A.I.N.?",a:"Militarism, Alliances, Imperialism, Nationalism"},{q:"Triple Alliance?",a:"Germany, Austria-Hungary, Italy"},{q:"Triple Entente?",a:"France, Russia, UK"},{q:"Balkan Wars?",a:"1912-13"},{q:"Sarajevo?",a:"June 28, 1914"}],
  ),
  mk(8, "8.1", "Contextualizing 20th-Century Global Conflicts",
    "WWI, Russian Revolution, Versailles, Depression, WWII, Holocaust, atomic age.",
    ["WWI 1914-18.", "Russian Revolution 1917.", "Versailles (1919) reshaped map.", "Depression + fascism.", "WWII 1939-45.", "Holocaust (6M Jews).", "Atomic bombs (1945).", "Period dates: 1914-present."],
    "SAQ: Briefly describe ONE feature of 20th-c. global conflict.",
    "The 20th century's global conflicts killed an estimated 100+ million people — including ~17M in WWI, ~70-85M in WWII (including 6M Jews in the Holocaust), and tens of millions more in subsequent wars and genocides — driven by industrialized mass killing, totalitarian ideologies, and superpower rivalries.",
    [{q:"WWI?",a:"1914-18"},{q:"Russian Revolution?",a:"1917"},{q:"Versailles?",a:"1919"},{q:"WWII?",a:"1939-45"},{q:"Period?",a:"1914-present"}],
  ),
  mk(8, "8.2", "World War I",
    "1914-18. Industrial total war. Trench stalemate, massive casualties. US entry 1917. Armistice Nov 1918.",
    ["Triggered by Sarajevo (June 28, 1914).", "Western Front trench stalemate.", "Verdun (1916), Somme (1916) massive casualties.", "Russian collapse → Brest-Litovsk 1918.", "US entered April 1917.", "Armistice Nov 11, 1918.", "~17M dead."],
    "SAQ: Briefly explain ONE feature of WWI.",
    "The Western Front settled into trench stalemate after the First Battle of the Marne (Sept 1914). Industrial weapons (machine guns, poison gas, barbed wire) made frontal assaults catastrophic — Verdun (1916) and the Somme (1916) each produced ~1M casualties for negligible territorial gains.",
    [{q:"Sarajevo date?",a:"June 28, 1914"},{q:"Verdun?",a:"1916 (~700K casualties)"},{q:"Somme?",a:"1916 (~1M casualties)"},{q:"US entered?",a:"April 1917"},{q:"Armistice?",a:"Nov 11, 1918"}],
  ),
  mk(8, "8.3", "The Russian Revolution and Its Effects",
    "Feb 1917 (tsar abdicated) → Oct 1917 (Bolsheviks) → Civil War (1918-22) → USSR (1922).",
    ["Feb Revolution: tsar abdicated.", "Provisional Government.", "Lenin returned on German train (April 1917).", "Oct Revolution: Bolshevik coup.", "Brest-Litovsk 1918: ceded huge territory.", "Civil War 1918-22.", "USSR 1922."],
    "SAQ: Briefly explain ONE effect of the Russian Revolution.",
    "The Bolshevik victory in the Russian Civil War (1918-22) established the Soviet Union (1922) — the world's first Marxist state. It became the model for 20th-century communist movements and set up the Cold War ideological division between liberal capitalism and state socialism.",
    [{q:"Feb Revolution?",a:"March 1917 (tsar abdicates)"},{q:"Oct Revolution?",a:"Nov 1917 (Bolsheviks)"},{q:"Lenin return?",a:"April 1917"},{q:"Treaty of Brest-Litovsk?",a:"March 1918"},{q:"USSR founded?",a:"1922"}],
  ),
  mk(8, "8.4", "Versailles Conference and Peace Settlement",
    "Versailles (June 1919) harsh on Germany. Mandate system. Self-determination not for colonized.",
    ["Big Four: Wilson, Clemenceau, Lloyd George, Orlando.", "War Guilt Clause + reparations ($33B).", "Territorial losses + military limits.", "League of Nations (US rejected).", "Mandate system.", "Ignored colonial self-determination."],
    "SAQ: Briefly explain ONE provision of the Treaty of Versailles.",
    "Article 231 (War Guilt Clause) forced Germany to accept sole responsibility for WWI, enabling massive reparations ($33B = ~$400B today). Combined with territorial losses and military restrictions, it humiliated Germany and fueled political instability (Weimar Republic) — seeding conditions for Nazi rise.",
    [{q:"Versailles year?",a:"1919"},{q:"War Guilt Clause?",a:"Article 231"},{q:"Reparations?",a:"$33B"},{q:"League of Nations?",a:"US Senate rejected"},{q:"Mandates?",a:"Ottoman + German colonies to victors"}],
  ),
  mk(8, "8.5", "Global Economic Crisis",
    "1929 Wall Street Crash → Great Depression (1929-39). Mass unemployment, failed democracies.",
    ["Wall Street Crash Oct 1929.", "Unemployment ~25% US, ~30% Germany.", "Smoot-Hawley Tariff (1930).", "Gold standard abandoned.", "Delegitimized liberal democracies.", "Enabled Nazi rise (Hitler chancellor Jan 1933)."],
    "SAQ: Briefly explain ONE effect of the Great Depression.",
    "Mass unemployment in Germany (~30% at peak) delegitimized the Weimar Republic and enabled Nazi Party rise. Nazi Party grew from insignificant to second-largest in 1932 elections; Hindenburg appointed Hitler chancellor January 1933. Without the Depression, Nazi takeover would have been much less likely.",
    [{q:"Wall Street Crash?",a:"Oct 1929"},{q:"Peak US unemployment?",a:"~25% (1933)"},{q:"Peak German unemployment?",a:"~30%"},{q:"Hitler chancellor?",a:"Jan 1933"},{q:"Smoot-Hawley?",a:"1930 US tariff"}],
  ),
  mk(8, "8.6", "Fascism and Totalitarianism",
    "Mussolini (1922), Hitler (1933), Franco (1939). Single-party, leader cult, extreme nationalism, terror.",
    ["Mussolini's March on Rome (1922).", "Hitler chancellor Jan 1933.", "Franco won Spanish Civil War (1939).", "Stalin's Soviet Union.", "Features: single party, leader cult, terror, corporatism, extreme nationalism.", "Used mass propaganda."],
    "SAQ: Briefly explain ONE feature of fascism.",
    "Fascism combined extreme nationalism with totalitarian one-party state — glorifying the nation (or race) above individuals, concentrating power in a charismatic leader (Mussolini, Hitler), suppressing opposition through terror, mobilizing society through propaganda and mass rallies, and rejecting both liberal democracy and Marxism.",
    [{q:"Mussolini's rise?",a:"March on Rome 1922"},{q:"Hitler chancellor?",a:"Jan 1933"},{q:"Franco's victory?",a:"1939 Spanish Civil War"},{q:"Totalitarian features?",a:"Single party, leader cult, terror, mass propaganda"},{q:"Fascism vs communism?",a:"Far-right vs far-left totalitarianism"}],
  ),
  mk(8, "8.7", "Europe During the Interwar Period",
    "Weimar Germany, Great Depression, appeasement, Hitler's expansion.",
    ["Weimar Republic weak from start.", "German hyperinflation (1923).", "Locarno Treaties (1925) briefly stabilized.", "Depression undermined everything.", "Hitler's rearmament, Rhineland (1936), Anschluss (1938), Munich (1938).", "Appeasement failed."],
    "SAQ: Briefly explain ONE interwar European development.",
    "The failure of appeasement at Munich (Sept 1938) — where Britain and France allowed Hitler's annexation of the Sudetenland — emboldened Nazi expansion. After Hitler dismembered Czechoslovakia (March 1939) and invaded Poland (Sept 1, 1939), Britain and France finally declared war.",
    [{q:"Weimar Republic?",a:"Post-WWI German democracy"},{q:"Hyperinflation year?",a:"1923"},{q:"Rhineland remilitarization?",a:"1936"},{q:"Anschluss?",a:"March 1938"},{q:"Munich Agreement?",a:"Sept 1938"}],
  ),
  mk(8, "8.8", "World War II",
    "1939-45. Hitler's rapid conquests → Barbarossa (1941) → Stalingrad → D-Day → Berlin. Atomic bombs ended Pacific war.",
    ["Sept 1, 1939: Hitler invaded Poland.", "Blitzkrieg conquered France (1940).", "Battle of Britain.", "Operation Barbarossa (June 1941) vs USSR.", "Stalingrad (1942-43) turning point.", "D-Day (June 6, 1944).", "Berlin (May 1945).", "Hiroshima/Nagasaki (Aug 1945)."],
    "SAQ: Briefly explain ONE turning point in WWII.",
    "The Battle of Stalingrad (Aug 1942-Feb 1943) destroyed the German 6th Army and marked the decisive turning point on the Eastern Front. Combined with the Battle of Midway in the Pacific (June 1942) and El Alamein in N. Africa (Oct 1942), it showed Axis powers could not sustain their conquests.",
    [{q:"WWII start?",a:"Sept 1, 1939 Poland invasion"},{q:"France fell?",a:"June 1940"},{q:"Barbarossa?",a:"June 1941 USSR invasion"},{q:"Stalingrad?",a:"1942-43"},{q:"D-Day?",a:"June 6, 1944"}],
  ),
  mk(8, "8.9", "The Holocaust",
    "Nazi murder of 6M Jews + millions of others. Industrialized genocide in death camps.",
    ["Nuremberg Laws (1935).", "Kristallnacht (Nov 1938).", "Einsatzgruppen mobile killing units in USSR.", "Wannsee Conference (Jan 1942): coordinated 'Final Solution.'", "Death camps: Auschwitz, Treblinka, Sobibor.", "~6M Jews + Roma, disabled, Soviet POWs killed."],
    "SAQ: Briefly explain ONE feature of the Holocaust.",
    "The Wannsee Conference (Jan 1942) coordinated the 'Final Solution' — systematic extermination of European Jews. Death camps like Auschwitz-Birkenau used gas chambers and crematoria to murder ~1.1 million at Auschwitz alone. The Holocaust represented industrialized genocide at unprecedented scale.",
    [{q:"Nuremberg Laws?",a:"1935 stripped Jewish citizenship"},{q:"Kristallnacht?",a:"Nov 1938"},{q:"Wannsee Conference?",a:"Jan 1942 coordinated Final Solution"},{q:"Auschwitz deaths?",a:"~1.1M"},{q:"Holocaust Jewish dead?",a:"~6M"}],
  ),
  mk(8, "8.10", "20th-Century Cultural, Intellectual, and Artistic Developments",
    "Modernism, existentialism, rise of mass media, post-war disillusionment.",
    ["Modernism: Picasso, Joyce, Eliot.", "Existentialism (Sartre, Camus).", "Post-WWII disillusionment.", "Mass media: radio, film, later TV.", "Abstract expressionism.", "Postmodernism later."],
    "SAQ: Briefly explain ONE 20th-c. intellectual development.",
    "Existentialism (Sartre, Camus) responded to WWII devastation with the claim that existence precedes essence — humans must create meaning through their choices in a morally indifferent universe. It shaped post-war European thought and cultural criticism.",
    [{q:"Modernist writers?",a:"Joyce, Eliot, Kafka"},{q:"Existentialism leaders?",a:"Sartre, Camus"},{q:"Post-war mood?",a:"Disillusionment after fascism + war"},{q:"Mass media?",a:"Radio, film, TV"},{q:"Postmodernism?",a:"Later 20th c."}],
  ),
  mk(8, "8.11", "Causation in Global Conflict",
    "WWI + Versailles + Depression + ideologies → WWII. Ultimate continuity: industrial mass warfare.",
    ["WWI alliance system + mobilization → general war.", "Versailles humiliated Germany.", "Depression enabled fascism.", "Appeasement emboldened Hitler.", "Industrial weapons + ideologies → mass killing."],
    "LEQ: Compare causes of WWI and WWII.",
    "Both arose from nationalism, industrial military capacity, alliances, and great-power competition. WWI was triggered by alliance-system miscalculation after Sarajevo (1914). WWII was driven by revisionist ideological powers (Nazi Germany, Fascist Italy, Militarist Japan) seeking to overturn Versailles order. Great Depression enabled fascist rise; Appeasement accelerated it. Both wars' mass casualties reflected industrial total war's devastating capacity.",
    [{q:"WWI cause?",a:"Alliance + mobilization + Balkans"},{q:"WWII cause?",a:"Revisionist powers + Depression + appeasement"},{q:"WWI dead?",a:"~17M"},{q:"WWII dead?",a:"~70-85M"},{q:"Common thread?",a:"Industrial mass warfare"}],
  ),
  mk(9, "9.1", "Contextualizing Cold War and Contemporary Europe",
    "Post-1945 Europe devastated. Bipolar Cold War. Decolonization. European integration. End of Cold War 1989-91.",
    ["1945: Europe economically + politically devastated.", "Cold War bipolar (NATO vs Warsaw Pact).", "Decolonization lost empires.", "EEC (1957) → EU (1993).", "Cold War ended 1989-91.", "Post-Cold War: expansion, populism."],
    "SAQ: Briefly describe ONE feature of post-WWII Europe.",
    "The European Economic Community (EEC, 1957) began European integration with France, West Germany, Italy, Benelux — seeking to bind former enemies economically to prevent another war. Evolved into European Union (1993) with common currency (Euro 1999) — the most successful supranational project.",
    [{q:"Post-WWII Europe?",a:"Devastated, rebuilt with Marshall Plan"},{q:"EEC?",a:"1957"},{q:"EU?",a:"1993"},{q:"Cold War end?",a:"1989-91"},{q:"Euro?",a:"1999"}],
  ),
  mk(9, "9.2", "Rebuilding Europe",
    "Marshall Plan (1948-52), economic miracles, welfare state expansion, nationalized industries.",
    ["Marshall Plan (1948-52): ~$13B to Western Europe.", "West German economic miracle (Wirtschaftswunder).", "French 'Trente Glorieuses' (1945-75).", "Welfare states expanded (Beveridge in UK, Erhard in Germany).", "Mixed economies common."],
    "SAQ: Briefly explain ONE aspect of post-WWII European rebuilding.",
    "The Marshall Plan (1948-52) provided ~$13B to rebuild Western Europe, restore industrial production, and prevent communist takeovers. It succeeded spectacularly: W. Europe recovered by mid-1950s and enjoyed unprecedented prosperity through the 1970s (Trente Glorieuses in France, Wirtschaftswunder in Germany).",
    [{q:"Marshall Plan?",a:"1948-52, ~$13B to W Europe"},{q:"German miracle?",a:"Wirtschaftswunder"},{q:"French term?",a:"Trente Glorieuses (1945-75)"},{q:"British welfare?",a:"NHS 1948"},{q:"Why Marshall Plan?",a:"Recovery + anti-communist containment"}],
  ),
  mk(9, "9.3", "The Cold War",
    "1945-91 bipolar conflict. Key events: Berlin Blockade, NATO, Korean War, Cuban Missile Crisis, Vietnam, détente, Reagan.",
    ["Truman Doctrine (1947), Marshall Plan (1948).", "Berlin Blockade/Airlift (1948-49).", "NATO (1949), Warsaw Pact (1955).", "Korean War (1950-53).", "Cuban Missile Crisis (1962).", "Détente 1970s.", "Reagan's 'evil empire.'"],
    "SAQ: Briefly explain ONE Cold War event in Europe.",
    "The Berlin Blockade (1948-49) saw Stalin cut off Western access to Berlin; the US/UK airlift (~275K flights) supplied the city for ~11 months until Stalin backed down. It demonstrated Western resolve and hardened the division of Europe, leading to NATO (1949) and West Germany's creation.",
    [{q:"Truman Doctrine?",a:"1947"},{q:"Berlin Airlift?",a:"1948-49"},{q:"NATO?",a:"1949"},{q:"Warsaw Pact?",a:"1955"},{q:"Berlin Wall built?",a:"1961"}],
  ),
  mk(9, "9.4", "Two Europes, Two Blocs",
    "West: liberal democracies + market economies. East: Soviet satellites with communist governments.",
    ["NATO vs Warsaw Pact.", "Iron Curtain divided.", "West: liberal democracy + market + NATO.", "East: one-party communist + planned economy + Warsaw Pact.", "Satellites: Poland, East Germany, Czechoslovakia, Hungary, Romania, Bulgaria."],
    "SAQ: Briefly explain ONE difference between Eastern and Western blocs.",
    "Western Europe built liberal democracies with market economies (or mixed economies with welfare states) within NATO. Eastern Europe lived under one-party communist rule with planned economies in the Warsaw Pact. Living standards diverged sharply, with the West far exceeding the East by 1989.",
    [{q:"Iron Curtain?",a:"Cold War European divide"},{q:"Western bloc?",a:"NATO + liberal democracies"},{q:"Eastern bloc?",a:"Warsaw Pact + communist satellites"},{q:"Soviet satellites?",a:"Poland, E. Germany, Czech, Hungary, Romania, Bulgaria"},{q:"Living standards?",a:"West >> East by 1989"}],
  ),
  mk(9, "9.5", "Postwar Nationalism, Ethnic Conflict, and Atrocities",
    "Yugoslav Wars (1991-99), Bosnia genocide (Srebrenica 1995), Northern Ireland Troubles.",
    ["Yugoslav Wars (1991-99).", "Bosnia-Herzegovina war (1992-95): ethnic cleansing.", "Srebrenica massacre (July 1995): ~8,000 Bosniak men killed.", "Kosovo War (1998-99).", "Northern Ireland Troubles."],
    "SAQ: Briefly explain ONE post-Cold War European atrocity.",
    "The Srebrenica massacre (July 1995) saw Bosnian Serb forces kill ~8,000 Bosniak (Muslim) men and boys — the worst atrocity in Europe since WWII. It exposed limits of UN peacekeeping and international response, and led to NATO intervention and eventual Dayton Accords (Nov 1995) ending the Bosnian War.",
    [{q:"Yugoslav Wars?",a:"1991-99"},{q:"Srebrenica?",a:"July 1995 ~8,000 dead"},{q:"Kosovo War?",a:"1998-99"},{q:"Dayton Accords?",a:"Nov 1995"},{q:"N Ireland Troubles?",a:"1968-98 sectarian"}],
  ),
  mk(9, "9.6", "Contemporary Western Democracies",
    "Welfare states, civil rights expansion, political realignments, populism rise.",
    ["Expanded welfare states.", "Women's rights, LGBTQ+ rights.", "Immigration debates.", "Center-left (Labour, SPD, socialist) and center-right (Christian Democrats).", "Populism rising 2010s (Brexit, AfD, Le Pen, Italy)."],
    "SAQ: Briefly explain ONE development in Western democracy.",
    "Western European democracies expanded civil rights through the late 20th century: decriminalization of homosexuality, marriage equality (Netherlands first 2001), abortion rights, women's workforce participation. Immigration debates and populist movements (Brexit 2016, AfD rise in Germany) complicated this trajectory in 2010s-20s.",
    [{q:"Postwar dominant parties?",a:"Center-left + center-right"},{q:"Marriage equality first?",a:"Netherlands 2001"},{q:"Brexit referendum?",a:"June 2016"},{q:"Populism rising?",a:"2010s"},{q:"Welfare state expansion?",a:"1945-80s"}],
  ),
  mk(9, "9.7", "The Fall of Communism",
    "Soviet stagnation + Gorbachev + Polish Solidarity + 1989 revolutions → USSR dissolved Dec 1991.",
    ["Gorbachev (1985+): glasnost, perestroika.", "Polish Solidarity (1980+).", "Hungary opened border (May 1989).", "Berlin Wall fell Nov 9, 1989.", "Velvet Revolution (Czech, Nov 1989).", "Ceaușescu executed Dec 1989.", "USSR dissolved Dec 25, 1991."],
    "SAQ: Briefly explain ONE event in the fall of communism.",
    "The Berlin Wall fell on November 9, 1989 when East German authorities, overwhelmed by protests, effectively announced open travel. Within weeks, E. German communism collapsed; by 1990 Germany had reunified. The fall of the Wall was a symbol of the broader collapse of communism across Eastern Europe.",
    [{q:"Solidarity founded?",a:"Poland 1980"},{q:"Gorbachev?",a:"Soviet reformer 1985-91"},{q:"Berlin Wall fell?",a:"Nov 9, 1989"},{q:"Velvet Revolution?",a:"Nov 1989 Czechoslovakia"},{q:"USSR dissolved?",a:"Dec 25, 1991"}],
  ),
  mk(9, "9.8", "20th-Century Feminism",
    "First wave (suffrage, early 20th c.). Second wave (1960s-70s). Third wave later.",
    ["First wave: suffrage, early 20th c.", "Women got vote: UK 1918 (limited)/1928, US 1920, France 1944, Switzerland 1971.", "Second wave (1960s-70s): equal pay, reproductive rights, workplace.", "Simone de Beauvoir, The Second Sex (1949).", "Third wave later: intersectionality."],
    "SAQ: Briefly explain ONE 20th-c. feminist achievement.",
    "Simone de Beauvoir's The Second Sex (1949) argued that 'one is not born, but rather becomes, a woman' — positioning gender as socially constructed rather than biological destiny. Foundational text for second-wave feminism, which achieved equal pay laws, reproductive rights, and workplace access in the 1960s-70s.",
    [{q:"First wave?",a:"Suffrage (early 20th c.)"},{q:"Second wave?",a:"1960s-70s equal pay, reproductive rights"},{q:"Beauvoir's Second Sex?",a:"1949"},{q:"French women vote?",a:"1944"},{q:"Swiss women vote?",a:"1971"}],
  ),
  mk(9, "9.9", "Decolonization",
    "European empires collapsed 1945-75. Mostly peacefully (India 1947, Ghana 1957) or violently (Algeria 1962, Vietnam 1954-75).",
    ["India (1947) Gandhi's nonviolence.", "Indonesia (1949).", "Ghana (1957) Nkrumah.", "'Year of Africa' (1960).", "Algerian War (1954-62) bloody.", "Portuguese colonies 1974-75.", "Suez Crisis (1956) symbolic end of European Middle East power."],
    "SAQ: Briefly explain ONE decolonization of European empires.",
    "The Algerian War of Independence (1954-62) was a brutal anti-colonial war against French settler colonialism. FLN waged urban bombings and rural insurgency; France responded with widespread torture. ~500,000-1.5 million Algerians died before France withdrew — demonstrating high costs of holding settler colonies.",
    [{q:"India independence?",a:"1947 (Partition)"},{q:"Ghana independence?",a:"1957"},{q:"Year of Africa?",a:"1960"},{q:"Algerian War?",a:"1954-62"},{q:"Suez Crisis?",a:"1956"}],
  ),
  mk(9, "9.10", "The European Union",
    "1957 EEC → 1993 EU → 1999 Euro. Supranational integration. Expanded after Cold War.",
    ["1951 ECSC, 1957 EEC, 1993 EU, 1999 Eurozone.", "Single market + common currency for most.", "Eastern expansion post-1989.", "Brexit (2016 referendum, 2020 departure).", "Ongoing tensions over sovereignty."],
    "SAQ: Briefly explain ONE stage of European integration.",
    "The Maastricht Treaty (1993) transformed the EEC into the European Union, creating common citizenship, common foreign policy, and paving the way for the Euro (1999) and Schengen free movement. It represented the most ambitious supranational integration in history — though Brexit (2020) showed its limits.",
    [{q:"EEC year?",a:"1957"},{q:"EU year?",a:"1993 (Maastricht)"},{q:"Eurozone?",a:"1999"},{q:"Eastern expansion?",a:"2004 (10 new members)"},{q:"Brexit?",a:"2020 departure"}],
  ),
  mk(9, "9.11", "Migration and Immigration",
    "Postwar labor migration to W. Europe. Guest workers. Asylum seekers. Integration debates.",
    ["Postwar labor shortages + guest worker programs.", "Turks to Germany, N. Africans to France, S. Asians to UK.", "Former colonial subjects.", "Family reunification changed demographics.", "Asylum seekers + refugees 2010s+.", "Integration and political backlash."],
    "SAQ: Briefly explain ONE postwar European migration.",
    "West Germany's Gastarbeiter (guest worker) program recruited millions of Turkish workers from 1960s. Intended as temporary, most settled permanently, bringing families and creating multicultural Germany. Integration has been contested — fueling both cultural diversity and political backlash (AfD, PEGIDA).",
    [{q:"Guest workers?",a:"Postwar temporary labor migration"},{q:"Turkish to Germany?",a:"From 1960s"},{q:"Postcolonial migrants?",a:"Former empires' subjects"},{q:"2015 refugee crisis?",a:"Syrian + others to Europe"},{q:"Political backlash?",a:"AfD, FN, Lega Nord"}],
  ),
  mk(9, "9.12", "Technology",
    "Computer revolution, internet, mobile phones, biotechnology. Europe significant but not leading.",
    ["Computing: initially US-dominated.", "ARPANET (1969) → WWW (Berners-Lee, CERN 1989).", "Mobile phones widespread 1990s+.", "Biotech: human genome (2003).", "Europe strong in some areas (CERN, Airbus).", "Digital divide initially."],
    "SAQ: Briefly explain ONE late 20th-c. technological development in Europe.",
    "Tim Berners-Lee invented the World Wide Web (1989) at CERN in Geneva, making the internet accessible to ordinary users through hyperlinks and browsers. Though the internet's core infrastructure was largely American, the web democratized digital access globally.",
    [{q:"WWW invented?",a:"1989 (Berners-Lee at CERN)"},{q:"Human Genome Project?",a:"2003 completion"},{q:"Airbus?",a:"European aerospace consortium"},{q:"Mobile phone spread?",a:"1990s-2000s"},{q:"CERN?",a:"European physics research center"}],
  ),
  mk(9, "9.13", "Globalization",
    "Post-1945 + post-1989 acceleration. Integration via trade, finance, migration, information.",
    ["WTO (1995).", "Financial globalization.", "Outsourcing.", "European + Chinese + Asian tiger industrialization.", "Global commodity chains.", "Migration flows.", "Digital globalization.", "2008 financial crisis and backlash."],
    "SAQ: Briefly explain ONE feature of late 20th-c. globalization.",
    "The World Trade Organization (1995) replaced GATT with binding dispute resolution, accelerating global trade liberalization. China joined in 2001. Combined with containerization and internet, globalization integrated production worldwide — lifting hundreds of millions out of poverty while exposing workers in developed countries to wage competition.",
    [{q:"WTO?",a:"1995"},{q:"China joined WTO?",a:"2001"},{q:"2008 crisis?",a:"Financial"},{q:"Globalization driver?",a:"Trade + information + migration"},{q:"Backlash?",a:"Populism, Brexit, Trump"}],
  ),
  mk(9, "9.14", "20th- and 21st-Century Culture, Arts, and Demographic Trends",
    "Mass media culture, postmodernism, aging populations, changing family structures.",
    ["Postmodernism.", "Mass media: film, TV, streaming.", "Demographic transition + aging.", "Family changes: cohabitation, divorce, single parents.", "Gender norms evolving.", "Cultural globalization (American + global counter-flows)."],
    "SAQ: Briefly explain ONE late 20th-c. cultural trend.",
    "Postmodernism (Derrida, Foucault, Lyotard) challenged grand narratives and claims to universal truth, emphasizing power relations, discourse, and cultural construction of knowledge. Influenced philosophy, literary theory, and humanities scholarship from 1970s onward.",
    [{q:"Postmodernism?",a:"Skepticism of universal truths + grand narratives"},{q:"Foucault?",a:"Power/knowledge analysis"},{q:"Demographic trend?",a:"Aging + declining fertility in Europe"},{q:"Family changes?",a:"Cohabitation, divorce, diverse forms"},{q:"Streaming?",a:"Netflix, Spotify etc. 2010s+"}],
  ),
  mk(9, "9.15", "Continuity and Change in the 20th and 21st Centuries",
    "Massive change (world wars, decolonization, technology, EU) + continuities (inequality, nationalism).",
    ["Changes: decolonization, EU integration, welfare states, tech revolution, women's rights.", "Continuities: inequality, nationalism (populism), class divisions.", "21st-c. challenges: climate, pandemic, AI, Russian aggression, polarization."],
    "LEQ: Evaluate Europe's transformation from 1914 to present.",
    "Dramatic change: Europe lost its global hegemony through two world wars, decolonized its empires, survived Cold War division, and integrated via EU. Welfare states expanded; women gained full citizenship; civil rights expanded. Continuities: inequality, nationalism, sectarian tensions (Balkans, N Ireland), anxieties about migration and identity. 21st c. poses challenges: climate change, Russian aggression (Ukraine 2022), digital disruption, populist backlash against globalization.",
    [{q:"1914 vs 2025 Europe?",a:"Lost global dominance, integrated regionally"},{q:"EU success?",a:"Unprecedented supranational integration"},{q:"Continuities?",a:"Inequality + nationalism + ethnic tensions"},{q:"21st-c. challenge?",a:"Climate, Russia, populism, AI"},{q:"Ukraine invasion?",a:"Feb 2022"}],
  ),
];
