import type { Lesson } from "@/lib/topics";

/**
 * AP Physics C: Electricity & Magnetism — one Lesson per CED topic so the
 * Flashcards tab and sample-problem walkthrough surface across the whole
 * course, not just a curated subset. Compact format: slug, title, blurb,
 * 3-4 key ideas, one sample problem + walkthrough, 5 flashcards, 1-2 links.
 */

const KHAN = "https://www.khanacademy.org/science/physics";
const HYPERPHYSICS = "https://hyperphysics.phy-astr.gsu.edu/hbase/electric/elecon.html";

const UNIT = {
  1: "Electrostatics",
  2: "Conductors, Capacitors, Dielectrics",
  3: "Electric Circuits",
  4: "Magnetic Fields",
  5: "Electromagnetism",
};

export const AP_PHYSICS_C_EM_LESSONS: Lesson[] = [
  {
    slug: "pcem-1-1",
    title: "Electric Charge",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 1, unitTitle: UNIT[1] }],
    blurb: "Charge is conserved, quantized in units of e, and comes in two signs.",
    keyIdeas: [
      "Charge is conserved and quantized: q = ±ne where e = 1.6×10⁻¹⁹ C.",
      "Like charges repel; unlike attract.",
      "Conductors let charge flow freely; insulators trap it.",
      "Charge transfer: friction, conduction, induction.",
    ],
    sampleProblem: "A sphere has net charge -3.2 μC. How many excess electrons does it carry?",
    sampleWalkthrough:
      "Number of excess electrons = |q|/e = (3.2×10⁻⁶) / (1.6×10⁻¹⁹) = 2×10¹³ electrons.\nSign is negative because we have excess ELECTRONS (negatively charged).\n\nTakeaway: always separate magnitude and sign when counting charge carriers.",
    flashcards: [
      { q: "Elementary charge e?", a: "1.6×10⁻¹⁹ C" },
      { q: "Conservation of charge?", a: "Total charge in an isolated system is constant." },
      { q: "Induction?", a: "Separate charges without contact using a nearby charged object + grounding." },
      { q: "Conductor vs. insulator?", a: "Conductor: free electrons; insulator: bound electrons." },
      { q: "Electron charge sign?", a: "Negative. Proton is positive." },
    ],
    links: [{ title: "Electric charge", url: KHAN + "/electric-charge-electric-force-and-voltage", source: "Khan Academy" }],
  },
  {
    slug: "pcem-1-2",
    title: "Coulomb's Law",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 1, unitTitle: UNIT[1] }],
    blurb: "Point-charge force: F = kq₁q₂/r², directed along the line between charges.",
    keyIdeas: [
      "F = kq₁q₂/r² with k = 8.99×10⁹ N·m²/C².",
      "Force is a vector — direction along the line joining the charges; use superposition.",
      "Inverse-square like gravitation, but charge can be negative (gravity cannot).",
      "1/(4πε₀) = k where ε₀ = 8.85×10⁻¹² C²/(N·m²).",
    ],
    sampleProblem: "Two +1.0 μC charges are 0.10 m apart. Find the force magnitude between them.",
    sampleWalkthrough:
      "F = kq₁q₂/r² = (8.99×10⁹)(1×10⁻⁶)(1×10⁻⁶)/(0.10)² = 0.899 N, repulsive.\n\nTakeaway: watch units (μC = 10⁻⁶ C) and keep repulsion/attraction explicit.",
    flashcards: [
      { q: "Coulomb's law magnitude?", a: "F = kq₁q₂/r²" },
      { q: "k in SI?", a: "8.99×10⁹ N·m²/C²" },
      { q: "ε₀?", a: "8.85×10⁻¹² C²/(N·m²)" },
      { q: "Relation k ↔ ε₀?", a: "k = 1/(4πε₀)" },
      { q: "Superposition?", a: "Net force = vector sum of pairwise Coulomb forces." },
    ],
    links: [{ title: "Coulomb's law", url: KHAN + "/electric-charge-electric-force-and-voltage/coulombs-law", source: "Khan Academy" }],
  },
  {
    slug: "pcem-1-3",
    title: "Electric Field",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 1, unitTitle: UNIT[1] }],
    blurb: "E is force per unit positive test charge: E = F/q. Point charge: E = kQ/r².",
    keyIdeas: [
      "E is a vector; direction is the force on a positive test charge.",
      "Point charge: E = kQ/r² pointing radially (outward if Q>0, inward if Q<0).",
      "Net field from multiple charges: vector sum (superposition).",
      "Field lines start on +, end on −; density ∝ |E|.",
    ],
    sampleProblem: "Find E at 0.20 m from a +5.0 nC point charge.",
    sampleWalkthrough:
      "E = kQ/r² = (8.99×10⁹)(5×10⁻⁹)/(0.20)² = 1124 N/C ≈ 1.1×10³ N/C, pointing away from the charge.",
    flashcards: [
      { q: "Definition of E?", a: "E = F/q (force per unit positive test charge)" },
      { q: "Point-charge E?", a: "E = kQ/r² radially" },
      { q: "Units of E?", a: "N/C or V/m (equivalent)" },
      { q: "Direction on +q test charge?", a: "Same as E." },
      { q: "Field lines rule?", a: "Start on +, end on −; never cross; density ∝ strength." },
    ],
    links: [{ title: "Electric fields", url: KHAN + "/electric-charge-electric-force-and-voltage/electric-field", source: "Khan Academy" }],
  },
  {
    slug: "pcem-1-4",
    title: "Electric Field Due to Continuous Charge Distributions",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 1, unitTitle: UNIT[1] }],
    blurb: "Break distribution into differential elements dq, integrate dE = k dq/r².",
    keyIdeas: [
      "dE = k dq/r² r̂ — add vectorially, exploit symmetry to cancel components.",
      "Linear λ = dq/dL, surface σ = dq/dA, volume ρ = dq/dV.",
      "Rings and disks: use axial-symmetry result E_axis = kqz/(z²+R²)^(3/2) for a ring.",
      "Infinite line of charge: E = 2kλ/r; infinite sheet: E = σ/(2ε₀).",
    ],
    sampleProblem: "A thin ring of radius R carries charge Q. Find E on the axis at distance z from center.",
    sampleWalkthrough:
      "By symmetry the radial components cancel; only z-components survive. Each dq contributes dE_z = k dq·z/(z²+R²)^(3/2). Integrate dq over the whole ring: E_z = kQz/(z²+R²)^(3/2).\n\nCheck limits: z » R ⇒ E ≈ kQ/z² (point charge); z = 0 ⇒ E = 0 (center by symmetry).",
    flashcards: [
      { q: "dE for continuous distribution?", a: "dE = k dq/r² r̂" },
      { q: "E on axis of ring radius R, charge Q, distance z?", a: "E = kQz/(z²+R²)^(3/2)" },
      { q: "Infinite line of charge, density λ?", a: "E = 2kλ/r, radially outward" },
      { q: "Infinite sheet, σ?", a: "E = σ/(2ε₀)" },
      { q: "Use symmetry how?", a: "Identify components that cancel so you integrate only the surviving ones." },
    ],
    links: [{ title: "E from continuous charge", url: HYPERPHYSICS, source: "HyperPhysics" }],
  },
  {
    slug: "pcem-1-5",
    title: "Gauss's Law",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 1, unitTitle: UNIT[1] }],
    blurb: "∮ E·dA = Q_enc/ε₀. Use symmetry (spherical, cylindrical, planar) to compute E.",
    keyIdeas: [
      "Φ = ∮ E·dA; choose a Gaussian surface matching the symmetry.",
      "Spherical symmetry: sphere Gaussian surface; cylindrical: cylinder; planar: pillbox.",
      "Sphere of radius r outside charge Q: E = kQ/r² (as if Q were at center).",
      "Infinite sheet: E = σ/(2ε₀); between parallel plates: E = σ/ε₀.",
      "Inside a solid conductor in electrostatic equilibrium: E = 0.",
    ],
    sampleProblem: "Infinite line of charge, linear density λ. Find E at distance r using Gauss's law.",
    sampleWalkthrough:
      "Choose cylindrical Gaussian surface of radius r, length L. By symmetry, E points radially and is constant on the curved surface; flux through end caps = 0.\n∮ E·dA = E(2πrL) = Q_enc/ε₀ = λL/ε₀ ⇒ E = λ/(2πε₀r) = 2kλ/r.",
    flashcards: [
      { q: "Gauss's law?", a: "∮ E·dA = Q_enc/ε₀" },
      { q: "When is Gauss's law useful?", a: "When symmetry (spherical, cylindrical, planar) makes E constant on the Gaussian surface." },
      { q: "E inside a solid conductor at equilibrium?", a: "0" },
      { q: "E outside a uniformly charged sphere?", a: "E = kQ/r² (treat as point charge)" },
      { q: "E from infinite plane sheet σ?", a: "E = σ/(2ε₀), perpendicular to sheet" },
    ],
    links: [{ title: "Gauss's law", url: KHAN + "/magnetic-forces-and-magnetic-fields", source: "Khan Academy" }],
  },
  {
    slug: "pcem-1-6",
    title: "Electric Potential Energy",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 1, unitTitle: UNIT[1] }],
    blurb: "Work done by an external agent to assemble charges. U = kq₁q₂/r for two point charges.",
    keyIdeas: [
      "U = kq₁q₂/r for two point charges (U→0 as r→∞ is the convention).",
      "For systems: U_system = sum over all pairs.",
      "Work-energy theorem: W_ext = ΔU (slow, no KE change) or W_field = −ΔU.",
      "Signs matter: two positives ⇒ U>0 (must do work to bring them together).",
    ],
    sampleProblem: "Find U for two +2.0 μC charges at r = 0.30 m.",
    sampleWalkthrough:
      "U = kq₁q₂/r = (8.99×10⁹)(2×10⁻⁶)(2×10⁻⁶)/0.30 = 0.120 J.\nPositive U means external work must be done to bring them from infinity.",
    flashcards: [
      { q: "U for two point charges?", a: "U = kq₁q₂/r" },
      { q: "Reference point for U?", a: "U = 0 at infinite separation." },
      { q: "W_field vs. ΔU?", a: "W_field = −ΔU" },
      { q: "Sign of U for like charges?", a: "Positive." },
      { q: "Units?", a: "Joules" },
    ],
    links: [{ title: "Electric potential energy", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcem-1-7",
    title: "Electric Potential",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 1, unitTitle: UNIT[1] }],
    blurb: "V = U/q. Point charge: V = kQ/r. E = −∇V (field is minus gradient of potential).",
    keyIdeas: [
      "V is a scalar — add algebraically, not vectorially.",
      "Point charge: V = kQ/r (sign of Q included).",
      "E = −dV/dr (radial); in general E = −∇V.",
      "Equipotential surfaces ⊥ E field lines; no work to move along equipotential.",
      "Volt = J/C.",
    ],
    sampleProblem: "V at 0.40 m from a −3.0 nC charge?",
    sampleWalkthrough: "V = kQ/r = (8.99×10⁹)(−3×10⁻⁹)/0.40 = −67.4 V. Negative because Q is negative.",
    flashcards: [
      { q: "Definition of V?", a: "V = U/q (potential energy per unit positive charge)" },
      { q: "Point-charge V?", a: "V = kQ/r" },
      { q: "Relation E and V?", a: "E = −∇V (or E_x = −dV/dx)" },
      { q: "Equipotential surface?", a: "Surface where V is constant; perpendicular to E." },
      { q: "Volt?", a: "1 V = 1 J/C" },
    ],
    links: [{ title: "Electric potential", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcem-2-1",
    title: "Conductors and Insulators",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 2, unitTitle: UNIT[2] }],
    blurb: "Conductors have free charges that rearrange; insulators don't. Key: E=0 inside a conductor at equilibrium.",
    keyIdeas: [
      "Inside a conductor at electrostatic equilibrium: E = 0.",
      "Excess charge on a conductor resides on its surface.",
      "Just outside conductor: E ⊥ surface, magnitude σ/ε₀.",
      "Whole conductor is at a single potential at equilibrium.",
    ],
    sampleProblem: "A solid metal sphere carries excess charge Q. Where does Q reside?",
    sampleWalkthrough:
      "At equilibrium, charges move until interior E = 0. Excess charge pushes itself to the outer surface so they're as far apart as possible.\nAny Gaussian surface entirely inside the conductor encloses zero net charge.",
    flashcards: [
      { q: "E inside conductor at equilibrium?", a: "0" },
      { q: "Where does excess charge sit on a conductor?", a: "On the outer surface." },
      { q: "E just outside a conductor?", a: "E = σ/ε₀, perpendicular to surface." },
      { q: "V on a conductor at equilibrium?", a: "Constant everywhere on and inside the conductor." },
      { q: "Insulator vs. conductor?", a: "Insulator: bound charges; conductor: free charges." },
    ],
    links: [{ title: "Conductors", url: HYPERPHYSICS, source: "HyperPhysics" }],
  },
  {
    slug: "pcem-2-2",
    title: "Capacitance",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 2, unitTitle: UNIT[2] }],
    blurb: "C = Q/V. Capacitance depends on geometry, not on charge or voltage.",
    keyIdeas: [
      "C = Q/V — amount of charge stored per volt applied.",
      "Units: Farad = C/V.",
      "Parallel plate: C = ε₀A/d (vacuum).",
      "With dielectric κ: C = κε₀A/d.",
    ],
    sampleProblem: "A 5 μF capacitor is charged to 12 V. How much charge is stored?",
    sampleWalkthrough: "Q = CV = (5×10⁻⁶)(12) = 6×10⁻⁵ C = 60 μC.",
    flashcards: [
      { q: "Definition of C?", a: "C = Q/V" },
      { q: "Parallel-plate C?", a: "C = ε₀A/d (vacuum)" },
      { q: "With dielectric κ?", a: "C = κε₀A/d" },
      { q: "Unit?", a: "Farad (F) = 1 C/V" },
      { q: "C depends on charge/voltage?", a: "No — only geometry and dielectric." },
    ],
    links: [{ title: "Capacitance", url: KHAN + "/circuits-topic/circuits-with-capacitors", source: "Khan Academy" }],
  },
  {
    slug: "pcem-2-3",
    title: "Parallel-Plate Capacitors and Dielectrics",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 2, unitTitle: UNIT[2] }],
    blurb: "Uniform E between plates: E = σ/ε₀ = V/d. Dielectrics multiply C by κ.",
    keyIdeas: [
      "Between plates E = V/d; σ = ε₀E on plate surface.",
      "Inserting dielectric κ at fixed Q: V drops by κ, E drops by κ, C rises by κ.",
      "Inserting dielectric κ at fixed V: Q rises by κ, U rises by κ.",
      "Breakdown: beyond κ-specific E_max, dielectric becomes conductive.",
    ],
    sampleProblem: "A 10 pF air capacitor is filled with κ = 3 dielectric. New C?",
    sampleWalkthrough: "C_new = κ·C_old = 3 × 10 pF = 30 pF.",
    flashcards: [
      { q: "E between parallel plates (V applied, gap d)?", a: "E = V/d" },
      { q: "Effect of dielectric κ on C?", a: "C → κC" },
      { q: "Fixed Q, insert dielectric: V does what?", a: "Drops by factor κ." },
      { q: "Fixed V, insert dielectric: Q does what?", a: "Rises by factor κ." },
      { q: "Why use dielectrics?", a: "Increase C, raise breakdown voltage, keep plates apart." },
    ],
    links: [{ title: "Dielectrics", url: HYPERPHYSICS, source: "HyperPhysics" }],
  },
  {
    slug: "pcem-2-4",
    title: "Energy Stored in Capacitors",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 2, unitTitle: UNIT[2] }],
    blurb: "U = ½CV² = ½Q²/C = ½QV. Energy lives in the electric field (density u = ½ε₀E²).",
    keyIdeas: [
      "U = ½CV² = ½Q²/C = ½QV — all equivalent.",
      "Energy density in vacuum: u = ½ε₀E².",
      "Integrating u over the volume gives total stored U.",
      "Doubling V on a fixed capacitor quadruples U.",
    ],
    sampleProblem: "Energy stored in 100 μF capacitor at 50 V?",
    sampleWalkthrough: "U = ½CV² = ½(100×10⁻⁶)(50)² = 0.125 J.",
    flashcards: [
      { q: "Three forms of U for a capacitor?", a: "U = ½CV² = ½Q²/C = ½QV" },
      { q: "Energy density of E field (vacuum)?", a: "u = ½ε₀E²" },
      { q: "Double V on fixed C: U?", a: "×4" },
      { q: "Halve C (disconnect then separate plates) at fixed Q: U?", a: "×2 (external work done)" },
      { q: "Where does capacitor energy reside?", a: "In the electric field between the plates." },
    ],
    links: [{ title: "Capacitor energy", url: HYPERPHYSICS, source: "HyperPhysics" }],
  },
  {
    slug: "pcem-2-5",
    title: "Capacitors in Series and Parallel",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 2, unitTitle: UNIT[2] }],
    blurb: "Series: 1/C_eq = Σ1/C_i. Parallel: C_eq = ΣC_i. Note: opposite of resistors!",
    keyIdeas: [
      "Series: share the SAME Q; V adds; 1/C_eq = 1/C₁ + 1/C₂ + …",
      "Parallel: share the SAME V; Q adds; C_eq = C₁ + C₂ + …",
      "Mirror-image of resistor rules — easy to confuse, so memorize carefully.",
      "Series C_eq < smallest C; parallel C_eq > largest C.",
    ],
    sampleProblem: "Find equivalent C for 4 μF and 6 μF (a) in series, (b) in parallel.",
    sampleWalkthrough:
      "(a) Series: 1/C = 1/4 + 1/6 = 5/12 ⇒ C = 12/5 = 2.4 μF.\n(b) Parallel: C = 4 + 6 = 10 μF.\n\nTakeaway: think physically — series stacks dielectrics (harder), parallel widens plate area (easier).",
    flashcards: [
      { q: "Capacitors in series, C_eq?", a: "1/C_eq = 1/C₁ + 1/C₂ + …" },
      { q: "Capacitors in parallel, C_eq?", a: "C_eq = C₁ + C₂ + …" },
      { q: "Series capacitors: what's the same on each?", a: "Charge Q is the same." },
      { q: "Parallel capacitors: what's the same?", a: "Voltage V is the same." },
      { q: "Series C_eq compared to smallest C?", a: "Less than smallest." },
    ],
    links: [{ title: "Series/parallel capacitors", url: HYPERPHYSICS, source: "HyperPhysics" }],
  },
  {
    slug: "pcem-3-1",
    title: "Current, Resistance, and Power",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 3, unitTitle: UNIT[3] }],
    blurb: "I = dQ/dt. Ohm's law V = IR. Power P = IV = I²R = V²/R.",
    keyIdeas: [
      "Current I = dQ/dt; unit Ampere = C/s.",
      "Conventional current flows in the direction positive charges would move (opposite to actual electron flow).",
      "Ohm's law: V = IR (for Ohmic materials).",
      "R = ρL/A where ρ is resistivity, L length, A cross-section.",
      "Power dissipated: P = IV = I²R = V²/R.",
    ],
    sampleProblem: "A 12 V battery drives 2.0 A through a resistor. Find R and P.",
    sampleWalkthrough: "R = V/I = 12/2.0 = 6 Ω.\nP = IV = (2.0)(12) = 24 W (or I²R = 4·6 = 24 W).",
    flashcards: [
      { q: "Definition of current?", a: "I = dQ/dt" },
      { q: "Ohm's law?", a: "V = IR" },
      { q: "R in terms of resistivity?", a: "R = ρL/A" },
      { q: "Power dissipated in resistor?", a: "P = I²R = V²/R = IV" },
      { q: "Unit of R?", a: "Ohm (Ω) = V/A" },
    ],
    links: [{ title: "Ohm's law", url: KHAN + "/circuits-topic", source: "Khan Academy" }],
  },
  {
    slug: "pcem-3-2",
    title: "Steady-State DC Circuits with Batteries and Resistors",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 3, unitTitle: UNIT[3] }],
    blurb: "Series: R_eq = ΣR_i. Parallel: 1/R_eq = Σ1/R_i. Use Kirchhoff's laws for complex circuits.",
    keyIdeas: [
      "Series: same current, voltages add, R_eq = R₁ + R₂ + …",
      "Parallel: same voltage, currents add, 1/R_eq = 1/R₁ + 1/R₂ + …",
      "Kirchhoff's voltage law (KVL): ΣV around a loop = 0.",
      "Kirchhoff's current law (KCL): ΣI in = ΣI out at a node.",
      "Internal resistance r: terminal V = ε − Ir.",
    ],
    sampleProblem: "Three 10 Ω resistors: one in series with a parallel pair. Find R_eq.",
    sampleWalkthrough:
      "Parallel pair: 1/R = 1/10 + 1/10 ⇒ R_p = 5 Ω.\nAdd the series 10 Ω: R_eq = 10 + 5 = 15 Ω.",
    flashcards: [
      { q: "R_eq for series resistors?", a: "R_eq = R₁ + R₂ + …" },
      { q: "R_eq for parallel resistors?", a: "1/R_eq = 1/R₁ + 1/R₂ + …" },
      { q: "KVL?", a: "Sum of voltage drops around a closed loop = 0." },
      { q: "KCL?", a: "Total current into a node = total current out." },
      { q: "Terminal voltage with internal r?", a: "V = ε − Ir" },
    ],
    links: [{ title: "Kirchhoff's laws", url: KHAN + "/circuits-topic", source: "Khan Academy" }],
  },
  {
    slug: "pcem-3-3",
    title: "Capacitors in Circuits",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 3, unitTitle: UNIT[3] }],
    blurb: "At steady state, no current flows through a fully charged capacitor (it acts as an open).",
    keyIdeas: [
      "Initially uncharged capacitor acts like a wire (short).",
      "Fully charged capacitor acts like an open — no current flows through it.",
      "Charge stored at steady state: Q = CV_across.",
      "For DC at steady state, ignore capacitor current; solve the rest of the circuit.",
    ],
    sampleProblem: "Battery 12 V, resistor 4 Ω in series with a capacitor. At steady state, I = ?",
    sampleWalkthrough: "Steady state: capacitor fully charged, I = 0 through the branch. V_capacitor = 12 V, V_R = 0.",
    flashcards: [
      { q: "Capacitor at t = 0 (uncharged)?", a: "Acts like a wire (short)." },
      { q: "Capacitor at t → ∞ (steady state)?", a: "Acts like an open — no current." },
      { q: "Q on capacitor at steady state?", a: "Q = C × V_across" },
      { q: "Does current 'flow through' a capacitor at DC steady state?", a: "No — it's fully charged." },
      { q: "Energy stored at steady state?", a: "U = ½CV²" },
    ],
    links: [{ title: "Capacitors in circuits", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcem-3-4",
    title: "RC Circuits",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 3, unitTitle: UNIT[3] }],
    blurb: "Charging: Q(t)=CV(1−e^(−t/RC)). Discharging: Q(t)=Q₀e^(−t/RC). τ = RC.",
    keyIdeas: [
      "Time constant τ = RC; after 1τ, about 63% charged (or 63% discharged).",
      "Charging: Q(t) = CV(1 − e^(−t/τ)), I(t) = (V/R)e^(−t/τ).",
      "Discharging: Q(t) = Q₀ e^(−t/τ), I(t) = (Q₀/RC) e^(−t/τ).",
      "After ~5τ, essentially at steady state (less than 1% off).",
    ],
    sampleProblem: "R = 10 kΩ, C = 100 μF. τ = ?",
    sampleWalkthrough: "τ = RC = (10×10³)(100×10⁻⁶) = 1.0 s.",
    flashcards: [
      { q: "Time constant?", a: "τ = RC" },
      { q: "Charge on charging capacitor Q(t)?", a: "Q(t) = CV(1 − e^(−t/τ))" },
      { q: "Q on discharging capacitor?", a: "Q(t) = Q₀ e^(−t/τ)" },
      { q: "After 1τ, fraction charged?", a: "≈ 63%" },
      { q: "After ~5τ?", a: "Approximately fully charged (or discharged)." },
    ],
    links: [{ title: "RC circuits", url: KHAN + "/circuits-topic/circuits-with-capacitors", source: "Khan Academy" }],
  },
  {
    slug: "pcem-4-1",
    title: "Forces on Moving Charges in Magnetic Fields",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 4, unitTitle: UNIT[4] }],
    blurb: "F = qv × B. Magnetic force is always perpendicular to v — does no work.",
    keyIdeas: [
      "F = qv × B; magnitude F = qvB sin θ.",
      "Magnetic force ⊥ v → no work, speed unchanged, only direction changes.",
      "Charged particle in uniform B moves in circles: qvB = mv²/r ⇒ r = mv/(qB).",
      "Cyclotron period T = 2πm/(qB) — independent of v.",
      "Right-hand rule: fingers along v, curl toward B, thumb = F on positive charge (reverse for negative).",
    ],
    sampleProblem: "A proton moves at 2×10⁶ m/s perpendicular to a 0.50 T field. Find the radius of circular motion.",
    sampleWalkthrough:
      "r = mv/(qB) = (1.67×10⁻²⁷)(2×10⁶) / (1.6×10⁻¹⁹)(0.50) = 0.042 m ≈ 4.2 cm.",
    flashcards: [
      { q: "Force on moving charge?", a: "F = qv × B" },
      { q: "Does magnetic force do work?", a: "No — F ⊥ v always." },
      { q: "Radius of circular motion in B?", a: "r = mv/(qB)" },
      { q: "Cyclotron period?", a: "T = 2πm/(qB)" },
      { q: "Direction of F on electron (vs. proton) moving same v in same B?", a: "Opposite direction." },
    ],
    links: [{ title: "Magnetic forces on charges", url: KHAN + "/magnetic-forces-and-magnetic-fields", source: "Khan Academy" }],
  },
  {
    slug: "pcem-4-2",
    title: "Forces on Current-Carrying Wires",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 4, unitTitle: UNIT[4] }],
    blurb: "F = IL × B on a straight wire. Parallel wires with like currents attract, unlike repel.",
    keyIdeas: [
      "F = IL × B; magnitude IL B sin θ.",
      "Direction: right-hand rule on current I and B.",
      "Force per unit length between parallel wires separated by d: F/L = μ₀I₁I₂/(2πd).",
      "Same-direction currents attract; opposite-direction currents repel.",
      "Used to define Ampere: 2×10⁻⁷ N/m between 1 A parallel wires at 1 m.",
    ],
    sampleProblem: "A 0.50 m wire carries 3.0 A perpendicular to a 0.20 T field. Find F.",
    sampleWalkthrough: "F = ILB = (3.0)(0.50)(0.20) = 0.30 N, direction via right-hand rule.",
    flashcards: [
      { q: "Force on straight current-carrying wire?", a: "F = IL × B" },
      { q: "Parallel wires, currents same direction?", a: "Attract." },
      { q: "Parallel wires, opposite currents?", a: "Repel." },
      { q: "F/L between parallel wires?", a: "μ₀I₁I₂/(2πd)" },
      { q: "μ₀?", a: "4π×10⁻⁷ T·m/A" },
    ],
    links: [{ title: "Force on current", url: KHAN + "/magnetic-forces-and-magnetic-fields", source: "Khan Academy" }],
  },
  {
    slug: "pcem-4-3",
    title: "Magnetic Fields from Current Configurations",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 4, unitTitle: UNIT[4] }],
    blurb: "Long wire: B = μ₀I/(2πr). Loop center: B = μ₀I/(2R). Solenoid: B = μ₀nI inside.",
    keyIdeas: [
      "Long straight wire: B = μ₀I/(2πr), field lines concentric circles around wire.",
      "Circular loop center: B = μ₀I/(2R).",
      "Ideal solenoid interior: B = μ₀nI where n = turns/length; nearly zero outside.",
      "Right-hand rule for wire: thumb along I, fingers curl in direction of B.",
    ],
    sampleProblem: "Solenoid with 1000 turns/m, I = 2 A. Field inside?",
    sampleWalkthrough: "B = μ₀nI = (4π×10⁻⁷)(1000)(2) ≈ 2.5×10⁻³ T = 2.5 mT.",
    flashcards: [
      { q: "B from long straight wire at distance r?", a: "B = μ₀I/(2πr)" },
      { q: "B at center of circular loop radius R?", a: "B = μ₀I/(2R)" },
      { q: "B inside ideal solenoid?", a: "B = μ₀nI (n = turns per meter)" },
      { q: "B outside ideal solenoid?", a: "≈ 0" },
      { q: "Right-hand rule for wire?", a: "Thumb along I; fingers curl in direction of B." },
    ],
    links: [{ title: "Magnetic fields from currents", url: HYPERPHYSICS, source: "HyperPhysics" }],
  },
  {
    slug: "pcem-4-4",
    title: "Biot-Savart Law and Ampère's Law",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 4, unitTitle: UNIT[4] }],
    blurb: "Biot-Savart: dB = μ₀I dL × r̂/(4πr²). Ampère: ∮B·dL = μ₀I_enc (use with symmetry).",
    keyIdeas: [
      "Biot-Savart: contribution of a current element to B field.",
      "Ampère's law: line integral around closed loop = μ₀ × enclosed current.",
      "Use Ampère when symmetry makes B constant along an 'Amperian loop' (straight wire, solenoid, toroid).",
      "Solenoid via Ampère: rectangular loop with one side inside, B·L = μ₀(nL)I ⇒ B = μ₀nI.",
    ],
    sampleProblem: "Derive B from infinite straight wire at distance r using Ampère's law.",
    sampleWalkthrough:
      "Choose circular Amperian loop of radius r centered on wire. By symmetry B is tangent to loop, constant magnitude.\n∮B·dL = B(2πr) = μ₀I ⇒ B = μ₀I/(2πr).",
    flashcards: [
      { q: "Biot-Savart law?", a: "dB = (μ₀/4π) I dL × r̂ / r²" },
      { q: "Ampère's law?", a: "∮ B·dL = μ₀ I_enc" },
      { q: "When to use Ampère vs. Biot-Savart?", a: "Ampère when symmetry allows; Biot-Savart otherwise (integrate directly)." },
      { q: "Solenoid via Ampère?", a: "Rectangular loop one side inside, B = μ₀nI" },
      { q: "Toroid B inside?", a: "B = μ₀NI/(2πr) where N = total turns" },
    ],
    links: [{ title: "Ampère's law", url: HYPERPHYSICS, source: "HyperPhysics" }],
  },
  {
    slug: "pcem-5-1",
    title: "Electromagnetic Induction (Faraday's Law and Lenz's Law)",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 5, unitTitle: UNIT[5] }],
    blurb: "EMF = −dΦ_B/dt. Lenz's law: induced current opposes the change in flux.",
    keyIdeas: [
      "Magnetic flux Φ_B = ∫ B·dA.",
      "Faraday: EMF = −dΦ_B/dt — signs carry direction info.",
      "Lenz: induced current flows in the direction that OPPOSES the flux change.",
      "Motional EMF: ε = BLv for a straight rod of length L moving at v through field B.",
      "Power dissipated P = ε²/R for induced-EMF circuits.",
    ],
    sampleProblem: "A loop of area 0.20 m² sits in a B that grows from 0 to 0.50 T in 2.0 s. Find induced EMF.",
    sampleWalkthrough: "|EMF| = ΔΦ/Δt = (0.50)(0.20)/2.0 = 0.050 V = 50 mV.",
    flashcards: [
      { q: "Magnetic flux?", a: "Φ_B = ∫ B·dA" },
      { q: "Faraday's law?", a: "EMF = −dΦ_B/dt" },
      { q: "Lenz's law?", a: "Induced current opposes the change in flux that caused it." },
      { q: "Motional EMF of rod?", a: "ε = BLv (v ⊥ L, L ⊥ B)" },
      { q: "Sign meaning of −?", a: "Encodes Lenz's law — opposing sense." },
    ],
    links: [{ title: "Faraday's law", url: KHAN + "/electromagnetic-induction", source: "Khan Academy" }],
  },
  {
    slug: "pcem-5-2",
    title: "Inductance, LR and LC Circuits",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 5, unitTitle: UNIT[5] }],
    blurb: "Inductor: V = L dI/dt. LR circuit: τ = L/R. LC oscillates at ω = 1/√(LC).",
    keyIdeas: [
      "Self-inductance L: V_L = L dI/dt (opposes change in current).",
      "Energy stored in inductor: U = ½LI².",
      "LR charging: I(t) = (V/R)(1 − e^(−tR/L)), τ = L/R.",
      "LC oscillation: ω = 1/√(LC), Q(t) = Q₀ cos(ωt).",
      "Solenoid inductance: L = μ₀n²Vol.",
    ],
    sampleProblem: "L = 20 mH, C = 50 μF. Resonant angular frequency?",
    sampleWalkthrough: "ω = 1/√(LC) = 1/√(0.020 × 50×10⁻⁶) = 1000 rad/s.",
    flashcards: [
      { q: "Voltage across inductor?", a: "V_L = L dI/dt" },
      { q: "Energy in inductor?", a: "U = ½LI²" },
      { q: "LR time constant?", a: "τ = L/R" },
      { q: "LC angular frequency?", a: "ω = 1/√(LC)" },
      { q: "Energy in LC circuit?", a: "Oscillates between capacitor (½CV²) and inductor (½LI²), total constant." },
    ],
    links: [{ title: "Inductance", url: KHAN + "/electromagnetic-induction", source: "Khan Academy" }],
  },
  {
    slug: "pcem-5-3",
    title: "Maxwell's Equations",
    courses: [{ courseSlug: "ap-physics-c-em", unitNumber: 5, unitTitle: UNIT[5] }],
    blurb: "Four equations unify electricity and magnetism; predict EM waves at c = 1/√(ε₀μ₀).",
    keyIdeas: [
      "Gauss (E): ∮ E·dA = Q_enc/ε₀ — charges source E fields.",
      "Gauss (B): ∮ B·dA = 0 — no magnetic monopoles.",
      "Faraday: ∮ E·dL = −dΦ_B/dt — changing B induces E.",
      "Ampère-Maxwell: ∮ B·dL = μ₀(I_enc + ε₀ dΦ_E/dt) — currents and changing E produce B.",
      "EM waves: c = 1/√(ε₀μ₀) ≈ 3×10⁸ m/s.",
    ],
    sampleProblem: "What does Maxwell's displacement term (ε₀ dΦ_E/dt) physically represent?",
    sampleWalkthrough:
      "It extends Ampère's law: a changing electric flux produces a magnetic field just as a real current would. Without it, the equations would fail in regions where currents are non-continuous (e.g., between capacitor plates). This symmetry between E and B is what predicts self-propagating EM waves.",
    flashcards: [
      { q: "Gauss's law for E?", a: "∮ E·dA = Q_enc/ε₀" },
      { q: "Gauss's law for B?", a: "∮ B·dA = 0 (no magnetic monopoles)" },
      { q: "Faraday's law (Maxwell form)?", a: "∮ E·dL = −dΦ_B/dt" },
      { q: "Ampère-Maxwell?", a: "∮ B·dL = μ₀(I_enc + ε₀ dΦ_E/dt)" },
      { q: "Speed of EM waves?", a: "c = 1/√(ε₀μ₀) ≈ 3×10⁸ m/s" },
    ],
    links: [{ title: "Maxwell's equations", url: HYPERPHYSICS, source: "HyperPhysics" }],
  },
];
