import type { Lesson } from "@/lib/topics";

/** AP Physics C: Mechanics — one Lesson per CED topic for all 7 units. */

const KHAN = "https://www.khanacademy.org/science/physics";
const HP = "https://hyperphysics.phy-astr.gsu.edu/hbase/hframe.html";

const U = {
  1: "Kinematics",
  2: "Force and Translational Dynamics",
  3: "Work, Energy, and Power",
  4: "Linear Momentum",
  5: "Torque and Rotational Dynamics",
  6: "Energy and Momentum of Rotating Systems",
  7: "Oscillations",
};

export const AP_PHYSICS_C_MECH_LESSONS: Lesson[] = [
  {
    slug: "pcm-1-1",
    title: "Scalars and Vectors in One Dimension",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 1, unitTitle: U[1] }],
    blurb: "Scalars have magnitude; vectors have magnitude + direction. In 1D, sign carries direction.",
    keyIdeas: [
      "Scalar: distance, speed, mass, time, energy.",
      "Vector: displacement, velocity, acceleration, force, momentum.",
      "In 1D, sign (+/−) encodes direction.",
      "Magnitude = |vector|; direction specified by angle or unit vector.",
    ],
    sampleProblem: "An ant walks 5 m east, then 3 m west. Distance vs. displacement?",
    sampleWalkthrough: "Distance = 5 + 3 = 8 m (scalar). Displacement = +5 − 3 = +2 m east (vector).",
    flashcards: [
      { q: "Scalar vs vector?", a: "Scalar = magnitude only; vector = magnitude + direction." },
      { q: "Example of scalar?", a: "Mass, energy, temperature." },
      { q: "Example of vector?", a: "Velocity, force, displacement." },
      { q: "1D vector direction?", a: "Encoded by sign." },
      { q: "Distance vs displacement?", a: "Distance = total path; displacement = final − initial position." },
    ],
    links: [{ title: "Scalars & vectors", url: KHAN + "/one-dimensional-motion", source: "Khan Academy" }],
  },
  {
    slug: "pcm-1-2",
    title: "Displacement, Velocity, and Acceleration",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 1, unitTitle: U[1] }],
    blurb: "Derivatives: v = dx/dt, a = dv/dt = d²x/dt². Integration gives position from velocity.",
    keyIdeas: [
      "Δx = displacement; v_avg = Δx/Δt.",
      "Instantaneous: v = dx/dt, a = dv/dt.",
      "Constant-acceleration kinematics: x = x₀ + v₀t + ½at², v² = v₀² + 2aΔx.",
      "x(t) = ∫ v dt, v(t) = ∫ a dt — with initial conditions.",
    ],
    sampleProblem: "v(t) = 3t² + 2. Find x(t) given x(0) = 1.",
    sampleWalkthrough: "x = ∫(3t² + 2)dt = t³ + 2t + C. x(0) = 1 ⇒ C = 1. x(t) = t³ + 2t + 1.",
    flashcards: [
      { q: "Definition of velocity?", a: "v = dx/dt" },
      { q: "Definition of acceleration?", a: "a = dv/dt = d²x/dt²" },
      { q: "Constant a kinematic equation for x?", a: "x = x₀ + v₀t + ½at²" },
      { q: "No-t kinematic equation?", a: "v² = v₀² + 2aΔx" },
      { q: "Average velocity?", a: "v_avg = Δx/Δt" },
    ],
    links: [{ title: "Kinematics", url: KHAN + "/one-dimensional-motion", source: "Khan Academy" }],
  },
  {
    slug: "pcm-1-3",
    title: "Representing Motion",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 1, unitTitle: U[1] }],
    blurb: "x–t, v–t, a–t graphs: slope of x–t is v, slope of v–t is a, area under v–t is Δx.",
    keyIdeas: [
      "Slope of position–time = velocity.",
      "Slope of velocity–time = acceleration.",
      "Area under velocity–time graph = displacement.",
      "Area under acceleration–time graph = change in velocity.",
    ],
    sampleProblem: "v–t graph: constant v = 4 m/s from t = 0 to t = 3 s. Δx?",
    sampleWalkthrough: "Δx = area under v–t = (4)(3) = 12 m.",
    flashcards: [
      { q: "Slope of x–t graph?", a: "Velocity" },
      { q: "Slope of v–t?", a: "Acceleration" },
      { q: "Area under v–t?", a: "Displacement" },
      { q: "Area under a–t?", a: "Change in velocity" },
      { q: "Constant v on v–t looks like?", a: "Horizontal line" },
    ],
    links: [{ title: "Motion graphs", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-1-4",
    title: "Reference Frames and Relative Motion",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 1, unitTitle: U[1] }],
    blurb: "Velocity depends on reference frame: v_AC = v_AB + v_BC (add velocities vectorially).",
    keyIdeas: [
      "Galilean velocity addition: v_AC = v_AB + v_BC.",
      "Observers in different inertial frames measure different velocities but same acceleration.",
      "In 2D, use vector addition.",
      "Relative velocity problems: choose one object as 'ground' and relate others.",
    ],
    sampleProblem: "Boat moves 3 m/s east relative to water; water moves 2 m/s north. Boat velocity relative to ground?",
    sampleWalkthrough: "v = √(3² + 2²) = √13 ≈ 3.6 m/s, direction arctan(2/3) ≈ 34° N of E.",
    flashcards: [
      { q: "Galilean velocity addition?", a: "v_AC = v_AB + v_BC" },
      { q: "Do all inertial frames agree on a?", a: "Yes." },
      { q: "Do they agree on v?", a: "No — v is frame-dependent." },
      { q: "Inertial frame?", a: "A frame moving at constant velocity (no acceleration)." },
      { q: "How to find relative velocity in 2D?", a: "Add velocity vectors component-wise." },
    ],
    links: [{ title: "Relative motion", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-1-5",
    title: "Vectors and Motion in Two Dimensions",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 1, unitTitle: U[1] }],
    blurb: "Projectile motion: independent x and y components, a_y = −g, a_x = 0.",
    keyIdeas: [
      "Treat x and y motion INDEPENDENTLY.",
      "Projectile: a_x = 0, a_y = −g; v_x stays constant.",
      "Time of flight from v₀_y; range R = v₀²sin(2θ)/g (level ground, same launch/land height).",
      "Max height H = (v₀ sinθ)²/(2g).",
    ],
    sampleProblem: "Projectile launched at 20 m/s, 30° above horizontal. Max height?",
    sampleWalkthrough: "v_0y = 20 sin 30° = 10 m/s. H = v_0y²/(2g) = 100/19.6 ≈ 5.1 m.",
    flashcards: [
      { q: "Projectile: a_x?", a: "0" },
      { q: "Projectile: a_y?", a: "−g = −9.8 m/s² (downward)" },
      { q: "Range formula level ground?", a: "R = v₀² sin(2θ)/g" },
      { q: "Max height?", a: "H = (v₀ sin θ)²/(2g)" },
      { q: "When does angle maximize range?", a: "45°" },
    ],
    links: [{ title: "Projectile motion", url: KHAN + "/two-dimensional-motion", source: "Khan Academy" }],
  },
  {
    slug: "pcm-2-1",
    title: "Systems and Center of Mass",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 2, unitTitle: U[2] }],
    blurb: "x_cm = (Σm_i x_i)/(Σm_i). Newton's laws apply to the center of mass of a system.",
    keyIdeas: [
      "Center of mass: x_cm = (Σm_i x_i)/(Σm_i), similarly for y, z.",
      "Continuous body: x_cm = (1/M)∫x dm.",
      "Net external force on system = M·a_cm.",
      "Internal forces do NOT move the center of mass.",
    ],
    sampleProblem: "Two 2 kg masses at x = 0 and x = 4 m. x_cm?",
    sampleWalkthrough: "x_cm = (2·0 + 2·4)/(2+2) = 8/4 = 2 m.",
    flashcards: [
      { q: "Center of mass formula?", a: "x_cm = (Σm_i x_i)/M" },
      { q: "Net force on system ↔ a_cm?", a: "F_net = M a_cm" },
      { q: "Do internal forces move x_cm?", a: "No." },
      { q: "Continuous body cm?", a: "x_cm = (1/M) ∫ x dm" },
      { q: "Symmetric body cm?", a: "On axis of symmetry." },
    ],
    links: [{ title: "Center of mass", url: KHAN + "/linear-momentum", source: "Khan Academy" }],
  },
  {
    slug: "pcm-2-2",
    title: "Forces and Free-Body Diagrams",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 2, unitTitle: U[2] }],
    blurb: "FBD shows all forces on one object. Solve ΣF = ma component-wise.",
    keyIdeas: [
      "Isolate ONE object; draw every force acting on it (not by it).",
      "Common forces: gravity mg, normal N, tension T, friction f, applied forces.",
      "Choose axes along motion (incline: x along, y perp).",
      "Write ΣF_x = ma_x, ΣF_y = ma_y.",
    ],
    sampleProblem: "Block on frictionless incline θ. Acceleration?",
    sampleWalkthrough: "Along incline: mg sin θ = ma ⇒ a = g sin θ, down the slope.",
    flashcards: [
      { q: "What goes in FBD?", a: "Forces acting ON the object, not by it." },
      { q: "Weight?", a: "W = mg, downward." },
      { q: "Normal force?", a: "Perpendicular to contact surface." },
      { q: "Tension in ideal rope?", a: "Same magnitude throughout; pulls along rope." },
      { q: "Block on incline θ, frictionless, a along slope?", a: "a = g sin θ" },
    ],
    links: [{ title: "FBDs", url: KHAN + "/forces-newtons-laws", source: "Khan Academy" }],
  },
  {
    slug: "pcm-2-3",
    title: "Newton's Third Law",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 2, unitTitle: U[2] }],
    blurb: "For every force A→B, there's an equal and opposite force B→A. They act on DIFFERENT objects.",
    keyIdeas: [
      "Forces come in action–reaction PAIRS.",
      "Pair forces are equal magnitude, opposite direction, ACT ON DIFFERENT OBJECTS.",
      "Pair forces don't cancel (different objects, different FBDs).",
      "Applies even in acceleration — no 'winner' force.",
    ],
    sampleProblem: "Horse pulls cart with 200 N. Cart pulls horse with how much force?",
    sampleWalkthrough: "By N3L, 200 N back on the horse. Why does the system accelerate? The horse's feet push back on the GROUND; the ground pushes forward on the horse. That's a different pair.",
    flashcards: [
      { q: "Newton's 3rd law?", a: "A→B force equals B→A force, opposite direction." },
      { q: "Do pair forces cancel?", a: "No — they act on different objects." },
      { q: "Can you have a force with no reaction?", a: "No — all forces come in pairs." },
      { q: "Horse-cart problem — why does system accelerate?", a: "Because of horse-ground friction pair, not horse-cart pair." },
      { q: "Normal force reaction partner?", a: "Object pushes surface back with equal force." },
    ],
    links: [{ title: "Newton's 3rd law", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-2-4",
    title: "Newton's First Law",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 2, unitTitle: U[2] }],
    blurb: "Object at rest stays at rest, in motion stays in motion, unless net force acts.",
    keyIdeas: [
      "Inertia: resistance to change in motion; measured by mass.",
      "Equilibrium: ΣF = 0 ⇒ a = 0 (constant v, possibly zero).",
      "Static equilibrium (at rest) vs. dynamic (constant v).",
      "Inertial frames: N1L holds; non-inertial frames need fictitious forces.",
    ],
    sampleProblem: "Elevator moves at constant v upward. What's ΣF on a passenger?",
    sampleWalkthrough: "Constant v ⇒ a = 0 ⇒ ΣF = 0. Normal force equals weight: N = mg.",
    flashcards: [
      { q: "N1L?", a: "Object's velocity is constant unless a net force acts." },
      { q: "Equilibrium?", a: "ΣF = 0 (a = 0)" },
      { q: "Measure of inertia?", a: "Mass" },
      { q: "Static vs dynamic equilibrium?", a: "Static at rest; dynamic at constant nonzero v." },
      { q: "Inertial frame?", a: "A frame with no acceleration." },
    ],
    links: [{ title: "Newton's 1st law", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-2-5",
    title: "Newton's Second Law",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 2, unitTitle: U[2] }],
    blurb: "ΣF = ma, component-wise. For variable mass: F = dp/dt.",
    keyIdeas: [
      "ΣF = ma (vector); work in components.",
      "More general: F_net = dp/dt (covers rockets, variable mass).",
      "Direction of a is direction of net force.",
      "Unit: N = kg·m/s².",
    ],
    sampleProblem: "3.0 kg puck, 12 N horizontal. a = ?",
    sampleWalkthrough: "a = F/m = 12/3.0 = 4.0 m/s².",
    flashcards: [
      { q: "N2L?", a: "ΣF = ma" },
      { q: "Unit of force?", a: "Newton = kg·m/s²" },
      { q: "Generalized N2L?", a: "F_net = dp/dt" },
      { q: "Direction of a?", a: "Same as net force." },
      { q: "When is F_net = dp/dt needed?", a: "Variable mass (rockets) or relativistic." },
    ],
    links: [{ title: "Newton's 2nd law", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-2-6",
    title: "Gravitational Force",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 2, unitTitle: U[2] }],
    blurb: "Universal gravitation: F = Gm₁m₂/r². Near surface: F = mg, g ≈ 9.8 m/s².",
    keyIdeas: [
      "F = Gm₁m₂/r², G = 6.67×10⁻¹¹ N·m²/kg².",
      "Near Earth: g = GM/r² ≈ 9.8 m/s².",
      "Gravitational field points toward mass.",
      "Acceleration in free fall is INDEPENDENT of mass.",
    ],
    sampleProblem: "Force between two 1000 kg masses 2 m apart?",
    sampleWalkthrough: "F = G(1000)²/(2)² = (6.67×10⁻¹¹)(1×10⁶)/4 ≈ 1.7×10⁻⁵ N.",
    flashcards: [
      { q: "Universal gravitation?", a: "F = Gm₁m₂/r²" },
      { q: "G?", a: "6.67×10⁻¹¹ N·m²/kg²" },
      { q: "g at Earth surface?", a: "≈ 9.8 m/s²" },
      { q: "Free-fall a depends on mass?", a: "No — same for all masses in vacuum." },
      { q: "Direction of g field?", a: "Toward center of mass." },
    ],
    links: [{ title: "Gravity", url: KHAN + "/newton-gravitation", source: "Khan Academy" }],
  },
  {
    slug: "pcm-2-7",
    title: "Kinetic and Static Friction",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 2, unitTitle: U[2] }],
    blurb: "Static: f_s ≤ μ_s N (prevents motion). Kinetic: f_k = μ_k N (opposes motion).",
    keyIdeas: [
      "Static friction: 0 ≤ f_s ≤ μ_s N — adjusts up to maximum.",
      "Kinetic friction: f_k = μ_k N, opposes slipping direction.",
      "Usually μ_s > μ_k.",
      "Friction is parallel to contact surface, perpendicular to N.",
    ],
    sampleProblem: "μ_k = 0.20, mass 5 kg sliding on level surface. Friction force?",
    sampleWalkthrough: "N = mg = 49 N. f_k = μ_k N = (0.20)(49) = 9.8 N.",
    flashcards: [
      { q: "Static friction upper bound?", a: "f_s ≤ μ_s N" },
      { q: "Kinetic friction?", a: "f_k = μ_k N" },
      { q: "μ_s vs μ_k?", a: "Usually μ_s > μ_k" },
      { q: "Direction of kinetic friction?", a: "Opposite sliding velocity." },
      { q: "Does friction depend on contact area?", a: "Not in the simple model." },
    ],
    links: [{ title: "Friction", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-2-8",
    title: "Spring Forces",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 2, unitTitle: U[2] }],
    blurb: "Hooke's law: F = −kx. Spring PE: U = ½kx².",
    keyIdeas: [
      "F = −kx — force opposes displacement from equilibrium.",
      "Spring potential energy: U = ½kx².",
      "Springs in series: 1/k_eq = 1/k₁ + 1/k₂; parallel: k_eq = k₁ + k₂.",
      "Restoring force produces SHM (covered in Unit 7).",
    ],
    sampleProblem: "k = 200 N/m spring stretched 0.10 m. F and U?",
    sampleWalkthrough: "F = kx = 20 N (magnitude). U = ½(200)(0.10)² = 1.0 J.",
    flashcards: [
      { q: "Hooke's law?", a: "F = −kx" },
      { q: "Spring PE?", a: "U = ½kx²" },
      { q: "Springs in parallel?", a: "k_eq = k₁ + k₂ (stiffer)" },
      { q: "Springs in series?", a: "1/k_eq = 1/k₁ + 1/k₂ (softer)" },
      { q: "What produces SHM?", a: "Linear restoring force F = −kx." },
    ],
    links: [{ title: "Springs", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-2-9",
    title: "Resistive Forces",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 2, unitTitle: U[2] }],
    blurb: "Drag: F = −bv (linear, low speed) or F = −cv² (quadratic, high speed). Terminal velocity when F_drag = mg.",
    keyIdeas: [
      "Linear drag F = −bv: v(t) = v_terminal(1 − e^(−bt/m)) falling from rest.",
      "Quadratic drag F = −cv²: terminal v = √(mg/c).",
      "Terminal velocity: net force = 0, constant v.",
      "Solve ma = mg − bv with first-order linear ODE.",
    ],
    sampleProblem: "Object falls under linear drag F_drag = bv. Find v_terminal.",
    sampleWalkthrough: "At terminal v: mg = b·v_terminal ⇒ v_terminal = mg/b.",
    flashcards: [
      { q: "Linear drag?", a: "F = −bv" },
      { q: "Quadratic drag?", a: "F = −cv²" },
      { q: "Terminal v (linear drag)?", a: "v_t = mg/b" },
      { q: "Terminal v (quadratic drag)?", a: "v_t = √(mg/c)" },
      { q: "At terminal velocity?", a: "Net force = 0, constant v." },
    ],
    links: [{ title: "Air resistance", url: HP, source: "HyperPhysics" }],
  },
  {
    slug: "pcm-2-10",
    title: "Circular Motion",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 2, unitTitle: U[2] }],
    blurb: "Uniform: a_c = v²/r, directed toward center. Period T = 2πr/v.",
    keyIdeas: [
      "Centripetal acceleration: a_c = v²/r = ω²r.",
      "Centripetal force: F_c = mv²/r; directed toward center.",
      "Period T = 2πr/v; frequency f = 1/T.",
      "Common sources: tension (string), friction (car), gravity (orbit), normal (banked turn).",
    ],
    sampleProblem: "Car at v = 20 m/s on circle r = 50 m. a_c?",
    sampleWalkthrough: "a_c = v²/r = 400/50 = 8.0 m/s², toward center.",
    flashcards: [
      { q: "Centripetal acceleration?", a: "a_c = v²/r" },
      { q: "Direction?", a: "Toward center of circle." },
      { q: "Centripetal force?", a: "F_c = mv²/r, toward center." },
      { q: "Period of uniform circular motion?", a: "T = 2πr/v" },
      { q: "Is F_c a 'new' force?", a: "No — it's whatever real force provides the centripetal component." },
    ],
    links: [{ title: "Circular motion", url: KHAN + "/circular-motion-and-gravitation", source: "Khan Academy" }],
  },
  {
    slug: "pcm-3-1",
    title: "Translational Kinetic Energy",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 3, unitTitle: U[3] }],
    blurb: "KE = ½mv². Scalar quantity; depends on speed squared.",
    keyIdeas: [
      "KE = ½mv².",
      "Scalar — no direction; always ≥ 0.",
      "Doubling v quadruples KE.",
      "Work–energy theorem: W_net = ΔKE.",
    ],
    sampleProblem: "KE of 0.145 kg baseball at 40 m/s?",
    sampleWalkthrough: "KE = ½(0.145)(40)² = ½(0.145)(1600) = 116 J.",
    flashcards: [
      { q: "KE formula?", a: "KE = ½mv²" },
      { q: "Double v?", a: "KE × 4" },
      { q: "Work–energy theorem?", a: "W_net = ΔKE" },
      { q: "Units of KE?", a: "Joules" },
      { q: "Is KE a vector?", a: "No — scalar." },
    ],
    links: [{ title: "KE", url: KHAN + "/work-and-energy", source: "Khan Academy" }],
  },
  {
    slug: "pcm-3-2",
    title: "Work",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 3, unitTitle: U[3] }],
    blurb: "W = ∫ F·dr. Constant F along motion: W = F·d·cos θ.",
    keyIdeas: [
      "W = ∫ F·dr (line integral along path).",
      "Constant F: W = F d cos θ (θ = angle between F and displacement).",
      "F ⊥ v: W = 0 (no work, e.g., centripetal force).",
      "Sign: W > 0 if F has component along motion; < 0 if opposite.",
      "Net work = ΔKE.",
    ],
    sampleProblem: "A 30 N force pulls a box 5 m at 60° above horizontal. Work done?",
    sampleWalkthrough: "W = Fd cos θ = (30)(5) cos 60° = 75 J.",
    flashcards: [
      { q: "Work (constant F)?", a: "W = Fd cos θ" },
      { q: "General work?", a: "W = ∫ F·dr" },
      { q: "F ⊥ motion?", a: "W = 0" },
      { q: "W of friction?", a: "Negative (opposes motion)." },
      { q: "Net work ↔ KE?", a: "W_net = ΔKE" },
    ],
    links: [{ title: "Work", url: KHAN + "/work-and-energy", source: "Khan Academy" }],
  },
  {
    slug: "pcm-3-3",
    title: "Potential Energy",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 3, unitTitle: U[3] }],
    blurb: "Gravitational: U = mgh. Spring: U = ½kx². Conservative forces have well-defined U.",
    keyIdeas: [
      "U defined only for CONSERVATIVE forces (path-independent).",
      "Gravitational near surface: U_g = mgh.",
      "Spring: U_s = ½kx².",
      "Universal gravitation: U = −GMm/r (zero at r = ∞).",
      "F = −dU/dx (1D) — force is negative gradient of U.",
    ],
    sampleProblem: "Mass 2 kg raised h = 3 m. ΔU_g?",
    sampleWalkthrough: "ΔU_g = mgh = (2)(9.8)(3) = 58.8 J.",
    flashcards: [
      { q: "Gravitational U near surface?", a: "U = mgh" },
      { q: "Spring U?", a: "U = ½kx²" },
      { q: "Universal gravitation U?", a: "U = −GMm/r" },
      { q: "Relation F and U?", a: "F = −dU/dx" },
      { q: "Does U depend on path?", a: "No — only endpoints (for conservative forces)." },
    ],
    links: [{ title: "Potential energy", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-3-4",
    title: "Conservation of Energy",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 3, unitTitle: U[3] }],
    blurb: "In an isolated system: KE + U = constant. With non-conservative forces: ΔE = W_nc.",
    keyIdeas: [
      "Mechanical energy E = KE + U.",
      "Only conservative forces: E = constant.",
      "Non-conservative forces (friction): ΔE = W_nc (friction does negative work, reduces E).",
      "Energy is always conserved overall — but can leave as heat/sound etc.",
    ],
    sampleProblem: "Ball dropped from h. Find v just before hitting ground (no friction).",
    sampleWalkthrough: "mgh = ½mv² ⇒ v = √(2gh).",
    flashcards: [
      { q: "Mechanical energy?", a: "E = KE + U" },
      { q: "Conservation (ideal)?", a: "ΔKE + ΔU = 0" },
      { q: "With non-conservative forces?", a: "ΔE = W_nc" },
      { q: "Dropped from rest, v at ground?", a: "v = √(2gh)" },
      { q: "Is total energy always conserved?", a: "Yes — in closed systems (mech E can change via heat etc)." },
    ],
    links: [{ title: "Energy conservation", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-3-5",
    title: "Power",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 3, unitTitle: U[3] }],
    blurb: "Rate of work: P = dW/dt. Constant F: P = F·v.",
    keyIdeas: [
      "P = dW/dt = dE/dt.",
      "Constant F, velocity v: P = F·v cos θ (dot product).",
      "Unit: Watt = J/s.",
      "Horsepower: 1 hp ≈ 746 W.",
      "Average power: P_avg = W_total/t.",
    ],
    sampleProblem: "Motor does 1200 J of work in 4 s. Power?",
    sampleWalkthrough: "P = W/t = 1200/4 = 300 W.",
    flashcards: [
      { q: "Definition of power?", a: "P = dW/dt" },
      { q: "Constant F, velocity v?", a: "P = F·v" },
      { q: "Unit?", a: "Watt (W) = J/s" },
      { q: "Horsepower?", a: "1 hp ≈ 746 W" },
      { q: "Average power?", a: "P_avg = ΔW/Δt" },
    ],
    links: [{ title: "Power", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-4-1",
    title: "Linear Momentum",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 4, unitTitle: U[4] }],
    blurb: "p = mv. Vector quantity. Total momentum of isolated system is conserved.",
    keyIdeas: [
      "p = mv — vector.",
      "Units: kg·m/s.",
      "For systems: P = Σp_i = M·v_cm.",
      "Conservation: if ΣF_ext = 0, P_total is constant.",
    ],
    sampleProblem: "p of 1500 kg car at 20 m/s east?",
    sampleWalkthrough: "p = mv = (1500)(20) = 30,000 kg·m/s east.",
    flashcards: [
      { q: "Momentum?", a: "p = mv (vector)" },
      { q: "Units of p?", a: "kg·m/s" },
      { q: "System momentum?", a: "P = M v_cm" },
      { q: "When is P conserved?", a: "When net external force = 0." },
      { q: "Is p a scalar or vector?", a: "Vector." },
    ],
    links: [{ title: "Momentum", url: KHAN + "/linear-momentum", source: "Khan Academy" }],
  },
  {
    slug: "pcm-4-2",
    title: "Change in Momentum and Impulse",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 4, unitTitle: U[4] }],
    blurb: "J = Δp = ∫ F dt. Average force on short impact: F_avg = Δp/Δt.",
    keyIdeas: [
      "Impulse J = Δp (vector).",
      "J = ∫ F dt = area under F–t graph.",
      "Average force: F_avg = Δp/Δt.",
      "Long contact time ⇒ lower force (airbags, padding).",
    ],
    sampleProblem: "0.145 kg baseball hits bat at 30 m/s, rebounds at 40 m/s (opposite). J?",
    sampleWalkthrough: "Δv = 40 − (−30) = 70 m/s. J = mΔv = (0.145)(70) = 10.15 kg·m/s.",
    flashcards: [
      { q: "Impulse definition?", a: "J = Δp = ∫F dt" },
      { q: "F_avg from impulse?", a: "F_avg = Δp/Δt" },
      { q: "Area under F-t?", a: "Impulse" },
      { q: "Why airbags reduce injury?", a: "Longer Δt → lower F_avg for same Δp" },
      { q: "Sign of impulse?", a: "Direction of Δp." },
    ],
    links: [{ title: "Impulse", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-4-3",
    title: "Conservation of Linear Momentum",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 4, unitTitle: U[4] }],
    blurb: "No net external force ⇒ P_total conserved. Works in each direction independently.",
    keyIdeas: [
      "ΣF_ext = 0 ⇒ P_total before = P_total after.",
      "Apply component-wise (x and y separately).",
      "Internal forces don't change total P.",
      "Common applications: collisions, explosions, recoil.",
    ],
    sampleProblem: "4 kg and 2 kg at rest. Explosion sends 4 kg at 3 m/s left. v of 2 kg?",
    sampleWalkthrough: "P_before = 0. P_after = (4)(−3) + (2)(v₂) = 0 ⇒ v₂ = +6 m/s (right).",
    flashcards: [
      { q: "When is P conserved?", a: "When ΣF_ext = 0." },
      { q: "Do internal forces change P?", a: "No." },
      { q: "Explosion from rest?", a: "Fragments' momenta sum to zero." },
      { q: "Conservation in 2D?", a: "Apply x and y separately." },
      { q: "Recoil of rifle?", a: "Bullet's forward p = rifle's backward p." },
    ],
    links: [{ title: "Conservation of momentum", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-4-4",
    title: "Elastic and Inelastic Collisions",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 4, unitTitle: U[4] }],
    blurb: "Elastic: KE + p conserved. Inelastic: p conserved, KE lost. Perfectly inelastic: stick together.",
    keyIdeas: [
      "All collisions: p conserved (if external F = 0).",
      "Elastic: KE ALSO conserved.",
      "Inelastic: KE lost (to heat, sound, deformation).",
      "Perfectly inelastic: objects stick; maximum KE loss consistent with p conservation.",
      "1D elastic between m₁ (v) and m₂ (rest): v₁' = (m₁−m₂)/(m₁+m₂)·v, v₂' = 2m₁/(m₁+m₂)·v.",
    ],
    sampleProblem: "5 kg at 4 m/s hits 3 kg at rest (perfectly inelastic). Final v?",
    sampleWalkthrough: "Conservation of p: (5)(4) = (5+3)v ⇒ v = 20/8 = 2.5 m/s.",
    flashcards: [
      { q: "Elastic collision?", a: "Both p and KE conserved." },
      { q: "Inelastic?", a: "p conserved, KE lost." },
      { q: "Perfectly inelastic?", a: "Objects stick; maximum KE loss." },
      { q: "Elastic, m₁=m₂, m₂ at rest?", a: "They exchange velocities." },
      { q: "Momentum conservation always holds?", a: "Yes, in any collision (if no external F)." },
    ],
    links: [{ title: "Collisions", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-5-1",
    title: "Rotational Kinematics",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 5, unitTitle: U[5] }],
    blurb: "θ, ω, α. Same-form equations as linear kinematics with x→θ, v→ω, a→α.",
    keyIdeas: [
      "ω = dθ/dt, α = dω/dt.",
      "Constant α: θ = θ₀ + ω₀t + ½αt², ω² = ω₀² + 2α Δθ.",
      "Units: radians, rad/s, rad/s².",
      "1 revolution = 2π rad.",
    ],
    sampleProblem: "Wheel spinning at 10 rad/s, α = 2 rad/s². ω after 3 s?",
    sampleWalkthrough: "ω = ω₀ + αt = 10 + (2)(3) = 16 rad/s.",
    flashcards: [
      { q: "ω definition?", a: "ω = dθ/dt" },
      { q: "α definition?", a: "α = dω/dt" },
      { q: "Constant α: θ(t)?", a: "θ = θ₀ + ω₀t + ½αt²" },
      { q: "Constant α: ω²?", a: "ω² = ω₀² + 2αΔθ" },
      { q: "1 revolution?", a: "2π rad" },
    ],
    links: [{ title: "Rotational motion", url: KHAN + "/torque-angular-momentum", source: "Khan Academy" }],
  },
  {
    slug: "pcm-5-2",
    title: "Connecting Linear and Rotational Motion",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 5, unitTitle: U[5] }],
    blurb: "s = rθ, v = rω, a_t = rα. Plus centripetal a_c = rω² = v²/r.",
    keyIdeas: [
      "Arc length s = rθ (θ in radians).",
      "Tangential speed v = rω.",
      "Tangential acceleration a_t = rα.",
      "Centripetal acceleration a_c = rω² = v²/r.",
      "For rolling without slipping: v = rω, a = rα.",
    ],
    sampleProblem: "Wheel r = 0.30 m rolling at 10 m/s without slipping. ω?",
    sampleWalkthrough: "ω = v/r = 10/0.30 ≈ 33.3 rad/s.",
    flashcards: [
      { q: "Arc length?", a: "s = rθ" },
      { q: "Tangential v?", a: "v = rω" },
      { q: "Tangential a?", a: "a_t = rα" },
      { q: "Centripetal a?", a: "a_c = rω² = v²/r" },
      { q: "Rolling without slipping?", a: "v = rω, a = rα at the center of mass" },
    ],
    links: [{ title: "Rolling motion", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-5-3",
    title: "Torque",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 5, unitTitle: U[5] }],
    blurb: "τ = r × F, magnitude τ = rF sin θ. Right-hand rule for direction.",
    keyIdeas: [
      "τ = r × F; magnitude rF sin θ (θ between r and F).",
      "Unit: N·m.",
      "Torque about an axis; moment arm = r sin θ.",
      "Force through the axis → zero torque.",
    ],
    sampleProblem: "Apply 20 N perpendicular to a wrench at 0.30 m from bolt. Torque?",
    sampleWalkthrough: "τ = rF sin 90° = (0.30)(20) = 6 N·m.",
    flashcards: [
      { q: "Torque definition?", a: "τ = r × F" },
      { q: "Magnitude?", a: "τ = rF sin θ" },
      { q: "Units?", a: "N·m" },
      { q: "Max torque angle?", a: "θ = 90°" },
      { q: "Direction via RHR?", a: "Fingers from r to F; thumb = τ direction." },
    ],
    links: [{ title: "Torque", url: KHAN + "/torque-angular-momentum", source: "Khan Academy" }],
  },
  {
    slug: "pcm-5-4",
    title: "Rotational Inertia",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 5, unitTitle: U[5] }],
    blurb: "I = Σm_i r_i² (discrete) = ∫r² dm (continuous). Depends on mass distribution.",
    keyIdeas: [
      "I = ∫ r² dm — rotational analogue of mass.",
      "Point mass: I = mr².",
      "Solid cylinder (axis): I = ½MR².",
      "Solid sphere: I = (2/5)MR².",
      "Thin rod (center): I = (1/12)ML²; (end): I = (1/3)ML².",
      "Parallel-axis theorem: I = I_cm + Md².",
    ],
    sampleProblem: "Solid sphere M = 2 kg, R = 0.1 m. I?",
    sampleWalkthrough: "I = (2/5)MR² = (2/5)(2)(0.01) = 0.008 kg·m².",
    flashcards: [
      { q: "I for solid cylinder?", a: "½MR²" },
      { q: "I for solid sphere?", a: "(2/5)MR²" },
      { q: "I for thin rod about center?", a: "(1/12)ML²" },
      { q: "I for thin rod about end?", a: "(1/3)ML²" },
      { q: "Parallel-axis theorem?", a: "I = I_cm + Md²" },
    ],
    links: [{ title: "Moment of inertia", url: HP, source: "HyperPhysics" }],
  },
  {
    slug: "pcm-5-5",
    title: "Rotational Equilibrium",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 5, unitTitle: U[5] }],
    blurb: "Static equilibrium: ΣF = 0 AND Στ = 0 (about any axis).",
    keyIdeas: [
      "Need BOTH ΣF = 0 and Στ = 0.",
      "Can choose torque axis at any convenient point.",
      "Pick axis so unknown forces have zero moment arm (eliminate them).",
      "Watch signs: counterclockwise positive by convention.",
    ],
    sampleProblem: "Uniform 10 kg beam, 4 m, supported at ends. Person 60 kg stands 1 m from left end. Force on each support?",
    sampleWalkthrough:
      "ΣF: F_L + F_R = (10 + 60)g = 686 N.\nΣτ about left: F_R(4) = (10g)(2) + (60g)(1) = 196 + 588 = 784 ⇒ F_R = 196 N.\nF_L = 686 − 196 = 490 N.",
    flashcards: [
      { q: "Conditions for static equilibrium?", a: "ΣF = 0 AND Στ = 0." },
      { q: "Best axis choice?", a: "Through an unknown force — eliminates it." },
      { q: "Sign convention for torque?", a: "CCW positive (by most texts)." },
      { q: "Uniform beam weight acts where?", a: "At geometric center." },
      { q: "Is one condition (ΣF=0) sufficient?", a: "No — need Στ=0 too." },
    ],
    links: [{ title: "Static equilibrium", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-5-6",
    title: "Newton's Second Law in Rotational Form",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 5, unitTitle: U[5] }],
    blurb: "Στ = Iα (about a fixed axis). The rotational counterpart of ΣF = ma.",
    keyIdeas: [
      "Στ = Iα about a fixed axis.",
      "Write translational (ΣF = ma_cm) AND rotational (Στ = Iα) for compound problems.",
      "Constraint for rolling without slipping: a = rα, v = rω.",
      "For yo-yo, pulley, falling spool: use both equations.",
    ],
    sampleProblem: "Net torque 12 N·m on wheel with I = 4 kg·m². α?",
    sampleWalkthrough: "α = τ/I = 12/4 = 3 rad/s².",
    flashcards: [
      { q: "Rotational N2L?", a: "Στ = Iα" },
      { q: "Rolling without slipping constraint?", a: "a = rα" },
      { q: "For compound problem with pulley, need?", a: "Linear and rotational N2L simultaneously." },
      { q: "Units of Iα?", a: "N·m (same as τ)" },
      { q: "Direction of α?", a: "Same as Στ." },
    ],
    links: [{ title: "Rotational dynamics", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-6-1",
    title: "Rotational Kinetic Energy",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 6, unitTitle: U[6] }],
    blurb: "KE_rot = ½Iω². For rolling: total KE = ½Mv² + ½Iω² = ½Mv²(1 + I/(MR²)).",
    keyIdeas: [
      "KE_rot = ½Iω².",
      "Rolling: KE_total = ½Mv²_cm + ½I_cm ω².",
      "Conservation of energy with rotation: KE_trans + KE_rot + U = const (ideal).",
      "Different I → different fractions of KE are translational vs. rotational.",
    ],
    sampleProblem: "Solid cylinder (I = ½MR²) rolls without slipping. Translational vs. rotational KE?",
    sampleWalkthrough:
      "KE_rot = ½Iω² = ½(½MR²)(v/R)² = ¼Mv². KE_trans = ½Mv². So rotational is 1/3 of total.",
    flashcards: [
      { q: "KE_rot?", a: "½Iω²" },
      { q: "Rolling: total KE?", a: "½Mv² + ½Iω²" },
      { q: "Solid cylinder rolling: KE_rot/KE_total?", a: "1/3" },
      { q: "Hoop rolling: KE_rot/KE_total?", a: "1/2 (I = MR²)" },
      { q: "Solid sphere rolling: KE_rot/KE_total?", a: "2/7" },
    ],
    links: [{ title: "Rotational KE", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-6-2",
    title: "Torque and Work",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 6, unitTitle: U[6] }],
    blurb: "W = ∫τ dθ. Power P = τω.",
    keyIdeas: [
      "Rotational work: W = ∫ τ dθ.",
      "Constant τ: W = τΔθ.",
      "Power: P = τω (rotational analogue of F·v).",
      "Net rotational work = ΔKE_rot (work–energy theorem).",
    ],
    sampleProblem: "τ = 15 N·m applied over Δθ = 4 rad. Work?",
    sampleWalkthrough: "W = τΔθ = (15)(4) = 60 J.",
    flashcards: [
      { q: "Rotational work (constant τ)?", a: "W = τΔθ" },
      { q: "General rotational work?", a: "W = ∫τ dθ" },
      { q: "Rotational power?", a: "P = τω" },
      { q: "Net rotational work ↔ KE?", a: "W_net = ΔKE_rot" },
      { q: "Units?", a: "Joules" },
    ],
    links: [{ title: "Rotational work", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-6-3",
    title: "Angular Momentum and Angular Impulse",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 6, unitTitle: U[6] }],
    blurb: "L = Iω (rigid body); L = r × p (particle). Angular impulse = τΔt = ΔL.",
    keyIdeas: [
      "Rigid body about fixed axis: L = Iω.",
      "Particle: L = r × p.",
      "Angular impulse: J_ang = ∫ τ dt = ΔL.",
      "Units: kg·m²/s.",
      "Vector — use right-hand rule for direction.",
    ],
    sampleProblem: "I = 0.5 kg·m², ω = 8 rad/s. L?",
    sampleWalkthrough: "L = Iω = (0.5)(8) = 4 kg·m²/s.",
    flashcards: [
      { q: "Angular momentum (rigid body)?", a: "L = Iω" },
      { q: "Angular momentum (particle)?", a: "L = r × p" },
      { q: "Angular impulse?", a: "J_ang = ∫τ dt = ΔL" },
      { q: "Units of L?", a: "kg·m²/s" },
      { q: "L vector direction?", a: "Along axis; right-hand rule." },
    ],
    links: [{ title: "Angular momentum", url: KHAN + "/torque-angular-momentum", source: "Khan Academy" }],
  },
  {
    slug: "pcm-6-4",
    title: "Conservation of Angular Momentum",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 6, unitTitle: U[6] }],
    blurb: "No external torque ⇒ L conserved. Figure-skater spin: pulls arms in, I drops, ω rises.",
    keyIdeas: [
      "Στ_ext = 0 ⇒ L conserved.",
      "Skater pulls arms in → I decreases → ω increases so L stays same.",
      "Collisions with rotation: combine linear p conservation with angular L conservation.",
      "Planet orbits: L conserved about sun (Kepler's 2nd law).",
    ],
    sampleProblem: "Skater has I = 5 kg·m² spinning at 2 rad/s. Pulls arms in to I = 2 kg·m². New ω?",
    sampleWalkthrough: "I₁ω₁ = I₂ω₂ ⇒ ω₂ = (5)(2)/2 = 5 rad/s.",
    flashcards: [
      { q: "When is L conserved?", a: "When net external torque = 0." },
      { q: "Skater pulls arms in?", a: "I decreases, ω increases, L constant." },
      { q: "Kepler's 2nd law explained?", a: "L conserved about sun → equal areas in equal times." },
      { q: "Conservation when axle is frictionless?", a: "L conserved about axle." },
      { q: "Does KE stay constant when L conserved?", a: "No — work is done (muscles)." },
    ],
    links: [{ title: "Conservation of L", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-6-5",
    title: "Rolling",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 6, unitTitle: U[6] }],
    blurb: "Rolling without slipping: v_cm = rω, a_cm = rα. Objects with smaller I/MR² reach bottom faster.",
    keyIdeas: [
      "Rolling without slipping: v_cm = rω, a_cm = rα.",
      "Static friction provides the torque — does NO work (contact point is instantaneously at rest).",
      "Down incline: a_cm = g sin θ / (1 + I/(MR²)).",
      "Solid sphere (I = 2/5 MR²) beats cylinder (½MR²) beats hoop (MR²) at bottom of incline.",
    ],
    sampleProblem: "Solid sphere rolls down frictionless incline of angle θ without slipping. a_cm?",
    sampleWalkthrough:
      "a_cm = g sin θ / (1 + I/(MR²)) = g sin θ / (1 + 2/5) = (5/7)g sin θ.",
    flashcards: [
      { q: "Rolling w/o slipping constraint?", a: "v = rω, a = rα" },
      { q: "Does static friction do work?", a: "No — contact point is instantaneously at rest." },
      { q: "Which rolls fastest down: sphere, cylinder, hoop?", a: "Sphere (smallest I/MR²)" },
      { q: "a_cm down incline?", a: "g sin θ / (1 + I/(MR²))" },
      { q: "Hoop I/MR²?", a: "1 (slowest)" },
    ],
    links: [{ title: "Rolling motion", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-6-6",
    title: "Motion of Orbiting Satellites",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 6, unitTitle: U[6] }],
    blurb: "Circular orbit: GMm/r² = mv²/r. v = √(GM/r), T² ∝ r³ (Kepler).",
    keyIdeas: [
      "Gravity provides centripetal force: GMm/r² = mv²/r.",
      "Orbital speed: v = √(GM/r).",
      "Period: T = 2π√(r³/GM) — Kepler's third law.",
      "Total mechanical E (bound orbit) = −GMm/(2r) (negative).",
      "Escape speed from radius r: v_esc = √(2GM/r).",
    ],
    sampleProblem: "Satellite in low Earth orbit (r ≈ R_E = 6.37×10⁶ m). v?",
    sampleWalkthrough: "v = √(GM/r) = √((6.67×10⁻¹¹)(5.97×10²⁴)/6.37×10⁶) ≈ 7900 m/s.",
    flashcards: [
      { q: "Orbital speed?", a: "v = √(GM/r)" },
      { q: "Kepler's 3rd law?", a: "T² ∝ r³ (T = 2π√(r³/GM))" },
      { q: "Total E of bound circular orbit?", a: "E = −GMm/(2r)" },
      { q: "Escape speed?", a: "v_esc = √(2GM/r)" },
      { q: "What provides centripetal force?", a: "Gravity" },
    ],
    links: [{ title: "Orbits", url: KHAN + "/newton-gravitation", source: "Khan Academy" }],
  },
  {
    slug: "pcm-7-1",
    title: "Defining Simple Harmonic Motion (SHM)",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 7, unitTitle: U[7] }],
    blurb: "SHM: linear restoring force F = −kx produces sinusoidal motion.",
    keyIdeas: [
      "SHM criterion: F ∝ −x (linear restoring force).",
      "Equation: d²x/dt² = −ω²x.",
      "Solutions: x(t) = A cos(ωt + φ).",
      "Examples: spring-mass, pendulum (small angles).",
    ],
    sampleProblem: "Is the motion x(t) = 0.1 cos(4t) SHM? What's ω?",
    sampleWalkthrough: "Yes — sinusoidal with angular frequency ω = 4 rad/s.",
    flashcards: [
      { q: "SHM force rule?", a: "F = −kx (linear restoring)" },
      { q: "ODE form?", a: "d²x/dt² = −ω²x" },
      { q: "Solution?", a: "x(t) = A cos(ωt + φ)" },
      { q: "Pendulum SHM condition?", a: "Small angle approximation (sin θ ≈ θ)" },
      { q: "Is x = A cos(ωt) + Bcos(2ωt) SHM?", a: "No — mixed frequencies aren't SHM." },
    ],
    links: [{ title: "SHM", url: KHAN + "/mechanical-waves-and-sound", source: "Khan Academy" }],
  },
  {
    slug: "pcm-7-2",
    title: "Frequency and Period of SHM",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 7, unitTitle: U[7] }],
    blurb: "Spring-mass: ω = √(k/m). Pendulum: ω = √(g/L). T = 2π/ω.",
    keyIdeas: [
      "Spring-mass: ω = √(k/m); T = 2π√(m/k).",
      "Simple pendulum (small angle): ω = √(g/L); T = 2π√(L/g).",
      "Physical pendulum: ω = √(mgd/I).",
      "Period INDEPENDENT of amplitude for small oscillations.",
    ],
    sampleProblem: "2 kg on k = 200 N/m spring. T?",
    sampleWalkthrough: "T = 2π√(m/k) = 2π√(2/200) = 2π(0.1) ≈ 0.63 s.",
    flashcards: [
      { q: "Spring-mass ω?", a: "ω = √(k/m)" },
      { q: "Spring-mass T?", a: "T = 2π√(m/k)" },
      { q: "Simple pendulum T?", a: "T = 2π√(L/g)" },
      { q: "Is T amplitude-dependent?", a: "No (for ideal SHM, small angles)." },
      { q: "Physical pendulum T?", a: "T = 2π√(I/(mgd))" },
    ],
    links: [{ title: "SHM period", url: HP, source: "HyperPhysics" }],
  },
  {
    slug: "pcm-7-3",
    title: "Representing and Analyzing SHM",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 7, unitTitle: U[7] }],
    blurb: "x, v, a are sinusoids; v is 90° out of phase with x; a is 180° out.",
    keyIdeas: [
      "x(t) = A cos(ωt + φ).",
      "v(t) = −Aω sin(ωt + φ), amplitude Aω.",
      "a(t) = −Aω² cos(ωt + φ) = −ω²x.",
      "At x = ±A (ends): v = 0, a = max.",
      "At x = 0 (center): v = max, a = 0.",
    ],
    sampleProblem: "Amplitude 0.05 m, ω = 10 rad/s. Max v? Max a?",
    sampleWalkthrough: "v_max = Aω = 0.5 m/s. a_max = Aω² = 5 m/s².",
    flashcards: [
      { q: "v_max in SHM?", a: "Aω" },
      { q: "a_max in SHM?", a: "Aω²" },
      { q: "Where is v max?", a: "At equilibrium position (x=0)" },
      { q: "Where is a max?", a: "At endpoints (x=±A)" },
      { q: "Phase between x and a?", a: "180° (a = −ω²x)" },
    ],
    links: [{ title: "SHM graphs", url: KHAN, source: "Khan Academy" }],
  },
  {
    slug: "pcm-7-4",
    title: "Energy of Simple Harmonic Oscillators",
    courses: [{ courseSlug: "ap-physics-c-mech", unitNumber: 7, unitTitle: U[7] }],
    blurb: "Total E = ½kA² = ½mω²A². KE and U exchange every quarter cycle.",
    keyIdeas: [
      "Total mechanical E = ½kA² = ½mv_max² = ½mω²A².",
      "E is constant in ideal SHM.",
      "At equilibrium: all KE; at extremes: all U.",
      "KE(t) + U(t) = E (constant).",
    ],
    sampleProblem: "k = 400 N/m, A = 0.10 m. Total E?",
    sampleWalkthrough: "E = ½kA² = ½(400)(0.01) = 2.0 J.",
    flashcards: [
      { q: "Total E in SHM?", a: "E = ½kA² = ½mω²A²" },
      { q: "At x=0 (equilibrium)?", a: "E = KE (all KE)" },
      { q: "At x=±A?", a: "E = U (all U)" },
      { q: "Max KE?", a: "½mv_max² = ½kA²" },
      { q: "Is E constant in ideal SHM?", a: "Yes — no damping." },
    ],
    links: [{ title: "SHM energy", url: KHAN, source: "Khan Academy" }],
  },
];
