import type { Lesson } from "@/lib/topics";

/** AP Statistics — one Lesson per CED topic across all 9 units (80 topics). */

const KA = "https://www.khanacademy.org/math/ap-statistics";

const U = {
  1: "Exploring One-Variable Data",
  2: "Exploring Two-Variable Data",
  3: "Collecting Data",
  4: "Probability, Random Variables, and Probability Distributions",
  5: "Sampling Distributions",
  6: "Inference for Categorical Data: Proportions",
  7: "Inference for Quantitative Data: Means",
  8: "Inference for Categorical Data: Chi-Square",
  9: "Inference for Quantitative Data: Slopes",
};

const mk = (
  unit: keyof typeof U,
  id: string,
  title: string,
  blurb: string,
  keyIdeas: string[],
  sampleProblem: string,
  sampleWalkthrough: string,
  flashcards: { q: string; a: string }[]
): Lesson => ({
  slug: `stats-${id.replace(".", "-")}`,
  title,
  courses: [{ courseSlug: "ap-statistics", unitNumber: unit, unitTitle: U[unit] }],
  blurb,
  keyIdeas,
  sampleProblem,
  sampleWalkthrough,
  flashcards,
  links: [{ title: "AP Statistics", url: KA, source: "Khan Academy" }],
});

export const AP_STATISTICS_LESSONS: Lesson[] = [
  mk(1, "1.1", "Introducing Statistics: What Can We Learn from Data?",
    "Statistics turns variability into insight; variation is the object of study.",
    [
      "Variation is what makes statistics a field.",
      "Data = recorded observations; statistics = interpretation.",
      "Individual = the unit being measured; variable = the attribute.",
    ],
    "Is 'breed of dog' categorical or quantitative?",
    "Categorical — it's a label/group, not a numerical measurement.",
    [
      { q: "Individual?", a: "The unit (person, thing) being measured." },
      { q: "Variable?", a: "The attribute being recorded for each individual." },
      { q: "Categorical vs quantitative?", a: "Categorical = labels; quantitative = numerical." },
      { q: "Why study variation?", a: "Because differences between individuals contain information." },
      { q: "Parameter vs statistic?", a: "Parameter describes population; statistic describes sample." },
    ],
  ),
  mk(1, "1.2", "The Language of Variation: Variables",
    "Variables are categorical or quantitative; quantitative split into discrete vs. continuous.",
    [
      "Categorical: values are labels (Male/Female, red/blue).",
      "Quantitative: values are numbers.",
      "Discrete: countable values (children in family).",
      "Continuous: uncountable / measured values (height).",
    ],
    "Classify: 'number of texts sent today' — categorical, discrete, continuous?",
    "Quantitative and discrete (you count whole integers).",
    [
      { q: "Discrete variable?", a: "Takes countable values." },
      { q: "Continuous variable?", a: "Takes any value in an interval." },
      { q: "Height — discrete or continuous?", a: "Continuous." },
      { q: "Shoe size — discrete or continuous?", a: "Usually discrete (½ increments)." },
      { q: "Zip code — categorical or quantitative?", a: "Categorical (numbers used as labels)." },
    ],
  ),
  mk(1, "1.3", "Representing a Categorical Variable with Tables",
    "Frequency and relative-frequency tables summarize categorical counts.",
    [
      "Frequency = count; relative frequency = proportion.",
      "Marginal distribution from two-way table = totals.",
      "Conditional distribution = restricting to one category.",
    ],
    "A class has 12 seniors, 8 juniors. Relative frequency of juniors?",
    "8/(12+8) = 8/20 = 0.4 (40%).",
    [
      { q: "Relative frequency?", a: "Proportion = count / total." },
      { q: "Marginal distribution?", a: "Row or column totals in two-way table." },
      { q: "Conditional distribution?", a: "Distribution restricted to one category." },
      { q: "Do proportions sum to 1?", a: "Yes." },
      { q: "Two-way table shows what?", a: "Joint distribution of two categorical variables." },
    ],
  ),
  mk(1, "1.4", "Representing a Categorical Variable with Graphs",
    "Bar graphs and pie charts visualize categorical distributions.",
    [
      "Bar graph: bars proportional to frequency; gaps between bars.",
      "Pie chart: slice = proportion of whole.",
      "Mosaic plot shows two categorical variables at once.",
      "Always label axes, include sample size.",
    ],
    "Survey of 100 students shows: 40 like pizza, 30 burgers, 30 salad. Bar height for burgers?",
    "30 (or relative frequency 0.30).",
    [
      { q: "Bar graph vs histogram?", a: "Bar graph: categorical (gaps). Histogram: quantitative (no gaps)." },
      { q: "Pie chart best for?", a: "Showing parts of a whole, few categories." },
      { q: "Mosaic plot?", a: "Visualizes two categorical variables' joint distribution." },
      { q: "Do proportions matter?", a: "Yes — area or height should reflect them accurately." },
      { q: "Misleading bar graphs?", a: "Often from truncated y-axis." },
    ],
  ),
  mk(1, "1.5", "Representing a Quantitative Variable with Graphs",
    "Dotplots, stemplots, histograms display quantitative distributions.",
    [
      "Dotplot: one dot per observation.",
      "Stemplot (stem-and-leaf) keeps raw data visible.",
      "Histogram: bins with no gaps; shape depends on bin width.",
      "Ogive: cumulative relative frequency.",
    ],
    "Data: 12, 15, 18, 22, 25. Make a stemplot.",
    "Stems = 1,2. Leaves: 1|2 5 8  2|2 5.",
    [
      { q: "Dotplot?", a: "One dot per data value on a number line." },
      { q: "Stemplot preserves?", a: "Individual data values." },
      { q: "Histogram bins?", a: "Non-overlapping equal-width intervals." },
      { q: "Shape depends on bin width?", a: "Yes — can mask or reveal structure." },
      { q: "Ogive?", a: "Cumulative relative-frequency graph." },
    ],
  ),
  mk(1, "1.6", "Describing the Distribution of a Quantitative Variable",
    "SOCS: Shape, Outliers, Center, Spread.",
    [
      "Shape: symmetric, skewed left/right, uniform, bimodal.",
      "Outliers: unusually far from bulk.",
      "Center: mean or median.",
      "Spread: range, IQR, SD.",
    ],
    "Distribution has a long right tail. Skew?",
    "Right (positively) skewed — mean > median.",
    [
      { q: "SOCS?", a: "Shape, Outliers, Center, Spread." },
      { q: "Right skew?", a: "Long tail on right; mean > median." },
      { q: "Left skew?", a: "Long tail on left; mean < median." },
      { q: "Bimodal?", a: "Two peaks — often two subgroups." },
      { q: "Why describe shape first?", a: "Shape determines which summary statistics make sense." },
    ],
  ),
  mk(1, "1.7", "Summary Statistics for a Quantitative Variable",
    "Mean, median, range, IQR, SD, variance.",
    [
      "Mean x̄ = Σx/n; median is the middle value.",
      "Range = max − min; IQR = Q3 − Q1.",
      "SD s = √(Σ(x−x̄)²/(n−1)); variance = s².",
      "Mean sensitive to outliers; median robust.",
    ],
    "Data: 2, 4, 6, 8, 10. Mean and median?",
    "Mean = 30/5 = 6. Median = 6 (middle).",
    [
      { q: "Mean formula?", a: "x̄ = Σx/n" },
      { q: "Median for even n?", a: "Average of two middle values." },
      { q: "Resistant measures?", a: "Median and IQR (not affected by outliers)." },
      { q: "SD formula (sample)?", a: "s = √(Σ(x−x̄)²/(n−1))" },
      { q: "IQR?", a: "Q3 − Q1" },
    ],
  ),
  mk(1, "1.8", "Graphical Representations of Summary Statistics",
    "Boxplots visualize five-number summary; 1.5·IQR rule flags outliers.",
    [
      "Five-number summary: min, Q1, median, Q3, max.",
      "Boxplot shows quartiles and outliers.",
      "1.5·IQR rule: outliers < Q1 − 1.5·IQR or > Q3 + 1.5·IQR.",
      "Whiskers extend to last non-outlier.",
    ],
    "Q1 = 10, Q3 = 22. IQR outlier cutoffs?",
    "IQR = 12. Lower: 10 − 18 = −8. Upper: 22 + 18 = 40. Outside [−8, 40] = outlier.",
    [
      { q: "Five-number summary?", a: "Min, Q1, median, Q3, max." },
      { q: "Boxplot middle line?", a: "Median." },
      { q: "Boxplot ends?", a: "Q1 and Q3 (edges of box)." },
      { q: "IQR outlier rule?", a: "Below Q1 − 1.5·IQR or above Q3 + 1.5·IQR." },
      { q: "Whiskers end where?", a: "At last data point within 1.5·IQR." },
    ],
  ),
  mk(1, "1.9", "Comparing Distributions of a Quantitative Variable",
    "Compare SOCS of two or more groups side-by-side.",
    [
      "Use parallel boxplots, back-to-back stemplots, or overlaid histograms.",
      "Always compare Shape, Outliers, Center, Spread.",
      "Support comparisons with specific numbers.",
      "Explicitly state which distribution is higher/wider/more skewed.",
    ],
    "Boys' heights have median 170 cm, girls' 165 cm. Compare centers.",
    "Boys' height distribution has a higher center (median 170 vs 165 cm).",
    [
      { q: "Best graphs for comparison?", a: "Parallel boxplots, back-to-back stemplots." },
      { q: "SOCS applies to?", a: "Every distribution comparison." },
      { q: "Support comparison how?", a: "Specific numerical values." },
      { q: "Never compare via?", a: "Vague 'higher' without numbers." },
      { q: "Same-scale axes?", a: "Essential for fair comparison." },
    ],
  ),
  mk(1, "1.10", "The Normal Distribution",
    "Bell-shaped, symmetric; empirical rule 68-95-99.7; z-scores standardize.",
    [
      "Normal ~ bell curve with parameters μ, σ.",
      "Empirical rule: 68% within 1σ, 95% within 2σ, 99.7% within 3σ.",
      "z-score: z = (x − μ)/σ.",
      "Use normalcdf / invNorm on calculator.",
    ],
    "μ = 100, σ = 15. P(X < 115)?",
    "z = (115-100)/15 = 1. P(Z < 1) ≈ 0.8413.",
    [
      { q: "z-score?", a: "z = (x − μ)/σ" },
      { q: "Empirical rule?", a: "68-95-99.7% within 1σ, 2σ, 3σ." },
      { q: "P(|z| < 2)?", a: "≈ 0.95" },
      { q: "Standard normal?", a: "μ=0, σ=1" },
      { q: "Find x from percentile?", a: "x = μ + zσ (use invNorm)" },
    ],
  ),
  mk(2, "2.1", "Introducing Statistics: Are Variables Related?",
    "Associations between variables — the heart of two-variable analysis.",
    [
      "Explanatory variable (x) might influence response variable (y).",
      "Association ≠ causation.",
      "Both variables can be categorical, quantitative, or mixed.",
    ],
    "Height vs weight — which is explanatory, which response?",
    "Typically height explains weight; but either can be chosen depending on the research question.",
    [
      { q: "Explanatory variable?", a: "x — the predictor." },
      { q: "Response variable?", a: "y — the outcome." },
      { q: "Association vs causation?", a: "Association = relationship; causation needs experiment." },
      { q: "Two categorical variables?", a: "Analyze via two-way tables." },
      { q: "Two quantitative variables?", a: "Scatterplot, correlation, regression." },
    ],
  ),
  mk(2, "2.2", "Representing Two Categorical Variables",
    "Two-way tables; segmented/stacked bar charts.",
    [
      "Rows = one variable, columns = other.",
      "Joint frequency in the cells.",
      "Marginal totals on edges.",
      "Segmented bar chart shows conditional distributions.",
    ],
    "2x2 table: 30 sunny-bike, 10 sunny-drive, 5 rain-bike, 25 rain-drive. Proportion bike on sunny days?",
    "30/(30+10) = 0.75.",
    [
      { q: "Joint frequency?", a: "Count in a specific cell of two-way table." },
      { q: "Marginal distribution?", a: "Row or column totals." },
      { q: "Conditional distribution?", a: "Distribution within a row or column." },
      { q: "Segmented bar?", a: "Bars split to show conditional percentages." },
      { q: "How to see association?", a: "Compare conditional distributions." },
    ],
  ),
  mk(2, "2.3", "Statistics for Two Categorical Variables",
    "Compare conditional distributions to detect association.",
    [
      "Independent if conditional distributions are identical.",
      "Simpson's paradox: association reverses when conditioned on a lurking variable.",
      "Always verify by computing percentages, not raw counts.",
    ],
    "Does P(bike|sunny) = P(bike|rainy)? If yes, no association.",
    "Compute both and compare — if equal → independent; if very different → association exists.",
    [
      { q: "Independence (categorical)?", a: "Conditional distributions identical." },
      { q: "Simpson's paradox?", a: "Direction of association reverses after conditioning." },
      { q: "Detect association from raw counts?", a: "No — must use proportions." },
      { q: "Lurking variable?", a: "Not measured but influencing relationship." },
      { q: "Test of independence?", a: "Chi-square (Unit 8)" },
    ],
  ),
  mk(2, "2.4", "Representing Two Quantitative Variables",
    "Scatterplots: x horizontal, y vertical. Describe form, direction, strength.",
    [
      "Form: linear, curved, none.",
      "Direction: positive (up), negative (down).",
      "Strength: how tightly points cluster around trend.",
      "Outliers and clusters also noteworthy.",
    ],
    "A scatterplot shows y increasing with x. Direction?",
    "Positive association.",
    [
      { q: "Scatterplot axes?", a: "x (explanatory) horizontal; y (response) vertical." },
      { q: "Describe scatterplots via?", a: "Form, direction, strength + outliers/clusters." },
      { q: "Positive direction?", a: "y increases as x increases." },
      { q: "Strong linear?", a: "Points cluster tightly on a line." },
      { q: "Non-linear form?", a: "Curved pattern — r doesn't capture it." },
    ],
  ),
  mk(2, "2.5", "Correlation",
    "r measures strength/direction of LINEAR association. −1 ≤ r ≤ 1.",
    [
      "r > 0: positive; r < 0: negative; r = 0: no linear association.",
      "Sensitive to outliers; dimensionless.",
      "r doesn't capture curvature or cause.",
      "r² (below) = fraction of variation explained.",
    ],
    "A dataset has r = −0.9. Describe.",
    "Strong negative linear association.",
    [
      { q: "Range of r?", a: "[−1, 1]" },
      { q: "r = 1 means?", a: "Perfect positive linear." },
      { q: "r near 0?", a: "Weak or no LINEAR relationship (could still be curved)." },
      { q: "Does r change if we swap x and y?", a: "No." },
      { q: "Is r resistant to outliers?", a: "No — sensitive." },
    ],
  ),
  mk(2, "2.6", "Linear Regression Models",
    "ŷ = a + bx. Slope b = r·(s_y/s_x); intercept a = ȳ − b·x̄.",
    [
      "Slope: predicted change in y per unit change in x.",
      "Intercept: ŷ when x = 0 (may or may not be meaningful).",
      "Regression line passes through (x̄, ȳ).",
      "Only valid within range of observed x (extrapolation warning).",
    ],
    "r = 0.8, s_y = 10, s_x = 5. Slope?",
    "b = r·(s_y/s_x) = 0.8·(10/5) = 1.6.",
    [
      { q: "Regression equation?", a: "ŷ = a + bx" },
      { q: "Slope formula?", a: "b = r·(s_y/s_x)" },
      { q: "Intercept formula?", a: "a = ȳ − b·x̄" },
      { q: "Line passes through?", a: "(x̄, ȳ)" },
      { q: "Extrapolation?", a: "Predicting outside observed x range — unreliable." },
    ],
  ),
  mk(2, "2.7", "Residuals",
    "Residual = y − ŷ (actual − predicted). Residual plot should show random scatter.",
    [
      "Residual = observed y − predicted ŷ.",
      "Positive residual: observation above line.",
      "Sum of residuals = 0 for least-squares line.",
      "Residual plot with pattern ⇒ linear model inappropriate.",
    ],
    "At x=5, y=12, ŷ=10. Residual?",
    "Residual = 12 − 10 = +2 (observation above line).",
    [
      { q: "Residual?", a: "y − ŷ" },
      { q: "Sum of least-squares residuals?", a: "0" },
      { q: "Good linear fit residual plot?", a: "Random scatter, no pattern." },
      { q: "Curve in residual plot?", a: "Non-linear trend missed." },
      { q: "Large residual?", a: "Possible outlier or poor fit." },
    ],
  ),
  mk(2, "2.8", "Least Squares Regression",
    "Minimizes Σ(residual)². Produces a = ȳ − bx̄, b = r(s_y/s_x).",
    [
      "Least squares minimizes sum of squared residuals.",
      "Always passes through (x̄, ȳ).",
      "Coefficient of determination r² = fraction of y-variation explained.",
      "SE of residuals (s) = typical prediction error.",
    ],
    "r² = 0.64. Interpret.",
    "64% of variation in y is explained by the linear relationship with x.",
    [
      { q: "What does LSR minimize?", a: "Sum of squared residuals." },
      { q: "r² interpretation?", a: "Fraction of variation in y explained by x." },
      { q: "Relation to r?", a: "r² = r² (same number squared)." },
      { q: "Range of r²?", a: "[0, 1]" },
      { q: "High r² guarantees good fit?", a: "No — check residual plot too." },
    ],
  ),
  mk(2, "2.9", "Analyzing Departures from Linearity",
    "Transform or switch models if residual plot shows pattern or outliers are influential.",
    [
      "Non-linear pattern: try log, square, reciprocal transforms.",
      "Influential points: affect slope substantially when removed.",
      "High-leverage points: extreme x values.",
      "Report r², residual SE, and residual plot together.",
    ],
    "Residual plot shows U-shape. Action?",
    "Try a non-linear model (e.g., quadratic or log transform) — linear model isn't adequate.",
    [
      { q: "U-shaped residual plot?", a: "Non-linear trend missed." },
      { q: "Influential observation?", a: "Removing it changes regression line notably." },
      { q: "Leverage vs influence?", a: "Leverage = extreme x; influence = moves the line." },
      { q: "Common transforms?", a: "log(y), √y, 1/y; or log(x)." },
      { q: "Why look at residuals not r alone?", a: "Curved data can still have high r." },
    ],
  ),
  mk(3, "3.1", "Introducing Statistics: Do the Data We Collected Tell the Truth?",
    "Bias — systematic error from design — distorts conclusions.",
    [
      "Bias: study consistently misses the truth.",
      "Random error: variability around the truth.",
      "Good design reduces bias; larger samples reduce random error.",
      "Common biases: selection, nonresponse, response, undercoverage.",
    ],
    "Sampling only people at church to estimate religiosity — bias?",
    "Selection bias — overstates religiosity.",
    [
      { q: "Bias?", a: "Systematic error — consistently off in one direction." },
      { q: "Random error?", a: "Variability; reduced by larger samples." },
      { q: "Selection bias?", a: "Sample chosen so certain groups overrepresented." },
      { q: "Nonresponse bias?", a: "Non-responders differ from responders." },
      { q: "Larger sample fixes bias?", a: "No — only random error." },
    ],
  ),
  mk(3, "3.2", "Introduction to Planning a Study",
    "Observational study vs. experiment: observation can't establish causation.",
    [
      "Observational: observe as-is; can find associations.",
      "Experimental: assign treatments; can establish causation.",
      "Sample survey: observational study using a sample.",
      "Census: observe entire population (usually impractical).",
    ],
    "Is the Framingham Heart Study observational or experimental?",
    "Observational — researchers followed participants without assigning treatments.",
    [
      { q: "Observational study?", a: "No treatment assigned; records natural behavior." },
      { q: "Experiment?", a: "Researcher assigns treatments." },
      { q: "Which establishes causation?", a: "Experiment." },
      { q: "Sample survey?", a: "Observational study on a sample." },
      { q: "Census?", a: "Entire population measured." },
    ],
  ),
  mk(3, "3.3", "Random Sampling and Data Collection",
    "Probability-based samples: SRS, stratified, cluster, systematic.",
    [
      "SRS: every sample of size n equally likely.",
      "Stratified: divide into strata (homogeneous groups), sample each.",
      "Cluster: divide into clusters (heterogeneous), sample whole clusters.",
      "Systematic: every kth person.",
    ],
    "Want to estimate a state's average income and have urban vs. rural data. Best design?",
    "Stratified sample by urban/rural — reduces variability within strata.",
    [
      { q: "SRS?", a: "Simple random sample: every sample of size n equally likely." },
      { q: "Stratified?", a: "Divide into strata, SRS from each." },
      { q: "Cluster?", a: "Sample whole groups (clusters)." },
      { q: "Systematic?", a: "Every kth unit from a list." },
      { q: "Strata vs clusters?", a: "Strata: within-homogeneous; clusters: within-heterogeneous." },
    ],
  ),
  mk(3, "3.4", "Potential Problems with Sampling",
    "Undercoverage, nonresponse, response bias, voluntary response skew samples.",
    [
      "Undercoverage: some groups excluded from sampling frame.",
      "Nonresponse: selected individuals don't respond.",
      "Response bias: answers affected by interviewer or question wording.",
      "Voluntary response: self-selected respondents differ.",
    ],
    "Online poll asking 'Do you support X?' — type of bias?",
    "Voluntary response bias — strong-opinion people self-select.",
    [
      { q: "Undercoverage?", a: "Frame misses part of population." },
      { q: "Nonresponse?", a: "Some selected individuals don't reply." },
      { q: "Response bias?", a: "Answers influenced by wording, interviewer, setting." },
      { q: "Voluntary response?", a: "Self-selected sample — biased toward strong opinions." },
      { q: "Bigger sample fix for biases?", a: "No — bias doesn't shrink with n." },
    ],
  ),
  mk(3, "3.5", "Introduction to Experimental Design",
    "Experimental units, treatments, response variable, control/random assignment.",
    [
      "Unit: what receives a treatment.",
      "Treatment: what we impose; has levels.",
      "Response: what we measure.",
      "Control + randomization + replication = good design.",
    ],
    "Test drug effectiveness: what is the treatment?",
    "Drug vs. placebo — and dose level if varied.",
    [
      { q: "Experimental unit?", a: "Who/what receives the treatment." },
      { q: "Treatment?", a: "Imposed condition we compare." },
      { q: "Control group purpose?", a: "Baseline for comparison." },
      { q: "Randomization?", a: "Random assignment of treatments to units." },
      { q: "Replication?", a: "Applying treatment to multiple units." },
    ],
  ),
  mk(3, "3.6", "Selecting an Experimental Design",
    "Completely randomized vs. randomized block vs. matched-pairs design.",
    [
      "CRD: randomly assign treatments to units.",
      "Randomized block: group similar units (block), randomize within.",
      "Matched pairs: pair similar units, random assign within each pair.",
      "Double-blind controls placebo and observer effects.",
    ],
    "Testing shoe durability: each participant wears left-foot A, right-foot B. Design?",
    "Matched pairs (each person is their own pair).",
    [
      { q: "Randomized block?", a: "Randomize within homogeneous groups (blocks)." },
      { q: "Matched pairs?", a: "Pair similar units; randomize within pair." },
      { q: "Double-blind?", a: "Neither subjects nor data-collectors know treatment." },
      { q: "Placebo?", a: "Inactive treatment to isolate real effect." },
      { q: "Why block?", a: "Reduce variability from known factor." },
    ],
  ),
  mk(3, "3.7", "Inference and Experiments",
    "Random SELECTION lets us generalize to population; random ASSIGNMENT lets us conclude cause.",
    [
      "Random selection (sampling) → generalize.",
      "Random assignment (experiment) → causal claim.",
      "Scope of inference depends on both.",
      "Observational + random selection → generalize association (not cause).",
    ],
    "Random volunteers randomly assigned to treatments. Scope?",
    "Random assignment supports causation; random selection supports generalization (if selection was random).",
    [
      { q: "Random selection enables?", a: "Generalization to population." },
      { q: "Random assignment enables?", a: "Causal conclusions." },
      { q: "Observational study + SRS?", a: "Can generalize an association, not cause." },
      { q: "Experiment on volunteers?", a: "Cause OK; generalization limited." },
      { q: "Both random?", a: "Both cause AND generalization." },
    ],
  ),
  mk(4, "4.1", "Introducing Statistics: Random and Non-Random Patterns",
    "Chance produces patterns; we use probability to quantify them.",
    [
      "Random process: long-run proportions predictable, short-run unpredictable.",
      "Probability: long-run relative frequency.",
      "Simulations estimate probabilities.",
    ],
    "Flip a fair coin 10 times and get 8 heads. Is the coin biased?",
    "Not necessarily — short-run deviations are common. Run more flips; check proportion approach 0.5.",
    [
      { q: "Probability interpretation?", a: "Long-run relative frequency." },
      { q: "Short-run random?", a: "Unpredictable." },
      { q: "Simulation role?", a: "Estimate probabilities empirically." },
      { q: "Law of large numbers?", a: "As n grows, sample prop → true prop." },
      { q: "Gambler's fallacy?", a: "Expecting past random events to affect future." },
    ],
  ),
  mk(4, "4.2", "Estimating Probabilities Using Simulation",
    "Run many trials of a chance process; estimate P(event) by relative frequency.",
    [
      "Design the simulation: random device, events, stop rule.",
      "Run many trials (100+, often 1000+).",
      "Estimate P(event) = count/trials.",
      "As trials increase, estimate stabilizes (LLN).",
    ],
    "Simulate P(at least one head in 3 flips) using 100 simulations, got 87. Estimate?",
    "87/100 = 0.87 (theoretical = 1 − 0.5³ = 0.875).",
    [
      { q: "How to estimate P via simulation?", a: "Proportion of trials where event occurred." },
      { q: "Why simulate?", a: "When analytical probability is difficult." },
      { q: "More trials → ?", a: "More accurate estimate." },
      { q: "Random device examples?", a: "Coins, dice, digit tables, RNG." },
      { q: "Law of large numbers?", a: "Sample proportion converges to true probability." },
    ],
  ),
  mk(4, "4.3", "Introduction to Probability",
    "P(event) ∈ [0,1]. Complement, union (add), intersection (multiply if indep).",
    [
      "P(A) ∈ [0,1]; P(S) = 1.",
      "P(A^c) = 1 − P(A).",
      "Mutually exclusive: P(A∩B)=0 ⇒ P(A∪B)=P(A)+P(B).",
      "General: P(A∪B) = P(A)+P(B)−P(A∩B).",
    ],
    "P(A) = 0.5, P(B) = 0.4, P(A∩B) = 0.2. P(A∪B)?",
    "P(A∪B) = 0.5 + 0.4 − 0.2 = 0.7.",
    [
      { q: "P(A^c)?", a: "1 − P(A)" },
      { q: "General addition rule?", a: "P(A∪B)=P(A)+P(B)−P(A∩B)" },
      { q: "Mutually exclusive?", a: "P(A∩B)=0; events can't both occur." },
      { q: "Sample space?", a: "All possible outcomes." },
      { q: "Simple event?", a: "One outcome in sample space." },
    ],
  ),
  mk(4, "4.4", "Mutually Exclusive Events",
    "Mutually exclusive events never occur together; P(A or B) = P(A) + P(B).",
    [
      "ME: A and B can't both happen.",
      "P(A∪B) = P(A) + P(B) for ME.",
      "ME ≠ independent. ME events are maximally DEPENDENT.",
      "Rolling die: {1} and {2} are ME; they're not independent.",
    ],
    "P(rolling a 1) = 1/6, P(rolling a 2) = 1/6. P(1 or 2)?",
    "ME ⇒ P = 1/6 + 1/6 = 1/3.",
    [
      { q: "Mutually exclusive?", a: "Events cannot both occur." },
      { q: "P(A or B) for ME?", a: "P(A) + P(B)" },
      { q: "ME same as independent?", a: "No — opposite." },
      { q: "Can ME events be independent?", a: "Only if one has P=0." },
      { q: "Disjoint = ?", a: "Mutually exclusive." },
    ],
  ),
  mk(4, "4.5", "Conditional Probability",
    "P(A|B) = P(A∩B)/P(B) — probability of A given B occurred.",
    [
      "P(A|B) = P(A∩B)/P(B).",
      "Multiplication rule: P(A∩B) = P(A)P(B|A).",
      "Tree diagrams help compute multi-stage probabilities.",
      "In two-way tables, condition by restricting to row or column.",
    ],
    "P(A)=0.6, P(B)=0.5, P(A∩B)=0.3. P(A|B)?",
    "P(A|B) = 0.3/0.5 = 0.6.",
    [
      { q: "P(A|B) definition?", a: "P(A∩B)/P(B)" },
      { q: "Multiplication rule?", a: "P(A∩B) = P(A)·P(B|A)" },
      { q: "If A,B independent, P(A|B)?", a: "= P(A)" },
      { q: "Is P(A|B) = P(B|A)?", a: "Generally no." },
      { q: "Tree diagrams used for?", a: "Multi-stage conditional probabilities." },
    ],
  ),
  mk(4, "4.6", "Independent Events and Unions of Events",
    "Independent: P(A∩B)=P(A)P(B). Don't confuse with mutually exclusive.",
    [
      "Independent: P(A|B) = P(A).",
      "For indep: P(A∩B) = P(A)·P(B).",
      "At-least-one problems: use complements; P(at least one) = 1 − P(none).",
      "Testing independence: check P(A|B) = P(A).",
    ],
    "Three independent coin flips. P(at least one head)?",
    "1 − P(all tails) = 1 − 0.5³ = 0.875.",
    [
      { q: "Independence test?", a: "P(A|B) = P(A) (or P(A∩B)=P(A)P(B))" },
      { q: "Indep vs ME?", a: "Indep: P doesn't change; ME: can't both happen." },
      { q: "At least one strategy?", a: "1 − P(none)" },
      { q: "P(A∩B) for indep A,B?", a: "P(A)P(B)" },
      { q: "3 indep with P=p each, at least one?", a: "1 − (1−p)³" },
    ],
  ),
  mk(4, "4.7", "Introduction to Random Variables and Probability Distributions",
    "Random variable = numerical outcome of a random process. Distribution gives all values and probabilities.",
    [
      "Discrete RV: countable values (list P(X=x)).",
      "Continuous RV: interval values (density function).",
      "Probabilities sum / integrate to 1.",
      "Tables, formulas, graphs all represent distributions.",
    ],
    "X = number of heads in 2 flips. Distribution?",
    "X ∈ {0,1,2}; P(0)=0.25, P(1)=0.5, P(2)=0.25.",
    [
      { q: "Random variable?", a: "Numerical outcome of a random process." },
      { q: "Discrete vs continuous RV?", a: "Discrete: countable; continuous: interval." },
      { q: "Sum of probabilities?", a: "1" },
      { q: "Probability distribution?", a: "Values + their probabilities." },
      { q: "Continuous RV probability at single point?", a: "0 (use intervals)." },
    ],
  ),
  mk(4, "4.8", "Mean and Standard Deviation of Random Variables",
    "μ_X = Σx·P(x); σ_X² = Σ(x − μ)²·P(x).",
    [
      "Expected value E(X) = Σx·P(x).",
      "Variance Var(X) = Σ(x−μ)²·P(x).",
      "SD σ_X = √Var(X).",
      "Linear transform: E(aX+b) = aμ + b; Var(aX+b) = a²Var(X).",
    ],
    "X: 1 (p=0.3), 2 (p=0.5), 3 (p=0.2). Mean?",
    "μ = 1(0.3)+2(0.5)+3(0.2) = 0.3+1.0+0.6 = 1.9.",
    [
      { q: "Expected value?", a: "E(X) = Σx·P(x)" },
      { q: "Variance?", a: "Var(X) = Σ(x−μ)²P(x)" },
      { q: "E(aX+b)?", a: "aμ + b" },
      { q: "Var(aX+b)?", a: "a²Var(X)" },
      { q: "SD of X?", a: "√Var(X)" },
    ],
  ),
  mk(4, "4.9", "Combining Random Variables",
    "Mean adds: E(X+Y)=μ_X + μ_Y. Variance adds IF independent: Var(X+Y)=Var(X)+Var(Y).",
    [
      "E(X+Y) = E(X) + E(Y) always.",
      "If X, Y independent: Var(X ± Y) = Var(X) + Var(Y).",
      "Variance is ALWAYS ADDED even for differences (when independent).",
      "SD does NOT add — combine via variance then sqrt.",
    ],
    "X: μ=5, σ=2. Y: μ=3, σ=1. X,Y indep. σ_{X−Y}?",
    "Var(X−Y) = 4 + 1 = 5 ⇒ σ = √5 ≈ 2.24.",
    [
      { q: "E(X+Y)?", a: "E(X) + E(Y) (always)" },
      { q: "Var(X+Y) if indep?", a: "Var(X) + Var(Y)" },
      { q: "Var(X−Y) if indep?", a: "Var(X) + Var(Y) (still added!)" },
      { q: "SD(X+Y)?", a: "√(σ_X² + σ_Y²) — not sum of SDs" },
      { q: "Do SDs add?", a: "No — variances do." },
    ],
  ),
  mk(4, "4.10", "Introduction to the Binomial Distribution",
    "Binomial: fixed n trials, P(success)=p, count # successes. P(X=k) = C(n,k) p^k (1−p)^(n−k).",
    [
      "Conditions: Binary, Independent, Number of trials fixed, Same p (BINS).",
      "P(X=k) = C(n,k) p^k (1-p)^(n-k).",
      "Calculator: binompdf/binomcdf.",
      "Right-skewed if p<0.5, left-skewed if p>0.5.",
    ],
    "n=5, p=0.3. P(X=2)?",
    "C(5,2)(0.3)²(0.7)³ = 10(0.09)(0.343) ≈ 0.309.",
    [
      { q: "Binomial conditions (BINS)?", a: "Binary, Independent, Number fixed, Same p." },
      { q: "P(X=k) formula?", a: "C(n,k)p^k(1-p)^(n-k)" },
      { q: "Binomial mean?", a: "np" },
      { q: "Binomial SD?", a: "√(np(1-p))" },
      { q: "binompdf vs binomcdf?", a: "pdf = P(X=k); cdf = P(X≤k)." },
    ],
  ),
  mk(4, "4.11", "Parameters for a Binomial Distribution",
    "Mean μ = np; SD σ = √(np(1−p)).",
    [
      "E(X) = np.",
      "Var(X) = np(1−p); SD = √(np(1−p)).",
      "Symmetric when p = 0.5.",
      "Calculator normalcdf can approximate for large n (np ≥ 10 and n(1−p) ≥ 10).",
    ],
    "n=20, p=0.4. μ and σ?",
    "μ = 20(0.4) = 8. σ = √(20·0.4·0.6) = √4.8 ≈ 2.19.",
    [
      { q: "Binomial mean?", a: "np" },
      { q: "Binomial variance?", a: "np(1−p)" },
      { q: "Binomial SD?", a: "√(np(1−p))" },
      { q: "Normal approximation condition?", a: "np ≥ 10 AND n(1−p) ≥ 10" },
      { q: "Skew direction?", a: "Right if p<0.5, left if p>0.5." },
    ],
  ),
  mk(4, "4.12", "The Geometric Distribution",
    "Count trials until first success. P(X=k) = (1−p)^(k−1) p.",
    [
      "Conditions: BITS — Binary, Independent, Trials until success, Same p.",
      "P(X=k) = (1-p)^(k-1) p.",
      "Mean: E(X) = 1/p.",
      "Variance: Var(X) = (1-p)/p².",
    ],
    "p = 0.2. Expected number of trials until first success?",
    "E(X) = 1/0.2 = 5.",
    [
      { q: "Geometric conditions (BITS)?", a: "Binary, Independent, Trials until success, Same p." },
      { q: "P(X=k)?", a: "(1-p)^(k-1) p" },
      { q: "Geometric mean?", a: "1/p" },
      { q: "Var?", a: "(1-p)/p²" },
      { q: "Differences binomial vs geometric?", a: "Binomial fixes n; geometric counts trials to first success." },
    ],
  ),
  mk(5, "5.1", "Introducing Statistics: Why Is My Sample Not Like Yours?",
    "Sampling variability: statistics vary from sample to sample.",
    [
      "Different samples → different statistics.",
      "Sampling distribution: distribution of a statistic over all possible samples of size n.",
      "Statistics estimate parameters; variability quantified.",
    ],
    "Two different SRSs of n=50 give different sample means. Why?",
    "Sampling variability — each sample reflects a different subset of the population.",
    [
      { q: "Sampling distribution?", a: "Distribution of a statistic over all possible samples." },
      { q: "Parameter?", a: "Fixed value for population (μ, p)." },
      { q: "Statistic?", a: "Sample value (x̄, p̂) that varies." },
      { q: "Sampling variability?", a: "Differences between statistics across samples." },
      { q: "Reducing variability?", a: "Larger n → smaller variability." },
    ],
  ),
  mk(5, "5.2", "The Normal Distribution, Revisited",
    "Reuse normal to describe sampling distributions when conditions met.",
    [
      "Normal shape: bell-shaped, symmetric about μ.",
      "Use z-scores to standardize.",
      "Sampling distributions often approximately normal (CLT).",
    ],
    "Normal with μ=50, σ=10. P(X>65)?",
    "z = 1.5; P(Z>1.5) ≈ 0.0668.",
    [
      { q: "Standard normal?", a: "Z ~ N(0,1)" },
      { q: "z-score?", a: "z = (x − μ)/σ" },
      { q: "Why normal is central?", a: "CLT makes many sampling distributions approximately normal." },
      { q: "normalcdf(a,b,μ,σ)?", a: "P(a ≤ X ≤ b) for normal." },
      { q: "invNorm(p,μ,σ)?", a: "x such that P(X ≤ x) = p." },
    ],
  ),
  mk(5, "5.3", "The Central Limit Theorem",
    "CLT: for large n, sampling distribution of x̄ is approximately normal.",
    [
      "CLT: x̄ ~ N(μ, σ/√n) approximately when n is large.",
      "Rule of thumb: n ≥ 30 usually enough; larger if population very skewed.",
      "True regardless of population shape.",
      "Proportions: p̂ ~ N(p, √(p(1−p)/n)) when np ≥ 10 and n(1−p) ≥ 10.",
    ],
    "Population μ=100, σ=15. SRS n=36. Mean and SD of x̄?",
    "μ_x̄ = 100, σ_x̄ = 15/√36 = 2.5.",
    [
      { q: "CLT?", a: "Sampling distribution of x̄ approaches normal as n grows." },
      { q: "μ_x̄?", a: "μ (same as population)" },
      { q: "σ_x̄?", a: "σ/√n" },
      { q: "n rule for CLT?", a: "Usually n ≥ 30." },
      { q: "Does CLT require normal population?", a: "No — works for any population given large enough n." },
    ],
  ),
  mk(5, "5.4", "Biased and Unbiased Point Estimates",
    "Unbiased estimator: mean of sampling distribution equals parameter.",
    [
      "x̄ is unbiased for μ.",
      "p̂ is unbiased for p.",
      "s² is unbiased for σ² (uses n−1).",
      "Bias ≠ bias of one sample — it's a property of the estimator.",
    ],
    "Why divide by n−1 instead of n in sample variance?",
    "Dividing by n−1 (Bessel's correction) makes s² unbiased for σ².",
    [
      { q: "Unbiased estimator?", a: "Mean of its sampling distribution = parameter." },
      { q: "Is x̄ unbiased?", a: "Yes, for μ." },
      { q: "Is s² unbiased?", a: "Yes (uses n−1)." },
      { q: "Is s (SD) unbiased?", a: "No, but nearly." },
      { q: "Bias of a single estimate?", a: "Property of estimator, not single value." },
    ],
  ),
  mk(5, "5.5", "Sampling Distributions for Sample Proportions",
    "p̂ ~ N(p, √(p(1−p)/n)) for large enough n.",
    [
      "μ_p̂ = p.",
      "σ_p̂ = √(p(1-p)/n).",
      "Conditions for normal approx: np ≥ 10 AND n(1-p) ≥ 10.",
      "10%: sample should be <10% of population.",
    ],
    "p = 0.4, n = 100. SD of p̂?",
    "σ_p̂ = √((0.4)(0.6)/100) = √0.0024 ≈ 0.049.",
    [
      { q: "μ_p̂?", a: "p" },
      { q: "σ_p̂?", a: "√(p(1-p)/n)" },
      { q: "Normal condition for p̂?", a: "np ≥ 10 AND n(1-p) ≥ 10" },
      { q: "10% condition?", a: "n ≤ 10% of population (ensures independence)." },
      { q: "Larger n → σ_p̂?", a: "Smaller." },
    ],
  ),
  mk(5, "5.6", "Sampling Distributions for Differences in Sample Proportions",
    "p̂₁ − p̂₂ ~ approximately N(p₁ − p₂, √(p₁(1−p₁)/n₁ + p₂(1−p₂)/n₂)).",
    [
      "Mean: p₁ − p₂.",
      "SD: √(p₁q₁/n₁ + p₂q₂/n₂), q = 1 − p.",
      "Normal conditions: n_i p_i ≥ 10 and n_i q_i ≥ 10 for both samples.",
      "Independence: samples independent of each other.",
    ],
    "p₁ = 0.5, p₂ = 0.4, n₁ = n₂ = 100. SD of p̂₁ − p̂₂?",
    "√(0.5·0.5/100 + 0.4·0.6/100) = √(0.0025 + 0.0024) ≈ 0.070.",
    [
      { q: "Mean of p̂₁ − p̂₂?", a: "p₁ − p₂" },
      { q: "SD of p̂₁ − p̂₂?", a: "√(p₁q₁/n₁ + p₂q₂/n₂)" },
      { q: "Normal conditions both samples?", a: "n_i p_i ≥ 10 AND n_i q_i ≥ 10 for i=1,2" },
      { q: "Independence condition?", a: "Samples independent of each other and each <10% of its population." },
      { q: "Why variance adds?", a: "Independent RVs → variances add." },
    ],
  ),
  mk(5, "5.7", "Sampling Distributions for Sample Means",
    "x̄ ~ N(μ, σ/√n) when n large (CLT) or population normal.",
    [
      "μ_x̄ = μ.",
      "σ_x̄ = σ/√n.",
      "Normal shape when population is normal OR n ≥ 30 (CLT).",
      "Independence / 10% condition for sampling without replacement.",
    ],
    "μ=50, σ=8, n=16 (normal pop). Distribution of x̄?",
    "x̄ ~ N(50, 8/√16) = N(50, 2).",
    [
      { q: "μ_x̄?", a: "μ" },
      { q: "σ_x̄?", a: "σ/√n" },
      { q: "Shape when population normal?", a: "x̄ exactly normal for any n." },
      { q: "Shape for large n non-normal population?", a: "Approximately normal via CLT." },
      { q: "Effect of 4× sample size on σ_x̄?", a: "Halved." },
    ],
  ),
  mk(5, "5.8", "Sampling Distributions for Differences in Sample Means",
    "x̄₁ − x̄₂ ~ approximately N(μ₁ − μ₂, √(σ₁²/n₁ + σ₂²/n₂)).",
    [
      "Mean: μ₁ − μ₂.",
      "SD: √(σ₁²/n₁ + σ₂²/n₂).",
      "Conditions: both populations normal OR both n_i ≥ 30.",
      "Independence between samples.",
    ],
    "Samples n₁=30 (σ₁=2), n₂=40 (σ₂=3). SD of x̄₁ − x̄₂?",
    "√(4/30 + 9/40) = √(0.133 + 0.225) ≈ 0.599.",
    [
      { q: "Mean x̄₁ − x̄₂?", a: "μ₁ − μ₂" },
      { q: "SD x̄₁ − x̄₂?", a: "√(σ₁²/n₁ + σ₂²/n₂)" },
      { q: "Normal conditions?", a: "Both populations normal OR both n_i ≥ 30." },
      { q: "Why variance adds?", a: "Independent samples." },
      { q: "Sample independence check?", a: "Different people, random assignment, or separate SRSs." },
    ],
  ),
  mk(6, "6.1", "Introducing Statistics: Why Be Normal?",
    "We use normality of sampling distributions to build CIs and tests.",
    [
      "CI = point estimate ± critical value × SE.",
      "Test statistic z (or t) = (estimate − hypothesized)/SE.",
      "Normal-based inference requires normality conditions.",
    ],
    "What's the logic of a CI?",
    "We capture the true parameter in our interval at a stated confidence level by using the sampling distribution.",
    [
      { q: "Confidence interval form?", a: "estimate ± (critical value)(SE)" },
      { q: "Test statistic?", a: "(estimate − H₀)/SE" },
      { q: "Why normal matters?", a: "Enables z- and t-based inference." },
      { q: "Confidence level?", a: "% of random intervals containing true parameter." },
      { q: "Sampling distribution role?", a: "Gives us the SE and shape for inference." },
    ],
  ),
  mk(6, "6.2", "Constructing a Confidence Interval for a Population Proportion",
    "1-prop z-interval: p̂ ± z* √(p̂(1−p̂)/n).",
    [
      "Conditions: Random, Independent (10% rule), Normal (np̂ ≥ 10 and n(1-p̂) ≥ 10).",
      "CI = p̂ ± z* √(p̂(1-p̂)/n).",
      "z* for 90/95/99%: 1.645/1.960/2.576.",
      "Wider CI = more confidence; narrower = less.",
    ],
    "p̂ = 0.60, n = 200. 95% CI?",
    "SE = √(0.6·0.4/200) ≈ 0.0346. CI = 0.60 ± 1.96(0.0346) = (0.532, 0.668).",
    [
      { q: "1-prop z-interval formula?", a: "p̂ ± z*√(p̂(1-p̂)/n)" },
      { q: "z* for 95%?", a: "1.960" },
      { q: "z* for 99%?", a: "2.576" },
      { q: "Normality condition?", a: "np̂ ≥ 10 AND n(1-p̂) ≥ 10" },
      { q: "Effect of higher confidence?", a: "Wider interval." },
    ],
  ),
  mk(6, "6.3", "Justifying a Claim Based on a Confidence Interval for a Population Proportion",
    "If claimed value is outside CI ⇒ evidence against claim at (1 − α) confidence.",
    [
      "CI includes value → plausible.",
      "CI excludes value → unlikely at this confidence level.",
      "Interpretation: 'We are C% confident true p is in (a,b).'",
      "Confidence applies to method, not to any one interval.",
    ],
    "95% CI = (0.4, 0.5). Is p = 0.3 plausible?",
    "No — 0.3 is outside the interval, so 0.3 is not plausible at 95% confidence.",
    [
      { q: "CI excludes 0 ⇒?", a: "Evidence of non-zero effect at (1-α) confidence." },
      { q: "Correct CI interpretation?", a: "'We are C% confident that the parameter is in (a,b).'" },
      { q: "Incorrect: 'probability p is in this CI'?", a: "Wrong — p is fixed; the CI is random." },
      { q: "Wider CI means?", a: "Less precise estimate (more uncertainty)." },
      { q: "Margin of error?", a: "z*·SE (half-width of CI)." },
    ],
  ),
  mk(6, "6.4", "Setting Up a Test for a Population Proportion",
    "H₀: p = p₀ vs. H_a (one or two-sided). Check Random, 10%, Normal (np₀ ≥ 10, nq₀ ≥ 10).",
    [
      "Hypotheses: H₀ and H_a stated BEFORE data.",
      "One-sided: p > p₀, p < p₀. Two-sided: p ≠ p₀.",
      "Conditions: SRS, independence (10%), normality with p₀.",
      "Test statistic uses p₀, not p̂, in SE.",
    ],
    "Claim: more than 30% of students read daily. Set up.",
    "H₀: p = 0.30; H_a: p > 0.30 (one-sided right).",
    [
      { q: "Null hypothesis?", a: "H₀: p = p₀ (status quo)." },
      { q: "Two-sided H_a?", a: "p ≠ p₀" },
      { q: "SE for test?", a: "√(p₀(1-p₀)/n), uses p₀ not p̂." },
      { q: "Normality condition?", a: "np₀ ≥ 10 AND n(1-p₀) ≥ 10" },
      { q: "Why p₀ in SE?", a: "Assumes H₀ is true." },
    ],
  ),
  mk(6, "6.5", "Interpreting p-Values",
    "p-value = probability of test stat at least as extreme as observed, assuming H₀ true.",
    [
      "Small p → data unlikely under H₀ → reject H₀.",
      "p < α ⇒ reject H₀.",
      "p ≥ α ⇒ fail to reject H₀.",
      "p is NOT P(H₀ true).",
    ],
    "p-value = 0.02, α = 0.05. Decision?",
    "Reject H₀ — there's evidence at α=0.05.",
    [
      { q: "p-value definition?", a: "P(test stat at least as extreme | H₀ true)" },
      { q: "Small p means?", a: "Data unlikely under H₀." },
      { q: "Decision rule?", a: "p < α → reject H₀." },
      { q: "p = P(H₀ true)?", a: "No." },
      { q: "α (significance level)?", a: "Threshold for rejection (commonly 0.05)." },
    ],
  ),
  mk(6, "6.6", "Concluding a Test for a Population Proportion",
    "State conclusion IN CONTEXT: 'evidence/no evidence' that the claim holds.",
    [
      "Reject H₀: 'evidence that p [differs from/exceeds/etc.] p₀.'",
      "Fail to reject: 'no evidence that p differs from p₀.'",
      "Never 'accept H₀' — just fail to reject.",
      "Always state decision, evidence strength, and context.",
    ],
    "Test of p = 0.5 vs p > 0.5. p-value = 0.01. Conclusion?",
    "Reject H₀: there is significant evidence at α=0.05 that p > 0.5 (in context of the problem).",
    [
      { q: "Conclusion if reject?", a: "'Evidence supports H_a' — in context." },
      { q: "Conclusion if fail to reject?", a: "'No evidence' — in context." },
      { q: "Can we 'accept H₀'?", a: "No — only fail to reject." },
      { q: "Always include?", a: "Context, not just rejection verdict." },
      { q: "p < α for rejection?", a: "Yes." },
    ],
  ),
  mk(6, "6.7", "Potential Errors When Performing Tests",
    "Type I: reject true H₀ (prob = α). Type II: fail to reject false H₀ (prob = β). Power = 1 − β.",
    [
      "Type I: reject true H₀; rate = α.",
      "Type II: fail to reject false H₀; rate = β.",
      "Power = 1 − β = P(reject H₀ | H_a true).",
      "Increase n or α → higher power.",
    ],
    "α = 0.05 means Type I error rate of?",
    "5%.",
    [
      { q: "Type I error?", a: "Reject true H₀; probability = α." },
      { q: "Type II error?", a: "Fail to reject false H₀; probability = β." },
      { q: "Power?", a: "1 − β = P(reject H₀ | H_a true)" },
      { q: "How to increase power?", a: "Larger n, larger effect size, larger α." },
      { q: "Tradeoff α vs β?", a: "Decrease α → increase β (for fixed n)." },
    ],
  ),
  mk(6, "6.8", "Confidence Intervals for the Difference of Two Proportions",
    "2-prop z-interval: (p̂₁ − p̂₂) ± z* √(p̂₁q̂₁/n₁ + p̂₂q̂₂/n₂).",
    [
      "Conditions (both samples): Random, 10%, Normal (each n_i p̂_i ≥ 10, n_i q̂_i ≥ 10).",
      "SE = √(p̂₁q̂₁/n₁ + p̂₂q̂₂/n₂) — each sample's own p̂.",
      "No pooling in CI (since we don't assume equal proportions).",
      "Independence between the two samples.",
    ],
    "p̂₁ = 0.50 (n=100), p̂₂ = 0.40 (n=120). 95% CI?",
    "Diff = 0.10. SE = √(0.5·0.5/100 + 0.4·0.6/120) ≈ √0.0045 ≈ 0.067. CI ≈ 0.10 ± 1.96(0.067) = (-0.031, 0.231).",
    [
      { q: "2-prop z-interval formula?", a: "(p̂₁−p̂₂) ± z*√(p̂₁q̂₁/n₁ + p̂₂q̂₂/n₂)" },
      { q: "Do we pool in CI?", a: "No." },
      { q: "Normality condition?", a: "Each n_i p̂_i ≥ 10 and each n_i q̂_i ≥ 10." },
      { q: "CI contains 0?", a: "No significant difference at this level." },
      { q: "z* for 95% CI?", a: "1.960" },
    ],
  ),
  mk(6, "6.9", "Justifying a Claim Based on a Confidence Interval for a Difference of Proportions",
    "If CI for p₁−p₂ contains 0 ⇒ no significant difference at confidence level.",
    [
      "CI contains 0: no evidence of difference.",
      "CI entirely above 0: p₁ > p₂.",
      "CI entirely below 0: p₁ < p₂.",
      "Interpretation as before: 'We are C% confident…'",
    ],
    "95% CI for p₁ − p₂ = (0.02, 0.18). Significant difference?",
    "Yes — entire interval above 0 so p₁ > p₂ at 95% confidence.",
    [
      { q: "CI for diff contains 0?", a: "No significant difference." },
      { q: "CI entirely above 0 means?", a: "p₁ > p₂ at that confidence." },
      { q: "Two-sided test at α = 1 − C related to CI?", a: "Reject if CI doesn't contain 0." },
      { q: "Claim p₁ > p₂ supported if?", a: "Entire CI above 0." },
      { q: "Effect of wider CI?", a: "Less precise; more likely to include 0." },
    ],
  ),
  mk(6, "6.10", "Setting Up a Test for the Difference of Two Population Proportions",
    "H₀: p₁ = p₂. Use pooled p̂_c = (x₁+x₂)/(n₁+n₂) for SE.",
    [
      "H₀: p₁ − p₂ = 0 (no difference).",
      "Pooled proportion: p̂_c = (x₁+x₂)/(n₁+n₂).",
      "Test SE: √(p̂_c q̂_c (1/n₁ + 1/n₂)).",
      "Conditions: Random, 10%, Normal (use p̂_c in each n_i p̂_c ≥ 10, n_i q̂_c ≥ 10).",
    ],
    "x₁=40 (n=100), x₂=30 (n=100). Pooled p̂_c?",
    "p̂_c = (40+30)/(100+100) = 0.35.",
    [
      { q: "Pooled p̂_c?", a: "(x₁+x₂)/(n₁+n₂)" },
      { q: "SE for test?", a: "√(p̂_c q̂_c (1/n₁ + 1/n₂))" },
      { q: "H₀ for 2-prop test?", a: "p₁ = p₂" },
      { q: "Why pool?", a: "Assumes H₀ true so both samples from same proportion." },
      { q: "Pool for CI?", a: "No — only for test." },
    ],
  ),
  mk(6, "6.11", "Carrying Out a Test for the Difference of Two Population Proportions",
    "z = (p̂₁ − p̂₂)/√(p̂_c q̂_c(1/n₁ + 1/n₂)). Compare to critical or compute p-value.",
    [
      "Compute pooled p̂_c, test statistic z, p-value.",
      "Compare p-value to α to decide.",
      "State conclusion in context.",
      "If CI excludes 0 ↔ two-sided test rejects.",
    ],
    "p̂₁=0.50, p̂₂=0.30, n=100 each. Pooled p̂_c = 0.40. z?",
    "SE = √(0.4·0.6·(1/100+1/100)) ≈ √0.0048 ≈ 0.0693. z = 0.20/0.0693 ≈ 2.89. p < 0.005 (two-sided).",
    [
      { q: "2-prop z test stat?", a: "z = (p̂₁-p̂₂)/√(p̂_c q̂_c(1/n₁+1/n₂))" },
      { q: "Pool for test?", a: "Yes (assumes H₀ true)." },
      { q: "Pool for CI?", a: "No." },
      { q: "Two-sided p-value?", a: "2·P(Z ≥ |z|)" },
      { q: "Reject when?", a: "p-value < α" },
    ],
  ),
  mk(7, "7.1", "Introducing Statistics: Should I Worry About Error?",
    "Sample means have uncertainty — use t-based methods when σ unknown.",
    [
      "When σ unknown (usual), estimate with s; use t distribution.",
      "t is bell-shaped but heavier tails; approaches normal as df grows.",
      "Df = n − 1 for one sample.",
      "tdf with larger df closer to z.",
    ],
    "Why use t instead of z?",
    "Because we estimate σ with s, which adds variability — t accounts for this.",
    [
      { q: "When use t vs z?", a: "t when σ unknown (use s)." },
      { q: "df for one sample?", a: "n − 1" },
      { q: "Shape of t?", a: "Symmetric, heavier tails than normal." },
      { q: "As df → ∞?", a: "t → z (standard normal)." },
      { q: "Conservative df for two-sample t?", a: "Smaller of (n₁-1, n₂-1) if no pool." },
    ],
  ),
  mk(7, "7.2", "Constructing a Confidence Interval for a Population Mean",
    "1-sample t-interval: x̄ ± t* (s/√n). df = n − 1.",
    [
      "Conditions: Random, Independent (10%), Normal (population normal OR n ≥ 30 or graph ok).",
      "SE = s/√n.",
      "CI = x̄ ± t*·SE with df = n − 1.",
      "Use invT or table for t*.",
    ],
    "x̄ = 25, s = 4, n = 16. 95% CI?",
    "SE = 4/4 = 1. df=15, t* ≈ 2.131. CI = 25 ± 2.131 = (22.87, 27.13).",
    [
      { q: "1-sample t-interval?", a: "x̄ ± t*(s/√n), df = n−1" },
      { q: "Normality condition?", a: "Population normal OR n ≥ 30 OR sample graph symmetric no outliers." },
      { q: "SE?", a: "s/√n" },
      { q: "df?", a: "n − 1" },
      { q: "t* vs z*?", a: "Slightly larger for same confidence (small n)." },
    ],
  ),
  mk(7, "7.3", "Justifying a Claim About a Population Mean Based on a Confidence Interval",
    "CI for μ excludes μ₀ → evidence μ ≠ μ₀ at (1−α) confidence.",
    [
      "CI includes claimed μ₀ → plausible.",
      "CI excludes μ₀ → reject claim at two-sided α.",
      "Support with context.",
      "Never claim CI contains the parameter with certainty.",
    ],
    "95% CI for μ = (50, 60). Is μ=45 plausible?",
    "No — 45 is outside; reject claim at 95% confidence.",
    [
      { q: "CI contains μ₀ → ?", a: "μ₀ plausible at that confidence." },
      { q: "CI excludes → ?", a: "Evidence μ ≠ μ₀ at two-sided α = 1−C." },
      { q: "Correct CI interpretation?", a: "'We are C% confident that μ lies in (a,b).'" },
      { q: "Wrong interpretation?", a: "'Probability μ is in this interval.'" },
      { q: "Margin of error (MoE)?", a: "t*·s/√n" },
    ],
  ),
  mk(7, "7.4", "Setting Up a Test for a Population Mean",
    "H₀: μ = μ₀. Test stat: t = (x̄ − μ₀)/(s/√n). Conditions: Random, 10%, Normal.",
    [
      "Hypotheses BEFORE data: H₀ and H_a.",
      "Test statistic: t = (x̄ − μ₀)/(s/√n).",
      "df = n − 1.",
      "Conditions: Random, 10% independence, Normal (pop normal or n ≥ 30 or ok graph).",
    ],
    "Claim μ > 20, x̄=23, s=6, n=25. Test stat?",
    "t = (23-20)/(6/5) = 3/1.2 = 2.5; df = 24.",
    [
      { q: "1-sample t test stat?", a: "t = (x̄ − μ₀)/(s/√n)" },
      { q: "df?", a: "n − 1" },
      { q: "Conditions?", a: "Random, 10%, Normal" },
      { q: "One-sided H_a options?", a: "μ > μ₀ or μ < μ₀" },
      { q: "Before computing t?", a: "State hypotheses." },
    ],
  ),
  mk(7, "7.5", "Carrying Out a Test for a Population Mean",
    "Compute t, use tcdf / table for p-value, compare to α, conclude in context.",
    [
      "Use tcdf(t, 1E99, df) for right-tail p-value.",
      "Two-sided p = 2 × one-sided.",
      "p < α → reject H₀.",
      "Conclusion in context.",
    ],
    "t = 2.5, df = 24, one-sided right. p ≈ ?",
    "tcdf(2.5, 1E99, 24) ≈ 0.010. Reject at α=0.05.",
    [
      { q: "Right-tail p for t?", a: "tcdf(t, 1E99, df)" },
      { q: "Two-sided p?", a: "2·(one-sided p)" },
      { q: "Reject when?", a: "p < α" },
      { q: "Conclude how?", a: "'Evidence that μ …' in context." },
      { q: "t critical values in table?", a: "Rows by df, columns by tail area." },
    ],
  ),
  mk(7, "7.6", "Confidence Intervals for the Difference of Two Means",
    "2-sample t-interval: (x̄₁−x̄₂) ± t* √(s₁²/n₁ + s₂²/n₂). Conservative df = min(n₁-1, n₂-1).",
    [
      "Unpooled (default on AP): SE = √(s₁²/n₁ + s₂²/n₂).",
      "Df conservative = smaller of n_i − 1 (or use calculator Satterthwaite).",
      "Conditions: Random, 10%, Normal for both.",
      "Independence BETWEEN samples.",
    ],
    "x̄₁=50, s₁=6, n₁=20; x̄₂=45, s₂=7, n₂=25. SE?",
    "SE = √(36/20 + 49/25) = √(1.8 + 1.96) = √3.76 ≈ 1.94.",
    [
      { q: "2-sample t CI SE?", a: "√(s₁²/n₁ + s₂²/n₂)" },
      { q: "Conservative df?", a: "Smaller of n_i − 1" },
      { q: "Do we pool on AP?", a: "Usually no (unpooled)." },
      { q: "Independence required?", a: "Yes — between the two samples." },
      { q: "Normal conditions?", a: "Both populations normal OR both n_i ≥ 30 OR both sample graphs acceptable." },
    ],
  ),
  mk(7, "7.7", "Justifying a Claim About the Difference of Two Means",
    "CI for μ₁ − μ₂ excludes 0 ⇒ evidence μ₁ ≠ μ₂.",
    [
      "CI contains 0 → no significant difference.",
      "CI above 0 → μ₁ > μ₂.",
      "CI below 0 → μ₁ < μ₂.",
      "State conclusion in context.",
    ],
    "95% CI for μ₁-μ₂ = (−2, 8). Significant?",
    "No — interval contains 0.",
    [
      { q: "CI contains 0?", a: "No significant difference." },
      { q: "CI all positive?", a: "μ₁ > μ₂ at that confidence." },
      { q: "CI all negative?", a: "μ₁ < μ₂." },
      { q: "Effect of wider CI?", a: "More likely to contain 0 — less precision." },
      { q: "Interpretation of μ₁ − μ₂?", a: "Difference of means in context." },
    ],
  ),
  mk(7, "7.8", "Setting Up a Test for the Difference of Two Population Means",
    "H₀: μ₁ = μ₂. Test stat t = (x̄₁-x̄₂)/SE. Conditions both samples.",
    [
      "H₀: μ₁ − μ₂ = 0.",
      "SE = √(s₁²/n₁ + s₂²/n₂) (unpooled).",
      "df conservative = smaller of n_i − 1.",
      "Conditions: Random (both), Independent (10% each), Normal (each pop or n ≥ 30 or ok graph).",
    ],
    "Claim: treatment A mean > B mean. Hypotheses?",
    "H₀: μ_A = μ_B; H_a: μ_A > μ_B.",
    [
      { q: "H₀ for 2-sample means?", a: "μ₁ = μ₂" },
      { q: "SE (unpooled)?", a: "√(s₁²/n₁ + s₂²/n₂)" },
      { q: "Conservative df?", a: "min(n₁-1, n₂-1)" },
      { q: "Independence?", a: "Between samples + within each (10%)." },
      { q: "Test stat t?", a: "(x̄₁−x̄₂)/SE" },
    ],
  ),
  mk(7, "7.9", "Carrying Out a Test for the Difference of Two Population Means",
    "Compute t, p-value, compare α, conclude in context.",
    [
      "t = (x̄₁-x̄₂)/√(s₁²/n₁ + s₂²/n₂).",
      "Use tcdf with conservative df (or calc df).",
      "Two-sided: p = 2·one-sided.",
      "Matched pairs: use 1-sample t on differences (not 2-sample t).",
    ],
    "Matched pairs data: differences d̄ = 3, s_d = 4, n = 10. Test H₀: μ_d = 0.",
    "t = 3/(4/√10) ≈ 2.37, df = 9. Two-sided p ≈ 0.042 → reject at 0.05.",
    [
      { q: "Matched pairs uses which test?", a: "1-sample t on differences." },
      { q: "df for matched pairs?", a: "n − 1 (pairs)" },
      { q: "Test stat for 2-sample (unpooled)?", a: "(x̄₁-x̄₂)/√(s₁²/n₁ + s₂²/n₂)" },
      { q: "Two-sided p?", a: "2·(one-sided tail)" },
      { q: "Reject when?", a: "p < α" },
    ],
  ),
  mk(7, "7.10", "Skew and Its Impact on Inference for Means",
    "Skew + small n = t-procedures unreliable. Check sample plot; larger n mitigates via CLT.",
    [
      "Normal condition: population normal OR large n (CLT).",
      "If sample graph shows strong skew and n small → inference suspect.",
      "Outliers particularly distort mean-based methods.",
      "Consider non-parametric or resampling approaches for small, skewed samples.",
    ],
    "n=10, sample strongly right-skewed. Proceed with t?",
    "Risky — skewness + small n violates normality condition. Consider other methods or larger sample.",
    [
      { q: "Robust t assumption?", a: "Moderate skew + n ≥ 30 usually OK." },
      { q: "Strong skew + small n?", a: "Inference unreliable." },
      { q: "Check normality how?", a: "Dotplot, histogram, boxplot, normal probability plot." },
      { q: "Outliers effect on mean-based inference?", a: "Inflate s and distort x̄." },
      { q: "Alternative?", a: "Transform, bootstrap, or use nonparametric tests." },
    ],
  ),
  mk(8, "8.1", "Introducing Statistics: Are My Results Unexpected?",
    "Chi-square tests compare observed counts to expected under a model.",
    [
      "Observed (O) from data; Expected (E) under model.",
      "χ² = Σ(O-E)²/E.",
      "Large χ² ⇒ observed far from expected.",
      "Three chi-square tests: GoF, homogeneity, independence.",
    ],
    "Expected 25, observed 30. Contribution to χ²?",
    "(30-25)²/25 = 1.",
    [
      { q: "Chi-square formula?", a: "χ² = Σ(O-E)²/E" },
      { q: "Large χ²?", a: "Observed far from expected — evidence against H₀." },
      { q: "Three chi-square tests?", a: "GoF, Homogeneity, Independence." },
      { q: "Need all E ≥ ?", a: "E ≥ 5 (condition)." },
      { q: "df (for GoF)?", a: "k − 1 (k categories)." },
    ],
  ),
  mk(8, "8.2", "Setting Up a Chi-Square Goodness of Fit Test",
    "H₀: distribution matches specified model. Compute expected counts; check conditions.",
    [
      "H₀: proportions match model (p₁=…, p₂=…, …).",
      "H_a: distribution differs.",
      "Expected count: n·p_i.",
      "Conditions: Random, Independent (10%), Expected counts ≥ 5.",
    ],
    "Test die fairness with 60 rolls. Expected per side?",
    "60/6 = 10 each.",
    [
      { q: "χ² GoF hypotheses?", a: "H₀: data fit the model; H_a: they don't." },
      { q: "Expected count?", a: "n × model proportion" },
      { q: "df?", a: "categories − 1" },
      { q: "Condition on expected counts?", a: "All ≥ 5." },
      { q: "Larger O-E mismatch → ?", a: "Larger χ², smaller p." },
    ],
  ),
  mk(8, "8.3", "Carrying Out a Chi-Square Goodness of Fit Test",
    "Compute χ², use χ²cdf, compare p-value, conclude in context.",
    [
      "χ² = Σ(O-E)²/E.",
      "p = χ²cdf(χ², 1E99, df).",
      "Reject if p < α.",
      "Always in context.",
    ],
    "χ² = 8.2, df = 5. p-value?",
    "≈ 0.145 (χ²cdf(8.2, 1E99, 5)). Don't reject at 0.05.",
    [
      { q: "χ² right-tail p?", a: "χ²cdf(χ², 1E99, df)" },
      { q: "Larger χ² means?", a: "Smaller p, stronger evidence against H₀." },
      { q: "Is χ² test one- or two-sided?", a: "One-sided (right tail only)." },
      { q: "df for GoF?", a: "categories − 1" },
      { q: "Decision?", a: "Reject if p < α." },
    ],
  ),
  mk(8, "8.4", "Expected Counts in Two-Way Tables",
    "E = (row total × column total)/grand total.",
    [
      "For any cell: E_ij = (row i total × col j total) / grand total.",
      "Must be consistent with the marginal totals.",
      "Required for homogeneity and independence tests.",
      "All E ≥ 5 for valid chi-square.",
    ],
    "Row 1 total = 40, Col 1 total = 30, grand = 100. Cell (1,1) expected?",
    "E₁₁ = (40·30)/100 = 12.",
    [
      { q: "Expected count (two-way)?", a: "(row total × col total)/grand total" },
      { q: "Condition?", a: "All E ≥ 5." },
      { q: "Why?", a: "χ² approximation fails with small expected counts." },
      { q: "Observed counts?", a: "Actual values in each cell." },
      { q: "Sum of expected = grand total?", a: "Yes, same as observed." },
    ],
  ),
  mk(8, "8.5", "Setting Up a Chi-Square Test for Homogeneity or Independence",
    "Homogeneity: same distribution across groups. Independence: no association between two variables.",
    [
      "Homogeneity: multiple populations/groups, one categorical variable.",
      "Independence: one population, two categorical variables.",
      "Both use same test stat and df formula.",
      "df = (rows − 1)(cols − 1).",
    ],
    "Test whether gender is independent of college major. Type?",
    "Chi-square test of independence (one population, two variables).",
    [
      { q: "Homogeneity test?", a: "Same distribution of ONE categorical var across multiple groups." },
      { q: "Independence test?", a: "Association between TWO categoricals in ONE population." },
      { q: "df for both?", a: "(rows − 1)(cols − 1)" },
      { q: "Conditions?", a: "Random, 10%, E ≥ 5 in every cell." },
      { q: "Distinction matter for calc?", a: "No — same computation; wording differs." },
    ],
  ),
  mk(8, "8.6", "Carrying Out a Chi-Square Test for Homogeneity or Independence",
    "Compute expected counts, χ², p-value, conclude in context.",
    [
      "E_ij = (row total)(col total)/grand total.",
      "χ² = Σ(O - E)²/E over all cells.",
      "df = (r-1)(c-1).",
      "p = χ²cdf(χ², 1E99, df).",
    ],
    "2×3 table, χ² = 15.0. df and p?",
    "df = (2-1)(3-1) = 2. p = χ²cdf(15, 1E99, 2) ≈ 0.00055.",
    [
      { q: "χ² cell contribution?", a: "(O-E)²/E" },
      { q: "df 2×3?", a: "2" },
      { q: "df 3×4?", a: "6" },
      { q: "p-value?", a: "Right-tail χ² area." },
      { q: "Conclusion language?", a: "'Evidence that distributions differ' (homogeneity) or 'variables not independent.'" },
    ],
  ),
  mk(8, "8.7", "Selecting an Appropriate Inference Procedure for Categorical Data",
    "Distinguish 1-prop, 2-prop, GoF, homogeneity, independence — by data structure.",
    [
      "1 prop: single sample, 2 categories, compare to p₀.",
      "2 prop: two samples, 2 categories (e.g., success/fail).",
      "GoF: 1 sample, many categories, compare to model.",
      "Homogeneity: multiple samples, 1 categorical.",
      "Independence: 1 sample, 2 categoricals.",
    ],
    "Two schools — compare proportion passing. Which test?",
    "2-proportion z-test.",
    [
      { q: "1-prop z?", a: "One sample vs. hypothesized p₀." },
      { q: "2-prop z?", a: "Two samples, compare p₁ vs p₂." },
      { q: "GoF?", a: "Test whether 1-sample distribution matches claimed model." },
      { q: "Homogeneity?", a: "Multiple samples — same distribution?" },
      { q: "Independence?", a: "Two variables in one sample — associated?" },
    ],
  ),
  mk(9, "9.1", "Introducing Statistics: Do Those Points Align?",
    "Linear regression slope is an estimate; inference quantifies uncertainty.",
    [
      "β = true slope; b = sample estimate.",
      "Inference: CI or test for β.",
      "Assumes LINE: Linear, Independent, Normal residuals, Equal SD.",
    ],
    "What do we infer about in regression inference?",
    "The true population slope β; b is just our estimate.",
    [
      { q: "True slope?", a: "β (population parameter)" },
      { q: "Sample slope?", a: "b (statistic)" },
      { q: "LINE acronym?", a: "Linear, Independent, Normal residuals, Equal variance" },
      { q: "Standard error of slope?", a: "SE_b (from output)" },
      { q: "df for slope inference?", a: "n − 2" },
    ],
  ),
  mk(9, "9.2", "Confidence Intervals for the Slope of a Regression Model",
    "CI: b ± t*·SE_b, df = n − 2.",
    [
      "b from regression output.",
      "SE_b from output.",
      "df = n − 2.",
      "Same LINE conditions as test.",
    ],
    "b = 1.5, SE_b = 0.3, n = 20. 95% CI?",
    "df = 18, t* ≈ 2.101. CI = 1.5 ± 2.101(0.3) = (0.87, 2.13).",
    [
      { q: "CI for slope?", a: "b ± t*·SE_b, df = n-2" },
      { q: "SE_b from?", a: "Regression output." },
      { q: "df?", a: "n − 2" },
      { q: "CI excludes 0 ⇒ ?", a: "Evidence of nonzero slope." },
      { q: "Conditions (LINE)?", a: "Linear, Independent, Normal, Equal SD." },
    ],
  ),
  mk(9, "9.3", "Justifying a Claim About the Slope of a Regression Model",
    "CI excludes 0 ⇒ evidence of linear relationship at (1−α) confidence.",
    [
      "CI for β contains 0 → no significant linear relationship.",
      "CI entirely positive → positive association.",
      "CI entirely negative → negative association.",
      "Conclusion in context.",
    ],
    "CI for slope = (0.5, 2.3). Evidence of linear association?",
    "Yes — entire interval > 0, so positive linear association at this confidence.",
    [
      { q: "CI for β includes 0?", a: "No significant linear association." },
      { q: "CI all above 0?", a: "Positive association at confidence." },
      { q: "CI all below 0?", a: "Negative association." },
      { q: "Width of CI?", a: "Measure of precision." },
      { q: "Report what in context?", a: "Units (per unit x, change in y)." },
    ],
  ),
  mk(9, "9.4", "Setting Up a Test for the Slope of a Regression Model",
    "H₀: β = 0 (no linear relationship). Test stat: t = b/SE_b, df = n − 2.",
    [
      "H₀: β = 0 vs H_a (one- or two-sided).",
      "Conditions: LINE.",
      "Test stat: t = b/SE_b.",
      "df = n − 2.",
    ],
    "Claim: x and y are linearly related. Hypotheses?",
    "H₀: β = 0; H_a: β ≠ 0.",
    [
      { q: "H₀ for slope?", a: "β = 0" },
      { q: "Test stat?", a: "t = b/SE_b" },
      { q: "df?", a: "n − 2" },
      { q: "LINE conditions?", a: "Linear, Independent, Normal residuals, Equal SD." },
      { q: "Two-sided H_a?", a: "β ≠ 0" },
    ],
  ),
  mk(9, "9.5", "Carrying Out a Test for the Slope of a Regression Model",
    "Compute t = b/SE_b, p-value from tcdf with df = n − 2, conclude.",
    [
      "Use output: b, SE_b, sometimes t already printed.",
      "p-value: tcdf(|t|, 1E99, df)×2 for two-sided.",
      "Reject H₀ if p < α.",
      "Conclusion in context.",
    ],
    "b = 2, SE_b = 0.5, n = 10. t and p?",
    "t = 4, df = 8. Two-sided p ≈ 0.004 → reject at α=0.05.",
    [
      { q: "Slope test stat?", a: "t = b/SE_b" },
      { q: "df?", a: "n − 2" },
      { q: "p-value (two-sided)?", a: "2·P(T ≥ |t|)" },
      { q: "Reject when?", a: "p < α" },
      { q: "Same as testing r = 0?", a: "Yes — equivalent tests." },
    ],
  ),
  mk(9, "9.6", "Selecting an Appropriate Inference Procedure",
    "Decision tree: categorical or quantitative? One/two samples? Means/props? Pair structure?",
    [
      "Quantitative data, 1 sample → 1-sample t.",
      "Quantitative, 2 ind samples → 2-sample t.",
      "Quantitative, paired → matched pairs (1-sample t on differences).",
      "Categorical, 1 prop → 1-prop z.",
      "Categorical, 2 props → 2-prop z.",
      "Categorical, multiple cat or multi-group → chi-square.",
      "Linear relationship quantitative → slope t.",
    ],
    "Comparing math scores of 2 randomly chosen classes. Test?",
    "Two-sample t-test for means (assuming conditions met).",
    [
      { q: "Matched pairs?", a: "1-sample t on differences." },
      { q: "2 independent samples, means?", a: "2-sample t (unpooled)." },
      { q: "2 independent samples, proportions?", a: "2-prop z." },
      { q: "Test of independence?", a: "Chi-square independence." },
      { q: "Slope significance?", a: "t-test on β with df = n − 2." },
    ],
  ),
];
