import type { Lesson } from "@/lib/topics";

/** AP World History: Modern — one Lesson per CED topic across all 9 units (71 topics). */

const KA = "https://www.khanacademy.org/humanities/world-history";

const U: Record<number, string> = {
  1: "The Global Tapestry (c. 1200-1450)",
  2: "Networks of Exchange (c. 1200-1450)",
  3: "Land-Based Empires (c. 1450-1750)",
  4: "Transoceanic Interconnections (c. 1450-1750)",
  5: "Revolutions (c. 1750-1900)",
  6: "Consequences of Industrialization (c. 1750-1900)",
  7: "Global Conflict (c. 1900-present)",
  8: "Cold War and Decolonization (c. 1900-present)",
  9: "Globalization (c. 1900-present)",
};

const mk = (
  unit: number,
  id: string,
  title: string,
  blurb: string,
  keyIdeas: string[],
  sampleProblem: string,
  sampleWalkthrough: string,
  flashcards: { q: string; a: string }[]
): Lesson => ({
  slug: `apworld-${id.replace(".", "-")}`,
  title,
  courses: [{ courseSlug: "ap-world-history", unitNumber: unit, unitTitle: U[unit] }],
  blurb,
  keyIdeas,
  sampleProblem,
  sampleWalkthrough,
  flashcards,
  links: [{ title: "AP World History", url: KA, source: "Khan Academy" }],
});

export const AP_WORLD_HISTORY_LESSONS: Lesson[] = [
  mk(1, "1.1", "Developments in East Asia from c. 1200 to c. 1450",
    "Song China dominant: Neo-Confucianism, civil-service exam, Champa rice, paper money, gunpowder.",
    ["Song China most commercialized in 1200.", "Neo-Confucianism + civil-service exams.", "Champa rice doubled harvests.", "Tributary system extended cultural reach.", "Japan: feudal samurai/shogun. Korea/Vietnam selectively borrowed."],
    "SAQ: Briefly explain ONE Song economic development.",
    "Champa rice from Vietnam allowed Song China to support over 100M and cities like Hangzhou, financing paper money, iron industry, and Neo-Confucian bureaucracy that became a template for East Asia.",
    [{q:"Song dynasty?",a:"960-1279, commercialized China"},{q:"Champa rice?",a:"Drought-resistant from Vietnam"},{q:"Neo-Confucianism?",a:"Song revival blending Buddhist metaphysics"},{q:"Civil service exam?",a:"Merit-based bureaucracy"},{q:"Mandate of Heaven?",a:"Divine right to rule legitimacy"}],
  ),
  mk(1, "1.2", "Developments in Dar al-Islam from c. 1200 to c. 1450",
    "Abbasid fragmented but Islam expanded. Mamluks, Delhi Sultanate, Mali. Cultural golden age.",
    ["Abbasid politically declined; Mongol sack 1258.", "Mamluks defeated Mongols at Ain Jalut (1260).", "Delhi Sultanate (1206) brought Islam to N India.", "Mali (Mansa Musa 1324 hajj).", "Ibn Battuta, Ibn Khaldun cultural giants.", "Sufism main missionary force."],
    "SAQ: Briefly explain ONE way Islamic intellectual life expanded c. 1200-1450.",
    "After the Mongol sack of Baghdad (1258), Cairo under the Mamluks became a leading center of Sunni scholarship. Ibn Khaldun's Muqaddimah (1377) founded social-historical analysis, while Maragheh observatory (al-Tusi) produced planetary models later used by Copernicus.",
    [{q:"Mongol sack of Baghdad?",a:"1258"},{q:"Ain Jalut?",a:"1260 Mamluks defeat Mongols"},{q:"Delhi Sultanate?",a:"1206-1526"},{q:"Mansa Musa hajj?",a:"1324-25"},{q:"Sufism's role?",a:"Mystical Islam, main vehicle for conversion"}],
  ),
  mk(1, "1.3", "Developments in South and Southeast Asia from c. 1200 to c. 1450",
    "Hindu/Buddhist/Muslim mix. Delhi Sultanate, Vijayanagara, Khmer Angkor. Indianization of SE Asia.",
    ["Delhi Sultanate (1206-1526) ruled N India.", "Vijayanagara (1336-1646) Hindu south.", "Bhakti devotional movement.", "Khmer Empire (Angkor Wat).", "Srivijaya, Majapahit (Indonesia).", "Islam reached Malacca (~1400)."],
    "SAQ: Briefly explain ONE example of Indianization in SE Asia.",
    "The Khmer Empire built Angkor Wat (early 12th c.) using Hindu temple architecture and devaraja god-king ideology — adopted from India through trade, never via conquest.",
    [{q:"Delhi Sultanate?",a:"Muslim N India 1206-1526"},{q:"Vijayanagara?",a:"Hindu S India empire"},{q:"Bhakti movement?",a:"Devotional Hinduism"},{q:"Angkor Wat?",a:"Khmer Hindu (later Buddhist) temple"},{q:"Indianization?",a:"Cultural diffusion via trade, not conquest"}],
  ),
  mk(1, "1.4", "State Building in the Americas",
    "Aztec tribute empire (Tenochtitlán). Inca Tawantinsuyu with mit'a labor and quipu.",
    ["Aztec: tribute empire, Triple Alliance (1428).", "Tenochtitlán huge city.", "Religion required human sacrifice.", "Inca: largest pre-Columbian empire.", "Mit'a labor tax.", "Quipu records, road system."],
    "SAQ: Briefly compare Aztec and Inca governance.",
    "Aztecs ruled indirectly through tribute from conquered city-states, allowing local rulers to remain. Incas ruled directly with centralized bureaucracy, mit'a labor draft, and 25,000-mile road system. Aztec used religious terror; Inca used state redistribution.",
    [{q:"Aztec capital?",a:"Tenochtitlán"},{q:"Triple Alliance?",a:"1428 Aztec founding"},{q:"Inca empire size?",a:"Largest pre-Columbian"},{q:"Mit'a?",a:"Andean labor tax"},{q:"Quipu?",a:"Knotted string records"}],
  ),
  mk(1, "1.5", "State Building in Africa",
    "Mali (Mansa Musa), Swahili Coast city-states, Great Zimbabwe, Christian Ethiopia.",
    ["Mali rich on trans-Saharan gold.", "Mansa Musa hajj (1324) crashed Egyptian gold prices.", "Timbuktu Islamic learning center.", "Swahili Coast: independent merchant city-states.", "Great Zimbabwe: stone-walled trade kingdom.", "Christian Ethiopia surrounded by Islam."],
    "SAQ: Briefly explain ONE African state's wealth source c. 1200-1450.",
    "Mali grew wealthy on the trans-Saharan gold-salt trade. Mansa Musa's 1324 hajj displayed this wealth so spectacularly that he crashed Egyptian gold markets for over a decade. Timbuktu became a major Islamic scholarly center.",
    [{q:"Mali wealth from?",a:"Trans-Saharan gold trade"},{q:"Mansa Musa?",a:"Mali king, 1324 hajj"},{q:"Swahili Coast feature?",a:"Independent Indian Ocean city-states"},{q:"Great Zimbabwe?",a:"Stone-walled gold-trading kingdom"},{q:"Ethiopia religion?",a:"Coptic Christian"}],
  ),
  mk(1, "1.6", "Developments in Europe from c. 1200 to c. 1450",
    "Feudalism + Catholic Church + Black Death. Universities, Crusades, Hundred Years' War.",
    ["Feudalism + manorialism organized society.", "Catholic Church most universal institution.", "Universities (Bologna, Paris, Oxford).", "Crusades (1095-1291) increased Mediterranean contact.", "Black Death (1347-51) killed 30-50%.", "Hundred Years' War (1337-1453)."],
    "SAQ: Briefly explain ONE effect of the Black Death.",
    "The Black Death (1347-51) killed 30-50% of Europeans, creating labor shortages that raised peasant wages and weakened serfdom in Western Europe. It also shook Catholic Church authority and inspired anti-Jewish pogroms.",
    [{q:"Feudalism?",a:"Land for military service"},{q:"Black Death years?",a:"1347-51"},{q:"Black Death mortality?",a:"30-50% of Europe"},{q:"Crusades?",a:"1095-1291"},{q:"Hundred Years' War?",a:"1337-1453"}],
  ),
  mk(1, "1.7", "Comparison in the Period from c. 1200 to c. 1450",
    "All major regions: complex bureaucracies, religious legitimation, trade-based wealth, patriarchy.",
    ["Similarities: bureaucracies, religion, trade, patriarchy.", "Differences: political structure (centralized vs feudal), religion (5 major), labor systems, women's status."],
    "LEQ: Compare administration in two regions c. 1200-1450.",
    "Song China and Inca both used centralized bureaucracies for vast territories, but differently. Song staffed via Neo-Confucian exam and used paper money/Grand Canal. Inca had no writing or money — used mit'a labor tax, quipu records, and 25,000-mile road network with chasqui runners.",
    [{q:"Universal feature?",a:"Religion legitimized state"},{q:"Centralized vs feudal?",a:"Song China vs Europe"},{q:"Neo-Confucianism feature?",a:"Foot binding for elite women"},{q:"Mongol women's status?",a:"Higher than Song Chinese"},{q:"Long-distance trade?",a:"Funded states everywhere"}],
  ),
  mk(2, "2.1", "The Silk Roads",
    "Overland Eurasian luxury trade. Pax Mongolica (1250-1350) enabled boom. Caravanserai, paper money.",
    ["Silk Roads = network, not single road.", "Boomed under Pax Mongolica.", "Carried silk, porcelain, gunpowder west; horses, silver east.", "Spread Buddhism, Islam, Black Death.", "Caravanserai gave caravans rest.", "Paper money + sakk (Islamic checks)."],
    "SAQ: Briefly explain ONE reason Silk Roads expanded c. 1200-1450.",
    "Mongol unification (Pax Mongolica, 1250-1350) made the entire route safe for caravans for the first time. Marco Polo and Ibn Battuta could travel from Karakorum to Tabriz with relative safety, and goods like Chinese porcelain reached Europe in greater volume than ever.",
    [{q:"Pax Mongolica?",a:"1250-1350 Mongol-protected trade"},{q:"Caravanserai?",a:"Inns for caravans"},{q:"Sakk?",a:"Islamic credit system"},{q:"Marco Polo?",a:"Venetian traveler 1271-95"},{q:"Why Silk Roads declined?",a:"Black Death + Mongol fragmentation"}],
  ),
  mk(2, "2.2", "The Mongol Empire and the Modern World",
    "Largest contiguous land empire. Pax Mongolica integrated Eurasia; transferred technologies, ideas, disease.",
    ["Genghis Khan unified Mongols 1206.", "By 1260: Korea to Hungary.", "Four khanates after Genghis.", "Pax Mongolica enabled exchange.", "Gunpowder, printing, compass moved west.", "Black Death traveled along Mongol routes.", "Yuan ousted by Ming (1368)."],
    "SAQ: Briefly explain ONE way Mongol Empire facilitated exchange.",
    "Mongol political unification of Eurasia enabled safe transfer of Chinese inventions like gunpowder, printing, and compass to the Islamic world and Europe. Persian astronomers worked at the Yuan court; Indo-Arabic numerals spread eastward — unprecedented exchange that prefigured early modern globalization.",
    [{q:"Genghis Khan?",a:"Unified Mongols 1206"},{q:"Mongol khanates?",a:"4: Yuan, Ilkhanate, Chagatai, Golden Horde"},{q:"Yuan Dynasty?",a:"China under Mongols 1271-1368"},{q:"Yam system?",a:"Mongol postal relays"},{q:"Mongol religious tolerance?",a:"Yes — diverse religions allowed"}],
  ),
  mk(2, "2.3", "Exchange in the Indian Ocean",
    "Largest pre-modern maritime system. Monsoon winds, dhows + junks, diasporic merchants.",
    ["Connected E. Africa, Arabia, India, SE Asia, China.", "Monsoon winds enabled scheduled voyages.", "Dhows (Arab/Indian), junks (Chinese).", "Diasporic merchants in port cities.", "Spread Islam to E. Africa, Indonesia.", "Zheng He fleets (1405-33)."],
    "SAQ: Briefly explain ONE factor enabling Indian Ocean trade.",
    "Predictable monsoon wind reversals (NE in winter, SW in summer) allowed ships to make planned round trips across the Indian Ocean basin, enabling the largest pre-modern maritime trade system from East Africa to China.",
    [{q:"Indian Ocean trade size?",a:"Largest pre-modern maritime system"},{q:"Monsoons enabled?",a:"Scheduled long voyages"},{q:"Swahili language?",a:"Bantu + Arabic mix"},{q:"Zheng He years?",a:"1405-33"},{q:"Malacca conversion?",a:"To Islam ~1414"}],
  ),
  mk(2, "2.4", "Trans-Saharan Trade Routes",
    "Camel caravans across Sahara. Gold-salt trade. Mali, Songhai. Spread Islam to W Africa.",
    ["Camel saddle + caravanserai = Sahara crossing.", "Gold from south, salt from Saharan mines.", "Mali (Mansa Musa) and Songhai built on this trade.", "Islam spread through merchants (not conquest).", "Timbuktu Islamic scholarly center."],
    "SAQ: Briefly explain ONE feature of trans-Saharan trade.",
    "Camel caravans (often 1,000+ camels) crossed the Sahara on routes punctuated by oasis caravanserai. The exchange of West African gold for Saharan salt enriched empires like Mali and made Timbuktu a major center of Islamic learning.",
    [{q:"Trans-Saharan main trade?",a:"Gold + salt"},{q:"Mali king famous for hajj?",a:"Mansa Musa (1324)"},{q:"Songhai successor?",a:"Replaced Mali (1464+)"},{q:"Camel role?",a:"Made caravan crossing feasible"},{q:"Decline cause?",a:"Portuguese caravels reached W African coasts"}],
  ),
  mk(2, "2.5", "Cultural Consequences of Connectivity",
    "Religion, language, technology, art spread along trade routes.",
    ["Islam spread via merchants (W Africa, SE Asia).", "Sikhism (~1500) fused Hindu and Sufi.", "Swahili = Bantu + Arabic.", "Chinese gunpowder, printing west.", "Indo-Arabic numerals to Europe.", "Travelers documented integration."],
    "SAQ: Briefly explain ONE cultural diffusion example.",
    "Indo-Arabic numerals reached Europe via Italy in 1202 (Fibonacci). They replaced Roman numerals in commerce, enabling more sophisticated mathematics, accounting, and eventually scientific calculation in Renaissance Europe.",
    [{q:"Sikhism founder?",a:"Guru Nanak (~1500)"},{q:"Swahili?",a:"Bantu + Arabic"},{q:"Indo-Arabic numerals to Europe?",a:"Via Italy 1202 (Fibonacci)"},{q:"Marco Polo wrote?",a:"Travels (mid-1290s)"},{q:"Ibn Battuta?",a:"Moroccan traveled 75K miles"}],
  ),
  mk(2, "2.6", "Environmental Consequences of Connectivity",
    "Crops moved (Champa rice, sugar, bananas); Black Death devastated 30-50% of Europe.",
    ["Champa rice → Song China.", "Bananas → Africa via Indian Ocean.", "Sugar → Mediterranean.", "Black Death (1346-53) traveled Mongol routes.", "Killed 30-50% Europe, 1/3 ME, much in China.", "Broke European serfdom."],
    "SAQ: Briefly explain ONE environmental consequence of trade networks.",
    "The Black Death originated in Central Asia and traveled along Mongol-era trade routes, reaching Europe in 1347 via Crimea. It killed 30-50% of Europeans within 4 years, breaking serfdom in W Europe, raising peasant wages, and shaking Church authority.",
    [{q:"Champa rice impact?",a:"Doubled Song Chinese harvest"},{q:"Black Death origin?",a:"Central Asia"},{q:"Black Death European mortality?",a:"30-50%"},{q:"Bananas spread to?",a:"Sub-Saharan Africa via Indian Ocean"},{q:"Sugar's later impact?",a:"Atlantic plantation slavery"}],
  ),
  mk(2, "2.7", "Comparison of Economic Exchange",
    "Compare Silk Roads, Indian Ocean, trans-Saharan networks.",
    ["Similarities: luxury goods, religion, disease, expansion 1200-1350.", "Differences: scale (Indian Ocean largest); medium (overland vs maritime); cultural reach (Islam dominates 2)."],
    "LEQ: Compare two trade networks c. 1200-1450.",
    "Both Silk Roads and Indian Ocean networks carried luxury goods + religion + disease, used diasporic merchants, and depended on state protection. Silk Roads were overland with caravanserai; Indian Ocean was maritime with port cities. Indian Ocean carried much larger volume (including bulk goods); Silk Roads carried mostly low-volume luxuries.",
    [{q:"Largest by volume?",a:"Indian Ocean"},{q:"Mostly overland?",a:"Silk Roads + trans-Saharan"},{q:"Islam spread on?",a:"Indian Ocean and trans-Saharan"},{q:"All declined post-1350?",a:"Yes (Black Death + Mongol fragmentation)"},{q:"Diasporic merchants?",a:"Universal feature"}],
  ),
  mk(3, "3.1", "Empires Expand",
    "Five gunpowder empires: Ottoman, Safavid, Mughal, Qing, Russian. Cannons + standing armies.",
    ["Ottoman: Constantinople 1453.", "Safavid: forced Twelver Shi'ism on Persia 1501.", "Mughal: Babur at Panipat 1526.", "Qing (Manchu): replaced Ming 1644.", "Russia: Ivan III ended Mongol tribute 1480; Peter the Great westernized."],
    "SAQ: Briefly explain ONE way gunpowder enabled empire expansion.",
    "Ottoman use of large bronze cannons in 1453 brought down the Theodosian walls of Constantinople — walls that had repelled attackers for over a millennium. Conquest gave the Ottomans control of the Bosporus and a base for expansion into the Balkans and Egypt.",
    [{q:"Five gunpowder empires?",a:"Ottoman, Safavid, Mughal, Qing, Russian"},{q:"Constantinople fell?",a:"1453"},{q:"Safavid religion?",a:"Twelver Shia (forced)"},{q:"Mughal founder?",a:"Babur at Panipat 1526"},{q:"Manchu Qing year?",a:"1644 (replaced Ming)"}],
  ),
  mk(3, "3.2", "Empires: Administration",
    "Bureaucracies bypassed hereditary aristocracy. Devshirme, mansabdars, bannermen, Table of Ranks.",
    ["Ottoman devshirme: Christian boys → Janissaries.", "Mughal mansabdars ranked by service.", "Qing banners + Confucian exams.", "Russian Peter's Table of Ranks (1722).", "Tax farming (iltizam, zamindar)."],
    "SAQ: Briefly explain ONE way an empire used non-aristocratic servants.",
    "The Ottoman devshirme system took Christian boys from the Balkans, converted them to Islam, and trained them as Janissaries (military) or palace administrators. Loyal only to the sultan, they helped check aristocratic power — though the system also generated its own elite over time.",
    [{q:"Devshirme?",a:"Ottoman tax of Christian boys"},{q:"Janissaries?",a:"Elite Ottoman infantry from devshirme"},{q:"Mansabdars?",a:"Mughal ranked nobles"},{q:"Tax farming?",a:"Selling tax-collection rights"},{q:"Peter's Table of Ranks?",a:"1722 — service-based status"}],
  ),
  mk(3, "3.3", "Empires: Belief Systems",
    "Each empire used religion to legitimize. Ottoman millets, Safavid Shi'ization, Akbar tolerance, Aurangzeb persecution.",
    ["Ottoman millet: religious autonomy + jizya.", "Safavid: forced Shi'ism on Persia.", "Akbar abolished jizya, tried Din-i Ilahi.", "Aurangzeb reimposed jizya.", "Qing: Confucianism + Tibetan Buddhism.", "Russia: Orthodox Christianity."],
    "SAQ: Briefly explain ONE empire's religious policy.",
    "The Ottoman millet system organized non-Muslim subjects (Greek Orthodox, Armenian, Jewish) into self-governing religious communities under their own leaders, paying jizya — a hierarchical pluralism that contrasted sharply with Safavid forced Shi'ism.",
    [{q:"Millet system?",a:"Ottoman religious autonomy with jizya"},{q:"Akbar's policy?",a:"Tolerance, abolished jizya"},{q:"Aurangzeb reversed?",a:"Reimposed jizya, persecuted"},{q:"Safavid policy?",a:"Forced Shi'ism on Persia"},{q:"Russia religion?",a:"Orthodox Christian, 'Third Rome'"}],
  ),
  mk(3, "3.4", "Comparison in Land-Based Empires",
    "Shared gunpowder + bureaucracy + religious legitimation. Differed in religion and succession.",
    ["Common: gunpowder + standing armies + central tax.", "Common: religion legitimizing rule.", "Differ: religion (Sunni Ottoman, Shia Safavid, etc.).", "Differ: succession (Ottoman fratricide, Mughal civil war, Qing secret choice)."],
    "LEQ: Compare administration in Ottoman vs. Mughal empires.",
    "Both ruled religiously diverse populations and accommodated some pluralism. Ottomans used the millet system: non-Muslims under their own clergy + jizya. Mughals under Akbar abolished jizya and integrated Hindu Rajputs as mansabdars. Aurangzeb reversed Mughal tolerance after 1658, while millets remained stable through 1750. Both built bureaucracies bypassing hereditary aristocrats.",
    [{q:"Shared empire features?",a:"Gunpowder, bureaucracy, religious legitimation"},{q:"Ottoman religion?",a:"Sunni Islam"},{q:"Safavid religion?",a:"Shia Islam (Twelver)"},{q:"Mughal religion?",a:"Sunni Islam (ruling Hindu majority)"},{q:"Russia religion?",a:"Orthodox Christianity"}],
  ),
  mk(4, "4.1", "Technological Innovations from 1450 to 1750",
    "Caravel, carrack, galleon ships + compass, astrolabe. Knowledge globally borrowed.",
    ["Caravel: maneuverable for African coast.", "Carrack, galleon: ocean ships.", "Compass (China), astrolabe (Muslim).", "Lateen sail (Arab).", "Cartography, Mercator projection.", "Volta do mar wind knowledge."],
    "SAQ: Briefly explain ONE technological innovation enabling oceanic voyages.",
    "The combination of compass (Chinese), astrolabe (Muslim/Greek), and lateen sail (Arab) allowed ships to navigate open oceans and sail upwind — making Portuguese exploration along Africa and Spanish westward voyages technologically feasible.",
    [{q:"Caravel?",a:"Portuguese maneuverable ship"},{q:"Compass origin?",a:"China"},{q:"Astrolabe?",a:"Improved by Muslims"},{q:"Volta do mar?",a:"Portuguese wind navigation knowledge"},{q:"Mercator projection?",a:"1569 — constant-bearing courses"}],
  ),
  mk(4, "4.2", "Exploration: Causes and Events from 1450 to 1750",
    "God, Gold, Glory drove Iberian then northern European exploration. Tordesillas split.",
    ["Motivations: religion, wealth, state competition.", "Portugal: Dias 1488, da Gama 1498 → trading-post empire.", "Spain: Columbus 1492 → conquest.", "Treaty of Tordesillas (1494).", "Northern Europeans (English, Dutch, French) followed with joint-stock companies."],
    "SAQ: Briefly explain ONE motivation for European exploration.",
    "Ottoman dominance over Asian trade routes (after Constantinople fell 1453) made finding sea routes commercially essential — driving Portuguese voyages around Africa (da Gama 1498) and Spanish westward voyages (Columbus 1492).",
    [{q:"Three Gs?",a:"God, Gold, Glory"},{q:"Da Gama reached India?",a:"1498"},{q:"Columbus year?",a:"1492"},{q:"Tordesillas?",a:"1494 split between Spain and Portugal"},{q:"VOC, EIC?",a:"Dutch, English East India Companies"}],
  ),
  mk(4, "4.3", "Columbian Exchange",
    "Bidirectional plant/animal/people/disease transfer. Disease killed 50-90% of Natives.",
    ["To Americas: wheat, sugar, horses, cattle, smallpox.", "To Eurasia/Africa: maize, potato, tomato, syphilis.", "Native mortality: 50-90%.", "Potato boosted European population 25%+.", "Silver from Potosí globalized economy."],
    "SAQ: Briefly explain ONE effect of the Columbian Exchange.",
    "New World silver from Potosí (1545+) flowed to Europe and onward to China, integrating the global economy as Europeans used American silver to buy Asian luxuries. This sparked Europe's 'price revolution' and made China the world's silver sink.",
    [{q:"Mortality estimate?",a:"50-90% of Natives died"},{q:"Smallpox effect?",a:"Devastated Tenochtitlán 1520-21"},{q:"Potato impact?",a:"+25% European population by 1800"},{q:"Potosí silver?",a:"Globalized economy"},{q:"Maize spread?",a:"Throughout Europe, Africa, China"}],
  ),
  mk(4, "4.4", "Maritime Empires Established",
    "Spanish territorial, Portuguese trading-post, Dutch commercial, English settler/plantation.",
    ["Spanish: territorial empire in Americas (Cortés 1521, Pizarro 1533).", "Portuguese: trading posts (Goa, Malacca, Macau) + Brazil plantations.", "Dutch: VOC commercial empire.", "English/French: settlements + plantations + India trading."],
    "SAQ: Briefly explain ONE difference among European maritime empires.",
    "Spanish empires were territorial conquests in the Americas based on silver mining and Native labor; Portuguese empires were strings of fortified trading posts (Goa, Malacca, Macau) extracting profit from controlling trade choke-points without territorial conquest of Asian states.",
    [{q:"Cortés conquered?",a:"Aztec 1521"},{q:"Pizarro conquered?",a:"Inca 1533"},{q:"VOC year?",a:"1602"},{q:"Trading-post empire?",a:"Portuguese (Goa, Malacca)"},{q:"Manila galleons?",a:"1565-1815 silver to Asia"}],
  ),
  mk(4, "4.5", "Maritime Empires Maintained and Developed",
    "Mercantilism, joint-stock companies, Atlantic slave trade (~12.5M Africans), triangular trade.",
    ["Mercantilism: state-managed trade.", "Navigation Acts (1651+).", "VOC, EIC: joint-stock companies.", "Atlantic slave trade: ~12.5M Africans embarked.", "Triangular trade: goods/Africans/raw materials.", "African states (Asante, Dahomey) participated."],
    "SAQ: Briefly explain ONE feature of the Atlantic slave trade.",
    "About 12.5 million Africans embarked on the Middle Passage between 1500 and 1866. African states (Asante, Dahomey, Kongo) actively participated by selling captives in exchange for European guns — which raised the stakes of warfare and slave-raiding across West Africa.",
    [{q:"Atlantic slave trade total?",a:"~12.5M Africans"},{q:"Middle Passage mortality?",a:"~15%"},{q:"Mercantilism?",a:"State-managed export-positive trade"},{q:"VOC powers?",a:"War, treaties, mint coin"},{q:"China silver demand?",a:"Single-Whip law, 1581"}],
  ),
  mk(4, "4.6", "Internal and External Challenges to State Power",
    "Slave revolts (Maroon communities), peasant rebellions (Pugachev), Pueblo Revolt (1680), Túpac Amaru.",
    ["Maroon communities (Palmares Brazil, Jamaica).", "Pueblo Revolt (1680) drove Spanish from NM 12 years.", "Pugachev (1773-75) Russian peasants.", "Celali Revolts (Ottoman).", "Sikh + Maratha resistance to Aurangzeb.", "Túpac Amaru II (1780) Andean revolt."],
    "SAQ: Briefly explain ONE rebellion against early modern empires.",
    "The Pueblo Revolt (1680) was the most successful pre-1776 anti-colonial uprising in North America. Pope coordinated Pueblo peoples to drive Spanish settlers from Santa Fe; Spanish didn't return for 12 years.",
    [{q:"Maroon community example?",a:"Palmares (Brazil)"},{q:"Pueblo Revolt?",a:"1680 New Mexico"},{q:"Pugachev?",a:"1773-75 Russian peasants"},{q:"Túpac Amaru II?",a:"1780 Peruvian"},{q:"Maratha resistance?",a:"Hindu vs Aurangzeb"}],
  ),
  mk(4, "4.7", "Changing Social Hierarchies from 1450 to 1750",
    "Spanish casta system; British North America hardened racial slavery (Bacon's 1676); merchant class rose.",
    ["Spanish casta: peninsulares > criollos > mestizos > indios > Africans.", "British N. America: rigid Black/white binary post-Bacon's Rebellion (1676).", "Merchant bourgeoisie expanded.", "Russian boyars sidelined by Peter.", "Tokugawa samurai lost military function."],
    "SAQ: Briefly explain ONE change in social hierarchy 1450-1750.",
    "After Bacon's Rebellion (1676), Virginia hardened racial slavery into law: indentured servants who'd been ethnically mixed were separated, with Europeans freed and Africans permanently enslaved. The legal category 'white' as racial identity congealed.",
    [{q:"Casta hierarchy top?",a:"Peninsulares (Spain-born)"},{q:"Bacon's Rebellion year?",a:"1676 Virginia"},{q:"Russian boyar fate?",a:"Sidelined by Peter the Great"},{q:"Tokugawa samurai?",a:"Lost military function under peace"},{q:"Female rulers?",a:"Elizabeth I, Catherine the Great"}],
  ),
  mk(4, "4.8", "Continuity and Change from 1450 to 1750",
    "Continuities: agriculture, religion, patriarchy, slavery (existed before). Changes: oceanic integration, Columbian Exchange, joint-stock companies.",
    ["Continuities: agriculture, religion-state, patriarchy, slavery.", "Changes: oceanic integration, Columbian Exchange, silver economy, Atlantic slavery, gunpowder empires, Reformation, Scientific Revolution."],
    "LEQ: Evaluate transoceanic exchange's effect on Americas 1450-1750.",
    "Dramatically transformed: silver economy (Potosí → Manila → China), sugar plantations + enslaved Africans, decimated Native populations, Spanish casta society. Some continuity in Native subsistence agriculture and remote-area cultures. The Atlantic became the global economy's engine.",
    [{q:"Major change 1450-1750?",a:"Oceanic global integration"},{q:"Atlantic slave trade — invented slavery?",a:"No — expanded it dramatically"},{q:"Joint-stock companies?",a:"VOC 1602, EIC 1600"},{q:"Periodization?",a:"1450 transoceanic begins; 1750 industrial revolution starts"},{q:"Reformation?",a:"1517+ Protestant break"}],
  ),
  mk(5, "5.1", "The Enlightenment",
    "Reason applied to society. Locke, Voltaire, Montesquieu, Rousseau, Wollstonecraft.",
    ["Locke: natural rights, social contract.", "Montesquieu: separation of powers.", "Rousseau: general will.", "Adam Smith: free markets.", "Wollstonecraft: women's rights.", "Influenced US, French, Haitian, Latin American revolutions."],
    "SAQ: Briefly explain ONE Enlightenment idea's effect on revolution.",
    "John Locke's argument that legitimate government rests on consent of the governed — and that people may overthrow tyrants — directly shaped the US Declaration of Independence (1776), French Declaration of the Rights of Man (1789), and the Haitian Constitution (1801).",
    [{q:"Locke contributions?",a:"Natural rights, social contract"},{q:"Montesquieu?",a:"Separation of powers"},{q:"Rousseau?",a:"General will, popular sovereignty"},{q:"Adam Smith book?",a:"Wealth of Nations 1776"},{q:"Wollstonecraft work?",a:"Vindication of the Rights of Woman 1792"}],
  ),
  mk(5, "5.2", "Nationalism and Revolutions in the Period from 1750 to 1900",
    "Atlantic revolutions: American (1776), French (1789), Haitian (1791-1804), Latin American (1810-25).",
    ["American Revolution (1775-83): independence + Constitution.", "French Revolution (1789): Declaration, Terror, Napoleon.", "Haitian Revolution (1791-1804): first independent slave-revolt state.", "Latin American (Bolívar, San Martín, Hidalgo).", "1848 European revolutions.", "German (1871), Italian (1871) unifications."],
    "SAQ: Briefly explain ONE Atlantic revolution.",
    "The Haitian Revolution (1791-1804) was the first successful slave revolt to create an independent state. Toussaint Louverture and later Dessalines defeated French forces (decimated by yellow fever); Haiti declared independence 1804 — sending shockwaves through the Atlantic world.",
    [{q:"American Revolution years?",a:"1775-83"},{q:"French Revolution start?",a:"1789"},{q:"Haitian Revolution?",a:"1791-1804"},{q:"Bolívar?",a:"Liberated northern South America"},{q:"German unification?",a:"1871 (Bismarck)"}],
  ),
  mk(5, "5.3", "Industrial Revolution Begins",
    "Britain first c.1750-1850. Coal, capital, colonies, agricultural revolution, innovation.",
    ["Britain first: coal+iron, capital, colonies, gov stability, science.", "Cotton textile innovation: jenny, water frame, mule.", "Steam engine (Watt 1769).", "Railways (1830s).", "Factory system.", "Great Divergence: Britain pulls ahead of China/India."],
    "SAQ: Briefly explain ONE reason Britain industrialized first.",
    "Britain combined abundant coal (energy), capital from Atlantic trade, agricultural revolution (free labor + food surplus), colonies (raw materials + markets), and stable property-rights government. No single factor was decisive — the convergence enabled the world's first industrial economy.",
    [{q:"Industrial Revolution start?",a:"~1750 Britain"},{q:"Steam engine inventor?",a:"Watt (1769 condenser)"},{q:"Cotton machine?",a:"Spinning jenny, water frame, mule"},{q:"First railway?",a:"1830s Britain"},{q:"Great Divergence?",a:"Britain pulled ahead of China/India"}],
  ),
  mk(5, "5.4", "Industrialization Spreads in the Period from 1750 to 1900",
    "Spread to Belgium, France, Germany, US (1815-70), then Russia, Japan (state-led, late 19th c.).",
    ["Belgium first continental.", "Germany via Zollverein (1834).", "US Northeast then post-Civil War boom.", "Russia: Witte's Trans-Siberian.", "Japan: Meiji (1868), defeated Russia 1905.", "China Self-Strengthening failed.", "India deindustrialized by Britain."],
    "SAQ: Briefly explain ONE late industrialization case.",
    "Japan's Meiji Restoration (1868) overthrew the Tokugawa, restored imperial authority, abolished samurai privileges, and built railroads, factories, and modern army/navy. Defeating Russia in 1905 was Japan's announcement that an Asian power could industrialize fast enough to beat a great power.",
    [{q:"Meiji Restoration?",a:"1868"},{q:"Trans-Siberian Railway?",a:"Witte's project"},{q:"China's failed reform?",a:"Self-Strengthening Movement (1861-95)"},{q:"India and industry?",a:"Deindustrialized by Britain"},{q:"Adwa?",a:"1896 — Ethiopia defeated Italy"}],
  ),
  mk(5, "5.5", "Technology of the Industrial Age",
    "Second Industrial Revolution (1870-1914): steel, electricity, chemicals, internal combustion.",
    ["Bessemer steel (1856) cheap.", "Electricity: Edison, Tesla.", "Internal combustion: Otto, Benz, Ford.", "Chemicals: dyes, fertilizers, dynamite.", "Telegraph (1844), telephone (1876), radio.", "Suez (1869), Panama (1914) canals."],
    "SAQ: Briefly explain ONE Second Industrial Revolution technology.",
    "Bessemer steel (1856) made steel cheap enough for railroads, skyscrapers, ships, and machinery — transforming industry. Andrew Carnegie's American steel empire became the model for modern corporations and made industrial civilization possible at unprecedented scale.",
    [{q:"Bessemer process?",a:"Cheap steel (1856)"},{q:"Edison invention?",a:"Light bulb (1879)"},{q:"Telegraph year?",a:"1844 (Morse)"},{q:"Suez Canal?",a:"1869"},{q:"Maxim machine gun?",a:"1884"}],
  ),
  mk(5, "5.6", "Industrialization: Government's Role from 1750 to 1900",
    "Britain laissez-faire post-1846. Others protectionist (List). Russia, Japan state-led.",
    ["Britain: laissez-faire after Corn Laws repealed (1846).", "List argued infant industries need protection.", "US (Hamilton tariffs), Germany (Bismarck 1879).", "Russia (Witte), Japan (Meiji): state-led.", "Bismarck's social insurance (1883-89).", "Slave trade abolished (UK 1807); slavery (UK 1833, US 1865, Brazil 1888)."],
    "SAQ: Briefly explain ONE government role in industrialization.",
    "Bismarck's social insurance (health, accident, old-age, 1883-89) was the world's first welfare state. Aimed at undercutting socialist appeal, it set the template for 20th-century welfare programs across industrializing nations.",
    [{q:"British free trade after?",a:"Corn Laws repeal 1846"},{q:"List's argument?",a:"Protect infant industries"},{q:"Bismarck social insurance?",a:"1883-89"},{q:"UK abolished slave trade?",a:"1807"},{q:"Brazilian abolition?",a:"1888 (last in Americas)"}],
  ),
  mk(5, "5.7", "Economic Developments and Innovations in the Industrial Age",
    "Limited liability, joint-stock corps, trusts (US), cartels (Germany), multinationals.",
    ["Limited liability laws (UK 1855).", "Trusts (US): Standard Oil, US Steel.", "Cartels (Germany): chemicals, steel.", "Multinationals: Singer, Standard Oil.", "Global commodity chains.", "Mass production, Taylor's scientific management, Ford assembly line."],
    "SAQ: Briefly explain ONE economic innovation of the Industrial Age.",
    "Limited liability (UK 1855, 1862) shielded investors from personal loss beyond their investment, unleashing equity markets. Joint-stock corporations could raise vast capital for railroads, steel, and oil — making industrial capitalism possible at modern scale.",
    [{q:"Limited liability year?",a:"UK 1855"},{q:"Standard Oil?",a:"Rockefeller's trust"},{q:"Multinational examples?",a:"Singer, Standard Oil, United Fruit"},{q:"Ford assembly line?",a:"1913"},{q:"Taylor scientific management?",a:"1911"}],
  ),
  mk(5, "5.8", "Reactions to the Industrial Economy from 1750 to 1900",
    "Marxism, anarchism, labor unions, Bismarck's welfare. Luddites, Taiping, 1857 India.",
    ["Marx + Engels: Communist Manifesto (1848), Capital (1867).", "Anarchists: Bakunin.", "Trade unions, May Day (1889).", "SPD (1875), Labour Party (1900).", "Bismarck's social insurance.", "Rerum Novarum (1891).", "Taiping Rebellion (1850-64) 20-30M dead."],
    "SAQ: Briefly explain ONE response to industrial conditions.",
    "Karl Marx and Friedrich Engels' Communist Manifesto (1848) framed industrial conflict as proletariat vs. bourgeoisie, predicting workers would overthrow capitalism. Marxism became globally influential — the framework for socialist parties (SPD 1875), the Russian Revolution (1917), and Cold War politics.",
    [{q:"Communist Manifesto?",a:"Marx, Engels 1848"},{q:"SPD?",a:"German Social Democratic Party 1875"},{q:"Bismarck welfare?",a:"1883-89 to undercut socialism"},{q:"Taiping Rebellion?",a:"1850-64, 20-30M dead"},{q:"Sepoy Mutiny?",a:"India 1857"}],
  ),
  mk(5, "5.9", "Society and the Industrial Age",
    "New class structure, separate spheres, first-wave feminism, demographic transition, mass migration.",
    ["Industrial bourgeoisie, middle class, proletariat.", "Separate spheres for middle-class women.", "Seneca Falls (1848) US feminism.", "NZ women suffrage (1893), Australia (1902).", "Demographic transition.", "~50M Europeans + 30M Asians migrated 1820-1914."],
    "SAQ: Briefly explain ONE social effect of industrialization.",
    "Industrialization's separation of home and workplace produced 'separate spheres' ideology, assigning middle-class women to domestic life while drawing working-class women into wage labor (Lowell mills, Manchester textiles). Both created tensions that fueled first-wave feminism.",
    [{q:"Separate spheres?",a:"Middle-class doctrine: men public, women domestic"},{q:"Seneca Falls?",a:"1848 US women's rights convention"},{q:"NZ women's suffrage?",a:"1893 (first nation)"},{q:"Demographic transition?",a:"Industrializing societies' birth/death rates fall"},{q:"Migration scale?",a:"~80M global 1820-1914"}],
  ),
  mk(5, "5.10", "Continuity and Change in the Industrial Age",
    "Massive change in economy + politics + society. Continuities: peasant majority globally, patriarchy, religion.",
    ["Changes: factory, fossil energy, urbanization, mass politics, industrial empire, ideologies.", "Continuities: most humans peasants, patriarchy, religion, hierarchy, famines."],
    "LEQ: Evaluate gender role changes 1750-1900.",
    "Significant change in industrializing societies: separate spheres ideology emerged in middle class; working-class women became factory laborers; first-wave feminists organized; women got vote in NZ (1893), Australia (1902). But patriarchy continued: women excluded from political power globally, paid less, primary childcare. Form changed; fundamental hierarchy persisted.",
    [{q:"Industrial Age major change?",a:"Factory system + global integration"},{q:"Major continuity?",a:"Most humans still peasants in 1900"},{q:"Slavery legally ended?",a:"By late 19th c. globally"},{q:"Coerced labor continued?",a:"Yes — indenture, peonage"},{q:"1750 to 1900?",a:"Industrial-imperial peak"}],
  ),
  mk(6, "6.1", "Rationales for Imperialism from 1750 to 1900",
    "Social Darwinism, civilizing mission, Christianity, economic, strategic. Hobson + Lenin critiqued.",
    ["Social Darwinism justified European 'fitness.'", "White Man's Burden (Kipling 1899).", "Christian missionary movement.", "Hobson, Lenin: economic causes.", "Strategic: Suez, naval bases.", "Critics existed."],
    "SAQ: Briefly explain ONE rationale for imperialism.",
    "Social Darwinism misapplied Darwin's natural selection to nations and races, claiming European dominance proved their racial superiority. Used to justify colonial conquest as 'natural' and to legitimize what economic and strategic interests already pursued.",
    [{q:"Social Darwinism?",a:"Survival of fittest applied to nations"},{q:"Civilizing mission?",a:"French + British justification"},{q:"Hobson critique?",a:"1902 — capital surplus drives imperialism"},{q:"Lenin extension?",a:"1916 — late capitalism"},{q:"Maxim gun?",a:"1884 — colonial military advantage"}],
  ),
  mk(6, "6.2", "State Expansion from 1750 to 1900",
    "Scramble for Africa (1880-1914): 10% to 90% European-ruled. Berlin Conference (1884-85). India under Crown (1858).",
    ["Berlin Conference (1884-85) partitioned Africa.", "1880: 10% European; 1914: 90%.", "India: 1857 Rebellion → British Crown rule (1858).", "Adwa (1896) Ethiopia defeated Italy.", "Belgian Congo Free State atrocities.", "US: continental + 1898 (Hawaii, PI, PR, Guam, Cuba)."],
    "SAQ: Briefly explain ONE feature of late 19th c. imperialism.",
    "The Berlin Conference (1884-85) saw 14 European powers + US partition Africa with no Africans present. It established 'effective occupation' as the rule for claiming African territory, accelerating the Scramble for Africa and reducing African independence to Ethiopia and Liberia by 1914.",
    [{q:"Berlin Conference?",a:"1884-85, partitioned Africa"},{q:"Scramble for Africa?",a:"1880-1914 (10% → 90%)"},{q:"Adwa victory?",a:"1896 Ethiopia vs Italy"},{q:"Indian Rebellion?",a:"1857 Sepoy Mutiny"},{q:"British Raj?",a:"1858+ Crown rule of India"}],
  ),
  mk(6, "6.3", "Indigenous Responses to State Expansion from 1750 to 1900",
    "Armed (Zulu, Mahdist, Boxer, Ghost Dance), reform (Self-Strengthening, Tanzimat, Meiji), political (INC).",
    ["Zulu: Isandlwana 1879.", "Mahdist Sudan: defeated Gordon 1885; defeated Omdurman 1898.", "Boxer Rebellion (1899-1901).", "Ghost Dance/Wounded Knee (1890).", "Self-Strengthening (China), Tanzimat (Ottoman) failed.", "Meiji (Japan) succeeded.", "Indian National Congress (1885)."],
    "SAQ: Briefly explain ONE indigenous response to imperialism.",
    "The Boxer Rebellion (1899-1901) was a Chinese anti-foreign uprising encouraged by Empress Dowager Cixi, attacking foreigners and Chinese Christians. Suppressed by an Eight-Nation Alliance — illustrating both Chinese resistance and the Qing's weakness against industrial powers.",
    [{q:"Zulu victory?",a:"Isandlwana 1879"},{q:"Mahdist victory?",a:"Khartoum 1885"},{q:"Boxer Rebellion?",a:"1899-1901 China"},{q:"Wounded Knee?",a:"1890 massacre"},{q:"Indian National Congress?",a:"1885 (later led independence)"}],
  ),
  mk(6, "6.4", "Global Economic Development from 1750 to 1900",
    "Industrial cores vs. commodity peripheries. London = financial capital. Famines under British rule.",
    ["Industrial cores: Europe, US, Japan.", "Commodity peripheries: Africa, Latin America, much of Asia.", "Gold standard + London capital.", "British free trade imposed via navy.", "Indian famines (1876-78, 1896-1900) killed tens of millions.", "Settler economies (US, Argentina, Australia)."],
    "SAQ: Briefly explain ONE feature of late 19th c. global economy.",
    "By 1900 the world was divided between industrial cores (Europe, US, Japan) producing manufactured goods and commodity peripheries (Africa, Latin America, much of Asia) producing raw materials. London served as global financial capital, with British capital financing railways from Argentina to India.",
    [{q:"Industrial cores?",a:"Europe, US, Japan"},{q:"Commodity peripheries?",a:"Africa, Latin America, much of Asia"},{q:"Gold standard?",a:"Most by 1900"},{q:"Indian famines?",a:"1876-78, 1896-1900 — millions dead"},{q:"Settler economies?",a:"US, Canada, Australia, Argentina"}],
  ),
  mk(6, "6.5", "Economic Imperialism from 1750 to 1900",
    "Unequal treaties (China after Opium Wars), financial control (Egypt, Ottoman). Latin American 'informal empire.'",
    ["Treaty of Nanjing (1842): Hong Kong, treaty ports, extraterritoriality.", "Spheres of influence in China by 1900.", "Egypt: financial control → British occupation (1882).", "Ottoman Public Debt Administration (1881).", "Latin America: politically independent, economically dependent.", "Monroe Doctrine + Roosevelt Corollary."],
    "SAQ: Briefly explain ONE form of economic imperialism.",
    "After Britain's Opium War victory (1842), the Treaty of Nanjing forced China to cede Hong Kong, open five treaty ports, pay indemnity, and grant extraterritoriality (foreigners exempt from Chinese law). Subsequent treaties reduced China to semi-colonial status with European spheres of influence by 1900.",
    [{q:"Opium War 1?",a:"1839-42"},{q:"Treaty of Nanjing?",a:"1842 — Hong Kong, treaty ports"},{q:"Extraterritoriality?",a:"Foreigners exempt from local law"},{q:"Egyptian Public Debt?",a:"Foreign control of finances → 1882 occupation"},{q:"Roosevelt Corollary?",a:"1904 US right to intervene in Latin America"}],
  ),
  mk(6, "6.6", "Causes of Migration in an Interconnected World",
    "Industrialization, transport revolution, demographic pressure, labor demand. ~80M global migrants 1820-1914.",
    ["Push: population, famine (Irish 1845-49), persecution (Russian Jews).", "Pull: industrial labor demand, cheap steamships, end of slavery.", "European migration (~50M to Americas).", "Asian migration (~30M Chinese, Indian).", "Indentured labor replaced enslaved.", "Restrictions: Chinese Exclusion 1882."],
    "SAQ: Briefly explain ONE migration pattern of 1820-1914.",
    "Indian indentured workers — about 1.5 million between 1830s and 1920 — were shipped under contracts to British colonies (Caribbean, Mauritius, Fiji, South Africa, Malaya) to replace enslaved labor on plantations. Critics called it 'a new system of slavery.'",
    [{q:"European migration?",a:"~50M to Americas 1820-1914"},{q:"Indian indenture?",a:"~1.5M to British colonies"},{q:"Chinese Exclusion Act?",a:"US 1882"},{q:"Push factor for Russian Jews?",a:"1881+ pogroms"},{q:"Irish migration cause?",a:"Potato Famine 1845-49"}],
  ),
  mk(6, "6.7", "Effects of Migration",
    "Diaspora communities, cultural diffusion, remittances, nativist backlash, indigenous dispossession.",
    ["Demographic transformation of Americas, Australia.", "Cultural diffusion (food, language, religion).", "Diaspora communities: Chinese in SE Asia, Indians in Africa.", "Remittances supported origin societies.", "Nativist backlash (Know-Nothings, anti-Chinese).", "Indigenous dispossession (Plains Wars, Conquest of the Desert)."],
    "SAQ: Briefly explain ONE effect of migration.",
    "Chinese migration to Southeast Asia formed merchant diaspora communities (Singapore, Malaya, Vietnam, Indonesia) that became economically influential. They preserved Chinese cultural identity, sent remittances home, and sometimes faced violent backlash (anti-Chinese pogroms).",
    [{q:"Diaspora examples?",a:"Chinese in SE Asia, Indians in E Africa"},{q:"Remittances?",a:"Money sent home by migrants"},{q:"Nativist backlash example?",a:"Know-Nothing party, anti-Chinese laws"},{q:"Indigenous dispossession?",a:"US Plains Wars, Argentine Conquest of Desert"},{q:"Chinatown function?",a:"Support network for immigrants"}],
  ),
  mk(6, "6.8", "Causation in the Imperial Age",
    "Industrialization caused imperialism + migration; imperialism intensified inequality + resistance.",
    ["Industrialization → imperialism (markets, raw materials).", "Imperialism → famines, resistance, WWI tensions.", "Migration reshaped Americas, diasporas.", "Reciprocal: industrial + imperial mutually reinforced."],
    "LEQ: Evaluate causes of European imperialism 1750-1900.",
    "Economic and strategic factors most fundamental. Industrialization created insatiable demand for raw materials (rubber, cotton, oil) and outlets for capital (Hobson). Inter-state competition drove the Scramble. Military technology (Maxim gun, steamship, quinine) made conquest feasible. Ideologies (Social Darwinism, civilizing mission) provided moral justification but followed economic motives.",
    [{q:"Industrialization caused?",a:"Imperialism + migration + ideologies"},{q:"Hobson, Lenin?",a:"Saw imperialism as outlet for capital surplus"},{q:"Maxim gun year?",a:"1884"},{q:"Periodization?",a:"1900 = peak of industrial-imperial order"},{q:"Reciprocal causation?",a:"Industrial + imperial mutually reinforce"}],
  ),
  mk(7, "7.1", "Shifting Power After 1900",
    "Old land empires (Ottoman, Qing, Russian) declined; rising powers (US, Germany, Japan). 1910s revolutions.",
    ["Ottoman 'Sick Man.'", "Qing fell to Sun Yat-Sen's 1911 revolution.", "Russia: 1905 then 1917 revolutions.", "Mexican Revolution (1910-20) → Constitution 1917.", "US, Germany, Japan rising.", "ANC founded 1912."],
    "SAQ: Briefly explain ONE shift in global power c. 1900.",
    "Russia's 1917 Revolution overthrew the tsar, brought Lenin's Bolsheviks to power, and founded the Soviet Union (1922) — the world's first Marxist state and the model for later communist movements throughout the 20th century.",
    [{q:"Qing collapse year?",a:"1911 (Republic founded 1912)"},{q:"Mexican Revolution?",a:"1910-20"},{q:"Russian Revolution?",a:"Feb + Oct 1917"},{q:"USSR founded?",a:"1922"},{q:"Sun Yat-Sen Three Principles?",a:"Nationalism, democracy, livelihood"}],
  ),
  mk(7, "7.2", "Causes of World War I",
    "M.A.I.N.: Militarism, Alliances, Imperialism, Nationalism. Trigger: Sarajevo (June 1914).",
    ["Militarism: Anglo-German naval race.", "Alliances: Triple Alliance vs Triple Entente.", "Imperialism: colonial competition.", "Nationalism: Pan-Slavism, German.", "Trigger: Franz Ferdinand assassinated June 28, 1914.", "Mobilization plans turned crisis into war."],
    "SAQ: Briefly explain ONE long-term cause of WWI.",
    "Decades of European nationalism — particularly Pan-Slavism (Russian and Serbian sponsorship of South Slav nationalism) and Pan-Germanism — destabilized the Balkans. The Balkan Wars (1912-13) immediately preceded WWI, with Serbia growing more confrontational with Austria-Hungary.",
    [{q:"M.A.I.N.?",a:"Militarism, Alliances, Imperialism, Nationalism"},{q:"Triple Alliance?",a:"Germany, Austria-Hungary, Italy"},{q:"Triple Entente?",a:"France, Russia, UK"},{q:"Trigger?",a:"Franz Ferdinand assassination June 28, 1914"},{q:"Schlieffen Plan?",a:"German plan: defeat France quickly via Belgium"}],
  ),
  mk(7, "7.3", "Conducting World War I",
    "Industrial total war. Trench stalemate, machine guns, gas, tanks, planes. Colonial troops. ~17M dead.",
    ["Western Front: trench stalemate (Verdun, Somme).", "Eastern: Russian collapse → Brest-Litovsk 1918.", "Industrial weapons: machine gun, gas, tanks.", "Total war + women workers + propaganda.", "Colonial troops: 1M Indians + 600K+ Africans for France.", "US entry 1917; Armistice Nov 11, 1918."],
    "SAQ: Briefly explain ONE feature of WWI.",
    "WWI demanded total war mobilization: economies, women in factories, conscription of millions of soldiers (including ~1 million Indians for Britain and ~600,000 Africans for France), rationing, propaganda, and suspended civil liberties. Colonial soldiers' service shaped post-war demands for self-determination.",
    [{q:"Verdun?",a:"1916 ~700K casualties"},{q:"Somme?",a:"1916 ~1M casualties"},{q:"US entry?",a:"April 1917"},{q:"Armistice?",a:"Nov 11, 1918"},{q:"Spanish flu?",a:"1918-19, ~50M global dead"}],
  ),
  mk(7, "7.4", "The Economy in the Interwar Period",
    "Versailles reparations, German hyperinflation, Roaring Twenties, Great Depression (1929-39).",
    ["Versailles reparations $33B.", "German hyperinflation (1923).", "Dawes (1924), Young (1929) Plans.", "US Roaring Twenties.", "USSR Five-Year Plans (1928+).", "Great Depression: ~25% US unemployment.", "Smoot-Hawley Tariff (1930) deepened crisis.", "FDR New Deal."],
    "SAQ: Briefly explain ONE economic crisis of the interwar period.",
    "The 1929 Wall Street Crash triggered global depression: bank failures, ~25% US unemployment, world trade collapsed by 65%. Smoot-Hawley Tariff (1930) deepened crisis. Mass unemployment delegitimized democratic governments and helped Hitler's Nazi Party rise (chancellor January 1933).",
    [{q:"Versailles reparations?",a:"$33B on Germany"},{q:"German hyperinflation?",a:"1923"},{q:"Wall Street Crash?",a:"Oct 1929"},{q:"FDR elected?",a:"1932"},{q:"Hitler chancellor?",a:"Jan 1933"}],
  ),
  mk(7, "7.5", "Unresolved Tensions After World War I",
    "Versailles humiliated Germany. League of Nations weak. Mandate system. Self-determination not for colonized.",
    ["Versailles: War Guilt, reparations, military limits.", "Mandate system gave Ottoman/German territories to Britain, France.", "League of Nations weak (no US).", "Self-determination NOT extended to colonized peoples.", "Ho Chi Minh, Du Bois ignored at Versailles.", "May 4 Movement (China 1919)."],
    "SAQ: Briefly explain ONE unresolved tension after WWI.",
    "Wilson's Fourteen Points promised self-determination but applied only to European nationalities, not colonized Asians and Africans. Vietnamese leader Ho Chi Minh appeared at Versailles (1919) seeking Vietnamese independence and was ignored — sparking decades of anti-colonial nationalist movements.",
    [{q:"Versailles year?",a:"1919"},{q:"League of Nations weakness?",a:"US Senate rejected membership"},{q:"Mandate system?",a:"Colonial rule with trusteeship veneer"},{q:"Sykes-Picot?",a:"1916 secret partition of Arab lands"},{q:"Balfour Declaration?",a:"1917 Jewish national home in Palestine"}],
  ),
  mk(7, "7.6", "Causes of World War II",
    "Fascism (Mussolini, Hitler, Franco), Japanese militarism, Depression, failed appeasement.",
    ["Mussolini's March on Rome (1922).", "Hitler chancellor Jan 1933.", "Spanish Civil War (1936-39): Franco won.", "Japan invaded Manchuria (1931), full China invasion (1937).", "Munich Agreement (1938): appeasement.", "Molotov-Ribbentrop Pact (Aug 1939).", "Sept 1, 1939 Hitler invaded Poland."],
    "SAQ: Briefly explain ONE cause of WWII.",
    "The failure of appeasement at Munich (Sept 1938) — where Britain and France allowed Hitler's annexation of the Sudetenland — emboldened Nazi expansion. After Hitler dismembered Czechoslovakia (March 1939) and invaded Poland (Sept 1, 1939), Britain and France finally declared war.",
    [{q:"Mussolini's rise?",a:"March on Rome 1922"},{q:"Hitler chancellor?",a:"Jan 1933"},{q:"Manchuria invasion?",a:"1931"},{q:"Munich Agreement?",a:"Sept 1938 (appeasement)"},{q:"Pearl Harbor?",a:"Dec 7, 1941"}],
  ),
  mk(7, "7.7", "Conducting World War II",
    "Total war, global theaters. Stalingrad (1942-43), Midway (1942), D-Day (1944), atomic bombs (1945).",
    ["European: Battle of Britain, Stalingrad (Soviet turning point), El Alamein, D-Day, Berlin.", "Pacific: Midway (turning point), island-hopping, atomic bombs.", "Soviet Eastern Front largest theater (~27M Soviet dead).", "Holocaust killed ~6M Jews.", "Total casualties: 70-85M."],
    "SAQ: Briefly explain ONE turning point of WWII.",
    "The Battle of Stalingrad (Aug 1942-Feb 1943) destroyed the German 6th Army and ended Hitler's eastward advance. With Soviet victories at Kursk (1943), the Red Army began its march to Berlin — making the Eastern Front the war's largest and bloodiest theater.",
    [{q:"Stalingrad?",a:"1942-43 Soviet turning point"},{q:"Midway?",a:"June 1942 Pacific turning"},{q:"D-Day?",a:"June 6, 1944"},{q:"Hiroshima?",a:"Aug 6, 1945"},{q:"VJ Day?",a:"Sept 2, 1945"}],
  ),
  mk(7, "7.8", "Mass Atrocities After 1900",
    "Armenian Genocide (1915-23), Holodomor, Holocaust (~6M Jews), Nanjing, Cambodian, Bosnia, Rwanda.",
    ["Armenian Genocide (1915-23) ~1-1.5M killed.", "Holodomor Ukraine famine 1932-33.", "Stalin's Great Purge (1937-38).", "Rape of Nanjing (1937).", "Holocaust (1941-45) ~6M Jews.", "Cambodian Genocide (1975-79).", "Rwandan Genocide (1994).", "UN Genocide Convention (1948)."],
    "SAQ: Briefly explain ONE 20th-century genocide.",
    "The Armenian Genocide (1915-23) saw the Ottoman Young Turk government order deportation and massacre of Armenian Christians. About 1-1.5 million Armenians died via massacres, death marches, and starvation — a template recognized by later scholars as the first modern genocide.",
    [{q:"Armenian Genocide?",a:"1915-23 ~1-1.5M killed"},{q:"Holocaust death toll?",a:"~6M Jews + millions of others"},{q:"Holodomor?",a:"Ukrainian famine 1932-33"},{q:"Cambodian genocide?",a:"1975-79 Khmer Rouge"},{q:"Rwandan genocide?",a:"1994 ~800K"}],
  ),
  mk(7, "7.9", "Causation in Global Conflict",
    "Industrial military + nationalism + ideologies + imperial competition. WWI vs WWII causes.",
    ["Common: industrial weapons, nationalism, ideologies, economic instability, imperial rivalry.", "WWI: alliance system + mobilization plans + Balkan crisis.", "WWII: revisionist powers + Depression + appeasement.", "Effects: ~70-100M dead, decolonization, UN, bipolar Cold War."],
    "LEQ: Compare causes of WWI and WWII.",
    "Both arose from industrial military capacity, nationalism, alliances, and imperial competition. WWI was triggered by Balkan crisis, alliance commitments, and rigid mobilization plans — a miscalculation. WWII was driven by ideologically revisionist powers (Nazi Germany, fascist Italy, militarist Japan) seeking to overturn the post-WWI order, with appeasement enabling rather than restraining Hitler.",
    [{q:"WWI cause?",a:"Alliance + mobilization + Balkan trigger"},{q:"WWII cause?",a:"Revisionist powers + Depression + appeasement failure"},{q:"WWI dead?",a:"~17M"},{q:"WWII dead?",a:"~70-85M"},{q:"Both wars accelerated?",a:"Decolonization"}],
  ),
  mk(8, "8.1", "Setting the Stage for the Cold War and Decolonization",
    "WWII left US and USSR superpowers. UN, Bretton Woods. European empires economically devastated.",
    ["US, USSR superpowers.", "Yalta (Feb 1945), Potsdam (July-Aug 1945).", "Iron Curtain (Churchill 1946).", "UN founded 1945.", "Bretton Woods: IMF, World Bank, GATT.", "Decolonization pressures: WWII destroyed European prestige."],
    "SAQ: Briefly explain ONE post-WWII institution.",
    "The Bretton Woods system (1944) established the IMF for currency stabilization, the World Bank for development lending, and the dollar (gold-backed) as global reserve currency. GATT (1947) liberalized trade. These institutions shaped the post-war global economy for decades.",
    [{q:"Iron Curtain?",a:"Churchill 1946 speech"},{q:"UN founded?",a:"1945"},{q:"Bretton Woods?",a:"1944 IMF + World Bank"},{q:"GATT?",a:"1947 trade"},{q:"Yalta?",a:"Feb 1945"}],
  ),
  mk(8, "8.2", "The Cold War",
    "1945-91 bipolar competition. Truman Doctrine, Marshall Plan, NATO, Korean War, Cuban Missile Crisis, Vietnam.",
    ["Truman Doctrine (1947), Marshall Plan (1948).", "Berlin Airlift (1948-49), NATO (1949).", "Korean War (1950-53).", "Cuban Missile Crisis (Oct 1962).", "Vietnam War (1955-75).", "Détente: Nixon-China 1972, SALT.", "Reagan + Gorbachev → end."],
    "SAQ: Briefly explain ONE Cold War crisis.",
    "The Cuban Missile Crisis (Oct 1962) was the closest the world came to nuclear war when USSR placed nuclear missiles in Cuba (response to US missiles in Turkey + Bay of Pigs). After 13 days of standoff, USSR withdrew Cuban missiles; US secretly removed Turkish missiles. Established hotline + partial test ban treaty (1963).",
    [{q:"Truman Doctrine?",a:"1947 aid to free peoples"},{q:"Marshall Plan?",a:"1948-52 ~$13B to W Europe"},{q:"NATO?",a:"1949"},{q:"Cuban Missile Crisis?",a:"Oct 1962"},{q:"Vietnam War years?",a:"1955-75"}],
  ),
  mk(8, "8.3", "Effects of the Cold War",
    "Proxy wars (Korea, Vietnam, Angola), NAM, arms race, MAD, military-industrial complex, covert interventions.",
    ["Proxy wars: Korea, Vietnam, Angola, Nicaragua.", "Non-Aligned Movement (Bandung 1955, Belgrade 1961).", "Arms race + MAD.", "Space race: Apollo 11 (1969).", "Military-industrial complex.", "Covert interventions (Iran 1953, Chile 1973)."],
    "SAQ: Briefly explain ONE Cold War effect on the Global South.",
    "The Cold War turned newly independent states into proxy battlegrounds. In Angola after 1975, Soviet/Cuban-backed MPLA fought US/South African-backed UNITA — extending Angola's civil war until 2002 with hundreds of thousands of deaths.",
    [{q:"Proxy war examples?",a:"Korea, Vietnam, Angola, Nicaragua"},{q:"Non-Aligned Movement?",a:"Bandung 1955 + Belgrade 1961"},{q:"MAD?",a:"Mutual Assured Destruction"},{q:"Apollo 11?",a:"July 1969 Moon landing"},{q:"Pinochet?",a:"Chile 1973 US-backed coup"}],
  ),
  mk(8, "8.4", "Spread of Communism After 1900",
    "Soviet (1917), Eastern Europe (1945+), China (Mao 1949), Vietnam, Cuba (Castro 1959), African/Latin variants.",
    ["Lenin/Stalin Soviet model.", "Eastern Europe satellites post-1945.", "Tito's Yugoslavia broke from Stalin (1948).", "Mao's PRC (1949). Great Leap Forward famine (~30-45M dead).", "Cultural Revolution (1966-76).", "Deng Xiaoping reforms (1978+).", "Vietnam, Cuba, Angola, Mozambique."],
    "SAQ: Briefly explain ONE spread of communism.",
    "Mao Zedong's PRC (1949) adapted Marxism to peasant China. The disastrous Great Leap Forward (1958-62) killed ~30-45 million in famine; the Cultural Revolution (1966-76) persecuted intellectuals. After Mao's death (1976), Deng Xiaoping reformed economically while keeping CCP rule.",
    [{q:"PRC founded?",a:"Oct 1, 1949"},{q:"Great Leap Forward?",a:"1958-62 famine ~30-45M dead"},{q:"Cultural Revolution?",a:"1966-76"},{q:"Deng reforms?",a:"1978+ market opening"},{q:"Castro Cuba revolution?",a:"1959"}],
  ),
  mk(8, "8.5", "Decolonization After 1900",
    "Most colonies independent 1945-75. India (1947), Ghana (1957), Algerian War (1962), Year of Africa (1960), Vietnam (1976).",
    ["India (1947): Gandhi satyagraha; Partition displaced ~15M.", "Ghana (1957): Nkrumah, first sub-Saharan independent.", "'Year of Africa' (1960): 17 nations.", "Algerian War (1954-62) bloody.", "Indonesia (1949), Vietnam (1976).", "Israel (1948), Suez (1956)."],
    "SAQ: Briefly explain ONE decolonization movement.",
    "Gandhi's Indian National Congress used satyagraha (nonviolent resistance) — Salt March (1930), Quit India (1942) — combined with negotiation. British transferred power Aug 1947, but Partition divided India and Pakistan, displacing ~15 million and killing ~1-2 million in communal violence.",
    [{q:"Indian independence?",a:"1947 (Partition)"},{q:"Ghana independence?",a:"1957 (Nkrumah)"},{q:"Year of Africa?",a:"1960"},{q:"Algerian War?",a:"1954-62"},{q:"Mandela elected?",a:"1994"}],
  ),
  mk(8, "8.6", "Newly Independent States",
    "Inherited colonial borders, weak institutions, economic dependency, Cold War pressure shaped diverse trajectories.",
    ["Common: weak institutions + ethnic tensions + Cold War interference.", "India: democracy.", "Many African states: military coups, one-party rule.", "Indonesia: Suharto coup (1965) ~500K killed.", "Iran 1979 Revolution.", "Asian Tigers (HK, Singapore, S. Korea, Taiwan).", "Structural adjustment 1980s+."],
    "SAQ: Briefly explain ONE challenge facing newly independent states.",
    "Inherited colonial borders ignored ethnic, religious, and linguistic boundaries — often grouping rivals or splitting unities. Combined with weak colonial-trained institutions and Cold War pressure to align with superpowers, many post-colonial states experienced military coups, civil wars, and authoritarian regimes.",
    [{q:"Asian Tigers?",a:"HK, Singapore, S. Korea, Taiwan"},{q:"Iran 1979 Revolution?",a:"Islamic Republic under Khomeini"},{q:"Suharto coup?",a:"1965 Indonesia"},{q:"Iran-Iraq War?",a:"1980-88"},{q:"Structural adjustment?",a:"1980s+ IMF imposed austerity"}],
  ),
  mk(8, "8.7", "Global Resistance to Established Power Structures After 1900",
    "Civil rights, anti-apartheid, second-wave feminism, anti-Vietnam, environmental, indigenous, LGBTQ+, religious revival.",
    ["Civil Rights Movement (US 1950s-60s): MLK, CRA 1964, VRA 1965.", "Anti-apartheid → Mandela (1994).", "Second-wave feminism: Friedan, Roe (1973), Beijing 1995.", "1968 global protests.", "Environmental: Earth Day (1970), Paris Agreement (2015).", "LGBTQ+: Stonewall 1969, marriage equality."],
    "SAQ: Briefly explain ONE global resistance movement.",
    "The international anti-apartheid movement combined sustained ANC organizing in South Africa (Mandela, Tutu) with global boycotts, divestment, and sanctions throughout the 1980s. By 1994, internal pressure + international isolation forced majority rule and Mandela's election.",
    [{q:"Civil Rights Act?",a:"US 1964"},{q:"Apartheid ended?",a:"1994 (Mandela elected)"},{q:"Roe v Wade?",a:"1973"},{q:"1968 protests?",a:"Global wave"},{q:"Stonewall?",a:"1969 NYC"}],
  ),
  mk(8, "8.8", "End of the Cold War",
    "Soviet stagnation + Reagan pressure + Gorbachev's glasnost/perestroika → 1989 revolutions → USSR dissolved 1991.",
    ["Gorbachev (1985+): glasnost, perestroika, renounced Brezhnev Doctrine.", "1989: Berlin Wall fell Nov 9; Eastern European revolutions.", "1991 hardliner coup failed; USSR dissolved Dec 25, 1991.", "Yeltsin presided over chaotic 'shock therapy.'", "NATO/EU expanded eastward."],
    "SAQ: Briefly explain ONE factor in Cold War's end.",
    "Soviet economic stagnation and the Afghan War drain (1979-89), combined with Reagan-era arms buildup forcing matching expenditure, made the USSR unsustainable. Gorbachev's 1985+ reforms (glasnost, perestroika) attempted reform but unleashed forces — nationalist movements, satellite revolutions — that dissolved the empire.",
    [{q:"Gorbachev?",a:"Soviet reformer 1985-91"},{q:"Berlin Wall fell?",a:"Nov 9, 1989"},{q:"USSR dissolved?",a:"Dec 25, 1991"},{q:"Afghan War?",a:"1979-89 Soviet defeat"},{q:"Successor states?",a:"15 (including Russia)"}],
  ),
  mk(8, "8.9", "Causation in the Age of the Cold War and Decolonization",
    "Cold War + decolonization intertwined for ~45 years. Reciprocal causation.",
    ["Both superpowers supported decolonization rhetorically.", "But intervened against left-leaning states (Iran 1953, Chile 1973).", "NAM tried to chart third path.", "Newly independent states became proxy battlegrounds.", "End of Cold War (1991) opened wave of democratization."],
    "LEQ: Evaluate Cold War's impact on decolonization.",
    "Profound: superpowers competed for new states' allegiance, providing arms and aid (Vietnam, Angola); covert interventions toppled left-leaning governments (Iran 1953, Chile 1973). Bandung NAM (1955) tried to chart third path. Cold War militarized post-colonial politics; ending the Cold War (1991) opened space for democratization in E Europe, Latin America, S Africa.",
    [{q:"Bandung year?",a:"1955"},{q:"NAM?",a:"Non-Aligned Movement"},{q:"Iran 1953?",a:"CIA coup against Mossadegh"},{q:"Chile 1973?",a:"Pinochet coup vs Allende"},{q:"S Africa apartheid ended?",a:"1994"}],
  ),
  mk(9, "9.1", "Advances in Technology and Exchange After 1900",
    "Containerization, jet aviation, satellites, computing, internet, smartphones radically accelerated globalization.",
    ["Container ships (1956) cut shipping costs ~95%.", "Jet aviation (1958+).", "Satellites: Sputnik (1957), GPS (1995).", "Internet: ARPANET (1969), web (1989), mass adoption 1990s.", "Smartphones (iPhone 2007).", "Green Revolution (1950s-70s) saved ~1B from famine."],
    "SAQ: Briefly explain ONE late 20th-c. technological change.",
    "Container shipping (introduced 1956) standardized cargo into 20-40 ft steel boxes, cutting maritime shipping costs by ~95% and enabling globally distributed supply chains. Combined with jet aviation, it made today's global economy possible.",
    [{q:"Container shipping?",a:"1956 — cut costs ~95%"},{q:"World Wide Web?",a:"1989 (Berners-Lee)"},{q:"iPhone year?",a:"2007"},{q:"Green Revolution period?",a:"1950s-70s"},{q:"Smartphones today?",a:"~6.5B users"}],
  ),
  mk(9, "9.2", "Technological Advances and Limitations After 1900: Disease",
    "Vaccines + antibiotics doubled life expectancy. Pandemics: 1918 flu, HIV/AIDS, COVID-19. Antibiotic resistance.",
    ["Smallpox eradicated 1980.", "Antibiotics (penicillin 1944).", "Life expectancy 30 → 73 globally.", "1918 flu killed ~50-100M.", "HIV/AIDS ~40M dead.", "COVID-19 (2019+).", "Antibiotic resistance growing concern."],
    "SAQ: Briefly explain ONE 20th-c. medical advance.",
    "Smallpox was eradicated by WHO in 1980 through global vaccination campaign — the only human disease ever eradicated. The success demonstrated coordinated global public health and inspired similar attempts (polio nearly there).",
    [{q:"Smallpox eradicated?",a:"WHO 1980"},{q:"Penicillin mass-produced?",a:"WWII"},{q:"1918 flu deaths?",a:"~50-100M"},{q:"COVID-19 confirmed deaths?",a:"~7M (excess ~15-20M+)"},{q:"Life expectancy 1900 vs 2023?",a:"~30 → ~73"}],
  ),
  mk(9, "9.3", "Technological Advances: Debates About the Environment After 1900",
    "Climate change, ozone depletion (Montreal 1987 successful), deforestation, biodiversity loss.",
    ["~1.2°C warming.", "IPCC, UNFCCC (1992), Kyoto (1997), Paris (2015).", "Montreal Protocol (1987) phased out CFCs successfully.", "Sixth mass extinction underway.", "Renewable energy costs collapsed post-2010."],
    "SAQ: Briefly explain ONE successful environmental treaty.",
    "The Montreal Protocol (1987) phased out CFCs (which damaged ozone). Nearly universal ratification + alternatives + strong science = ozone layer healing (expected fully by 2060-70). Most successful environmental treaty; model for climate cooperation.",
    [{q:"Montreal Protocol?",a:"1987 ozone (CFCs)"},{q:"Paris Agreement?",a:"2015 climate"},{q:"Climate warming?",a:"~1.2°C since pre-industrial"},{q:"IPCC?",a:"Intergovernmental Panel on Climate Change (1988)"},{q:"Renewable cost trend?",a:"Solar PV ~90% cheaper 2010-20"}],
  ),
  mk(9, "9.4", "Economics in the Global Age",
    "Bretton Woods → neoliberalism (Reagan/Thatcher 1980s) → 2008 crisis → populist backlash. Asian + Chinese rise.",
    ["Bretton Woods (1944): IMF, World Bank, GATT, dollar.", "Postwar prosperity 1945-73.", "Oil shocks (1973, 1979).", "Neoliberalism: Thatcher, Reagan, Washington Consensus.", "Asian Tigers + China (Deng 1978+) industrialized.", "WTO (1995); 2008 financial crisis; populist backlash."],
    "SAQ: Briefly explain ONE major economic transformation post-1980.",
    "Deng Xiaoping's economic reforms (1978+) opened China to foreign investment and markets while keeping CCP rule. Growth averaged ~10%/year for 30 years, lifting ~800 million out of poverty and making China the world's #2 economy by 2010 — the largest poverty reduction in history.",
    [{q:"Bretton Woods?",a:"1944"},{q:"OPEC oil shock?",a:"1973"},{q:"Thatcher elected?",a:"1979"},{q:"Reagan elected?",a:"1980"},{q:"China since Deng?",a:"~800M out of poverty"}],
  ),
  mk(9, "9.5", "Calls for Reform and Responses After 1900",
    "Civil rights, second-wave feminism, anti-globalization, Arab Spring, climate movement, populist backlash.",
    ["BLM (2013+, peak 2020).", "#MeToo (2017+).", "Marriage equality (Netherlands 2001, US 2015).", "Occupy Wall Street (2011).", "Arab Spring (2010-12).", "Hong Kong protests (2014, 2019).", "Climate: Thunberg, Extinction Rebellion."],
    "SAQ: Briefly explain ONE 21st-c. movement.",
    "Black Lives Matter (founded 2013 after Trayvon Martin's killing) became a global protest movement after George Floyd's 2020 murder, with worldwide protests against police violence and racial injustice. It reshaped American policy debates and global conversations on race.",
    [{q:"BLM founded?",a:"2013"},{q:"Arab Spring?",a:"2010-12"},{q:"Occupy Wall Street?",a:"2011"},{q:"Hong Kong protests?",a:"2014, 2019-20"},{q:"Greta Thunberg?",a:"Climate activist (FFF 2018+)"}],
  ),
  mk(9, "9.6", "Globalized Culture After 1900",
    "Mass media, English lingua franca, sports, music, food. Western exports + counter-flows (K-pop, Bollywood, anime).",
    ["Hollywood, Bollywood, K-pop globally.", "English lingua franca (~1.5B speakers).", "International sports (FIFA, Olympics).", "Religious globalization: Pentecostalism, Islamic ummah.", "Hybrid identities and diaspora cultures.", "Resistance to homogenization (language laws)."],
    "SAQ: Briefly explain ONE feature of cultural globalization.",
    "K-pop (Korean popular music) became globally dominant in the 2010s-20s with groups like BTS and Blackpink, demonstrating that cultural globalization isn't only Western-export but flows in multiple directions, including Bollywood films and Japanese anime reaching global audiences.",
    [{q:"Lingua franca?",a:"English (~1.5B)"},{q:"K-pop example?",a:"BTS, Blackpink"},{q:"Bollywood?",a:"Indian film industry"},{q:"Pentecostalism?",a:"Fastest-growing Christianity (~600M)"},{q:"Hybrid identities?",a:"Diaspora bicultural"}],
  ),
  mk(9, "9.7", "Resistance to Globalization After 1900",
    "Anti-globalization left, religious revival (Iran 1979, ISIS), populist nationalism (Trump, Brexit, Modi), Putin Russia.",
    ["Seattle WTO protests (1999).", "Iranian Revolution (1979).", "Al-Qaeda + 9/11 (2001).", "ISIS (2014-19).", "Populist nationalism: Trump, Brexit, Orbán, Modi, Bolsonaro.", "Putin: Crimea (2014), Ukraine invasion (Feb 2022)."],
    "SAQ: Briefly explain ONE form of resistance to globalization.",
    "The Iranian Revolution (1979) overthrew the Western-aligned Shah and established a Shia Islamic republic under Khomeini, explicitly rejecting Western liberal modernity. It demonstrated that religiously-grounded anti-Western movements could capture state power and reshape regional politics.",
    [{q:"Iranian Revolution?",a:"1979"},{q:"9/11?",a:"2001"},{q:"ISIS territorial defeat?",a:"2019"},{q:"Brexit referendum?",a:"June 2016"},{q:"Putin Crimea?",a:"2014"}],
  ),
  mk(9, "9.8", "Institutions Developing in a Globalized World",
    "International (UN, IMF, WTO, EU, NATO) + non-state actors (multinationals, NGOs, terrorist networks).",
    ["UN, IMF, World Bank, WTO.", "EU (1993), Eurozone (1999).", "NATO expanded eastward post-Cold War.", "ASEAN, AU, BRICS.", "ICC (2002).", "Multinationals (Apple, Aramco).", "NGOs (MSF, Amnesty, Gates Foundation)."],
    "SAQ: Briefly explain ONE non-state actor in globalization.",
    "Multinational corporations like Apple, Walmart, and Saudi Aramco have revenues exceeding many states' GDP. They organize global supply chains across dozens of countries (an iPhone draws components from China, Korea, Japan, Taiwan, Germany), making them key players in the global economy.",
    [{q:"WTO?",a:"1995"},{q:"EU founded?",a:"1993 (from EEC)"},{q:"Eurozone?",a:"1999"},{q:"ICC?",a:"2002 International Criminal Court"},{q:"NGO example?",a:"MSF, Amnesty, Gates Foundation"}],
  ),
  mk(9, "9.9", "Continuity and Change in a Globalized World",
    "Massive 20th-c. change. Continuities: inequality, patriarchy, war, nation-state. 21st-c. challenges: climate, AI, polarization.",
    ["Pop ~1.6B → 8B; life expect 30 → 73; urbanization 14 → 57%.", "Extreme poverty 75% → 10%.", "Decolonization, info revolution, women's status.", "Continuities: inequality, patriarchy, religion, war.", "21st-c. challenges: climate, pandemics, AI, great-power competition."],
    "LEQ: Evaluate globalization's impact on the world economy 1900-present.",
    "Profoundly transformed: integrated supply chains, China and Asian Tiger industrialization, instant capital flows, multinational corporations, WTO trade rules. Lifted billions out of poverty. But concentrated gains at top; 2008 crisis and post-2016 populist backlash showed limits. Most production still happens within nations; nation-state remains dominant. Massive change without abolishing older patterns.",
    [{q:"Population growth 1900 to 2023?",a:"~1.6B → 8B"},{q:"Life expectancy 1900 to today?",a:"~30 → 73"},{q:"Extreme poverty trend?",a:"75% → 10%"},{q:"Globalization peak?",a:"~1991-2008"},{q:"21st-c. challenges?",a:"Climate, pandemic, AI, great-power competition, inequality"}],
  ),
];
