/**
 * Official AP Course and Exam Description (CED) unit + topic breakdowns
 * for the history courses. Topic codes and titles track the College Board
 * framework; for the "Contextualizing" and topic titles common to all AP
 * history courses, we match the 2024 CED phrasing.
 */

export type ApTopicLite = { id: string; title: string };
export type ApUnitLite = { number: number; title: string; topics: ApTopicLite[] };

export const HISTORY_UNITS: Record<string, ApUnitLite[]> = {
  // =========================================================================
  // AP UNITED STATES HISTORY (APUSH, 9 Periods)
  // =========================================================================
  "ap-us-history": [
    {
      number: 1,
      title: "Period 1: 1491-1607",
      topics: [
        { id: "1.1", title: "Contextualizing Period 1" },
        { id: "1.2", title: "Native American Societies Before European Contact" },
        { id: "1.3", title: "European Exploration in the Americas" },
        { id: "1.4", title: "Columbian Exchange, Spanish Exploration, and Conquest" },
        { id: "1.5", title: "Labor, Slavery, and Caste in the Spanish Colonial System" },
        { id: "1.6", title: "Cultural Interactions Between Europeans, Native Americans, and Africans" },
        { id: "1.7", title: "Causation in Period 1" },
      ],
    },
    {
      number: 2,
      title: "Period 2: 1607-1754",
      topics: [
        { id: "2.1", title: "Contextualizing Period 2" },
        { id: "2.2", title: "European Colonization" },
        { id: "2.3", title: "The Regions of British Colonies" },
        { id: "2.4", title: "Transatlantic Trade" },
        { id: "2.5", title: "Interactions Between American Indians and Europeans" },
        { id: "2.6", title: "Slavery in the British Colonies" },
        { id: "2.7", title: "Colonial Society and Culture" },
        { id: "2.8", title: "Comparison in Period 2" },
      ],
    },
    {
      number: 3,
      title: "Period 3: 1754-1800",
      topics: [
        { id: "3.1", title: "Contextualizing Period 3" },
        { id: "3.2", title: "The Seven Years' War (The French and Indian War)" },
        { id: "3.3", title: "Taxation Without Representation" },
        { id: "3.4", title: "Philosophical Foundations of the American Revolution" },
        { id: "3.5", title: "The American Revolution" },
        { id: "3.6", title: "The Influence of Revolutionary Ideals" },
        { id: "3.7", title: "The Articles of Confederation" },
        { id: "3.8", title: "The Constitutional Convention and Debates over Ratification" },
        { id: "3.9", title: "The Constitution" },
        { id: "3.10", title: "Shaping a New Republic" },
        { id: "3.11", title: "Developing an American Identity" },
        { id: "3.12", title: "Movement in the Early Republic" },
        { id: "3.13", title: "Continuity and Change in Period 3" },
      ],
    },
    {
      number: 4,
      title: "Period 4: 1800-1848",
      topics: [
        { id: "4.1", title: "Contextualizing Period 4" },
        { id: "4.2", title: "The Rise of Political Parties and the Era of Jefferson" },
        { id: "4.3", title: "Politics and Regional Interests" },
        { id: "4.4", title: "America on the World Stage" },
        { id: "4.5", title: "Market Revolution: Industrialization" },
        { id: "4.6", title: "Market Revolution: Society and Culture" },
        { id: "4.7", title: "Expanding Democracy" },
        { id: "4.8", title: "Jackson and Federal Power" },
        { id: "4.9", title: "The Development of an American Culture" },
        { id: "4.10", title: "The Second Great Awakening" },
        { id: "4.11", title: "An Age of Reform" },
        { id: "4.12", title: "African Americans in the Early Republic" },
        { id: "4.13", title: "The Society of the South in the Early Republic" },
        { id: "4.14", title: "Causation in Period 4" },
      ],
    },
    {
      number: 5,
      title: "Period 5: 1844-1877",
      topics: [
        { id: "5.1", title: "Contextualizing Period 5" },
        { id: "5.2", title: "Manifest Destiny" },
        { id: "5.3", title: "The Mexican-American War" },
        { id: "5.4", title: "The Compromise of 1850" },
        { id: "5.5", title: "Sectional Conflict: Regional Differences" },
        { id: "5.6", title: "Failure of Compromise" },
        { id: "5.7", title: "Election of 1860 and Secession" },
        { id: "5.8", title: "Military Conflict in the Civil War" },
        { id: "5.9", title: "Government Policies During the Civil War" },
        { id: "5.10", title: "Reconstruction" },
        { id: "5.11", title: "Failure of Reconstruction" },
        { id: "5.12", title: "Comparison in Period 5" },
      ],
    },
    {
      number: 6,
      title: "Period 6: 1865-1898",
      topics: [
        { id: "6.1", title: "Contextualizing Period 6" },
        { id: "6.2", title: "Westward Expansion: Economic Development" },
        { id: "6.3", title: "Westward Expansion: Social and Cultural Development" },
        { id: "6.4", title: "The 'New South'" },
        { id: "6.5", title: "Technological Innovation" },
        { id: "6.6", title: "The Rise of Industrial Capitalism" },
        { id: "6.7", title: "Labor in the Gilded Age" },
        { id: "6.8", title: "Immigration and Migration in the Gilded Age" },
        { id: "6.9", title: "Responses to Immigration in the Gilded Age" },
        { id: "6.10", title: "Development of the Middle Class" },
        { id: "6.11", title: "Reform in the Gilded Age" },
        { id: "6.12", title: "Controversies over the Role of Government in the Gilded Age" },
        { id: "6.13", title: "Politics in the Gilded Age" },
        { id: "6.14", title: "Continuity and Change in Period 6" },
      ],
    },
    {
      number: 7,
      title: "Period 7: 1890-1945",
      topics: [
        { id: "7.1", title: "Contextualizing Period 7" },
        { id: "7.2", title: "Imperialism: Debates" },
        { id: "7.3", title: "The Spanish-American War" },
        { id: "7.4", title: "The Progressives" },
        { id: "7.5", title: "World War I: Military and Diplomacy" },
        { id: "7.6", title: "World War I: Home Front" },
        { id: "7.7", title: "1920s: Innovations in Communication and Technology" },
        { id: "7.8", title: "1920s: Cultural and Political Controversies" },
        { id: "7.9", title: "The Great Depression" },
        { id: "7.10", title: "The New Deal" },
        { id: "7.11", title: "Interwar Foreign Policy" },
        { id: "7.12", title: "World War II: Mobilization" },
        { id: "7.13", title: "World War II: Military" },
        { id: "7.14", title: "Postwar Diplomacy" },
        { id: "7.15", title: "Comparison in Period 7" },
      ],
    },
    {
      number: 8,
      title: "Period 8: 1945-1980",
      topics: [
        { id: "8.1", title: "Contextualizing Period 8" },
        { id: "8.2", title: "The Cold War from 1945 to 1980" },
        { id: "8.3", title: "The Red Scare" },
        { id: "8.4", title: "Economy After 1945" },
        { id: "8.5", title: "Culture After 1945" },
        { id: "8.6", title: "Early Steps in the Civil Rights Movement (1940s and 1950s)" },
        { id: "8.7", title: "America as a World Power" },
        { id: "8.8", title: "The Vietnam War" },
        { id: "8.9", title: "The Great Society" },
        { id: "8.10", title: "The African American Civil Rights Movement (1960s)" },
        { id: "8.11", title: "The Civil Rights Movement Expands" },
        { id: "8.12", title: "Youth Culture of the 1960s" },
        { id: "8.13", title: "The Environment and Natural Resources from 1968 to 1980" },
        { id: "8.14", title: "Society in Transition" },
        { id: "8.15", title: "Continuity and Change in Period 8" },
      ],
    },
    {
      number: 9,
      title: "Period 9: 1980-Present",
      topics: [
        { id: "9.1", title: "Contextualizing Period 9" },
        { id: "9.2", title: "Reagan and Conservatism" },
        { id: "9.3", title: "The End of the Cold War" },
        { id: "9.4", title: "A Changing Economy" },
        { id: "9.5", title: "Migration and Immigration in the 1990s and 2000s" },
        { id: "9.6", title: "Challenges of the 21st Century" },
        { id: "9.7", title: "Causation in Period 9" },
      ],
    },
  ],

  // =========================================================================
  // AP WORLD HISTORY: MODERN (9 units, c. 1200-present)
  // =========================================================================
  "ap-world-history": [
    {
      number: 1,
      title: "The Global Tapestry (c. 1200-1450)",
      topics: [
        { id: "1.1", title: "Developments in East Asia from c. 1200 to c. 1450" },
        { id: "1.2", title: "Developments in Dar al-Islam from c. 1200 to c. 1450" },
        { id: "1.3", title: "Developments in South and Southeast Asia from c. 1200 to c. 1450" },
        { id: "1.4", title: "State Building in the Americas" },
        { id: "1.5", title: "State Building in Africa" },
        { id: "1.6", title: "Developments in Europe from c. 1200 to c. 1450" },
        { id: "1.7", title: "Comparison in the Period from c. 1200 to c. 1450" },
      ],
    },
    {
      number: 2,
      title: "Networks of Exchange (c. 1200-1450)",
      topics: [
        { id: "2.1", title: "The Silk Roads" },
        { id: "2.2", title: "The Mongol Empire and the Modern World" },
        { id: "2.3", title: "Exchange in the Indian Ocean" },
        { id: "2.4", title: "Trans-Saharan Trade Routes" },
        { id: "2.5", title: "Cultural Consequences of Connectivity" },
        { id: "2.6", title: "Environmental Consequences of Connectivity" },
        { id: "2.7", title: "Comparison of Economic Exchange" },
      ],
    },
    {
      number: 3,
      title: "Land-Based Empires (c. 1450-1750)",
      topics: [
        { id: "3.1", title: "Empires Expand" },
        { id: "3.2", title: "Empires: Administration" },
        { id: "3.3", title: "Empires: Belief Systems" },
        { id: "3.4", title: "Comparison in Land-Based Empires" },
      ],
    },
    {
      number: 4,
      title: "Transoceanic Interconnections (c. 1450-1750)",
      topics: [
        { id: "4.1", title: "Technological Innovations from 1450 to 1750" },
        { id: "4.2", title: "Exploration: Causes and Events from 1450 to 1750" },
        { id: "4.3", title: "Columbian Exchange" },
        { id: "4.4", title: "Maritime Empires Established" },
        { id: "4.5", title: "Maritime Empires Maintained and Developed" },
        { id: "4.6", title: "Internal and External Challenges to State Power" },
        { id: "4.7", title: "Changing Social Hierarchies from 1450 to 1750" },
        { id: "4.8", title: "Continuity and Change from 1450 to 1750" },
      ],
    },
    {
      number: 5,
      title: "Revolutions (c. 1750-1900)",
      topics: [
        { id: "5.1", title: "The Enlightenment" },
        { id: "5.2", title: "Nationalism and Revolutions in the Period from 1750 to 1900" },
        { id: "5.3", title: "Industrial Revolution Begins" },
        { id: "5.4", title: "Industrialization Spreads in the Period from 1750 to 1900" },
        { id: "5.5", title: "Technology of the Industrial Age" },
        { id: "5.6", title: "Industrialization: Government's Role from 1750 to 1900" },
        { id: "5.7", title: "Economic Developments and Innovations in the Industrial Age" },
        { id: "5.8", title: "Reactions to the Industrial Economy from 1750 to 1900" },
        { id: "5.9", title: "Society and the Industrial Age" },
        { id: "5.10", title: "Continuity and Change in the Industrial Age" },
      ],
    },
    {
      number: 6,
      title: "Consequences of Industrialization (c. 1750-1900)",
      topics: [
        { id: "6.1", title: "Rationales for Imperialism from 1750 to 1900" },
        { id: "6.2", title: "State Expansion from 1750 to 1900" },
        { id: "6.3", title: "Indigenous Responses to State Expansion from 1750 to 1900" },
        { id: "6.4", title: "Global Economic Development from 1750 to 1900" },
        { id: "6.5", title: "Economic Imperialism from 1750 to 1900" },
        { id: "6.6", title: "Causes of Migration in an Interconnected World" },
        { id: "6.7", title: "Effects of Migration" },
        { id: "6.8", title: "Causation in the Imperial Age" },
      ],
    },
    {
      number: 7,
      title: "Global Conflict (c. 1900-present)",
      topics: [
        { id: "7.1", title: "Shifting Power After 1900" },
        { id: "7.2", title: "Causes of World War I" },
        { id: "7.3", title: "Conducting World War I" },
        { id: "7.4", title: "The Economy in the Interwar Period" },
        { id: "7.5", title: "Unresolved Tensions After World War I" },
        { id: "7.6", title: "Causes of World War II" },
        { id: "7.7", title: "Conducting World War II" },
        { id: "7.8", title: "Mass Atrocities After 1900" },
        { id: "7.9", title: "Causation in Global Conflict" },
      ],
    },
    {
      number: 8,
      title: "Cold War and Decolonization (c. 1900-present)",
      topics: [
        { id: "8.1", title: "Setting the Stage for the Cold War and Decolonization" },
        { id: "8.2", title: "The Cold War" },
        { id: "8.3", title: "Effects of the Cold War" },
        { id: "8.4", title: "Spread of Communism After 1900" },
        { id: "8.5", title: "Decolonization After 1900" },
        { id: "8.6", title: "Newly Independent States" },
        { id: "8.7", title: "Global Resistance to Established Power Structures After 1900" },
        { id: "8.8", title: "End of the Cold War" },
        { id: "8.9", title: "Causation in the Age of the Cold War and Decolonization" },
      ],
    },
    {
      number: 9,
      title: "Globalization (c. 1900-present)",
      topics: [
        { id: "9.1", title: "Advances in Technology and Exchange After 1900" },
        { id: "9.2", title: "Technological Advances and Limitations After 1900: Disease" },
        { id: "9.3", title: "Technological Advances: Debates About the Environment After 1900" },
        { id: "9.4", title: "Economics in the Global Age" },
        { id: "9.5", title: "Calls for Reform and Responses After 1900" },
        { id: "9.6", title: "Globalized Culture After 1900" },
        { id: "9.7", title: "Resistance to Globalization After 1900" },
        { id: "9.8", title: "Institutions Developing in a Globalized World" },
        { id: "9.9", title: "Continuity and Change in a Globalized World" },
      ],
    },
  ],

  // =========================================================================
  // AP EUROPEAN HISTORY (9 units, c. 1450-present)
  // =========================================================================
  "ap-euro-history": [
    {
      number: 1,
      title: "Renaissance and Exploration (c. 1450-1648)",
      topics: [
        { id: "1.1", title: "Contextualizing Renaissance and Discovery" },
        { id: "1.2", title: "Italian Renaissance" },
        { id: "1.3", title: "Northern Renaissance" },
        { id: "1.4", title: "Printing" },
        { id: "1.5", title: "New Monarchies" },
        { id: "1.6", title: "Technology and Exploration" },
        { id: "1.7", title: "Columbian Exchange, Commercial Revolution, and Mercantilism" },
        { id: "1.8", title: "Causation in the Renaissance and Age of Discovery" },
      ],
    },
    {
      number: 2,
      title: "Age of Reformation (c. 1450-1648)",
      topics: [
        { id: "2.1", title: "Contextualizing 16th- and 17th-Century Challenges and Developments" },
        { id: "2.2", title: "Luther and the Protestant Reformation" },
        { id: "2.3", title: "Protestant Reformation Beyond Germany" },
        { id: "2.4", title: "Wars of Religion" },
        { id: "2.5", title: "The Catholic Reformation" },
        { id: "2.6", title: "16th-Century Society and Politics" },
        { id: "2.7", title: "Art of the 16th Century" },
        { id: "2.8", title: "Causation in the Age of Reformation and the Wars of Religion" },
      ],
    },
    {
      number: 3,
      title: "Absolutism and Constitutionalism (c. 1648-1815)",
      topics: [
        { id: "3.1", title: "Contextualizing State Building" },
        { id: "3.2", title: "The English Civil War and the Glorious Revolution" },
        { id: "3.3", title: "Continuities and Changes to Economic Practice and Development" },
        { id: "3.4", title: "Economic Development and Mercantilism" },
        { id: "3.5", title: "The Dutch Golden Age" },
        { id: "3.6", title: "Balance of Power" },
        { id: "3.7", title: "Absolutist Approaches to Power" },
        { id: "3.8", title: "Comparison in the Age of Absolutism and Constitutionalism" },
      ],
    },
    {
      number: 4,
      title: "Scientific, Philosophical, and Political Developments (c. 1648-1815)",
      topics: [
        { id: "4.1", title: "Contextualizing the Scientific Revolution and the Enlightenment" },
        { id: "4.2", title: "The Scientific Revolution" },
        { id: "4.3", title: "The Enlightenment" },
        { id: "4.4", title: "18th-Century Society and Demographics" },
        { id: "4.5", title: "18th-Century Culture and Arts" },
        { id: "4.6", title: "Enlightened and Other Approaches to Power" },
        { id: "4.7", title: "Causation in the Age of the Scientific Revolution and the Enlightenment" },
      ],
    },
    {
      number: 5,
      title: "Conflict, Crisis, and Reaction in the Late 18th Century (c. 1648-1815)",
      topics: [
        { id: "5.1", title: "Contextualizing 18th-Century States" },
        { id: "5.2", title: "The Rise of Global Markets" },
        { id: "5.3", title: "Britain's Ascendency" },
        { id: "5.4", title: "The French Revolution" },
        { id: "5.5", title: "The French Revolution's Effects" },
        { id: "5.6", title: "Napoleon's Rise, Dominance, and Defeat" },
        { id: "5.7", title: "The Congress of Vienna" },
        { id: "5.8", title: "Romanticism" },
        { id: "5.9", title: "Continuity and Change in the 18th Century" },
      ],
    },
    {
      number: 6,
      title: "Industrialization and Its Effects (c. 1815-1914)",
      topics: [
        { id: "6.1", title: "Contextualizing Industrialization and Its Origins and Effects" },
        { id: "6.2", title: "The Industrial Revolution Begins in Britain" },
        { id: "6.3", title: "Spread of Industry Throughout Europe" },
        { id: "6.4", title: "Second Industrial Revolution" },
        { id: "6.5", title: "Social Effects of Industrialization" },
        { id: "6.6", title: "The Concert of Europe and European Conservatism" },
        { id: "6.7", title: "Reactions and Revolutions" },
        { id: "6.8", title: "Ideologies of Change and Reform Movements" },
        { id: "6.9", title: "19th-Century Social Reform" },
        { id: "6.10", title: "Institutional Responses and Reform" },
        { id: "6.11", title: "Causation in the Age of Industrialization" },
      ],
    },
    {
      number: 7,
      title: "19th-Century Perspectives and Political Developments (c. 1815-1914)",
      topics: [
        { id: "7.1", title: "Contextualizing 19th-Century Perspectives and Political Developments" },
        { id: "7.2", title: "Nationalism" },
        { id: "7.3", title: "National Unification and Diplomatic Tensions" },
        { id: "7.4", title: "Darwinism, Social Darwinism" },
        { id: "7.5", title: "The Age of Progress and Modernity" },
        { id: "7.6", title: "New Imperialism: Motivations and Methods" },
        { id: "7.7", title: "Imperialism's Global Effects" },
        { id: "7.8", title: "19th-Century Culture and Arts" },
        { id: "7.9", title: "Causation in 19th-Century Perspectives and Political Developments" },
      ],
    },
    {
      number: 8,
      title: "20th-Century Global Conflicts (c. 1914-present)",
      topics: [
        { id: "8.1", title: "Contextualizing 20th-Century Global Conflicts" },
        { id: "8.2", title: "World War I" },
        { id: "8.3", title: "The Russian Revolution and Its Effects" },
        { id: "8.4", title: "Versailles Conference and Peace Settlement" },
        { id: "8.5", title: "Global Economic Crisis" },
        { id: "8.6", title: "Fascism and Totalitarianism" },
        { id: "8.7", title: "Europe During the Interwar Period" },
        { id: "8.8", title: "World War II" },
        { id: "8.9", title: "The Holocaust" },
        { id: "8.10", title: "20th-Century Cultural, Intellectual, and Artistic Developments" },
        { id: "8.11", title: "Causation in Global Conflict" },
      ],
    },
    {
      number: 9,
      title: "Cold War and Contemporary Europe (c. 1914-present)",
      topics: [
        { id: "9.1", title: "Contextualizing Cold War and Contemporary Europe" },
        { id: "9.2", title: "Rebuilding Europe" },
        { id: "9.3", title: "The Cold War" },
        { id: "9.4", title: "Two Europes, Two Blocs" },
        { id: "9.5", title: "Postwar Nationalism, Ethnic Conflict, and Atrocities" },
        { id: "9.6", title: "Contemporary Western Democracies" },
        { id: "9.7", title: "The Fall of Communism" },
        { id: "9.8", title: "20th-Century Feminism" },
        { id: "9.9", title: "Decolonization" },
        { id: "9.10", title: "The European Union" },
        { id: "9.11", title: "Migration and Immigration" },
        { id: "9.12", title: "Technology" },
        { id: "9.13", title: "Globalization" },
        { id: "9.14", title: "20th- and 21st-Century Culture, Arts, and Demographic Trends" },
        { id: "9.15", title: "Continuity and Change in the 20th and 21st Centuries" },
      ],
    },
  ],
};
