/**
 * Official AP Course and Exam Description (CED) unit + topic breakdowns
 * for the math courses. Topic codes and titles track the College Board
 * framework as closely as possible; a handful are lightly paraphrased for
 * clarity when the CED title runs long.
 *
 * Sources:
 *  - AP Central course pages (apcentral.collegeboard.org)
 *  - Published CED PDFs for each course
 *  - Cross-checks against Khan Academy and Fiveable topic lists
 */

export type ApTopicLite = { id: string; title: string };
export type ApUnitLite = { number: number; title: string; topics: ApTopicLite[] };

export const MATH_UNITS: Record<string, ApUnitLite[]> = {
  // =========================================================================
  // AP PRECALCULUS (4 units; Unit 4 is optional on the exam)
  // =========================================================================
  "ap-precalc": [
    {
      number: 1,
      title: "Polynomial and Rational Functions",
      topics: [
        { id: "1.1", title: "Change in Tandem" },
        { id: "1.2", title: "Rates of Change" },
        { id: "1.3", title: "Rates of Change in Linear and Quadratic Functions" },
        { id: "1.4", title: "Polynomial Functions and Rates of Change" },
        { id: "1.5", title: "Polynomial Functions and Complex Zeros" },
        { id: "1.6", title: "Polynomial Functions and End Behavior" },
        { id: "1.7", title: "Rational Functions and End Behavior" },
        { id: "1.8", title: "Rational Functions and Zeros" },
        { id: "1.9", title: "Rational Functions and Vertical Asymptotes" },
        { id: "1.10", title: "Rational Functions and Holes" },
        { id: "1.11", title: "Equivalent Representations of Polynomial and Rational Expressions" },
        { id: "1.12", title: "Transformations of Functions" },
        { id: "1.13", title: "Function Model Selection and Assumption Articulation" },
        { id: "1.14", title: "Function Model Construction and Application" },
      ],
    },
    {
      number: 2,
      title: "Exponential and Logarithmic Functions",
      topics: [
        { id: "2.1", title: "Change in Arithmetic and Geometric Sequences" },
        { id: "2.2", title: "Change in Linear and Exponential Functions" },
        { id: "2.3", title: "Exponential Functions" },
        { id: "2.4", title: "Exponential Function Manipulation" },
        { id: "2.5", title: "Exponential Function Context and Data Modeling" },
        { id: "2.6", title: "Competing Function Model Validation" },
        { id: "2.7", title: "Composition of Functions" },
        { id: "2.8", title: "Inverse Functions" },
        { id: "2.9", title: "Logarithmic Expressions" },
        { id: "2.10", title: "Inverses of Exponential Functions" },
        { id: "2.11", title: "Logarithmic Functions" },
        { id: "2.12", title: "Logarithmic Function Manipulation" },
        { id: "2.13", title: "Exponential and Logarithmic Equations and Inequalities" },
        { id: "2.14", title: "Logarithmic Function Context and Data Modeling" },
        { id: "2.15", title: "Semi-log Plots" },
      ],
    },
    {
      number: 3,
      title: "Trigonometric and Polar Functions",
      topics: [
        { id: "3.1", title: "Periodic Phenomena" },
        { id: "3.2", title: "Sine, Cosine, and Tangent" },
        { id: "3.3", title: "Sine and Cosine Function Values" },
        { id: "3.4", title: "Sine and Cosine Function Graphs" },
        { id: "3.5", title: "Sinusoidal Functions" },
        { id: "3.6", title: "Sinusoidal Function Transformations" },
        { id: "3.7", title: "Sinusoidal Function Context and Data Modeling" },
        { id: "3.8", title: "The Tangent Function" },
        { id: "3.9", title: "Inverse Trigonometric Functions" },
        { id: "3.10", title: "Trigonometric Equations and Inequalities" },
        { id: "3.11", title: "The Secant, Cosecant, and Cotangent Functions" },
        { id: "3.12", title: "Equivalent Representations of Trigonometric Functions" },
        { id: "3.13", title: "Trigonometry and Polar Coordinates" },
        { id: "3.14", title: "Polar Function Graphs" },
        { id: "3.15", title: "Rates of Change in Polar Functions" },
      ],
    },
    {
      number: 4,
      title: "Functions Involving Parameters, Vectors, and Matrices",
      topics: [
        { id: "4.1", title: "Parametric Functions" },
        { id: "4.2", title: "Parametric Functions Modeling Planar Motion" },
        { id: "4.3", title: "Parametric Functions and Rates of Change" },
        { id: "4.4", title: "Parametrically Defined Circles and Lines" },
        { id: "4.5", title: "Implicitly Defined Functions" },
        { id: "4.6", title: "Conic Sections" },
        { id: "4.7", title: "Parametrization of Implicitly Defined Functions" },
        { id: "4.8", title: "Vectors" },
        { id: "4.9", title: "Vector-Valued Functions" },
        { id: "4.10", title: "Matrices" },
        { id: "4.11", title: "The Inverse and Determinant of a Matrix" },
        { id: "4.12", title: "Linear Transformations and Matrices" },
        { id: "4.13", title: "Matrices as Functions" },
        { id: "4.14", title: "Matrices Modeling Contexts" },
      ],
    },
  ],

  // =========================================================================
  // AP CALCULUS AB (8 units)
  // =========================================================================
  "ap-calc-ab": [
    {
      number: 1,
      title: "Limits and Continuity",
      topics: [
        { id: "1.1", title: "Introducing Calculus: Can Change Occur at an Instant?" },
        { id: "1.2", title: "Defining Limits and Using Limit Notation" },
        { id: "1.3", title: "Estimating Limit Values from Graphs" },
        { id: "1.4", title: "Estimating Limit Values from Tables" },
        { id: "1.5", title: "Determining Limits Using Algebraic Properties of Limits" },
        { id: "1.6", title: "Determining Limits Using Algebraic Manipulation" },
        { id: "1.7", title: "Selecting Procedures for Determining Limits" },
        { id: "1.8", title: "Determining Limits Using the Squeeze Theorem" },
        { id: "1.9", title: "Connecting Multiple Representations of Limits" },
        { id: "1.10", title: "Exploring Types of Discontinuities" },
        { id: "1.11", title: "Defining Continuity at a Point" },
        { id: "1.12", title: "Confirming Continuity over an Interval" },
        { id: "1.13", title: "Removing Discontinuities" },
        { id: "1.14", title: "Connecting Infinite Limits and Vertical Asymptotes" },
        { id: "1.15", title: "Connecting Limits at Infinity and Horizontal Asymptotes" },
        { id: "1.16", title: "Working with the Intermediate Value Theorem" },
      ],
    },
    {
      number: 2,
      title: "Differentiation: Definition and Fundamental Properties",
      topics: [
        { id: "2.1", title: "Defining Average and Instantaneous Rates of Change at a Point" },
        { id: "2.2", title: "Defining the Derivative of a Function and Using Derivative Notation" },
        { id: "2.3", title: "Estimating Derivatives of a Function at a Point" },
        { id: "2.4", title: "Connecting Differentiability and Continuity" },
        { id: "2.5", title: "Applying the Power Rule" },
        { id: "2.6", title: "Derivative Rules: Constant, Sum, Difference, and Constant Multiple" },
        { id: "2.7", title: "Derivatives of cos x, sin x, e^x, and ln x" },
        { id: "2.8", title: "The Product Rule" },
        { id: "2.9", title: "The Quotient Rule" },
        { id: "2.10", title: "Finding the Derivatives of Tangent, Cotangent, Secant, and/or Cosecant Functions" },
      ],
    },
    {
      number: 3,
      title: "Differentiation: Composite, Implicit, and Inverse Functions",
      topics: [
        { id: "3.1", title: "The Chain Rule" },
        { id: "3.2", title: "Implicit Differentiation" },
        { id: "3.3", title: "Differentiating Inverse Functions" },
        { id: "3.4", title: "Differentiating Inverse Trigonometric Functions" },
        { id: "3.5", title: "Selecting Procedures for Calculating Derivatives" },
        { id: "3.6", title: "Calculating Higher-Order Derivatives" },
      ],
    },
    {
      number: 4,
      title: "Contextual Applications of Differentiation",
      topics: [
        { id: "4.1", title: "Interpreting the Meaning of the Derivative in Context" },
        { id: "4.2", title: "Straight-Line Motion: Connecting Position, Velocity, and Acceleration" },
        { id: "4.3", title: "Rates of Change in Applied Contexts Other Than Motion" },
        { id: "4.4", title: "Introduction to Related Rates" },
        { id: "4.5", title: "Solving Related Rates Problems" },
        { id: "4.6", title: "Approximating Values of a Function Using Local Linearity and Linearization" },
        { id: "4.7", title: "Using L'Hôpital's Rule for Determining Limits of Indeterminate Forms" },
      ],
    },
    {
      number: 5,
      title: "Analytical Applications of Differentiation",
      topics: [
        { id: "5.1", title: "Using the Mean Value Theorem" },
        { id: "5.2", title: "Extreme Value Theorem, Global Versus Local Extrema, and Critical Points" },
        { id: "5.3", title: "Determining Intervals on Which a Function Is Increasing or Decreasing" },
        { id: "5.4", title: "Using the First Derivative Test to Determine Relative (Local) Extrema" },
        { id: "5.5", title: "Using the Candidates Test to Determine Absolute (Global) Extrema" },
        { id: "5.6", title: "Determining Concavity of Functions over Their Domains" },
        { id: "5.7", title: "Using the Second Derivative Test to Determine Extrema" },
        { id: "5.8", title: "Sketching Graphs of Functions and Their Derivatives" },
        { id: "5.9", title: "Connecting a Function, Its First Derivative, and Its Second Derivative" },
        { id: "5.10", title: "Introduction to Optimization Problems" },
        { id: "5.11", title: "Solving Optimization Problems" },
        { id: "5.12", title: "Exploring Behaviors of Implicit Relations" },
      ],
    },
    {
      number: 6,
      title: "Integration and Accumulation of Change",
      topics: [
        { id: "6.1", title: "Exploring Accumulations of Change" },
        { id: "6.2", title: "Approximating Areas with Riemann Sums" },
        { id: "6.3", title: "Riemann Sums, Summation Notation, and Definite Integral Notation" },
        { id: "6.4", title: "The Fundamental Theorem of Calculus and Accumulation Functions" },
        { id: "6.5", title: "Interpreting the Behavior of Accumulation Functions Involving Area" },
        { id: "6.6", title: "Applying Properties of Definite Integrals" },
        { id: "6.7", title: "The Fundamental Theorem of Calculus and Definite Integrals" },
        { id: "6.8", title: "Finding Antiderivatives and Indefinite Integrals: Basic Rules and Notation" },
        { id: "6.9", title: "Integration Using Substitution" },
        { id: "6.10", title: "Integrating Functions Using Long Division and Completing the Square" },
        { id: "6.14", title: "Selecting Techniques for Antidifferentiation" },
      ],
    },
    {
      number: 7,
      title: "Differential Equations",
      topics: [
        { id: "7.1", title: "Modeling Situations with Differential Equations" },
        { id: "7.2", title: "Verifying Solutions for Differential Equations" },
        { id: "7.3", title: "Sketching Slope Fields" },
        { id: "7.4", title: "Reasoning Using Slope Fields" },
        { id: "7.6", title: "Finding General Solutions Using Separation of Variables" },
        { id: "7.7", title: "Finding Particular Solutions Using Initial Conditions and Separation of Variables" },
        { id: "7.8", title: "Exponential Models with Differential Equations" },
      ],
    },
    {
      number: 8,
      title: "Applications of Integration",
      topics: [
        { id: "8.1", title: "Finding the Average Value of a Function on an Interval" },
        { id: "8.2", title: "Connecting Position, Velocity, and Acceleration Using Integrals" },
        { id: "8.3", title: "Using Accumulation Functions and Definite Integrals in Applied Contexts" },
        { id: "8.4", title: "Finding the Area Between Curves Expressed as Functions of x" },
        { id: "8.5", title: "Finding the Area Between Curves Expressed as Functions of y" },
        { id: "8.6", title: "Finding the Area Between Curves That Intersect at More Than Two Points" },
        { id: "8.7", title: "Volumes with Cross Sections: Squares and Rectangles" },
        { id: "8.8", title: "Volumes with Cross Sections: Triangles and Semicircles" },
        { id: "8.9", title: "Volume with Disc Method: Revolving Around the x- or y-Axis" },
        { id: "8.10", title: "Volume with Disc Method: Revolving Around Other Axes" },
        { id: "8.11", title: "Volume with Washer Method: Revolving Around the x- or y-Axis" },
        { id: "8.12", title: "Volume with Washer Method: Revolving Around Other Axes" },
      ],
    },
  ],

  // =========================================================================
  // AP CALCULUS BC (10 units; units 1-8 shared with AB, plus 9 and 10)
  // =========================================================================
  "ap-calc-bc": [
    // Units 1-8 repeat AB content. Using the same topic lists as above.
    {
      number: 1,
      title: "Limits and Continuity",
      topics: [
        { id: "1.1", title: "Introducing Calculus: Can Change Occur at an Instant?" },
        { id: "1.2", title: "Defining Limits and Using Limit Notation" },
        { id: "1.3", title: "Estimating Limit Values from Graphs" },
        { id: "1.4", title: "Estimating Limit Values from Tables" },
        { id: "1.5", title: "Determining Limits Using Algebraic Properties of Limits" },
        { id: "1.6", title: "Determining Limits Using Algebraic Manipulation" },
        { id: "1.7", title: "Selecting Procedures for Determining Limits" },
        { id: "1.8", title: "Determining Limits Using the Squeeze Theorem" },
        { id: "1.9", title: "Connecting Multiple Representations of Limits" },
        { id: "1.10", title: "Exploring Types of Discontinuities" },
        { id: "1.11", title: "Defining Continuity at a Point" },
        { id: "1.12", title: "Confirming Continuity over an Interval" },
        { id: "1.13", title: "Removing Discontinuities" },
        { id: "1.14", title: "Connecting Infinite Limits and Vertical Asymptotes" },
        { id: "1.15", title: "Connecting Limits at Infinity and Horizontal Asymptotes" },
        { id: "1.16", title: "Working with the Intermediate Value Theorem" },
      ],
    },
    {
      number: 2,
      title: "Differentiation: Definition and Fundamental Properties",
      topics: [
        { id: "2.1", title: "Defining Average and Instantaneous Rates of Change at a Point" },
        { id: "2.2", title: "Defining the Derivative of a Function and Using Derivative Notation" },
        { id: "2.3", title: "Estimating Derivatives of a Function at a Point" },
        { id: "2.4", title: "Connecting Differentiability and Continuity" },
        { id: "2.5", title: "Applying the Power Rule" },
        { id: "2.6", title: "Derivative Rules: Constant, Sum, Difference, and Constant Multiple" },
        { id: "2.7", title: "Derivatives of cos x, sin x, e^x, and ln x" },
        { id: "2.8", title: "The Product Rule" },
        { id: "2.9", title: "The Quotient Rule" },
        { id: "2.10", title: "Finding the Derivatives of Tangent, Cotangent, Secant, and/or Cosecant Functions" },
      ],
    },
    {
      number: 3,
      title: "Differentiation: Composite, Implicit, and Inverse Functions",
      topics: [
        { id: "3.1", title: "The Chain Rule" },
        { id: "3.2", title: "Implicit Differentiation" },
        { id: "3.3", title: "Differentiating Inverse Functions" },
        { id: "3.4", title: "Differentiating Inverse Trigonometric Functions" },
        { id: "3.5", title: "Selecting Procedures for Calculating Derivatives" },
        { id: "3.6", title: "Calculating Higher-Order Derivatives" },
      ],
    },
    {
      number: 4,
      title: "Contextual Applications of Differentiation",
      topics: [
        { id: "4.1", title: "Interpreting the Meaning of the Derivative in Context" },
        { id: "4.2", title: "Straight-Line Motion: Connecting Position, Velocity, and Acceleration" },
        { id: "4.3", title: "Rates of Change in Applied Contexts Other Than Motion" },
        { id: "4.4", title: "Introduction to Related Rates" },
        { id: "4.5", title: "Solving Related Rates Problems" },
        { id: "4.6", title: "Approximating Values of a Function Using Local Linearity and Linearization" },
        { id: "4.7", title: "Using L'Hôpital's Rule for Determining Limits of Indeterminate Forms" },
      ],
    },
    {
      number: 5,
      title: "Analytical Applications of Differentiation",
      topics: [
        { id: "5.1", title: "Using the Mean Value Theorem" },
        { id: "5.2", title: "Extreme Value Theorem, Global Versus Local Extrema, and Critical Points" },
        { id: "5.3", title: "Determining Intervals on Which a Function Is Increasing or Decreasing" },
        { id: "5.4", title: "Using the First Derivative Test to Determine Relative (Local) Extrema" },
        { id: "5.5", title: "Using the Candidates Test to Determine Absolute (Global) Extrema" },
        { id: "5.6", title: "Determining Concavity of Functions over Their Domains" },
        { id: "5.7", title: "Using the Second Derivative Test to Determine Extrema" },
        { id: "5.8", title: "Sketching Graphs of Functions and Their Derivatives" },
        { id: "5.9", title: "Connecting a Function, Its First Derivative, and Its Second Derivative" },
        { id: "5.10", title: "Introduction to Optimization Problems" },
        { id: "5.11", title: "Solving Optimization Problems" },
        { id: "5.12", title: "Exploring Behaviors of Implicit Relations" },
      ],
    },
    {
      number: 6,
      title: "Integration and Accumulation of Change",
      topics: [
        { id: "6.1", title: "Exploring Accumulations of Change" },
        { id: "6.2", title: "Approximating Areas with Riemann Sums" },
        { id: "6.3", title: "Riemann Sums, Summation Notation, and Definite Integral Notation" },
        { id: "6.4", title: "The Fundamental Theorem of Calculus and Accumulation Functions" },
        { id: "6.5", title: "Interpreting the Behavior of Accumulation Functions Involving Area" },
        { id: "6.6", title: "Applying Properties of Definite Integrals" },
        { id: "6.7", title: "The Fundamental Theorem of Calculus and Definite Integrals" },
        { id: "6.8", title: "Finding Antiderivatives and Indefinite Integrals: Basic Rules and Notation" },
        { id: "6.9", title: "Integration Using Substitution" },
        { id: "6.10", title: "Integrating Functions Using Long Division and Completing the Square" },
        { id: "6.11", title: "Integration Using Integration by Parts" },
        { id: "6.12", title: "Using Linear Partial Fractions" },
        { id: "6.13", title: "Evaluating Improper Integrals" },
        { id: "6.14", title: "Selecting Techniques for Antidifferentiation" },
      ],
    },
    {
      number: 7,
      title: "Differential Equations",
      topics: [
        { id: "7.1", title: "Modeling Situations with Differential Equations" },
        { id: "7.2", title: "Verifying Solutions for Differential Equations" },
        { id: "7.3", title: "Sketching Slope Fields" },
        { id: "7.4", title: "Reasoning Using Slope Fields" },
        { id: "7.5", title: "Approximating Solutions Using Euler's Method" },
        { id: "7.6", title: "Finding General Solutions Using Separation of Variables" },
        { id: "7.7", title: "Finding Particular Solutions Using Initial Conditions and Separation of Variables" },
        { id: "7.8", title: "Exponential Models with Differential Equations" },
        { id: "7.9", title: "Logistic Models with Differential Equations" },
      ],
    },
    {
      number: 8,
      title: "Applications of Integration",
      topics: [
        { id: "8.1", title: "Finding the Average Value of a Function on an Interval" },
        { id: "8.2", title: "Connecting Position, Velocity, and Acceleration Using Integrals" },
        { id: "8.3", title: "Using Accumulation Functions and Definite Integrals in Applied Contexts" },
        { id: "8.4", title: "Finding the Area Between Curves Expressed as Functions of x" },
        { id: "8.5", title: "Finding the Area Between Curves Expressed as Functions of y" },
        { id: "8.6", title: "Finding the Area Between Curves That Intersect at More Than Two Points" },
        { id: "8.7", title: "Volumes with Cross Sections: Squares and Rectangles" },
        { id: "8.8", title: "Volumes with Cross Sections: Triangles and Semicircles" },
        { id: "8.9", title: "Volume with Disc Method: Revolving Around the x- or y-Axis" },
        { id: "8.10", title: "Volume with Disc Method: Revolving Around Other Axes" },
        { id: "8.11", title: "Volume with Washer Method: Revolving Around the x- or y-Axis" },
        { id: "8.12", title: "Volume with Washer Method: Revolving Around Other Axes" },
        { id: "8.13", title: "The Arc Length of a Smooth, Planar Curve and Distance Traveled" },
      ],
    },
    {
      number: 9,
      title: "Parametric Equations, Polar Coordinates, and Vector-Valued Functions",
      topics: [
        { id: "9.1", title: "Defining and Differentiating Parametric Equations" },
        { id: "9.2", title: "Second Derivatives of Parametric Equations" },
        { id: "9.3", title: "Finding Arc Lengths of Curves Given by Parametric Equations" },
        { id: "9.4", title: "Defining and Differentiating Vector-Valued Functions" },
        { id: "9.5", title: "Integrating Vector-Valued Functions" },
        { id: "9.6", title: "Solving Motion Problems Using Parametric and Vector-Valued Functions" },
        { id: "9.7", title: "Defining Polar Coordinates and Differentiating in Polar Form" },
        { id: "9.8", title: "Finding the Area of a Polar Region or the Area Bounded by a Single Polar Curve" },
        { id: "9.9", title: "Finding the Area of the Region Bounded by Two Polar Curves" },
      ],
    },
    {
      number: 10,
      title: "Infinite Sequences and Series",
      topics: [
        { id: "10.1", title: "Defining Convergent and Divergent Infinite Series" },
        { id: "10.2", title: "Working with Geometric Series" },
        { id: "10.3", title: "The nth Term Test for Divergence" },
        { id: "10.4", title: "Integral Test for Convergence" },
        { id: "10.5", title: "Harmonic Series and p-Series" },
        { id: "10.6", title: "Comparison Tests for Convergence" },
        { id: "10.7", title: "Alternating Series Test for Convergence" },
        { id: "10.8", title: "Ratio Test for Convergence" },
        { id: "10.9", title: "Determining Absolute or Conditional Convergence" },
        { id: "10.10", title: "Alternating Series Error Bound" },
        { id: "10.11", title: "Finding Taylor Polynomial Approximations of Functions" },
        { id: "10.12", title: "Lagrange Error Bound" },
        { id: "10.13", title: "Radius and Interval of Convergence of Power Series" },
        { id: "10.14", title: "Finding Taylor or Maclaurin Series for a Function" },
        { id: "10.15", title: "Representing Functions as Power Series" },
      ],
    },
  ],

  // =========================================================================
  // AP STATISTICS (9 units)
  // =========================================================================
  "ap-statistics": [
    {
      number: 1,
      title: "Exploring One-Variable Data",
      topics: [
        { id: "1.1", title: "Introducing Statistics: What Can We Learn from Data?" },
        { id: "1.2", title: "The Language of Variation: Variables" },
        { id: "1.3", title: "Representing a Categorical Variable with Tables" },
        { id: "1.4", title: "Representing a Categorical Variable with Graphs" },
        { id: "1.5", title: "Representing a Quantitative Variable with Graphs" },
        { id: "1.6", title: "Describing the Distribution of a Quantitative Variable" },
        { id: "1.7", title: "Summary Statistics for a Quantitative Variable" },
        { id: "1.8", title: "Graphical Representations of Summary Statistics" },
        { id: "1.9", title: "Comparing Distributions of a Quantitative Variable" },
        { id: "1.10", title: "The Normal Distribution" },
      ],
    },
    {
      number: 2,
      title: "Exploring Two-Variable Data",
      topics: [
        { id: "2.1", title: "Introducing Statistics: Are Variables Related?" },
        { id: "2.2", title: "Representing Two Categorical Variables" },
        { id: "2.3", title: "Statistics for Two Categorical Variables" },
        { id: "2.4", title: "Representing the Relationship Between Two Quantitative Variables" },
        { id: "2.5", title: "Correlation" },
        { id: "2.6", title: "Linear Regression Models" },
        { id: "2.7", title: "Residuals" },
        { id: "2.8", title: "Least Squares Regression" },
        { id: "2.9", title: "Analyzing Departures from Linearity" },
      ],
    },
    {
      number: 3,
      title: "Collecting Data",
      topics: [
        { id: "3.1", title: "Introducing Statistics: Do the Data We Collected Tell the Truth?" },
        { id: "3.2", title: "Introduction to Planning a Study" },
        { id: "3.3", title: "Random Sampling and Data Collection" },
        { id: "3.4", title: "Potential Problems with Sampling" },
        { id: "3.5", title: "Introduction to Experimental Design" },
        { id: "3.6", title: "Selecting an Experimental Design" },
        { id: "3.7", title: "Inference and Experiments" },
      ],
    },
    {
      number: 4,
      title: "Probability, Random Variables, and Probability Distributions",
      topics: [
        { id: "4.1", title: "Introducing Statistics: Random and Non-Random Patterns" },
        { id: "4.2", title: "Estimating Probabilities Using Simulation" },
        { id: "4.3", title: "Introduction to Probability" },
        { id: "4.4", title: "Mutually Exclusive Events" },
        { id: "4.5", title: "Conditional Probability" },
        { id: "4.6", title: "Independent Events and Unions of Events" },
        { id: "4.7", title: "Introduction to Random Variables and Probability Distributions" },
        { id: "4.8", title: "Mean and Standard Deviation of Random Variables" },
        { id: "4.9", title: "Combining Random Variables" },
        { id: "4.10", title: "Introduction to the Binomial Distribution" },
        { id: "4.11", title: "Parameters for a Binomial Distribution" },
        { id: "4.12", title: "The Geometric Distribution" },
      ],
    },
    {
      number: 5,
      title: "Sampling Distributions",
      topics: [
        { id: "5.1", title: "Introducing Statistics: Why Is My Sample Not Like Yours?" },
        { id: "5.2", title: "The Normal Distribution, Revisited" },
        { id: "5.3", title: "The Central Limit Theorem" },
        { id: "5.4", title: "Biased and Unbiased Point Estimates" },
        { id: "5.5", title: "Sampling Distributions for Sample Proportions" },
        { id: "5.6", title: "Sampling Distributions for Differences in Sample Proportions" },
        { id: "5.7", title: "Sampling Distributions for Sample Means" },
        { id: "5.8", title: "Sampling Distributions for Differences in Sample Means" },
      ],
    },
    {
      number: 6,
      title: "Inference for Categorical Data: Proportions",
      topics: [
        { id: "6.1", title: "Introducing Statistics: Why Be Normal?" },
        { id: "6.2", title: "Constructing a Confidence Interval for a Population Proportion" },
        { id: "6.3", title: "Justifying a Claim Based on a Confidence Interval for a Population Proportion" },
        { id: "6.4", title: "Setting Up a Test for a Population Proportion" },
        { id: "6.5", title: "Interpreting p-Values" },
        { id: "6.6", title: "Concluding a Test for a Population Proportion" },
        { id: "6.7", title: "Potential Errors When Performing Tests" },
        { id: "6.8", title: "Confidence Intervals for the Difference of Two Proportions" },
        { id: "6.9", title: "Justifying a Claim Based on a Confidence Interval for a Difference of Proportions" },
        { id: "6.10", title: "Setting Up a Test for the Difference of Two Population Proportions" },
        { id: "6.11", title: "Carrying Out a Test for the Difference of Two Population Proportions" },
      ],
    },
    {
      number: 7,
      title: "Inference for Quantitative Data: Means",
      topics: [
        { id: "7.1", title: "Introducing Statistics: Should I Worry About Error?" },
        { id: "7.2", title: "Constructing a Confidence Interval for a Population Mean" },
        { id: "7.3", title: "Justifying a Claim About a Population Mean Based on a Confidence Interval" },
        { id: "7.4", title: "Setting Up a Test for a Population Mean" },
        { id: "7.5", title: "Carrying Out a Test for a Population Mean" },
        { id: "7.6", title: "Confidence Intervals for the Difference of Two Means" },
        { id: "7.7", title: "Justifying a Claim About the Difference of Two Means" },
        { id: "7.8", title: "Setting Up a Test for the Difference of Two Population Means" },
        { id: "7.9", title: "Carrying Out a Test for the Difference of Two Population Means" },
        { id: "7.10", title: "Skew and Its Impact on Inference for Means" },
      ],
    },
    {
      number: 8,
      title: "Inference for Categorical Data: Chi-Square",
      topics: [
        { id: "8.1", title: "Introducing Statistics: Are My Results Unexpected?" },
        { id: "8.2", title: "Setting Up a Chi-Square Goodness of Fit Test" },
        { id: "8.3", title: "Carrying Out a Chi-Square Goodness of Fit Test" },
        { id: "8.4", title: "Expected Counts in Two-Way Tables" },
        { id: "8.5", title: "Setting Up a Chi-Square Test for Homogeneity or Independence" },
        { id: "8.6", title: "Carrying Out a Chi-Square Test for Homogeneity or Independence" },
        { id: "8.7", title: "Skills Focus: Selecting an Appropriate Inference Procedure for Categorical Data" },
      ],
    },
    {
      number: 9,
      title: "Inference for Quantitative Data: Slopes",
      topics: [
        { id: "9.1", title: "Introducing Statistics: Do Those Points Align?" },
        { id: "9.2", title: "Confidence Intervals for the Slope of a Regression Model" },
        { id: "9.3", title: "Justifying a Claim About the Slope of a Regression Model" },
        { id: "9.4", title: "Setting Up a Test for the Slope of a Regression Model" },
        { id: "9.5", title: "Carrying Out a Test for the Slope of a Regression Model" },
        { id: "9.6", title: "Skills Focus: Selecting an Appropriate Inference Procedure" },
      ],
    },
  ],
};
